### ISSUE TITLE
lwIP only returns last interface address

### ISSUE THREAD

**Issue by elrussovic** [eclipse-cyclonedds/cyclonedds#1014]
Hello, not sure if I need to sign the ECA for this little issue.

I found that lwIP version of [`ddsrt_getifaddr()`](https://github.com/eclipse-cyclonedds/cyclonedds/blob/9a8dd67b44e7d6d6599b539d2be35b7534ddc8a4/src/ddsrt/src/ifaddrs/lwip/ifaddrs.c#L127) only returns the last element of the address list.

Replacing line [202](https://github.com/eclipse-cyclonedds/cyclonedds/blob/9a8dd67b44e7d6d6599b539d2be35b7534ddc8a4/src/ddsrt/src/ifaddrs/lwip/ifaddrs.c#L202) with the following fixed the issue for me:
```
*ifap = root_ifa;
```
Please let me know if I need to provide anything else.
Thanks!

**Comment by eboasson** [comment]
Hi @elrussovic, thanks for debugging that one and giving the fix. Regarding the ECA: for merging a PR we need one, no matter how small the change — I think we need one even if it only changes whitespace in a comment 🙂. Filing one is easy enough, and then you could contribute the change yourself. It could even be done straight from the GitHub website.

Otherwise I can do one, though probably not today.

**Comment by eboasson** [comment]
@elrussovic, I guess you prefer me to take care of it 🙂

**Comment by elrussovic** [comment]
@eboasson
I would have liked to do the contribution, however I was distracted by some metaphorical squirrels and forgot to send an answer 😆. Sorry about that.
Thanks for taking care of it and I am glad if I was of help!
