### ISSUE TITLE
security profile

### ISSUE THREAD

**Issue by PRADEEPKJ** [eclipse-cyclonedds/cyclonedds#102]
Hi All,

I am new to cyclonedds and looking for security profile related things. I would like to know the kind of security features that are supported by cyclonedds. Please let me know also if there are any example, how to use them.

Thanks & Regards,
Pradeep

**Comment by eboasson** [comment]
Hi Pradeep,

Cyclone doesn’t yet implement DDS Security, so the only options you have today are TCP+TLS for authenticated and encrypted (point-to-point) connections, and running over a VPN if you trust all nodes that are part of the VPN. A VPN-based solution requires no changes to the Cyclone configuration, the use of TCP+TLS does. If you’re interested I could whip up a minimal example — I don’t think it is documented anywhere at the moment (other than in the code).

For the longer term, DDS Security is obviously the goal. As implementing DDS Security is a pretty significant amount of work and I moreover have reason to believe that ADLINK intends to donate the OpenSplice implementation to Cyclone in the future (there is a fair bit of similarity between the DDSI stack in OpenSplice and the one in Cyclone), I prefer to focus on improving other aspects of Cyclone first.

**Comment by PRADEEPKJ** [comment]
Thanks for the clarification. There is some code in src/core/ddsi/src/q_security.c, any idea about this? 

It would be very helpful if you can get me some example, to show how to use TCP+TLS in cyclonedds.

**Comment by PRADEEPKJ** [comment]
Thanks for all the clarifications!. I am not in a hurry for the example, take your time.

**Comment by eboasson** [comment]
I tried to enable it and discovered to my dismay that the SSL support in the code was not actually enabled at build time — and of course that meant it had accrued some compilation issues. On going over it I spotted another few things, such as not disabling old SSL/TLS versions and not enabling certificate checks by default ... That led to PR #107 that at least brings it to a working state. I'm holding off on merging that PR for a while, perhaps someone knowledgeable will comment. Nothing worse than incorrectly suggesting something can safely be used in a hostile environment.

As I am no expert in using openssl but did feel my example configuration should go a bit further than simple self-signed certificates, I followed [this guide](https://jamielinux.com/docs/openssl-certificate-authority/) to setting up a CA and generating client and server certificates. From my limited testing it appears that it indeed accepts a connection from a peer with a certificate that was signed by the CA and refuses to establish a connection with peers that do not. That's good, but not proof of it really doing everything correctly. So please think twice before deploying to a public-facing machine ...

In the linked zip file you will find a server and client configuration file (DDS may be peer-to-peer, but TCP and TLS are not). These rely on "key stores" that include a private/public key for the process and a CA (unless you choose to accept self-signed certificates, in which case you are only getting protection against eavesdroppers), and the ``redtape`` script automates the process I referenced above for generating those files.

[cyclonedds-ssl-config.zip](https://github.com/eclipse-cyclonedds/cyclonedds/files/2813772/cyclonedds-ssl-config.zip)

**Comment by PRADEEPKJ** [comment]
Thanks a lot for the example. I will have a look. As of now I am looking how to implement Authorization and Encryption part of security in cycloneDDS.

**Comment by eboasson** [comment]
> As of now I am looking how to implement Authorization and Encryption part of security in cycloneDDS.

That is great. Any contribution towards improving the security of Cyclone DDS is appreciated very much.

I've merged the PR, so as of today, Cyclone DDS can be built (it can be completely disabled, but is done by default) with openssl 1.0.x or 1.1.x. It defaults to requiring TLS 1.3 for the connections but can be configured to accept TLS 1.2. The reason for pushing the default minimal TLS version all the way up is that there is no installed base yet, and that it therefore makes sense to default to the (presumably) most attack-resistant protocol version.

**Comment by PRADEEPKJ** [comment]
Thanks for the clarification. I would also like to know that which level its better to encrypt the messages. Is it good to do at DDS level or RTPS(ddsi) level?

**Comment by PRADEEPKJ** [comment]
Thanks for the detailed explanation. Yes, these information are very helpful for my future work.

**Comment by PRADEEPKJ** [comment]
Any idea how to enable the SSL module while compiling?. I do no see any switches in cmake file.

**Comment by eboasson** [comment]
The default behaviour is to require openssl and include support, but you can manually disable it. The CMake bit is buried in the ``src/core/CMakeLists.txt`` because the setting only affects the core library. See: https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/src/core/CMakeLists.txt#L36

**Comment by PRADEEPKJ** [comment]
Thanks, I cloned source code but it has some issue with the building.
I have Java 1.8 and Maven 3.6.
I also set the proxies in settings.xml. Still I am facing the same issue.

[ERROR] Plugin org.antlr:antlr4-maven-plugin:4.5 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.antlr:antlr4-maven-plugin:jar:4.5: Could not transfer artifact org.antlr:antlr4-maven-plugin:pom:4.5 from/to central (https://repo.maven.apache.org/maven2): Not authorized by proxy

**Comment by PRADEEPKJ** [comment]
One more question, the existing ssl support is only for the tcp ( reliable transport ) right?. What about when we use the Best_effort QoS?

**Comment by eboasson** [comment]
> Thanks, it worked.
> I ran helloworld example with ssl enabled, it works fine.

☺️

> One more question, the existing ssl support is only for the tcp ( reliable transport ) right?. What about when we use the Best_effort QoS?

When you use TCP, it pushes everything over the TCP connection (and if you enable TLS, everything goes over TCP+TLS) — so that includes the best-effort data. Evidently, that is less than ideal, because it means you get, e.g., head-of-line blocking behaviour on best-effort data, but there is not that much choice either.

Besides that, you might find it interesting to know that it runs the DDSI reliable protocol on top of TCP. In part, that's because it is by far the easiest way to deal with it, but in part it is also because the behaviour of and timeouts in DDS for detecting disconnections and handling reconnections is different from those of TCP, and so one has to deal with cases where a TCP connection drops but the connection is re-established before the peer's lease expired.

Now, in Cyclone, there are a number of known issues with the TCP support, and while addressing those won't change the fundamentals, it will provide a much better experience. Right now you can run into connection timeouts in the data path (whereas they should occur outside the data path, while doing discovery), and it doesn't gracefully deal with a blocked TCP connection, as the data will stall, rather than continuing unhindered on all connections other than the one that is stalled. These are issues that will be fixed in the future.

**Comment by PRADEEPKJ** [comment]
My bad, I did not test properly. Now I have problems with the ssl enablement
On publisher side:
1550248453.478765/    listen: tcp/ssl accept failed on socket 4 at invalid/0:0 errno 0
On Subscriber side
1550248453.478748/       tev: tcp/ssl connect failed error:00000005:lib(0):func(0):DH lib 0
Any idea what is the reason?
I looked into the code, the error is because of SSL_accept() failure.  Reason may be
 SSL_ERROR_SYSCALL or  SSL_ERROR_SSL

**Comment by PRADEEPKJ** [comment]
@eboasson 
I successfully enabled  and build the security code. Using some clues from security config example from the Adlink security document I tried running helloworld example. But facing the below issue.
My config file looks as below. Getting a error like " **Not a multicast address**". Please let me know what could be the reason and how can I resolve this.
<Partitioning>
                <NetworkPartitions >
                <NetworkPartition Name="broadcast"
                        Address="localhost"
                SecurityProfile="GlobalProfile"/>
                        <NetworkPartition Name="ChatRoomPartition"
                        Address="localaddress"
                        SecurityProfile="ChatRoomProfile" />
                </NetworkPartitions>
        <PartitionMappings>
        <PartitionMapping DCPSPartitionTopic="ChatRoom.*"
        NetworkPartition="ChatRoomPartition"/>
        </PartitionMappings>
        </Partitioning>
   <Security>
   <SecurityProfile name="GlobalProfile"
      Cipher="aes128"
      CipherKey="556B369ADBC42E57D259D78E475D18D3"
    />
    <SecurityProfile name="ChatRoomProfile"
      Cipher="aes128"
      CipherKey="556B369ADBC42E57D259D78E475D18D3"
    />
   </Security>

**Comment by eboasson** [comment]
Hi @PRADEEPKJ, I expect it is complaining about the addresses you specified in the "address" attributes of the NetworkPartition elements. It requires those to be multicast addresses, as the main purpose of the network partitions is to allow mapping traffic to different multicast addresses depending on topic/partition. The address to use for unicast traffic is simply the taken from the selected interface.

Readers matching a network partition advertise the address from the network partition as the multicast address on which they will be listening for data, forcing the writers to use that multicast address instead of some other address. If different processes use different configurations with different addresses, the data will simply be sent multiple times.

It seems to me that the combination of network partitions and unicast-only networking (General/AllowMulticast = false) might cause some trouble. That case is not really relevant when network partitions are used only for mapping traffic to multicast addresses, but that changes when you add this feature. It probably ignores the multicast addresses somewhere down the line and so it will probably work, but if not, the fix will be trivial.

**Comment by PRADEEPKJ** [comment]
> Hi @PRADEEPKJ, I expect it is complaining about the addresses you specified in the "address" attributes of the NetworkPartition elements. It requires those to be multicast addresses, as the main purpose of the network partitions is to allow mapping traffic to different multicast addresses depending on topic/partition. The address to use for unicast traffic is simply the taken from the selected interface.
> 
> Readers matching a network partition advertise the address from the network partition as the multicast address on which they will be listening for data, forcing the writers to use that multicast address instead of some other address. If different processes use different configurations with different addresses, the data will simply be sent multiple times.
> 
> It seems to me that the combination of network partitions and unicast-only networking (General/AllowMulticast = false) might cause some trouble. That case is not really relevant when network partitions are used only for mapping traffic to multicast addresses, but that changes when you add this feature. It probably ignores the multicast addresses somewhere down the line and so it will probably work, but if not, the fix will be trivial.

**Comment by PRADEEPKJ** [comment]
Does it mean that the existing security code (With network partition) works only for the multicast, i.e only UDP, not TCP right?

**Comment by eboasson** [comment]
I think no one has given any thought to it — I certainly haven't! — but from the way this DDSI stack works, there should be no issue. For TCP there'll probably be an issue defining the network partitions simply because it requires a multicast address.

Make it possible to define a network partition without using a special address (perfectly reasonable in the light of this feature) and I think it will work over TCP and over UDP, because it seems that during creation of a reader, the configured addresses of matching network partitions are collected in an "address set", and that this address set may be empty. It's worth looking into in more detail.

**Comment by PRADEEPKJ** [comment]
@eboasson  Thanks for the clarification. Yes, that is right the address set is empty so I have an issue.
One more question. Once the TLS/DTLS is enabled the communication channel is secure and all the messages will be encrypted by default. Why there is a separate encryption mechanism?. I fail to understand this.

**Comment by eboasson** [comment]
Hi @PRADEEPKJ ,

> Once the TLS/DTLS is enabled the communication channel is secure and all the messages will be encrypted by default. Why there is a separate encryption mechanism?. I fail to understand this.

I don't think the additional encryption would be valuable. What I am afraid happened is that I have unintentionally created some confusion by trying to explain that this mechanism is independent of the choice of transport, except for a few details at configuration level, thereby unintentionally leaving a suggesting that it might be of value.

And once more: the encryption code in ``q_security.c`` does **not** make it a secure DDS. It only provides for encryption of individual data samples with a fixed, pre-shared key and does not protect against tampering, replay attacks, spoofing, or any other bit of fun.

I fully intend to remove it sooner than later and might have done so already had you not shown a significant interest in it — perhaps you saw something in it that I overlooked, after all. Also keep in mind that support for the real DDS Security specification really is coming to Cyclone (see #132), and that one eliminates whatever small value there might once have been in this ancient bit of code.

**Comment by PRADEEPKJ** [comment]
> Hi @PRADEEPKJ ,
> 
> > Once the TLS/DTLS is enabled the communication channel is secure and all the messages will be encrypted by default. Why there is a separate encryption mechanism?. I fail to understand this.
> 
> I don't think the additional encryption would be valuable. What I am afraid happened is that I have unintentionally created some confusion by trying to explain that this mechanism is independent of the choice of transport, except for a few details at configuration level, thereby unintentionally leaving a suggesting that it might be of value.
OK 
> And once more: the encryption code in `q_security.c` does **not** make it a secure DDS. It only provides for encryption of individual data samples with a fixed, pre-shared key and does not protect against tampering, replay attacks, spoofing, or any other bit of fun.
OK
> 
> I fully intend to remove it sooner than later and might have done so already had you not shown a significant interest in it — perhaps you saw something in it that I overlooked, after all. Also keep in mind that support for the real DDS Security specification really is coming to Cyclone (see #132), and that one eliminates whatever small value there might once have been in this ancient bit of code.
Thanks for sharing the link to the security work. It is really helpful.
