### ISSUE TITLE
CycloneDDS doesn't include security function

### ISSUE THREAD

**Issue by Eyuel-Military-Project** [eclipse-cyclonedds/cyclonedds#1021]
It seems that the Package of CycloneDDS doesn't include security function.
I think there is something wrong (maybe lack of definition for building) while creating CycloneDDS packages:

Is there any work around this to build it with security?

1636390303.184139 [0]    python3: config: //CycloneDDS/Domain: 'DDSSecurity': deprecated alias for 'Security' (file:///../cyclonedds/cyclonedds.xml line 4)
1636390303.185639 [0]    python3: Could not load Authentication library: dds_security_auth: cannot open shared object file: No such file or directory
1636390303.185661 [0]    python3: Could not load Authentication plugin.
1636390303.185665 [0]    python3: Could not load security
Traceback (most recent call last):

**Comment by eboasson** [comment]
If you build Cyclone with OpenSSL available, it by default builds the security plug-ins. If you did a normal build (not statically linked) and CMake didn't warn you that OpenSSL could not be found, you should have those libraries. E.g., it should have generated a `libdds_security_auth.so` on Linux. Don't worry about the absence of the `lib` prefix or `.so` suffix: those are left out because it prints the name before making it system-specific because the name is different on different platforms.

Given that it seems to be Python (because of the `python3`), there are two obvious possibilities:
* "something" related to run-time linker's library path when using Python. On Linux this doesn't seem so likely, but on, e.g., macOS with its "System Integrity Protection" this happens all the time.
* The default procedure for installing the Python binding does indeed exclude DDS Security to keep things with library versions and locations simple. See https://github.com/eclipse-cyclonedds/cyclonedds-python#when-released-installing-with-pre-built-cyclone-dds-binaries

Those are the only obvious causes for running into this.

**Comment by Eyuel-Military-Project** [comment]
Thanks for the reply. I worked on lunix/ubunut 20.04 LTS. I first installed CycloneDDS and followed with the python binding.
I indeed installed python binding from from source via git as per the following:

`
$ git clone https://github.com/eclipse-cyclonedds/cyclonedds
$ cd cyclonedds && mkdir build install && cd build
$ cmake .. -DCMAKE_INSTALL_PREFIX=../install
$ cmake --build . --target install
$ cd ..
$ export CYCLONEDDS_HOME="$(pwd)/install"
$ pip3 install --user .[dev]
`
Is there a way to build and use cyclonedds with security with the python binding?
Maybe this issue would best posted in the cyclonedds-python repository.

**Comment by Eyuel-Military-Project** [comment]
Thank you for speedy reply, now installing cyclonedds from the source worked for me.
