### ISSUE TITLE
How to set configuration elements in ddsi_cfgelems.h

### ISSUE THREAD

**Issue by zhangyaothu** [eclipse-cyclonedds/cyclonedds#1051]
For stm32 on FreeRTOS, I do not have a environment configuration file, is this right to modify ddsi_cfgelems.h to set wanted configurations?
I modified the header file as below to add an unicast ip address for discovery logic.
```c
static struct cfgelem discovery_peer_cfgattrs[] = {
  STRING("Address", NULL, 1, "192.168.1.1",
    MEMBEROF(ddsi_config_peer_listelem, peer),
    FUNCTIONS(0, uf_ipv4, ff_free, pf_string),
    DESCRIPTION(
      "<p>This element specifies an IP address to which discovery packets "
      "must be sent, in addition to the default multicast address (see also "
      "General/AllowMulticast). Both a hostnames and a numerical IP address "
      "is accepted; the hostname or IP address may be suffixed with :PORT to "
      "explicitly set the port to which it must be sent. Multiple Peers may "
      "be specified.</p>"
    )),
  END_MARKER
};

static struct cfgelem discovery_peers_group_cfgelems[] = {
  GROUP("Peer", NULL, discovery_peer_cfgattrs, 1,
    MEMBER(peers_group),
    FUNCTIONS(if_peer, 0, 0, 0),
    DESCRIPTION(
      "<p>This element statically configures an addresses for discovery.</p>"
    )),
  END_MARKER
};

static struct cfgelem discovery_peers_cfgelems[] = {
  GROUP("Peer", NULL, discovery_peer_cfgattrs, 1,
    MEMBER(peers),
    FUNCTIONS(if_peer, 0, 0, 0),
    DESCRIPTION(
      "<p>This element statically configures an addresses for discovery.</p>"
    )),
  GROUP("Group", discovery_peers_group_cfgelems, NULL, 1,
    NOMEMBER,
    NOFUNCTIONS,
    DESCRIPTION(
      "<p>This element statically configures a fault tolerant group of "
      "addresses for discovery. Each member of the group is tried in "
      "sequence until one succeeds.</p>"
    ),
    MAXIMUM(0)), /* Group element can occur more than once, but 1 is required
                    because of the way its processed (for now) */
  END_MARKER
};
```

**Comment by eboasson** [comment]
You can do that, but a better way is to use either of
* `dds_create_domain`, which you takes a `config_xml` parameter. Like the contents of `CYCLONEDDS_URI`, this can be an XML string or a file (or actually a comma-separated list of them). In other words:
  ```C
  domain = dds_create_domain (42, "<CycloneDDS><Domain id=\"any\">\
  <Discovery>\
    <Peers><Peer address=\"192.168.1.1\"/></Peers>\
  </Discovery>\
  </Domain></CycloneDDS>");
  participant = dds_create_participant (42, ...);
  ```
  will get you the exact same participant without having to modify Cyclone sources.
* or `dds_create_domain_with_rawconfig`, where you pass in the configuration directly. With this, you become dependent on the internal representation of the configuration (not that it changes often) and you have to keep it around while the domain exists.
  ```C
  #include "dds/ddsi/ddsi_config.h"
  ...
  struct ddsi_config config;
  struct ddsi_config_peer_listelem peers = { .next = NULL, .peer = "192.168.1.1" };
  ddsi_config_init_default (&config);
  config.peers = &peers;
  domain = dds_create_domain_with_rawconfig (42, &config);
  participant = dds_create_participant (42, ...);
  ```

Something to be aware of: if you just call `dds_create_participant` and delete them, deleting the last participant in a domain (within the process) will automatically delete the domain entity as well. If you create a domain entity by calling `dds_create_domain`, it exists until you explicitly delete it.

Another thing to note: the XML strings accept abbreviations. If you grep `dds_create_domain`, you'll find it getting used a lot, with all kinds of shorthand in configuration strings.

Finally, beware of possible typos in the above 🙂

**Comment by zhangyaothu** [comment]
Thanks very much, @eboasson ! Just as your proposed first method, it works!
Still I want to confirm where to get a guide about all the configuration elements, from the header file "ddsi_cfgelems.h" or some other docs.

**Comment by eboasson** [comment]
I'd start with https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/docs/manual/config.rst and https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/docs/manual/options.md. `config.rst` is a bit outdated and was never entirely complete or accurate anyway; `options.md` is generated from `ddsi_cfgelems.h` and so merely a more convenient place to look.

(Another one is https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/etc/cyclonedds.xsd, same content as `options.md`, but useful if you have a nice XML editor.)

**Comment by zhangyaothu** [comment]
Thanks @eboasson! I configure the domain as below for a publisher in FreeRTOS, and a subscriber in ubuntu. The two participant can communicate with other, but I catch many malformed packet sent from the publisher. I wonder how to find the bug, can you explain more ? And I append the pcapng here to assist [rtps.zip](https://github.com/eclipse-cyclonedds/cyclonedds/files/7633178/rtps.zip).
```c
// publisher
const char domain_config[] =
    "<CycloneDDS>"
       "<Domain id=\"any\">"
        "<Sizing>"
          "<ReceiveBufferSize>32 KiB</ReceiveBufferSize>"
          "<ReceiveBufferChunkSize>2 KiB</ReceiveBufferChunkSize>"
        "</Sizing>"
        "<Discovery>"
          "<Peers><Peer address=\"192.168.1.1:17910\"/></Peers>"
        "</Discovery>"
      "</Domain>"
     "</CycloneDDS>";

const dds_entity_t domain_id = 42;

// subscriber
const char domain_config[] =
    "<CycloneDDS>"
      "<Domain id=\"any\">"
        "<General>"
          "<NetworkInterfaceAddress>192.168.1.1</NetworkInterfaceAddress>"
        "</General>"
        "<Sizing>"
          "<ReceiveBufferSize>32 KiB</ReceiveBufferSize>"
          "<ReceiveBufferChunkSize>2 KiB</ReceiveBufferChunkSize>"
        "</Sizing>"
        "<Discovery>"
          "<Peers><Peer address=\"192.168.1.10:17910\"/></Peers>"
        "</Discovery>"
      "</Domain>"
    "</CycloneDDS>";

const dds_entity_t domain_id = 42;
```

**Comment by eboasson** [comment]
Apologies for not responding earlier. I don't quite know what goes wrong, but I find it surprising (to see the least) that sometimes it comes out looking fine, and at other times it comes out garbled. For example, packet 32 is a perfectly fine looking pair of HEARTBEAT messages in a single packet, while packet 34 looks like it ought to be roughly the same is a mess (same source & destination GUID prefix, first HEARTBEAT is the same, then follows a mess).

To me, that makes the primary suspects something related to the/your FreeRTOS port with:
* memory corruption, in particular a problem at [`nn_xmsg_append`](https://github.com/eclipse-cyclonedds/cyclonedds/blob/717d9d7504670a20d96f7e74c00fb6ddc7dfc282/src/core/ddsi/src/q_xmsg.c#L602)
* a problem with the caching of `xmsg`s (see, e.g., [`nn_xmsg_new`](https://github.com/eclipse-cyclonedds/cyclonedds/blob/717d9d7504670a20d96f7e74c00fb6ddc7dfc282/src/core/ddsi/src/q_xmsg.c#L295)
* a problem with the refcounting of them (that seems unlikely, how hard can it be to let `gcc` generate an atomic instruction ...)
* a problem with how `ddsrt_sendmsg` is implemented, it gets called at https://github.com/eclipse-cyclonedds/cyclonedds/blob/717d9d7504670a20d96f7e74c00fb6ddc7dfc282/src/core/ddsi/src/ddsi_udp.c#L169 to send an array of blobs.

If you can write files, you might want to the Tracing/PacketCapture setting: that writes a Wireshark capture file straight from Cyclone. You (obviously) lose the Ethernet, IP and UDP headers (whatever is there is faked) but it should make it quite easy to see whether the corruption happens in `ddsrt_sendmsg` or not.

**Comment by zhangyaothu** [comment]
Thanks a lot @eboasson! Today, in order to check where went wrong, I run the publisher on FreeRTOS only. I caught the ethernet packet using wireshark and attach it at [pub_only.zip](https://github.com/eclipse-cyclonedds/cyclonedds/files/7674557/pub_only.zip). 

Packet 39 and packet 41 goes wrong and wireshark shows unknown submessage id. But other packets I think are right.

And in the above two packets, only submessage id and length goes wrong, other values are correct. This minor error in the constant position seems unlikely to happen in lwip.

Could you help to give more information?

![unkonwn](https://user-images.githubusercontent.com/40783676/145176421-f9bd8364-7583-4e51-b6af-6ea91136a3b5.png)

**Comment by eboasson** [comment]
@zhangyaothu thanks for running it in this way, that reduces the set of possible causes by quite a bit.

I do find it interesting that the IP/UDP header checksums are different for frames 37 and 39, they seem to be the same. That said, that's based on a quick visual inspection and I doubt it has anything to do with why the contents of the RTPS is different. My recollection is that those checksums only concern the IP/UDP headers and not the payload. So that suggests something is going awry in LwIP.

The bit in the payload that is different is 3 bytes starting at offset 0x3e, as is you note, so the header of the timestamp. The way the periodic sending of the participant discovery message works is that the sample content gets constructed once and then reused, but the RTPS message / UDP datagram gets constructed anew each time (by the `tev` thread).

Constructing the RTPS message means calling `create_fragment_message` (in q_transmit.c), where it allocates a new `nn_xmsg` (probably grabbing it from the cache), appending an INFO_TS submessage to it, and then appending a DATA submessage header + a reference to the payload (`nn_xmsg_serdata` is what sets the payload reference).

At that point it queues the `nn_xmsg`, and then the next iteration of the `tev` thread picks up out of the queue and starts building the RTPS message / UDP datagram. It does this by filling the `iov` array in the `nn_xpack` struct. We know it's the first, `xp->iov[0]` points to the header embedded in the `nn_xpack` struct, `xp->iov[1]` points to the "inline" content of the `nn_xmsg` (so it points to the INFO_TS submessage header, which is immediately followed by the timestamp itself and the DATA submessage header). Finally, `xp->iov[2]` then points to the referenced payload. Let's just say it is at very least interesting that it is the first few bytes of `xp->iov[1]` that get mangled.

This gets done all the time, on all platforms. I don't think it is simply a bug in Cyclone, nor do I think it is likely to be a bug in LwIP's `sendmsg`. It could be something related to configuring LwIP for dealing with multi-threaded applications, but that's just a random guess.

There are two things I would suggest doing:
* The publisher process tries to publish data. I don't know off the top of my head how much work is done on the samples it publishes (and that never make it to the network stack if there are no subscribers), and so whether they end up using `nn_xmsg`s temporarily or not. If they don't, this point is meaningless; but if it is, reducing the process to a mere `dds_create_participant` and a sleep would eliminate what interference there could have been. If that makes the difference, I think we can point to the allocation/reusing of `nn_xmsg`s as a likely suspect.
* The second is that (especially in the case just doing `dds_create_participant` and a sleep), it would be interesting to see what the `nn_xmsg` looks like immediately after constructing it — at the time it calls `qxev_msg` in `enqueue_spdp_sample_wrlock_held`. The second interesting point in time is in `nn_xpack_addmsg`. As you know not much else happens, it would be perfectly feasible to either print this to the console, or to memcpy it to a buffer that you can inspect later in a debugger. (I don't know how easy it is to do these things on FreeRTOS, there may be better ways, but this is how I'd go about it on a very unfriendly platform 🙂) With a bit of luck, the corruption still happens but is better localised.

If you could try that and let me know how it goes, I'd be happy to give it some more thought. I suspect it somehow has to do with the port, and so I don't think I can do much more right now with the information I have.

**Comment by zhangyaothu** [comment]
@eboasson , thanks for your help. After days of debugging, I find the issue is caused by the incoherence between data cache and sram. For testing purpose, I disable the data cache and now malformed packet will not occur.

Then I find a more confusing problem, the publisher on stm32 and the subscriber on pc communicate with other about publication, subscription, message information. But the discovery seems failed and the publisher unregistered and disposed.

I attach the pcap file [here](https://github.com/eclipse-cyclonedds/cyclonedds/files/7734866/pub_sub_disable_dcache.zip), would you give some advice?

**Comment by eboasson** [comment]
I've copied some fragments from the RTPS messages below, with some explanation on what's going on:

First, we have the SPDP from .1.01 to .1.1:
```
      1 0.000000000    192.168.1.10          192.168.1.1           RTPS     294    INFO_TS, DATA(p)

Frame 1: 294 bytes on wire (2352 bits), 294 bytes captured (2352 bits) on interface ens38, id 0
Ethernet II, Src: STMicroe_00:00:00 (00:80:e1:00:00:00), Dst: VMware_72:3e:72 (00:0c:29:72:3e:72)
Internet Protocol Version 4, Src: 192.168.1.10, Dst: 192.168.1.1
User Datagram Protocol, Src Port: 62510, Dst Port: 7660
Real-Time Publish-Subscribe Wire Protocol
    Magic: RTPS
    Protocol version: 2.1
    vendorId: 01.16 (Eclipse Foundation - Cyclone DDS)
    guidPrefix: 0110f601352c8c6fd5630aa4
    Default port mapping: domainId=1, participantIdx=0, nature=UNICAST_METATRAFFIC
    submessageId: INFO_TS (0x09)
        Flags: 0x01, Endianness bit
        octetsToNextHeader: 8
        Timestamp: Jan  1, 1970 00:00:03.073000000 UTC
    submessageId: DATA (0x15)
        Flags: 0x05, Data present, Endianness bit
        octetsToNextHeader: 216
        0000 0000 0000 0000 = Extra flags: 0x0000
        Octets to inline QoS: 16
        readerEntityId: ENTITYID_UNKNOWN (0x00000000)
        writerEntityId: ENTITYID_BUILTIN_PARTICIPANT_WRITER (0x000100c2)
        writerSeqNumber: 1
        serializedData
```

Then follow some packets trying to establish the reliable communication needed for discovery, among which the following key message in which .1.10 informs .1.1 that there is one sample available that describes an existing writer on .1.10:
```
     13 16.309708455   192.168.1.10          192.168.1.1           RTPS     142    INFO_DST, HEARTBEAT, HEARTBEAT
...
submessageId: HEARTBEAT (0x07)
        Flags: 0x01, Endianness bit
        octetsToNextHeader: 28
        readerEntityId: ENTITYID_UNKNOWN (0x00000000)
        writerEntityId: ENTITYID_BUILTIN_PUBLICATIONS_WRITER (0x000003c2)
        firstAvailableSeqNumber: 1
        lastSeqNumber: 1
        count: 5
```

Among other things, this triggers an ACKNACK message from .1.1 to ask for a retransmit of that sample:
```
     15 16.310168332   192.168.1.1           192.168.1.10          RTPS     430    INFO_DST, ACKNACK, ACKNACK, INFO_TS, DATA(r), INFO_TS, DATA(m), HEARTBEAT, HEARTBEAT
...
submessageId: ACKNACK (0x06)
        Flags: 0x03, Final flag, Endianness bit
        octetsToNextHeader: 28
        readerEntityId: ENTITYID_BUILTIN_PUBLICATIONS_READER (0x000003c7)
        writerEntityId: ENTITYID_BUILTIN_PUBLICATIONS_WRITER (0x000003c2)
        readerSNState
            bitmapBase: 1
            numBits: 1
            [Acknack Analysis: Lost samples 1 in range [1,1]]
            bitmap: 1
        Count: 1
```

but no response comes ... just another message that tells it that this sample exists, and a request to please retransmit it.
```
     18 16.409671782   192.168.1.10          192.168.1.1           RTPS     142    INFO_DST, HEARTBEAT, HEARTBEAT
...
    submessageId: HEARTBEAT (0x07)
        Flags: 0x01, Endianness bit
        octetsToNextHeader: 28
        readerEntityId: ENTITYID_UNKNOWN (0x00000000)
        writerEntityId: ENTITYID_BUILTIN_PUBLICATIONS_WRITER (0x000003c2)
        firstAvailableSeqNumber: 1
        lastSeqNumber: 1
        count: 7

     19 16.411189286   192.168.1.1           192.168.1.10          RTPS     142    INFO_DST, ACKNACK, ACKNACK
...
    submessageId: ACKNACK (0x06)
        Flags: 0x03, Final flag, Endianness bit
        octetsToNextHeader: 28
        readerEntityId: ENTITYID_BUILTIN_PUBLICATIONS_READER (0x000003c7)
        writerEntityId: ENTITYID_BUILTIN_PUBLICATIONS_WRITER (0x000003c2)
        readerSNState
            bitmapBase: 1
            numBits: 1
            [Acknack Analysis: Lost samples 1 in range [1,1]]
            bitmap: 1
        Count: 2
```

The cycle repeats a few times and then, at the end, you get DATA(w[UD]) when the process stops. That's data being pushed out, rather than a responding to a request for a retransmit.

We know .1.10 is receiving and processing packets, because packet 14 asks for a retransmit of the sample that defines a reader (packet 15 is the response from .1.1) and packet 20 confirms receiving it:
```
     20 16.411730792   192.168.1.10          192.168.1.1           RTPS     134    INFO_DST, ACKNACK, ACKNACK
...
    submessageId: ACKNACK (0x06)
        Flags: 0x03, Final flag, Endianness bit
        octetsToNextHeader: 24
        readerEntityId: ENTITYID_BUILTIN_SUBSCRIPTIONS_READER (0x000004c7)
        writerEntityId: ENTITYID_BUILTIN_SUBSCRIPTIONS_WRITER (0x000004c2)
        readerSNState
            bitmapBase: 2
            numBits: 0
            [Acknack Analysis: Expecting sample 2]
        Count: 6
```

So I think it is reasonable to conclude that the receive thread "recv" works, at least in principle. Sending ACKNACK and HEARTBEAT messages involves the "tev", so that must work, too. What I wonder is why .1.10 doesn't respond to the request for a retransmit. It can limit the amount of data it is willing to retransmit in one go, perhaps if the limit is set to 0 this would be the result — I haven't tried it, I'm just wondering out loud.

Is it possible to get a Cyclone trace out of the .1.10 machine (so the "<Tracing><Verbosity>finest</Verbosity><Tracing>" bit in the configuration)? If you don't have a file system or a console, you can still define a log "sink" and store it in memory (for an example: https://github.com/eclipse-cyclonedds/cyclonedds/blob/7c1ca9d2664d1143f7b6fe5f965c71adae97247b/src/core/ddsc/tests/config.c#L390-L392 is one of several tests that rely on configuring some special function to be called whenever a line is output).

**Comment by zhangyaothu** [comment]
Thanks very much for your help @eboasson ! It realy helps.

After several days of work, I find that the issur is caused by the ethernet transmission API. I think this problem is very specific for stm32. I generate the initialization code from STM32CubeMX, and use the default low_level_output API for transmission on ethernet. This API use one transimission descriptor for one pbuf, and only 4 are configured. This will lead to transmission failure when more pbufs need to be transmitted. So the response is lost on the way, rather not responding.

I try to change the default API to transmit one packet using one transmission descriptor in order to solve the issue. And now it works fine! Thanks again and I will close the issue with this comment.
