### ISSUE TITLE
Latency spikes

### ISSUE THREAD

**Issue by amfern** [eclipse-cyclonedds/cyclonedds#1056]
When I use cyclondds on ros2 galactic I experience abnormal latency spikes, my network is a wireless 3MBit/s network.
I use unicast discovery, and the spikes seems to happen when the dis
My XML profile looks like this, how can i reduce the spikes? 
```
<?xml version="1.0" encoding="UTF-8" ?>
<CycloneDDS xmlns="https://cdds.io/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://cdds.io/config https://raw.githubusercontent.com/eclipse-cyclonedds/cyclonedds/master/etc/cyclonedds.xsd">
    <Domain id="0">
        <Compatibility>
            <ManySocketsMode>single</ManySocketsMode>
        </Compatibility>
        <Internal>
		<HeartbeatInterval max="inf" min="1s" minsched="10s"/> 
		<MinimumSocketReceiveBufferSize>10MB</MinimumSocketReceiveBufferSize>
        </Internal>
        <General>
            <NetworkInterfaceAddress>eth0</NetworkInterfaceAddress>
            <AllowMulticast>false</AllowMulticast>
            <MaxMessageSize>14720B</MaxMessageSize>
            <FragmentSize>1450B</FragmentSize>
            <MaxRexmitMessageSize>1192B</MaxRexmitMessageSize>
            <Transport>udp</Transport>
        </General>
        <Discovery>
            <Peers>
                <Peer address="127.0.0.1"/> <!-- localhost -->
		<Peer address="192.0.11.30"/> <!-- drone 1 - unit it - 6 -->
		<Peer address="192.0.11.40"/> <!--  drone 2 - unit it - 7 -->
                <Peer address="192.0.11.50"/> <!-- drone 3 - unit it - 8 -->
            </Peers>
            <ParticipantIndex>auto</ParticipantIndex>
            <MaxAutoParticipantIndex>100</MaxAutoParticipantIndex>
        </Discovery>
        <Tracing>
            <Verbosity>finest</Verbosity>
	   <OutputFile>/opt/xtra/ping_spikes_log.log</OutputFile>
        </Tracing>
    </Domain>
</CycloneDDS>
```
[ping_spikes_log.log](https://github.com/eclipse-cyclonedds/cyclonedds/files/7627850/ping_spikes_log.log)
![single drone connected](https://user-images.githubusercontent.com/1176319/144103692-5aaeb51d-156e-44be-a477-0c177bc4beee.png)

**Comment by eboasson** [comment]
Hi @amfern, your message got garbled (lucky me that the web doesn't use Cyclone DDS so *that* can't have been a bug in Cyclone 😀):
> I use unicast discovery, and the spikes seems to happen when the dis

but looking at what did come through, the picture and the trace you included, I'm suspecting you meant "when the discovery messages get sent". Because it does seem to be once every 8s.

If you simply write:
```
<Peer address="192.0.11.30"/>
```
it will send discovery data to that address at the port numbers corresponding to participant index 0 ... (max = 9 by default — and this is why that limit is there). With 3 addresses over WiFi, that means a burst of 30 packets every 8s, each packet just shy of 300 bytes. That's 70kB (or thereabouts) and on a 3Mb/s network, that hurts.

What you can do to reduce it (if you can't rely on multicast for participant discovery, i.e. if the WiFi default of `AllowMulticast` = `spdp` doesn't work reliably, which I assume to be the case because you explicitly set it to `false`) is to see whether you *know* which port numbers are relevant, and then add only those ports.

E.g., if each drone runs only a single process, that'll use participant index 0, and so port 7410. Writing `<Peer address="192.0.11.30:7410"/>` then makes it send just one packet to that IP:PORT. That'll reduce the burst by a factor of 10 and is probably enough to make things work fine.

Alternatively, you could perhaps run base station with empty set of peers (or just localhost) and the drones with just the IP:PORT for the base station. Then you don't need to worry what the port number the drones use and you only need to worry about how you force the base station to use a known port number.

**Comment by amfern** [comment]
> I'm suspecting you meant "when the discovery messages get sent"

yes, this is exactly what i meant to write :)

Thanks for the detailed reply, unfortunately we have multiple nodes on the drone and multiple nodes on the ground station.

So if i apply the changes you suggested, such as:
- predefined participant ids for ros2 nodes
- reverse the discovery, so the drones would discover the nodes on the ground station using IP:PORT

Would this reduce the traffic?

Also will try `AllowMulticast = spdp`, will ipdate how it went.

**Comment by jwrl7** [comment]
Curious how these changed turned out. I may be facing a similar issue but not over wifi. Just locally on the system when using a non-ROS2 node that uses native cycloneDDS to talk to the ROS2 ecosystem on the same hardware. 

Im seeing a periodic increase in latency for the non-ROS2 node that seems to correlates to the number of subscribers on acting on the cycloneDDS writers. 

I have not dug too far into the cycloneDDS.xml parameters. Any recommendations would be welcomed. Thanks!

**Comment by amfern** [comment]
Hey @jwrl7,
I don't have an answer as I didn't get around to play with the DDS setup lately.
But someone on my team got to do the changes, and I may have an update for you soon.

**Comment by thijsmie** [comment]
Hi @amfern and @jwrl7,
I am closing this because your question was most probably answered. Feel free to add your feedback below, then I'll label this issue as "knowledge-base".
