### ISSUE TITLE
abort() in dds_stream_countops1 for deeply-nested message

### ISSUE THREAD

**Issue by ErikAtApex** [eclipse-cyclonedds/cyclonedds#1060]
Hi folks!

We recently received [an interesting report](https://gitlab.com/ApexAI/performance_test/-/issues/134) in the Apex.AI performance_test repository. It seems that Cyclone DDS is having trouble with a specific deeply-nested message.

- [`Struct32k`](https://gitlab.com/ApexAI/performance_test/-/blob/master/performance_test/msg/Struct32k.idl) is the message in question
- A `Struct32k` contains 8x [`Struct4k`](https://gitlab.com/ApexAI/performance_test/-/blob/master/performance_test/msg/Struct4k.idl) members
- A `Struct4k` contains 16x [`Struct256`](https://gitlab.com/ApexAI/performance_test/-/blob/master/performance_test/msg/Struct256.idl) members
- A `Struct256` contains 16x [`Struct16`](https://gitlab.com/ApexAI/performance_test/-/blob/master/performance_test/msg/Struct16.idl) members

When running the tool with `Struct32k`, the `abort` is generated when the first message is published. Strangely, the `Struct4k`, `Struct256`, and `Struct16` messages all work fine. Do you have any ideas why the `Struct32k` message specifically would cause this particular `abort`?

If you wish to observe this yourself, it can be easily reproduced:

```
git clone git@gitlab.com:ApexAI/performance_test.git
cd performance_test
docker build . -f dockerfiles/Dockerfile.CycloneDDS -t performance_test_cyclone_dds
docker run -it performance_test_cyclone_dds bash
/opt/performance_test/lib/performance_test/perf_test -c CycloneDDS -m Struct32k
```

This Dockerfile is using the default Cyclone DDS in ROS 2 rolling, but I have also tried with 0.8.1, with the same results.

Thanks a ton!

**Comment by eboasson** [comment]
@ErikAtApex it is the IDL compiler writing out an incomplete serializer (see the end of the generated output), I haven't (yet) tried to figure out why this happens. If it had written it out, the result would have been a horrific array of roughly 64k integers, because it enumerates *all* the primitive members explicitly.

In `master`, because of all the work for XTypes, changes got merged in where each type is written out once, and that works fine. However, I'm afraid that backporting those changes into the 0.8 branch defeats the purpose of having a release branch ...

Some observations:
* Serializing types like this by processing each field independently is stupid, and things could be improved by recognising that these are actually equivalent to arrays: that would make it run much faster (the base 16-byte array would become a memcpy).
* Changing just one of the structs to use an array makes it work. Which one you change affects throughput quite dramatically: in a `RelWithDebInfo` build with address + undefined behaviour sanitizer enabled (so not quite your representative release build):
  * changing `Struct16` to be an array of 16 octets: 150k/s
  * changing `Struct32k` to be an array of 8 `Struct4k`: 1.4k/s
* That it fails is a bug, no question about it, but I do have to wonder: is a type like this ever going to show up in an application? (*) I'm tempted to say that the bug could be fixed by finding whatever limit in the IDL compiler causes the problem, and then simply declaring any type exceeding that limit to be unsupported and raise an error doing compilation of the IDL. That would not help you, I am aware of that, but I hope you understand the sentiment.

(*) I do understand how it came to be in this case.

**Comment by eboasson** [comment]
One more note: the problem is specific to the C backend. The C++ code generator deals with it just fine. So a work-around other than changing the type definition could be to use the C++ binding. That seems feasible for `performance_test`, and it would make it more relevant to C++ application code as well.

**Comment by ErikAtApex** [comment]
@eboasson you're the best. That was such a great explanation, and I can't really think of any more questions. We're currently adding another performance_test plugin for the C++ binding, separate from the existing C plugin. It sounds like we should also upgrade the C plugin to work with 0.9, and I'm comfortable living with the bug until we get to it. Thanks Erik. Cheers!
