### ISSUE TITLE
Question about assert in Debug build mode

### ISSUE THREAD

**Issue by yooouxin** [eclipse-cyclonedds/cyclonedds#1065]
I want to build cyclonedds in Debug mode and run some examples.But I was failed,it will crash in some assertion.
I use cmake command like this,and run hello world example
```
cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_EXAMPLES=ON ..

bin/HelloworldPublisher

=== [Publisher]  Waiting for a reader to be discovered ...
HelloworldPublisher: /home/youxinxin/repos/cyclonedds/src/core/ddsi/src/ddsi_entity_index.c:404: entidx_lookup_proxy_writer_guid: Assertion `is_writer_entityid (guid->entityid)' failed.
[1]    13408 abort (core dumped)  bin/HelloworldPublisher
```
Everything ok if build in release mode,so is this assertion always be checked failed?

**Comment by eboasson** [comment]
No, it should never assert (and we run the CI both in Debug mode and in Release mode).

I'm really interested in what it is doing when it crashes (a stack trace would be a good start). If it has something to do with data that is on the network, a Wireshark capture would also be interesting.

**Comment by yooouxin** [comment]
@eboasson Thanks for your reply.
Here's the stack trace
```
#0  0x00007ffff7ca1d22 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff7c8b862 in abort () from /usr/lib/libc.so.6
#2  0x00007ffff7c8b747 in __assert_fail_base.cold () from /usr/lib/libc.so.6
#3  0x00007ffff7c9a616 in __assert_fail () from /usr/lib/libc.so.6
#4  0x00007ffff7eb70b1 in entidx_lookup_proxy_writer_guid (ei=0x5555555768d0, guid=0x7ffff51771a0)
    at /home/youxinxin/repos/cyclonedds/src/core/ddsi/src/ddsi_entity_index.c:404
#5  0x00007ffff7f0ddce in set_sampleinfo_proxy_writer (sampleinfo=0x7ffff5177320,
    pwr_guid=0x7ffff51771a0) at /home/youxinxin/repos/cyclonedds/src/core/ddsi/src/q_receive.c:284
#6  0x00007ffff7f0df85 in valid_Data (rst=0x7ffff51796a8, msg=0x7ffff5179580, size=292, byteswap=0,
    sampleinfo=0x7ffff5177320, keyhashp=0x7ffff51772b0, payloadp=0x7ffff51772a8,
    payloadsz=0x7ffff5177284) at /home/youxinxin/repos/cyclonedds/src/core/ddsi/src/q_receive.c:339
#7  0x00007ffff7f18769 in handle_submsg_sequence (ts1=0x55555556be40, gv=0x555555573948,
    conn=0x555555576370, srcloc=0x7ffff5177440, tnowWC=..., tnowE=..., src_prefix=0x7ffff5179558,
    dst_prefix=0x0, msg=0x7ffff5179550 "RTPS\002\002\210\210", len=340,
    submsg=0x7ffff5179580 "\025\005 \001", rmsg=0x7ffff5179520, rtps_encoded=false)
    at /home/youxinxin/repos/cyclonedds/src/core/ddsi/src/q_receive.c:3057
#8  0x00007ffff7f1954b in do_packet (ts1=0x55555556be40, gv=0x555555573948, conn=0x555555576370,
    guidprefix=0x0, rbpool=0x55555557e620)
    at /home/youxinxin/repos/cyclonedds/src/core/ddsi/src/q_receive.c:3296
#9  0x00007ffff7f1a4fb in recv_thread (vrecv_thread_arg=0x555555574118)
    at /home/youxinxin/repos/cyclonedds/src/core/ddsi/src/q_receive.c:3576
#10 0x00007ffff7f1bbfd in create_thread_wrapper (ptr=0x55555556be40)
    at /home/youxinxin/repos/cyclonedds/src/core/ddsi/src/q_thread.c:241
#11 0x00007ffff7f6b301 in os_startRoutineWrapper (threadContext=0x55555557e820)
    at /home/youxinxin/repos/cyclonedds/src/ddsrt/src/threads/posix/threads.c:165
```

And I find that there are many RTPS data packages in my network,so this issue may be releated to this?

**Comment by eboasson** [comment]
> And I find that there are many RTPS data packages(from other DDS implemention) on my network,so this issue may be releated to this?

I can tell: `RTPS\002\002\210\210` — that "other" implementation is using an undefined vendor code, by the way. If you're not deliberately fuzzing, you might want to try to find out who is using such a weird implementation and tell them to switch to Cyclone DDS instead 🙂

Back to the problem. It shouldn't have accepted the DATA submessage with something in which the source entity id is not a writer id, because the `assert` is there for sanity checks on the internals and is not supposed to ever get unexpected input. For this particular case, the lookup it is performing is guaranteed to return "not found" (because it is looking for a writer and there won't be any with a non-writer entity id), and so in a release build, the `assert` disappears and it'll just ignore the data. As it should.

So this can be fixed easily enough, but what really matters is to catch all places in the message validation where it can pass an entity id of an "attacker"-controlled kind to the lookup functions. That takes some time and means I (likely) won't be able to fix it today.
