### ISSUE TITLE
Segmentation fault occurs in q_addrset.c

### ISSUE THREAD

**Issue by joeyzhuzhuwei** [eclipse-cyclonedds/cyclonedds#1066]
Detail segmentation fault info：
![image](https://user-images.githubusercontent.com/95666953/145372771-79be607c-0773-49c0-b004-847f187a4c57.png)

Detail config info：
![image](https://user-images.githubusercontent.com/95666953/145372900-61ce27eb-e009-42cc-b91d-ceb5a26725e2.png)

Can you help solve this problem

3X

@eboasson

**Comment by k0ekk0ek** [comment]
Hi @joeyzhuzhuwei! First thought that pops into my head is that it's a little strange `joinleave_spdp_defmcip` is in there if you're really using `raweth` because raw ethernet doesn't use IP addresses. Of course, I may very well be wrong or it was just easier to reuse a function name or something. I was planning on working my way through the code and check if I can spot any oddities. It doesn't seem to be the current master branch?

**Comment by joeyzhuzhuwei** [comment]
Hi @k0ekk0ek
master  & release/0.8.x & tag 0.8.0beta6 all have this problem.
And then setting AllowMulticast to false, also reports some errors，
![image](https://user-images.githubusercontent.com/95666953/145503620-a2366cf5-cc99-45c6-9cc6-28ef544e85ba.png)

Config info：
![image](https://user-images.githubusercontent.com/95666953/145503701-1a913877-4e29-4b5a-801c-c3188999d03e.png)

**Comment by eboasson** [comment]
@joeyzhuzhuwei it is an initialisation problem; I must have broken it when I added support for multiple interfaces. (The trouble with raw ethernet support is that it rarely gets used and that I can't test it on the CI because of requires privileges we don't have on Azure. It is not a good excuse — I can emulate it with UDP, for example, it is only some background as to when/what/why it broke.)

A did a quick bit of hacking: https://github.com/eboasson/cyclonedds/commit/eb4eb94da4dbaef6faff9c01216a306bdbdabc34 makes it initialize for me (with multicast enabled, multicast still disabled causes trouble). I need to spend some more time on it to be sure that the changes in initialization order do not break things and I quickly added a "FIXME" as a note to myself that I really don't want to commit in master ...

But at least it means I know where it went wrong, that a fix is forthcoming and that it should allow you to continue what you were trying to do.

**Comment by joeyzhuzhuwei** [comment]
@k0ekk0ek 
OK.
Please deal with it 
THX

**Comment by eboasson** [comment]
@joeyzhuzhuwei I suspect English is not your native language (it isn't mine either) and so may not have realised that "OK. Please deal with it. THX" comes across as rather unfriendly and out of place when you're even getting a link to commit that addresses your problem so that you can move forward even before the fix is finalised and merged.

I assume it is the language barrier and treat it as a friendly comment.

**Comment by joeyzhuzhuwei** [comment]
sorry，English is not my native language.
