### ISSUE TITLE
pingpong test may be finishing with coredump

### ISSUE THREAD

**Issue by yds629** [eclipse-cyclonedds/cyclonedds#1074]
./bin/RoundtripPing -l 1024 0 10
 payloadSize: 1024 | numSamples: 0 | timeOut: 10

 Waiting for startup jitter to stabilise
 Warm up complete.

Latency measurements (in us)
           Latency [us]                                   Write-access time [us]       Read-access time [us]
Seconds     Count   median      min      99%      max      Count   median      min      Count   median      min
        1     15312       24        6      104      771      15312       17        5      15312        0        0
        2     13838       30       14      101      443      13838       18        5      13838        0        0
        3     13833       28       18       99      685      13833       15        5      13833        0        0
        4     13689       30       12      100     2764      13689       15        7      13689        0        0
        5     13355       29       16      103      753      13355       15        7      13355        0        0
        6     13473       26       15       99      618      13473       14        6      13473        0        0
        7     12341       28       18      104      395      12341       14        6      12341        0        0
        8     12374       28       18      103      692      12374       14       11      12374        0        0
        9     14400       26       18       94      493      14400       14        5      14400        0        0
       10     14809       25       16       96      712      14809       14        4      14809        0        0
       11     12430       28       15      108     3651      12430       15        5      12430        0        0

 Overall    149962       28        6      101     3651     149743       17        4     149705        0        0
**1639723757.650785 []     recvUC: dds_write_ts: Bad Parameter
Aborted (core dumped)**

Linux ubuntu 5.4.0-91-generic #102~18.04.1-Ubuntu SMP Thu Nov 11 14:46:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by eboasson** [comment]
That aborting and dumping core is caused by a rather stupid error handling in the example: it uses `DDS_FATAL` which combines a log message with a call to `abort()`. It is slowly being removed from the code base and there are only a few left in the core.

A "bad parameter" error from `dds_write_ts` means:
* an invalid handle/non-writer handle
* a null pointer for the data to be published
* a negative number in the timestamp field
* some weird edge cases (e.g., junk instead of a valid sample)

For the roundtrip example, we can rule out the null pointer for the data and the negative time stamp. I am also quite certain that none of the weird edge cases can be involved. So that leaves the case where the writer handle passed in is invalid.

*That* particular issue is plausible: when stopping, it simply calls `dds_delete` on the participant, which in turn delete all entities the participant created. It does this depth first, but otherwise in an arbitrary order. In particular, it may delete the data writer before it deletes the data reader. So when using a listener, there is a window during which a sample can be received and then `dds_write_ts` called when the writer has already been deleted. That would give rise to this error.

So when this happens, if you look at the stack traces in the core dump, you'll see that the main thread is deleting stuff, and likely blocked on deleting the reader because it is still executing the listener.

This really is an attempted use-after-free in the roundtrip example code. The mechanism with handles and how the handles are allocated exists precisely to protect the system against this type of error. It is actually nice to me to see the protections doing their job!

But, yes, calling abort in this case is rather stupid, and it would also be better to prevent this race condition. That is as simple as calling `dds_set_listener(reader, NULL)` prior to calling `dds_delete(pp)` in https://github.com/eclipse-cyclonedds/cyclonedds/blob/717d9d7504670a20d96f7e74c00fb6ddc7dfc282/examples/roundtrip/pong.c#L150.

Incidentally, [`ddsperf`](https://github.com/eclipse-cyclonedds/cyclonedds/blob/717d9d7504670a20d96f7e74c00fb6ddc7dfc282/src/tools/ddsperf/ddsperf.c#L2633) gets this right. (Except that the comment fails to note that this particular race condition ... but no one trusts comments anyway 😁)

**Comment by yds629** [comment]
@eboasson  Thanks for the answer， I add   dds_set_listener (reader, NULL);  dds_delete (reader); before dds_delete() to resolve it.
