### ISSUE TITLE
Is it possible to port security features on STM32H7 with FreeRTOS

### ISSUE THREAD

**Issue by zhangyaothu** [eclipse-cyclonedds/cyclonedds#1088]
I port the helloworld example on STM32H7 with FreeRTOS, and now I want to add security features. But when I add the security sources, I encounter several questions.
* What are the builtin_plugins functionalities and are they necessary?
* Is it possible to use [mbedtls](https://github.com/ARMmbed/mbedtls) to save flash size, istead of openssl?
* One member of the struct dds_security_plugin is [lib_handle](https://github.com/eclipse-cyclonedds/cyclonedds/blob/8e7fd85df9042f5ef217e6852f471150442804fc/src/security/core/include/dds/security/core/dds_security_plugins.h#L27), the type of which is ddsrt_dynlib_t, but dynlib is disabled when FreeRTOS is used. How to handle this?

**Comment by k0ekk0ek** [comment]
Hi @zhangyaothu! There's no reason why security in itself wouldn't work on that platform, there's a couple of reasons why it currently doesn't. Nothing that can't be fixed with a little elbow grease, but still. We've been meaning to include support for mbedtls and other implementations, especially because OpenSSL just isn't a terrific fit for embedded devices. The plugins provide the actual security implementation, like authentication, authorization, etc. The builtin ones are simply our implementation of them. User written plugins would work just as well. To use mbedtls, you could choose to implement plugins that provide similar functionality based on mbedtls. The problem as you stated lies in the fact that they're required to be dynamically loadable libraries, which is something FreeRTOS does not support. IMHO simply including a plugin in the binary itself should be configurable at compile-time and would solve the problem for embedded "operating-systems", unfortunately it's not currently implemented.

**Comment by thijsmie** [comment]
In short: yes it is possible, if you're willing to put in the work. If someone is willing to volunteer we're happy to help! :smile:

**Comment by CodeTornato** [comment]
@zhangyaothu 
es
