### ISSUE TITLE
Use package.xml versioning

### ISSUE THREAD

**Issue by Aposhian** [eclipse-cyclonedds/cyclonedds#1089]
It would be nice if the `package.xml` semantic version was bumped with every change. Without being diligent on this, ROS users get nonsensical debian package versions like these:
```
$ apt policy ros-galactic-cyclonedds

ros-galactic-cyclonedds:
  Installed: 0.8.0-5focal.20210608.002038
  Candidate: 0.8.0-6focal.20211217.210911
  Version table:
     0.8.0-6focal.20211217.210911 500
        500 http://packages.ros.org/ros2/ubuntu focal/main amd64 Packages
 *** 0.8.0-5focal.20210608.002038 100
        100 /var/lib/dpkg/status
```
where both packages are `0.8.0`, but with different build numbers, even though `0.8.0-6` has features that `0.8.0-5` does not, like `dds_is_loan_available`.

**Comment by k0ekk0ek** [comment]
Hi @Aposhian! Without knowing all the details, I'd say that sounds like a reasonable request :+1: And definitely something we should include in the release process. @eboasson, we should probably put it on a checklist or include it in some script so we don't forget this(?)

The version numbering does indicate that you're referring to custom (if that's the right term) versions. The `releases/0.8.x` branch should only get fixes, and if a new version is released the minor number gets bumped. e.g. we currently have a `0.8.1`. Actually, upon checking this feature has always been in the `0.8.0` release. Can it be that the first iteration of packages followed the master branch? If so, there seem to be two unrelated problems here right(?) I'm unfamiliar with how these packages get built, but if the first iteration of packages is created from e.g. master, the maintainer should probably use something like (`0.8.0~<data/rcX>`) at first so that it's obvious this particular version is not based on the actual `0.8.0` yet and switch to the release branch once we've tagged.

**Comment by Aposhian** [comment]
Yes, I'm not sure why the apt binary at `ros-galactic-cyclonedds=0.8.0-5focal.20210608.002038` does not have `dds_is_loan_available`, but it can be confirmed by running:
```
$ nm -gD /opt/ros/galactic/lib/x86_64-linux-gnu/libddsc.so.0 | grep is_loan_available
00000000000c1fc0 T is_loan_available
```

**Comment by Aposhian** [comment]
It also makes it difficult to see what changes are in what versions of 0.8.x, since the CHANGELOG is not updated for it. :joy:

**Comment by eboasson** [comment]
Thanks @Aposhian for taking the time to provide so many details (both here and https://github.com/ros2/rmw_cyclonedds/issues/362#issuecomment-1005029772). The version of cyclone used by Galactic was originally taken from a special branch and only recently switched to the official 0.8.1 release.

The other part is very simply a mess-up on my side. I forgot to update `package.xml` ... If you look at the 0.8.1 release, `package.xml` still says `0.8.0`; and indeed if you look at master, it *also* still says `0.8.0`. If I had updated it properly, the problem would never have surfaced. No versioning machinery will save you from such mistakes.

I'll fix it by bumping the version number to 0.8.2 (including `package.xml` this time) and I'll try to add a check to the CI that the package.xml and the CMakeLists.txt versions so it doesn't happen again.

**Comment by Aposhian** [comment]
When will the `0.8.2` release be published to the `ros-galactic-cyclonedds` debian package?

**Comment by eboasson** [comment]
@Aposhian, that depends on when the next patch release of Galactic gets done. There is "a repository" "somewhere" on GitHub that defines the exact content of the releases and I believe the way this works is that the `cyclonedds` entry there needs to be set to `0.8.2`. The trouble is that I forgot where exactly that repository is ...

@clalancette would probably know more about all this, though he is busy enough that I prefer not to bother him if I don't have to. I am sure he or someone else at OR can give you more details on the plans for a patch release of Galactic and how to verify that it will indeed include `0.8.2` for `cyclonedds`.
