### ISSUE TITLE
What does the filename prefix q stands for

### ISSUE THREAD

**Issue by skysky97** [eclipse-cyclonedds/cyclonedds#1113]
This might be a boring question, but it really bothers me a lot.

**Comment by eboasson** [comment]
Haha! No it is actually a very good question, and one without a good answer: parts of Cyclone's code base are pretty old (10+ years) and have moved around and were reshuffled a bit during its existence. The `q_` originates in that history (the same is true for the `nn_` you must also have seen) and while I really want to replace it with a proper prefix I never seem to get around to it ... In part because there are more interesting things to do, but also in part because it affects any PRs that touch them. But now with XTypes mostly sorted, I can't really use the latter argument anymore.

**Comment by skysky97** [comment]
Thanks, I got it.
