### ISSUE TITLE
Unknown origin of USER TRAFFIC packets

### ISSUE THREAD

**Issue by omertal88** [eclipse-cyclonedds/cyclonedds#1146]
Hello,

I'm using CycloneDDS as RMW of ROS2 nodes in my system. I have an issue where after my system runs for a long time, large packets of USER TRAFFIC are sent to another node (on a different machine - running micro ROS Agent).

Looking at the code, I can't find any reason why these packets would be sent. Also, when I take the agent down - the traffic goes back to normal.
I have a Wireshark capture where you can see how the traffic starts to climb up. Is there a way I can use Wireshark and the trace log to find the publisher (or topic name) which creates this traffic?

Please see the attached wireshark capture. You can see the spike in RTPS traffic at around time=350.
[wireshark-capture.zip](https://github.com/eclipse-cyclonedds/cyclonedds/files/8056044/wireshark-capture.zip)

Another observation worth mentioning, I looked at one of the big packets sent from `192.0.5.15` to `192.0.5.35`. In the serialized data section I expected to see random characters (as it is serialized)... But instead I saw an interesting, yet redundant pattern. For example:
```ä_*¦H°-/]EÜà @êÂÀÀ#êÿ9ë«RTPSÅPæwgWg$	|	bfV&Ä8Ð
ª 9ÅPæwgWg$Á/	xtra_osdNÅPæwgWg$ÅPæwgWg$
ÅPæwgWg$ÅPæwgWg$ÅPæwgWg$ÅPæwgWg$ÅPæwgWg$ÅPæwgWg$ÅPæwgWg$ÅPæwgWg$ÅPæwgWg$ÅPæwgWg$ÅPæwgWg$!ÅPæwgWg$"ÅPæwgWg$#ÅPæwgWg$$ÅPæwgWg$%ÅPæwgWg$(ÅPæwgWg$)ÅPæwgWg$*ÅPæwgWg$,ÅPæwgWg$-ÅPæwgWg$.ÅPæwgWg$/ÅPæwgWg$0ÅPæwgWg$1ÅPæwgWg$2ÅPæwgWg$3ÅPæwgWg$4ÅPæwgWg$5ÅPæwgWg$6ÅPæwgWg$7ÅPæwgWg$9ÅPæwgWg$;ÅPæwgWg$=ÅPæwgWg$?ÅPæwgWg$@ÅPæwgWg$AÅPæwgWg$BÅPæwgWg$CÅPæwgWg$DÅPæwgWg$EÅPæwgWg$FÅPæwgWg$GÅPæwgWg$HÅPæwgWg$IÅPæwgWg$JÅPæwgWg$KÅPæwgWg$MÅPæwgWg$OÅPæwgWg$QÅPæwgWg$SÅPæwgWg$TÅPæwgWg$UÅPæwgWg$VÅPæwgWg$W 
```

You can see `xtra_osd` which is probably the name of the node which sent the message. Then a repeating pattern of `ÅPæwgWg$` followed by all english alphabet characters, digits and keyboard symbols one at a time.

Thank you.
Omer

**Comment by eboasson** [comment]
Hi @omertal88, let me start with the self-help section of the answer:

> I have a Wireshark capture where you can see how the traffic starts to climb up. Is there a way I can use Wireshark and the trace log to find the publisher (or topic name) which creates this traffic?

Yes. Each DATA(_FRAG) message, or really any message but these are the ones that triggered it, contain a writer GUID. You have to look at the dissection of the packet, usually the full GUID is formed by the `guidPrefix` in the message header (*) and the `writerEntityId` in the DATA submessage header.

Now, I assume you mean this (there are many more following, I think this is the first):

<img width="739" alt="image" src="https://user-images.githubusercontent.com/16984005/153822689-35f00726-cb41-4f94-b717-46ede03afad9.png">

and so for the selected message, the full writer GUID is `c5501001:e6776757:1d006724:403`. Those GUIDs also occur in the Cyclone DDS trace, formatted like I did just now.

Wireshark tries to map them to topic names, it can do only do that for the "built-in ones" (because they have hard-coded entity ids, and Wireshark shows them as, for example, `writerEntityId: ENTITYID_BUILTIN_SUBSCRIPTIONS_WRITER (0x000004c2)`) and for those application writers for which the capture happens to include the SEDP message describing the writer. In those cases, Wireshark prints the topic name in the summary:
```
65772	350.983387360	192.0.5.15	192.0.5.35	RTPS	146	INFO_TS, DATA -> rt/drn6b5a05eb/rc/override/raw
```
as well as including the topic and type names and a reference to the SEDP message in the dissection. For the messages you are asking about, clearly the writer's SEDP messages is not in the capture and hence Wireshark won't help.

The Cyclone trace always starts at the beginning and so it always has the information (not doing log rotation can be an advantage). It also includes the topic name for each message because it makes life much more convenient while adding (relatively) little text to the (already gigantic) trace files. You may also want to have a look at this if you intend to also dive into the Cyclone DDS trace: https://gist.github.com/eboasson/56aa337c558151c7d9598214418f2fed which I started doing and meant to extend a bit further before turning it into a PR on Cyclone — I probably should just add it as it is ...

Sometimes you can make an informed guess and this is one of those cases. ROS 2 used to map each ROS 2 node to a DDS DomainParticipant, but most DDS implementations have horrendous overhead when you do that. Cyclone is a notable exception, but I failed to convince them not to change it and so now it uses a single DDS DomainParticipant per process (or more accurately "context" but they are almost synonymous). (https://github.com/ros2/design/pull/250 is a good starting point if you're curious.)

For the most part, this was a trivial change, but not for introspecting the ROS 2 graph: it used to be that you could derive all necessary information from the DDS discovery data, but that change means the mapping between readers/writers and ROS 2 nodes no longer exists in the discovery data. This was solved by adding a transient-local, keep-last-1 "ros_discovery_topic" containing a list of all ROS2 nodes and how the various endpoints relate to them. In short, it contains tons of GUIDs — for some reason stored as 24 byte arrays instead of 16 byte arrays ... The writer of this topic is one of the first writers created when a ROS application starts and so writer entity id `403` is a good candidate. Furthermore, if you look at the contents of the data, there is clear pattern which fits with it containing many GUIDs.

This topic gets published every time the application creates or deletes a ROS 2 subscription or publisher. If you look at the other traffic around the time this data is being published in the trace, you can see it correlates with `DATA(r[UD])` and `DATA(w[UD])` messages. That's how Wireshark indicates that it is a reader/writer SEDP message with flags "unregister" and "dispose", code-speak for "endpoint deleted". So that's what you are looking at here.

The end-result of trying to work around a nasty performance problem in some DDS implementations by changing the ROS 2 node-to-DDS DomainParticipant mapping is therefore a significant increase in data associated with discovery and that's what you're seeing here. As predicted. And your case is actually a mild case ...

(*) The protocol allows data from multiple DomainParticipants to be combined in a single packet, which is quite common in OpenSplice, but not with most implementations, and certainly not with ROS 2 because it only uses a single DDS DomainParticipant. There exists a special `INFO_SRC` submessage that changes the source `guidPrefix` for subsequent submessages in the same message.

**Comment by omertal88** [comment]
Hello @eboasson 

First allow me to show my deepest appreciation for your detailed answer.

Secondly, what did you mean by 
> changing the ROS 2 node-to-DDS DomainParticipant mapping
I do assign ParticipantIDs statically for each node that needs to communicate over a wireless channel, to actually reduce the discovery traffic. Just wondering is that what you meant? How did you know I'm doing so, and also, how come that creates an increase in discovery traffic instead of decreasing it? After all, each node only needs to send discovery data to pre-defined ports.

Since I'm using a wireless channel, I can't use multicast discovery, would you say a better alternative is to use SPDP and just set MaxAutoParticipants to a reasonable number? I feel that is wasteful.

Thirdly,
> This topic gets published every time the application creates or deletes a ROS 2 subscription or publisher. If you look at the other traffic around the time this data is being published in the trace, you can see it correlates with DATA(r[UD]) and DATA(w[UD]) messages. That's how Wireshark indicates that it is a reader/writer SEDP message with flags "unregister" and "dispose", code-speak for "endpoint deleted". So that's what you are looking at here.
I don't believe I create or delete any publisher / subscriber in my app during that time. Could it be that it happened in the other end? 

Thank you again for your help.
Omer

**Comment by omertal88** [comment]
OK yeah that actually makes perfect sense to me. Because I think during the time of t=350, I swapped the publishers / subscriptions of two devices (.35 and .75). You can see that after t=351, there are no more messages like that. During the period of t>351, no new publishers / subscribers were created and yet traffic is very high.
![image](https://user-images.githubusercontent.com/92671136/153877594-373ce447-5745-4794-b6ab-c35b5e579132.png)

**Comment by omertal88** [comment]
I've noticed this pattern but not sure if it means anything:
![image](https://user-images.githubusercontent.com/92671136/153885561-df64eddd-9173-4d29-990b-841cdaf65faa.png)
ACKNACK which keeps saying the same sample is missing 
![image](https://user-images.githubusercontent.com/92671136/153885611-ddf07446-fb6e-4072-ab02-d980c52cba0a.png)
followed by a big packet of data to ACKNACK sender.
The same sample `1545` is missing in all ACKNACK messages I see.

**Comment by eboasson** [comment]
I wrote what's below before you added the excerpt from the Cyclone trace. Thanks for sharing that, it confirms some of things I could only suspect before. Now we have to figure out whether my suspicions are correct :)

I have a suspicion. There are basically four cases in requesting retransmits:
1. `ACKNACK` requests retransmit of "small" sample, followed by `DATA` in response
2. `ACKNACK` requests retransmit of "large" sample, followed by all `DATA_FRAG`s making up the sample in response
3. `ACKNACK` requests retransmit of "large" sample, followed by some but not all `DATA_FRAG` in response
4. `NACK_FRAG` requests retransmits of some (perhaps all) fragments of a "large" sample, followed by ≥1 `DATA_FRAG` in response

Naturally, some or all of the packets in the response can be lost in transmission. There are recovery mechanisms to deal with that and they start with a `HEARTBEAT` message that suggests/requires the readers to acknowledge what they have received and request retransmissions for what is missing.

From packets 166835+166837 en 166843+166846 and knowing Cyclone, I suspect you're may be looking at case 3. When a remote reader requests a retransmission of a large sample, it only retransmits the first fragment and relies on the reader to request the remaining fragments via `NACK_FRAG`. (I learnt the hard way how much of a difference this makes in the predictability of the system when samples very in size from a few bytes to tens of megabytes.) If the other side doesn't request the remaining fragments using `NACK_FRAG` but simply asks for a full retransmit using an `ACKNACK` message, then this leads to a cycle.

The little bit I can see fits with this pattern. This is all very much a grey area in the specs, it doesn't say anywhere that you must use `NACK_FRAG`, though I do think it is daft not to use it.

Two things are interesting now:
1. Does the Fast-DDS side indeed receive the `DATA_FRAG` sent in response to its `ACKNACK`? (I suspect so, otherwise nothing would work, but it is best to check the basics.)
2. Is there anything weird in what happened before that cause Fast-DDS to not behave in a sensible manner? (Maybe it never does, they may have a different sense of what is "sensible" then I do.)

If it is what I suspect, a quick work-around that should at least work for a while is to raise the maximum message size and maximum fragment size in Cyclone. In the capture you shared everything is <16kB, so setting: `General/MaxMessageSize` to `65500B` and `General/FragmentSize` to `62kB` would avoid all fragmentation and presumably work around the problem.

But I'd be grateful if you could have a look into those two questions as well. Work-arounds are not solutions, and this one falls apart for anything over 62kB.

**Comment by omertal88** [comment]
Hey again,

So I'm not familiar with Fast-RTPS logs so I'll need some time to dig into it.
In the meanwhile here's the answer to your 2nd question:
In our system, we have one main device and multiple client devices which can connect to it.
Only one client can be "active" at a time. This includes video (RTSP) + control messages (DDS).
When we wish to switch between clients, we connect to the new RTSP server of the other client, delete all publishers / subscribers of the old client, and create new ones of the new client.
I've noticed that when we do this switch repeatedly, then the network traffic starts to climb.
So an answer to your question: Yes. It happens when we delete old publishers / subscribers and create new ones. After many iterations - this issue will occur. Hope it helps.

Thank you once again :)

**Comment by omertal88** [comment]
I think I may have a theory...
You said to increase the packet size... I think maybe to solution would be to lower the packet size. I notice that only large packets fail to be sent to the other end. Maybe the issue is the MTU.
I'm trying to lower the MaxFragmentSize to 500 B, and reproduce the issue.

Will update on the results...

**Comment by omertal88** [comment]
@eboasson,
I've noticed in my trace file that the first sample of ros_topic_info was:
```1644848544.774573 [0] xtra_osd_n: write_sample 16dc1001:7ca56c8b:6113ee07:403 #1: ST0 ros_discovery_info/rmw_dds_common::msg::dds_::ParticipantEntitiesInfo_:{{{{22,220,16,1,124,165,108,139,97,19,238,7,0,0,1,193,0,0,0,0,0,0,0,0}}},{{"/","xtra_osd",{},{}}}}```
Then the second was:
```1644848544.779657 [0] xtra_osd_n: write_sample 16dc1001:7ca56c8b:6113ee07:403 #2: ST0 ros_discovery_info/rmw_dds_common::msg::dds_::ParticipantEntitiesInfo_:{{{{22,220,16,1,124,165,108,139,97,19,238,7,0,0,1,193,0,0,0,0,0,0,0,0}}},{{"/","xtra_osd",{},{{{{22,220,16,1,124,165,108,139,97,19,238,7,0,0,6,3,0,0,0,0,0,0,0,0}}}}}}}```
And the 10th:
```1644848544.818250 [0] xtra_osd_n: write_sample 16dc1001:7ca56c8b:6113ee07:403 #10: ST0 ros_discovery_info/rmw_dds_common::msg::dds_::ParticipantEntitiesInfo_:{{{{22,220,16,1,124,165,108,139,97,19,238,7,0,0,1,193,0,0,0,0,0,0,0,0}}},{{"/","xtra_osd",{{{{22,220,16,1,124,165,108,139,97,19,238,7,0,0,8,4,0,0,0,0,0,0,0,0}}}{{{22,220,16,1,124,165,108,139,97,19,238,7,0,0,10,4,0,0,0,0,0,0,0,0}}}{{{22,220,16,1,124,165,108,139,97,19,238,7,0,0,12,4,0,0,0,0,0,0,0,0}}}{{{22,220,16,1,124,165,108,139,97,19,238,7,0,0,14,4,0,0,0,0,0,0,0,0}}}{{{22,220,16,1,124,165,108,139,97,19,238,7,0,0,16,4,0,0,0,0,0,0,0,0}}}{{{22,220,16,1,124,165,108,139,97,19,238,7,0,0,18,4,0,0,0,0,0,0,0,0}}}{{{22,220,16,1,124,165,108,139,97,19,238,7,0,0,20,4,0,0,0,0,0,0,0,0}}}},{{{{22,220,16,1,124,165,108,139,97,19,238,7,0,0,6,3,0,0,0,0,0,0,0,0}}}{{{22,220,16,1,124,165,108,139,97,19,238,7,0,0,7,3,0,0,0,0,0,0,0,0}}}{{{22,220,16,1,124,165,108,139,97,19,238,7,0,0,9,3,0,0,0,0,0,0,0,0}}}{{{22,220,16,1,124,165,108,139,97,19,238,7,0,0,11,3,0,0,0,0,0,0,0,0}}}{{{22,220,16,1,124,165,108,139,97,19,238,7,0,0,13,3,0,0,0,0,0,0,0,0}}}{{{22,220,16,1,124,165,108,139,97,19,238,7,0,0,15,3,0,0,0,0,0,0,0,0}}}{{{22,220,16,1,124,165,```
So it seems that when I remove publishers / subscription in my ROS node, it doesn't delete their readers / writters, so that message keeps growing until it's too big to be sent.
Could that be the cause?
I would expect that deleting a publisher / subscription would also remove their reader / writter.

Thanks again.
Omer

**Comment by eboasson** [comment]
When you create a node, several subscriptions and publishers (for parameters and the like) get created, and this fits with that pattern. I did a quick test by just starting (a derivative of) "listener" and stopping it again (it stops cleanly when it receives ^C) and that looks perfectly normal: first you see all the entities get created (with as many ros_discovery_info samples, with the samples growing ever larger), then you see them getting destroyed (again with ros_discovery_info samples, but now getting smaller again).

```
CYCLONEDDS_URI="$CYCLONEDDS_URI,<Tr><V>finest</><Out>cdds.log</>" build/hacked_demo/listener64 & sleep 1 ; kill -INT $!
rg 'WRITER|READER|write_sample.*ros_discovery_info|delete_(reader|writer)\(guid' cdds.log > filtered.txt
```
tail [filtered.txt](https://github.com/eclipse-cyclonedds/cyclonedds/files/8089143/filtered.txt):
```
1645106437.913739 [0]    6465549: delete_writer(guid 1103c14:58d4043a:239086f6:903) - no unack'ed samples
1645106437.913898 [0]    6465549: write_sample 1103c14:58d4043a:239086f6:403 #20: ST0 ros_discovery_info/rmw_dds_common::msg::dds_::ParticipantEntitiesInfo_:{{{{1,16,60,20,88,212,4,58,35,144,134,246,0,0,1,193,0,0,0,0,0,0,0,0}}},{{"/","listener",{{{{1,16,60,20,88,212,4,58,35,144,134,246,0,0,20,4,0,0,0,0,0,0,0,0}}}{{{1,16,60,20,88,212,4,58,35,144,134,246,0,0,21,4,0,0,0,0,0,0,0,0}}}},{{{{1,16,60,20,88,212,4,58,35,144,134,246,0,0,19,3,0,0,0,0,0,0,0,0}}}}}}}
1645106437.914020 [0]    6465549: delete_writer(guid 1103c14:58d4043a:239086f6:703) ...
1645106437.914027 [0]    6465549: delete_writer(guid 1103c14:58d4043a:239086f6:703) - no unack'ed samples
1645106437.914171 [0]    6465549: write_sample 1103c14:58d4043a:239086f6:403 #21: ST0 ros_discovery_info/rmw_dds_common::msg::dds_::ParticipantEntitiesInfo_:{{{{1,16,60,20,88,212,4,58,35,144,134,246,0,0,1,193,0,0,0,0,0,0,0,0}}},{{"/","listener",{{{{1,16,60,20,88,212,4,58,35,144,134,246,0,0,20,4,0,0,0,0,0,0,0,0}}}{{{1,16,60,20,88,212,4,58,35,144,134,246,0,0,21,4,0,0,0,0,0,0,0,0}}}},{}}}}
1645106437.914201 [0]    6465549: delete_writer(guid 1103c14:58d4043a:239086f6:1303) ...
1645106437.914207 [0]    6465549: delete_writer(guid 1103c14:58d4043a:239086f6:1303) - no unack'ed samples
1645106437.914376 [0]    6465549: write_sample 1103c14:58d4043a:239086f6:403 #22: ST0 ros_discovery_info/rmw_dds_common::msg::dds_::ParticipantEntitiesInfo_:{{{{1,16,60,20,88,212,4,58,35,144,134,246,0,0,1,193,0,0,0,0,0,0,0,0}}},{}}
1645106437.914466 [0]    6465549: delete_writer(guid 1103c14:58d4043a:239086f6:403) ...
1645106437.914472 [0]    6465549: delete_writer(guid 1103c14:58d4043a:239086f6:403) - no unack'ed samples
```

It gets big, yes, but not too big to be sent. It does get too big to be sent in one ethernet frame, then in what Cyclone by default uses as the limit before it starts fragmenting, &c., but the ones in the Wireshark capture would still fit in a single UDP datagram. Raising the message size limit in Cyclone would avoid DDSI-RTPS fragmentation, and that, I suspect, will work around the problem.

In theory all DDS implementations should interoperate perfectly with very large messages and fragmentation, but that's where I think you're running into some problem that hadn't surfaced before.

**Comment by omertal88** [comment]
Hello,
I've changed the value and now running my node and a script which repeatedly switching devices.
After about 15 minutes of run I can see this message in my trace file:
```1645109065.392445 [0]  RosThread: write_sample 4cff1001:ac1b8e9e:6714e943:403 #2565: ST0 ros_discovery_info/rmw_dds_common::msg::dds_::ParticipantEntitiesInfo_:{{{{76,255,16,1,172,27,142,158,103,20,233,67,0,0,1,193,0,0,0,0,0,0,0,0}}},{{"/","xtra_osd",{{{{76,255,16,1,172,27,142,158,103,20,233,67,0,0,8,4,0,0,0,0,0,0,0,0}}}{{{76,255,16,1,172,27,142,158,103,20,233,67,0,0,10,4,0,0,0,0,0,0,0,0}}}{{{76,255,16,1,172,27,142,158,103,20,233,67,0,0,12,4,0,0,0,0,0,0,0,0}}}{{{76,255,16,1,172,27,142,158,103,20,233,67,0,0,14,4,0,0,0,0,0,0,0,0}}}{{{76,255,16,1,172,27,142,158,103,20,233,67,0,0,16,4,0,0,0,0,0,0,0,0}}}{{{76,255,16,1,172,27,142,158,103,20,233,67,0,0,18,4,0,0,0,0,0,0,0,0}}}{{{76,255,16,1,172,27,142,158,103,20,233,67,0,0,20,4,0,0,0,0,0,0,0,0}}}{{{76,255,16,1,172,27,142,158,103,20,233,67,0,0,23,4,0,0,0,0,0,0,0,0}}}{{{76,255,16,1,172,27,142,158,103,20,233,67,0,0,25,4,0,0,0,0,0,0,0,0}}}{{{76,255,16,1,172,27,142,158,103,20,233,67,0,0,27,4,0,0,0,0,0,0,0,0}}}{{{76,255,16,1,172,27,142,158,103,20,233,67,0,0,29,4,0,0,0,0,0,0,0,0}}}{{{76,255,16,1,172,27,142,158,103,20,233,67,0,0,31,4,0,0,0,0,0,0,0,0}}}{{{76,255,16,1,172,27,142,158,103,20,233,67,0,0,33,4,0,0,0,0,0,0,0,0}}}{{{76,255
1645109065.392529 [0]  RosThread: xpack_addmsg 0x55ab568320 0x7f400382a0 0(data(4cff1001:ac1b8e9e:6714e943:403:#2565/1)): niov 0 sz 0 => now niov 3 sz 24672
1645109065.392549 [0]  RosThread: writer_hbcontrol: wr 4cff1001:ac1b8e9e:6714e943:403 multicasting (rel-prd 19 seq-eq-max 17 seq 2565 maxseq 2548)
```
If I understand it correctly, the ros_discovery_info message reached the size of 24672 bytes... So if I'm not wrong, in about 30 minutes from now it will start the loop again.
So it did delay the issue but not really solve it.
Anyway I will update this comment in about 30 minutes or so.

**Comment by omertal88** [comment]
Thank you for all of your help...
Now after a week of debugging, I think I earned myself a beer :)

**Comment by omertal88** [comment]
Hehe :)
I added my comment in the PR.
I'm not sure if I should close this issue now, or wait until the PR gets merged.
