### ISSUE TITLE
About Throughput example

### ISSUE THREAD

**Issue by i-and** [eclipse-cyclonedds/cyclonedds#118]
Hi,
There are a few questions related to the bandwidth test:
1. Which Linux distribution did you test on?  How did you install PREEMPT RT (rt14.20.el6rt.x86_64 _1 SMP PREEMPT RT) there? Which Linux distribution do you recommend to RT (as far as I understand, the Ubuntu goes without  PREEMPT RT)?
2. It may be necessary to display the following information on the resulting graph or in the form of a table: CPU load on the cores, the number of memory allocations/releases in the process, the number of page faults, number of context switches for the test application.

**Comment by eboasson** [comment]
> 1. Which Linux distribution did you test on? How did you install PREEMPT RT (rt14.20.el6rt.x86_64 _1 SMP PREEMPT RT) there?

It was measured on a pair of machines that sit somewhere in our network — I can use them, but I don't manage them. This is what I know:
```
$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 6.5 (Santiago)
$ uname -a
Linux perftest8.prismtech.com 3.8.13-rt14.20.el6rt.x86_64 #1 SMP PREEMPT RT Mon Aug 19 23:09:43 EDT 2013 x86_64 x86_64 x86_64 GNU/Linux
```
It seems kernel version 3.8.13 is not the original one from the RHEL 6.5 release, but there are kernel-rt-3.8.13-rt14.20.el6rt RPMs downloadable from RedHat, so I presume this machine has received a few upgrades since the initial installation.

> 1. Which Linux distribution do you recommend to RT (as far as I understand, the Ubuntu goes without  PREEMPT RT)?

As to what version I recommend ... I don't really pay much attention to the Linux distributions or versions. I do try to keep an eye on the more interesting fundamental improvements to the kernel, but I have no clue how those map to the commonly used distributions.

It does seem like a properly pre-emptible kernel is slowly becoming mainstream (much more slowly than I would ever have expected possible) and that it is pretty straightforward to replace the kernel in, say, Ubuntu, by one that does support it. See for example https://index.ros.org/doc/ros2/Tutorials/Building-Realtime-rt_preempt-kernel-for-ROS-2/ — the robotics community is a good source for this sort of thing, because robots operate in the real world and sometimes do need to respond within hard deadlines.

> 2. It may be necessary to display the following information on the resulting graph or in the form of a table: CPU load on the cores, the number of memory allocations/releases in the process, the number of page faults, number of context switches for the test application.

I agree that that is important information, but I decided to leave it out of the headline figure in the README. is quite a challenge to find a good representation of all that data, and besides the commercial guys also leave that out — so it isn't needed for a fair comparison with them 😁. But that doesn't mean the my [script](https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/performance/throughput-test) doesn't record at least something: the standard ``top`` output is all there — with threads and such that 100% of one thread is one 100% of one core. So at least CPU load and an indication of memory usage is available. If you know of an equivalent to Solaris' ``prstat`` that I used in years past …

Extracting CPU loads for individual threads from top output is somewhat tricky, but I have given it a go. This is from the same experiment as the graph in the README (I kept the full data set, see below), but I think that one was for the synchronous delivery mode where this one is for the asynchronous delivery mode (``data-async1-mode1``). Anyway, gnuplot:

```gnuplot
set st da l
p "< perl -w extract-cpuload-plot.pl sub-top.log pub-top.log" i 0 u 1:2 ti "sub[recv]", "" i 0 u 1:3 ti "sub[dq.user]", "" i 0 u 1:4 ti "sub", "" i 1 u 1:2 ti "pub[recv]", "" i 1 u 1:3 ti "pub"
```
(for the perl script, see below) gives you:

![image](https://user-images.githubusercontent.com/16984005/53166563-f1a5ec80-35d5-11e9-8575-33286a8fd956.png)

I'm pretty sure the spikes are artefacts from ``top``; the runs are for the different sized messages (0, 16, 32, 64, 128 — 256 should be there, too, but it seems to be missing). Full data set:

[throughput-result-20180117-98f757a5a.zip](https://github.com/eclipse-cyclonedds/cyclonedds/files/2889097/throughput-result-20180117-98f757a5a.zip)

``extract-cpuload-plot.pl``:
```perl
open FH, "< $ARGV[0]" or die "can't open sub-top.log";
$d = $r = $a = 0;
while (<FH>) {
  $p++ if /^top - 15:26:40/;
  next unless $p;
  @F = split;
  $d = $F[7] if /dq\.user/;
  $r = $F[7] if /recvUC/;
  $a = $F[7] if /Throughput/;
  if (/^top - (\d+):(\d+):(\d+)/) {
    my $t = 3600 * $1 + 60 * $2 + $3;
    $t0 = $t unless defined $t0;
    printf "%d %f %f %f\n", ($t-$t0), $r, $d, $a;
    $r = $d = $a = 0;
  }
}
close FH;
printf "\n\n";

open FH, "< $ARGV[1]" or die "can't open pub-top.log";
while (<FH>) {
  $p++ if /^top - 15:26:40/;
  next unless $p;
  @F = split;
  $z{$F[0]} = $F[8] if /^\s+\d+/;
  if (/^top - (\d+):(\d+):(\d+)/) {
    my $t = 3600 * $1 + 60 * $2 + $3;
    $t0 = $t unless defined $t0;
    @pids = sort { $a <=> $b } keys %z;
    next unless @pids > 0;
    $a = $z{$pids[0]};
    $r = $z{$pids[0] + 9};
    $r = 0 unless defined $r;
    printf "%d %f %f\n", ($t-$t0), $r, $a;
    undef %z;
  }
}
close FH;
undef $t0;
```

**Comment by i-and** [comment]
Hi, @eboasson,
Maybe it makes sense to integrate statistics calculation directly into the Cyclone? This will give a certain completeness in obtaining controlled parameters and flexibility in the formation of text reports (for further conversion to graphics in various ways). Also it would allow to use statistics on platforms other than Linux (where there is no utility "top", bash, perl,...). For example: to diagnose the performance could use CLOCK_THREAD_CPUTIME_ID, CLOCK_PROCESS_CPUTIME_ID, getrusage(total time, number of context switches). For memory statistics, I think it would be useful to integrate counters into the functions os_alloc(), os_free(), os_realloc() and use getrusage(used memory, number of page faults).

**Comment by eboasson** [comment]
Hi @i-and,

That would make sense, it is pretty trivial to report those things and/or keep track of those things. In fact, process-level rusage output and per-thread CPU times are already logged if the right tracing flag is set — I just forgot about it!

Of course that only tracks CPU usage, not allocations, &c.

**Comment by k0ekk0ek** [comment]
Fun fact, Logging CPU and user times per-thread will be available for all platforms in my upcoming pull request.

**Comment by eboasson** [comment]
@i-and, PR #209 added the CPU, memory and network usage information to the output of the ddsperf throughput and latency tester. Context switches will show up soonish (that's just a tiny detail and I added it locally already).

The allocation calls I haven't decided on yet ... they are interesting and useful, but there are also good ways of monitoring that from the outside on various platforms and in many cases a secondary thing. Merely observing that a throughput test doesn't allocate memory is not a way to not good enough if you want to run without dynamic memory allocation, and if dyn. memory allocation is not an issue, then, at least in my view, it is more a matter of seeing where the time is spent and what might be done to improve it. But I am not really against it either.

I am going to close this issue, given that it refers to old data on a platform I no longer have access to (it got reconfigured to an Ubuntu 16.04 earlier this year), using now-obsolete test programs, and that most of your sensible suggestions have actually worked their way into the code.
