### ISSUE TITLE
How to participate in developing CycloneDDS

### ISSUE THREAD

**Issue by lessismoreh** [eclipse-cyclonedds/cyclonedds#1185]
Hi friends,

I am so sorry to ask this dumb question. We are a group of fans of CycloneDDS, we 
have used CycloneDDS in our class projects. We all think the CycloneDDS is a lightweight and performant DDS implementation. So we want to participate in developing CycloneDDS. We have read the documents in the repo. However, we found that the code is hard for us to understand, for example the RTPS part. 
Could you help give us some advices about how to participate in the development of CycloneDDS? Would you create Discord channel or Slack channel for discussion?

Thanks

**Comment by eboasson** [comment]
Thank you so much for raising this issue! I dare say it is one of the nicest ever opened in the Cyclone repo!

Yes, unfortunately there is not enough material to help getting started with the internals of the stack. This is something we are very much aware of and we do plan on refactoring and cleaning up the code base after the 0.9 release (which is going to happen soon, not just because I say so, but also because we want it in the upcoming ROS 2 Humble release). We expect this will make it easier to contribute to the core code.

What we did find is that a very decent path into Cyclone (and even into DDS more in general) is via adding language bindings. It makes you familiar with all parts of the code and almost automatically makes you play with things and end up working your way into the innards. We currently have C (the base), C++ and Python, and I know that @sjames is working on a Rust binding. (I actually played a bit with a [Haskell binding](https://github.com/eboasson/cyclonedds-haskell), but I haven't found the time and I am like the worst Haskell programmer in the world anyway ...)

Would you be interested in doing, e.g., a C# binding (or a Java one, but C# is of more immediate relevance: #1176; it also doesn't require dealing with Windows these days 🙂)? Mapping (most of) the API is pretty straightforward, the only tricky part is getting the serialisation sorted, especially because we now have support for DDS XTypes. Several people know in detail how that works so it is not like you'd be in uncharted territory. We would definitely love to get such a contribution and would be more than happy to help.

It is just an idea, there are other possibilities as well, but one's got to start somewhere 🙂

As far as discussion channels go, currently we do have a [Gitter channel](https://gitter.im/atolab/cyclone-dds?utm_source=notification&utm_medium=email&utm_campaign=unread-notifications), it is not super-active, but you're welcome to change that.

**Comment by poetinger** [comment]
Hi @lessismoreh, I hope your question was answered sufficiently. As we haven't heard back, I will close this issue now. You are welcome to join our discussion in the mentioned Discord, and of course feel free to re-open this issue if you need to.
