### ISSUE TITLE
Ping/Pong: Assertion `os_threadEqual ' failed.

### ISSUE THREAD

**Issue by qqqshengwei** [eclipse-cyclonedds/cyclonedds#121]
Hi, we are trying to run ping with multiple pongs and getting in trouble (commit: 1c7f9035). The scene where the error occurred is like this:
When we run this in a virtual machine (Ubuntu 16.04)
> ./RoundtripPong & ./RoundtripPong & ./RoundtripPing 2097152 0 0
then the **error** occurrs
> RoundtripPong: /cyclonedds/src/core/ddsi/src/q_radmin.c:636: nn_rmsg_rmbias_and_adjust: Assertion `os_threadEqual (os_threadIdSelf (), (rmsg->chunk.rbuf->rbufpool)->owner_tid)' failed.
Our OS is: Ubuntu 16.04 SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux  
We only found out that this is a probability problem, the probability of occurrence on the virtual machine is very large, and it is difficult to reproduce on the physical machine.
Help! thank you.

**Comment by eboasson** [comment]
That is truly intriguing. I find a perverse enjoyment in figuring out such problems — so, in a way: thank you for running into it! 😁

Hopefully it will be solved without too much trouble ... we'll see ...

**Comment by eboasson** [comment]
Good news: a debug build on my (Apple) laptop reproduces it beautifully. I also already know what's happening and there is simple workaround until I get it fixed. Which I will do as soon as I can, because the workaround does mean giving up some of the precious µs I gained in [4f0b9cb](https://github.com/eclipse-cyclonedds/cyclonedds/commit/4f0b9cb471701ce3fd333213aa39cf6628523897).

What happens is that some fragments of a single sample are received over multicast and some over unicast. Thanks to that commit, those are handled by separate threads that do not need to multiplex over multiple sockets, but as a consequence they are are stored in separate receive buffer pools. You end up with a single large message spanning multiple pools. The thread receiving the fragment that completes the sample tries to adjust the reference counts from the fragments and so, against original design intent, it encounters another thread's receive buffer.

The design has always been that decrementing these refcounts may be done by any thread (e.g., the delivery queue threads do that all the time). The trouble is not in the normal decrementing of the refcounts, but rather in the incrementing: to not have to update these reference counts with atomic operations all the time, they start out with a "bias" value that allows deferring the incrementing of the refcount. Potentially a buffer could be handed to another thread that then decrements the refcount before the corresponding increment occured. Removing that bias was supposed to be done only on the receiving thread, hence the check.

Now, I'm not yet sure what the fix will be. Perhaps that "deferred incrementing" should simply be removed, at which point it becomes a non-issue which thread it is; perhaps the assertion is more strict than it needs to be; perhaps one should just handle _fragmented_ samples differently from complete ones because this problem cannot occur when the sample is not split over multiple fragments; perhaps there is some other consideration as well. I will think about it.

The workaround is pretty obvious: limit it to a single receive thread and there can never be a mix-up between threads. You can get that by setting ``Internal/MultipleReceiveThreads`` to ``false``. This penalizes performance a little bit because of I/O multiplexing it introduces (i.e., calling ``select`` or ``kqueue`` or …) but I doubt it would even be noticeable in the latency of large samples.

**Comment by qqqshengwei** [comment]
Thank you for your workaround.  We will keep testing and trying to find more traces about this .

**Comment by eboasson** [comment]
It's been a while already that this got fixed — it turned out the assertion was incorrect. The workaround of course will continue to work, albeit at a (really) minor reduction in performance.

**Comment by qqqshengwei** [comment]
Thank you for your generous explanation, I will continue to understand and pay attention to this issue.
