### ISSUE TITLE
DDS configuration setup advice

### ISSUE THREAD

**Issue by livanov93** [eclipse-cyclonedds/cyclonedds#1232]
I have a question regarding the use of cyclone DDS with ROS2.

I have one network card on my system which is used by DDS. The setup consists of many computationally expensive processes, whose results are shared on the ROS network (e.g. large messages are shared). On the other hand, I have a TCP/IP communication process that has strict timing constraints. This connection keeps dropping whenever the rest of the ROS2 setup is running (a lot of bandwidth is used). I am not allowed to relax timing constraints for the process, but I am interested in other solutions.

To finally conclude if it is DDS related problem, I tried the setup with two network cards where the cyclone DDS was using one, and the process with strict timing constraints the other one. I haven't seen it disconnected at all in this 2 network card setup.

Is there a way to isolate any communication process from the DDS? I know it is possible to reduce MaxMessageSize to inherently reduce the UDP payload, but that won't solve my problem.

What are other tweaks that can be done to make my system work with only 1 network card?

Thanks in advance for any advice!

**Comment by eboasson** [comment]
Hi @livanov93, my apologies for having kept you waiting for some time. I suspect the problem is not so much network bandwidth as delays caused the time it takes to publish (very) large messages on the network. In other words, that it would be fine if the TCP/IP part would run in a different thread than publishing these large ROS messages. The obvious way one can do that is by having multiple threads in the application.

The less-obvious way is to rely on asynchronous publication in DDS. Cyclone supports a limited form of asynchronous publication (a more general variant is to come in the future) by setting the "latency_budget" DDS QoS to something larger than 0. The difficulty with this approach is that ROS 2 doesn't really do this "latency budget" thing ...

There is a trick that I suspect will work, but that I haven't really tried. Cyclone's configuration has some settings to limit how much data it transmits in one go. By default it optimistically will send the entire message immediately and only limit the size of any required retransmits, but it supposedly can also do a partial *initial* transmission.

That setting is `Internal/BurstSize/MaxInitTransmit` and it is a percentage of the estimated socket receive buffer size. (Yay for wild experiments — but then it wasn't really added for the purpose of doing asynchronous publications when the latency budget is 0). It think it's worth a try!

**Comment by livanov93** [comment]
Hi @eboasson. Thank you for the reply.

> Hi @livanov93, my apologies for having kept you waiting for some time. I suspect the problem is not so much network bandwidth as delays caused the time it takes to publish (very) large messages on the network. In other words, that it would be fine if the TCP/IP part would run in a different thread than publishing these large ROS messages. The obvious way one can do that is by having multiple threads in the application.

The TCP/IP part is not ROS2/DDS dependent and runs in a separate thread. It is not part of any callback nor part of any publishing loop.

> The less-obvious way is to rely on asynchronous publication in DDS. Cyclone supports a limited form of asynchronous publication (a more general variant is to come in the future) by setting the "latency_budget" DDS QoS to something larger than 0. The difficulty with this approach is that ROS 2 doesn't really do this "latency budget" thing ...

Is there an estimate for this feature?

> There is a trick that I suspect will work, but that I haven't really tried. Cyclone's configuration has some settings to limit how much data it transmits in one go. By default it optimistically will send the entire message immediately and only limit the size of any required retransmits, but it supposedly can also do a partial initial transmission.
That setting is Internal/BurstSize/MaxInitTransmit and it is a percentage of the estimated socket receive buffer size. (Yay for wild experiments — but then it wasn't really added for the purpose of doing asynchronous publications when the latency budget is 0). It think it's worth a try!

I will test it and get back with the results.

> but then it wasn't really added for the purpose of doing asynchronous publications when the latency budget is 0

Can you elaborate a bit more on this?

**Comment by eboasson** [comment]
> The TCP/IP part is not ROS2/DDS dependent and runs in a separate thread. It is not part of any callback nor part of any publishing loop.

In hindsight, I probably could have concluded that from your original description. Oh well ... it is good to not have any uncertainty on this detail.

It also indeed implies that the timing problems indeed must be coming from the actual network (or IP stack/OS kernel/driver). Fiddling with which thread does the work in Cyclone won't do much (although the `Internal/BurstSize/MaxInitTransmit` might well work because it would prevent it from sending the data in one go).

Asynchronous publishing alone won't address it, bandwidth limiting/traffic shaping probably will. Strict speaking the two are independent, and some time back I spent some time restoring what exists in the code base to a working state. My estimate back then on when it would be ready is already in the past, and it really is because of all the different things that soak up energy. So

> Is there an estimate for this feature?

There should be :)

There is not nearly as much reason for doing bandwidth limiting or traffic shaping inside DDS as there used to be, because the network stacks have gotten much better. Ideal for you would probably be to use TSN, but that requires special hardware. If you're on a Linux machine, you have pretty sophisticated traffic shaping support built right into the kernel. From what I know (not from much actual trying) you can even handle different protocols separately. That's what I would try.

> > but then it wasn't really added for the purpose of doing asynchronous publications when the latency budget is 0
> Can you elaborate a bit more on this?

The burst limit got added to mitigate socket receive buffer overruns. The general advice to people using DDS is to make sure that buffer is large enough to comfortably hold at least one sample if samples are really large. Another pain point can be the IP defragmentation buffer, though I don't have the impression it matters so much in practice with current machines.

The problem with that general advice is that (most?) Linux distributions have a default limit of about 400kB. It can be raised by tweaking a kernel configuration setting, using sysctl or /proc, but that does require super-user privileges. At some point I made an effort to get better behaviour on an untuned system, and that involved in particular also trying not to overrun the socket receive buffer repeatedly. Hence the `Internal/BurstSize/MaxRexmit` setting. The initial transmit maximum got added because it was but a minor tweak and seemed like it might come in handy at some point, but as the documentation notes, it eliminates a lot of opportunities for using multicast, and so it seemed best to not limit it by default.

The latency budget setting exists to give implementations a bit of wiggle room for scheduling network traffic. Doing the data transmissions on a separate thread means there'll be a queue (of sorts) in between and priorities and latency budgets can then be used to give more urgent or higher priority data precedence over other data. It is a nice feature of ZettaScale OpenSplice and I do want it in Cyclone as well.
