### ISSUE TITLE
ResourceLimitsQoS problem

### ISSUE THREAD

**Issue by johnflj** [eclipse-cyclonedds/cyclonedds#1280]
HI, e god @eboasson 
I want to ask a question about ResourceLimitsQoS:
I create a recv client and a send client.
recv client set qos:
qos = dds_create_qos();
    dds_qset_history(qos, DDS_HISTORY_KEEP_ALL,5);
    dds_qset_resource_limits(qos, resource, 1, resource);
    dds_qset_reliability (qos, DDS_RELIABILITY_RELIABLE, DDS_SECS (10));

send client set qos:
qos = dds_create_qos();
    dds_qset_history(qos, DDS_HISTORY_KEEP_ALL,10);
    dds_qset_reliability (qos, DDS_RELIABILITY_RELIABLE, DDS_SECS (10)); 
    dds_qset_resource_limits(qos, resource, 1, resource);

recv client run ,but do not read cache
send client run,and send message immediately.

when send and recv client run in the same machines. 6th message will be blocked.
when send and recv client run in different machines. 6th message will not be blocked.

is it a problem?

**Comment by johnflj** [comment]
sorry Qos info renew:

recv client set qos:
qos = dds_create_qos();
    dds_qset_history(qos, DDS_HISTORY_KEEP_ALL,20);
    dds_qset_resource_limits(qos, 5, 1, 5);
    dds_qset_reliability (qos, DDS_RELIABILITY_RELIABLE, DDS_SECS (10));

send client set qos:
qos = dds_create_qos();
    dds_qset_history(qos, DDS_HISTORY_KEEP_ALL,20);
    dds_qset_reliability (qos, DDS_RELIABILITY_RELIABLE, DDS_SECS (10));
    dds_qset_resource_limits(qos, 10, 1, 10);

**Comment by johnflj** [comment]
Is it the problem of deliver_locally?@eboasson

**Comment by eboasson** [comment]
I know there are still some issues with resource limits handling that makes it behave differently if the reader and writer are taking the intra-process/local-delivery path, versus if they are communicating via the network protocol. When not using Iceoryx (and with `KEEP_ALL`, you can't be) there is no difference between two different processes or two different machines, other than the latency. So given what you describe, I suspect that's where the problem is.

My guess is that when on the same machine, the latency is low enough that the sender discovers the receiver before it tries to send the first sample, and that when on different machines the latency over the network is long enough that it doesn't.

Would that be possible?

**Comment by johnflj** [comment]
I don't think that's the case. Because, I am referring to different machines that are under the same switch and without communication interference from other devices.
I have the feeling that when the receiver and the sender are working on different machines, the sender can't check if the receiver's cache is full. But if they work on the same machine, the sender can.

**Comment by johnflj** [comment]
HI,e god, help me.@eboasson

**Comment by eboasson** [comment]
Hi @johnflj, as I said, unless you are using Iceoryx (and given the KEEP_ALL history setting, you cannot be) there is no difference between communication between processes on a single machine, and that between processes on different machines. It runs exactly the same code, exchanging DDSI protocol messages via the operating system's network interfaces. If it is one machine, that'll be the loopback interface instead of a "real" network interface.

The difference between a quiet GbE with a switch and the loopback interface is significant, something like 1µs vs 30µs latency or so. That means it takes a few microseconds longer for the writer to the discovery the reader, and that can make all the difference.

There are ways of determining whether the receiver gets the same data in both cases (if my understanding of the situation is correct, it doesn't get exactly the same in both cases because of the discovery latency). The easiest in your case (assuming I am understanding correctly) would be to call `dds_read` on the receiver: that way you can print what you received while leaving the data the reader history cache.

If you want to make it easy, just call `dds_read` periodically. If you want to make it fancy, you might want to do something like:
```C
dds_entity_t ws = dds_create_waitset (participant);
dds_entity_t readcond = dds_create_readcondition (reader, DDS_NOT_READ_SAMPLE_STATE | DDS_ANY_VIEW_STATE | DDS_ANY_INSTANCE_STATE);
dds_waitset_attach (ws, readcond, 0);
while (1) {
  dds_wait (ws, NULL, 0, DDS_SECS (1));
  n = dds_read (readcond, ...);
  for (i=0; i<n; i++) {
    print ...
  }
}
```
that'll wait until some data you haven't seen before is present in the reader history, then prints only that data.
(Beware of typos!)

**Comment by johnflj** [comment]
Hi，E god@eboasson
Do you mean that the delay in forwarding packets by the switch device is causing this problem, while communication through the local loopback port does not have such a problem?
But the phenomenon is still the same when I run the program on 2 virtual machines running locally. 2 virtual machines are communicating through the loopback port.

**Comment by johnflj** [comment]
Hi, e god@eboasson

**Comment by thijsmie** [comment]
Hi Johnflj,

I think Erik has fully answered your question, so I'll try to address your remaining concerns.

Firstly: **delivery of messages within a host between two processes is identical to delivery between two hosts**. This "checking wether a cache is full locally" you mentioned is not something that exists.

That means that what you are seeing **can only be a latency effect**. Even though the network is good, of course two machines have two OS network stacks and some wires and a switch in between, and that inherently costs time. That couple of microseconds can make all the difference depending on how you test things.

Lastly, there is not really a problem in the first place. The blocking you are seeing is because the reliability ensurance with the information the cache is full reaches the writer before doing the next write. However, if that doesn't happen the retransmit mechanism will still function to ensure delivery after the reader has space again. I'd say you should try to avoid situations where you rely on blocking due to resourcelimits, because it is really a faultcondition, DDS pulling an emergency brake on your application because otherwise it cannot fulfill its QoS mandated contract.

**Comment by johnflj** [comment]
Hi,thijsmie @thijsmie 
Do you really think the delay is the cause of this problem? The recv client I opened doesn't really read the cache until the sender finishes sending (the number is 20), I added getchar to the receiver to de-blocking to avoid the cache being affected by the timing, and after the sender finishes sending all the characters, I enter a character on the receiver and the receiver reads the record from the cache at that point (the number is 5).I have explained this situation in the beginning of the post, did you ignore this prerequisite?

**Comment by thijsmie** [comment]
Hi @johnflj,

I've tried out your reproducer, and I come to the following conclusions (all without any iceoryx in the mix):
 * I have no differences between local processes or processes communicating between hosts if I make sure the reader is discovered (e.g. look at matching subscriptions in the publisher before writing data)
 * The writer _never_ blocks, unless we get to the ~3500 samples region. This is because the ResourceLimits policy is actualy _unimplemented_ for the writer cache, which we should do.
 * If the dds_take is looped on the reader side we neatly get exactly `resource_limit` samples per iteration, the expected behaviour.
 * If the writer/reader are in the same process under the same participant the writer may block on the reader cache in local delivery, which is not quite right but requires a mountain of code to allow local delivery failure with fallback via whc.

So I agree, there is a unimplemented feature here that is an issue. You can still control the effective resource limits on the writer side with the XML options under `CycloneDDS/Domain/Internal/Watermarks` right now if you need to rely on them.

**Comment by johnflj** [comment]
HI，@thijsmie
Thank you very much for answering my questions.
My concern lies in these 2 points you mentioned:
1: Writer cannot block through ResourceLimitsQoS.
2: In some cases, the writer may block on the reader cache in local delivery(wrong way)。
If this feature is implemented, please tell me.
