### ISSUE TITLE
cyclonedds/src/security/api/../../core/ddsi/include/dds/ddsi/ddsi_shm_transport.h:27:10: fatal error: iceoryx_binding_c/config.h: No such file or directory    27 | #include "iceoryx_binding_c/config.h"  

### ISSUE THREAD

**Issue by monkey-king1** [eclipse-cyclonedds/cyclonedds#1287]
After i using 'the cmake --build .' directives，the make gave me such error '': fatal error: iceoryx_binding_c/config.h: No such file or directory    27 | #include "iceoryx_binding_c/config.h" ''.I cannot solve such problem.

**Comment by thijsmie** [comment]
Hi @monkey-king1,

I've seen similar errors before, I think it is caused by CMake getting confused because we swapped some options around between versions. Can you try to delete your build directory and rerunning your build from a blank slate?

**Comment by monkey-king1** [comment]
> 

I did as what you told, but it still can't work.

**Comment by eboasson** [comment]
@monkey-king1 If you do the CMake configuration step (so with the `--build` bit) in a new build directory, it looks for the Iceoryx package and will only enable the code that depends on Iceoryx if it can find it. The error you get is because it is trying to include the Iceoryx support but it can't find the files.

As @thijsmie suggested, we swapped some options around and just starting fresh usually solves the problem.

If it doesn't that makes me think that CMake found "something" Iceoryx but that it is incomplete — or perhaps an old version, Cyclone nowadays depends on Iceoryx 2.0. So you might want to check that.

And if nothing else helps, you could run the CMake configure step with [`-DENABLE_SHM=NO`](https://github.com/eclipse-cyclonedds/cyclonedds#build-configuration) added, to stop it from even trying.

**Comment by thijsmie** [comment]
No further comments received :slightly_smiling_face:
