### ISSUE TITLE
ShmThroughput test failed on master branch

### ISSUE THREAD

**Issue by xixioba** [eclipse-cyclonedds/cyclonedds#1289]
I'm testing shm feature(on Mac m1 macos 12.4), on **master** branch, run failed
```
./ShmThroughputPublisher 8192 0 1 0 "Throughput example"


payloadSize: 8192 bytes burstInterval: 0 ms burstSize: 1 timeOut: 0 seconds partitionName: Throughput example

=== [Publisher]  Waiting for a reader ...
=== [Publisher]  Writing samples...
1653877463.660943 []    3927583: dds_loan_sample: Unsupported
[1]    51025 abort      ./ShmThroughputPublisher 8192 0 1 0 "Throughput example"
```
~~on **iceoryx** branch, but it fails to compile~~ (already merge in master)
```
[ 80%] Building C object src/idl/CMakeFiles/idl.dir/parser.c.o
src/parser.y:307:9: error: use of undeclared label 'yyreturn'
      { TRY(idl_annotate(pstate, (yyvsp[-1].module_dcl), (yyvsp[-2].annotation_appl)));
        ^
src/parser.y:95:3: note: expanded from macro 'TRY'
  TRY_EXCEPT((action), 0)
  ^
src/parser.y:90:14: note: expanded from macro 'TRY_EXCEPT'
        goto yyreturn; \
             ^
src/parser.y:1098:16: error: use of undeclared identifier 'yytoknum'; did you mean 'toknum'?
      toknum = yytoknum[i];
               ^~~~~~~~
               toknum
src/parser.y:1085:7: note: 'toknum' declared here
  int toknum = 0;
      ^
src/parser.y:1098:24: error: subscripted value is not an array, pointer, or vector
      toknum = yytoknum[i];
               ~~~~~~~~^~
3 errors generated.
make[2]: *** [src/idl/CMakeFiles/idl.dir/parser.c.o] Error 1
make[1]: *** [src/idl/CMakeFiles/idl.dir/all] Error 2
make: *** [all] Error 2
```
~~It seems that iceoryx has not been updated for a long time, how can I test shm in the recent release?~~

**Comment by eboasson** [comment]
Hi @xixioba, the reason for the compilation problem is easy enough, it used some deprecated bison features and you've built it with a too-new version of bison. Those have been fixed since, in commits:

* 499fab8febda229db1faf49eca10a859804944dd
* 7151fef9820803f0b09ca943d14bbf9112ef2d7e
* b0160faf886395a51cb1993ba470a6d7eb7869f0

But more importantly, why bother with the `iceoryx` branch? There have been no updates to it because it has been merged a long time ago. The reason the branch is still around is because we want to avoid anyone picking up an old version of the ROS 2 repository list and getting errors.

So, my suggestion would be to use `releases/0.9.x` for the most recent release (a few weeks ago), or `master` if you are happy to track the development version. The release is more stable, but not by much.

**Comment by xixioba** [comment]
@eboasson ok i got it, i just need to focus on the master branch now 👍 
But when I test the ShmThroughput, it prompts `dds_loan_sample: Unsupported`
Terminal 1:
```
./ShmThroughputSubscriber 0 0 "Throughput example" 8192
Cycles: 0 | PollingDelay: 0 | Partition: Throughput example
=== [Subscriber] Waiting for samples...
```
Terminal 2:
```
./ShmThroughputPublisher 8192 0 1 0 "Throughput example"
payloadSize: 8192 bytes burstInterval: 0 ms burstSize: 1 timeOut: 0 seconds partitionName: Throughput example

=== [Publisher]  Waiting for a reader ...
=== [Publisher]  Writing samples...
1654134996.727189 []     637858: dds_loan_sample: Unsupported
[1]    7356 abort      ./ShmThroughputPublisher 8192 0 1 0 "Throughput example"
```
can you give some advice

**Comment by eboasson** [comment]
My first guess would be that you didn't enable the use of shared memory: it needs to be compiled in (by default when it can find Iceoryx, `-DENABLE_SHM=YES` makes it required), and you need to enable it at run-time (by setting `SharedMemory/Enable` to true).

Why so complicated? The first is because we don't want to require Iceoryx to be available (for example, it is not yet fully supported on Windows), and secondly because Iceoryx doesn't provide a fail-safe way in the API for discovering if its "roudi" service is running without blocking.

All these steps are described in detail in the [documentation](https://cyclonedds.io/docs/cyclonedds/latest/shared_memory.html), but you do have to know where to look for it!

**Comment by xixioba** [comment]
Thanks, it was very helpful for me.

**Comment by alexleel** [comment]
> DENABLE_SHM=YES
I also encounter the problem first I set -DENABLE_SHM=ON, and SharedMemory/Enable in cyclonedds.xml, however, ShmThroughputSubscriber 10 0 "Throughput example" 16384 has no out put, checked the code , seems dds_read_impl always return 0 since ShmThroughputPublisher end with sth likes  "1562491 samples written."
