### ISSUE TITLE
Hello World Example with TCP (using cyclonedds.xml)

### ISSUE THREAD

**Issue by Zhang8912** [eclipse-cyclonedds/cyclonedds#1302]
Hi everyone,

I am trying Hello World Example with TCP (using cyclonedds.xml). But there is no connection between Publischer and Subscriber.

It is possible that I did something wrong with cyclonedds.xml for TCP. Do you know, how/which parameter should I set for TCP?

Thank you
![image](https://user-images.githubusercontent.com/103993997/172750471-17f6b884-0955-499d-a33a-ab7c04b57f9f.png)

**Comment by eboasson** [comment]
Hi @Zhang8912, that's because with TCP you need to know where to listen and where to connect to, and besides you can't have multiple TCP servers on a single port number of a machine. Put differently, the zero-configuration discovery works thanks to multicast, and TCP doesn't do that.

You can specify the port number to listen on in a `TCP/Port` and specify hostnames+port numbers to try to connect to in the `Discovery/Peers` section. It is ok two have both processes listen on a port and trying to connect to the other process, or to have only one process listening and the other connecting.

For example (without checking, so beware of typos), if you make two config files, one:
```
<TCP><Port>12345</Port></TCP>
```
and the other like:
```
<Discovery><Peers><Peer address="localhost:12345"/></Peers></Discovery>
```
it should work.

Of course that is pretty unpleasant ... so you can also do something like:
```
<TCP><Port>${PORT:-1}</Port></TCP>
<Discovery><Peers>
  <Peer address="localhost:12345"/>
  <Peer address="localhost:12346"/>
  <Peer address="localhost:12347"/>
</Peers></Discovery>
```

and then each process will try to connect to ports 12345, 12346 and 12347 on the local host, and listen on the port set in the `PORT` environment variable. Setting the port number to -1 disables listening altogether (only outbound connections).

**Comment by Zhang8912** [comment]
Hi @eboasson [eboasson](https://github.com/eboasson), thank you for reply. **Yes, it works now**. I am a really DDS Noob here. I have a question again. You know, on Subscribe Side the following command is added in .xml file**<Discovery><Peers><Peer address="localhost:12345"/></Peers></Discovery>**, which localhost:12345 belongs to Publisch Side. My question: is it possible to connection without IP and Port from Publischer? （My idea: Data Reader from Subscriber looks for a Topic, in which the data is written by Data Writer from Publisher, maybe Subscriber can automatic get IP and Port from Publisher?）

**Comment by eboasson** [comment]
Hi @Zhang8912, assuming I understand you correctly, then I would say no, not really. TCP (and I mean TCP in general, not just the way it is used in DDS) requires you to know exactly where to connect to. When you give your web browser a URL, it simply connects to exactly the host and port number that the URL specifies (with some defaults). This is no different.

The closest thing you can get to it working magically is to run one program that every process connects to. That program then needs to tell the others where everyone can be reached, or it can route the data. There are some systems that can do this, the nicest of them all is [Eclipse Zenoh](https://zenoh.io) which is an elegant system for distributed computing, built on a super-efficient fault-tolerant mesh networking protocol that can transparently bridge DDS. Then all DDS processes can simply connect to a Zenoh router.

That said ... is there a specific reason for using TCP instead of UDP (the default)? I've only seen it bring some benefit for DDS in some cases where data needs to traverse the firewalls or the web.

P.S. If you end up using Zenoh directly because of my saying nice things about it, don't worry: it is the work of friends/colleagues, so it is good for Cyclone either way 😁 Really, do look at it, it is worth it!

**Comment by Zhang8912** [comment]
Hi @eboasson, Thanks for your explanation. You are right, I am a really noob. TCP uses a three-way handshake to establish a reliable connection. The first Handshake could not connect, if I did not set the destination IP. 
Yes, there is a reason for using TCP. I think that using UDP + QoS should be better(or equal with) than TCP. So I want to do some tests, after then I will check the result. （Bit Error Rate and Transfer Rate） 
1. Using UDP plus QoS send Data via Channel/Environment.
2. Using TCP send same Data via same condition Channel/Environment.

I am trying to set QoS now, do you know that where can I find any example about cycloneDDS QoS?
thank you in advance

**Comment by alexleel** [comment]
> Hi @Zhang8912, assuming I understand you correctly, then I would say no, not really. TCP (and I mean TCP in general, not just the way it is used in DDS) requires you to know exactly where to connect to. When you give your web browser a URL, it simply connects to exactly the host and port number that the URL specifies (with some defaults). This is no different.
> 
> The closest thing you can get to it working magically is to run one program that every process connects to. That program then needs to tell the others where everyone can be reached, or it can route the data. There are some systems that can do this, the nicest of them all is [Eclipse Zenoh](https://zenoh.io) which is an elegant system for distributed computing, built on a super-efficient fault-tolerant mesh networking protocol that can transparently bridge DDS. Then all DDS processes can simply connect to a Zenoh router.
> 
> That said ... is there a specific reason for using TCP instead of UDP (the default)? I've only seen it bring some benefit for DDS in some cases where data needs to traverse the firewalls or the web.
> 
> P.S. If you end up using Zenoh directly because of my saying nice things about it, don't worry: it is the work of friends/colleagues, so it is good for Cyclone either way 😁 Really, do look at it, it is worth it!

Can we use zenoh + cyclonedds as solution？

**Comment by eboasson** [comment]
> Can we use zenoh + cyclonedds as solution？

I assume you refer to a problem related to the one for which this issue was created, but that's not enough for me to answer your question. Perhaps it would be better to create a new issue and give some information on what you're trying to achieve.
