### ISSUE TITLE
Perftest between containers

### ISSUE THREAD

**Issue by JesseRengers** [eclipse-cyclonedds/cyclonedds#1303]
Hi, I'm trying to run the perftest between two identical containers that both cloned and build cyclonedds, but I don´t get it to work. As the script assumes, I can ssh from one container into the other without passwords.

If I understand correctly, the script searches for bin/ddsperf which is in cyclonedds/build/bin/ so I moved perftest to cyclonedds/build/ to run it like this `./perftest root@172.17.0.3` in one container where 172.17.0.3 is the address in the other container. This runs something but everything fails. Then I saw the `-d` option that you can use to locate the remote DIR that contains /bin/ddsperf/ so I use `./perftest -d ../cyclonedds/build root@172.17.0.3` with the same failing result. 

Am I doing something stupid? Or is this maybe not even possible. Any suggestion will be really welcome. Thanks a lot.

**Comment by eboasson** [comment]
It is a bit finicky ... I wouldn't be surprised if I am the only has actually used it, and so chances are you are simply encountering the consequences of that.

That said, the `perftest` script is merely a (somewhat complex) wrapper around the `ddsperf` executable. Do things seem like they work when you simply run `ddsperf sanity` in the two containers? The output should be something like:
```
# bin/ddsperf sanity
[16991] participant phantasie.example.com:16991: new (self)
[16991] participant phantasie.example.com:16990: new
[16991] 2.002  phantasie.example.com:16990 size 12 mean 274.999us min 274.999us 50% 274.999us 90% 274.999us 99% 274.999us max 274.999us cnt 1
[16991] 3.005  phantasie.example.com:16990 size 12 mean 203.999us min 203.999us 50% 203.999us 90% 203.999us 99% 203.999us max 203.999us cnt 1
```
I simply ran two copies on my laptop (don't mind the numbers, the machine has to come out of sleep states for each message and it is a debug build) hence the same host name.

If that fails, most likely it has something to do with trying to run it in containers; if that works, most likely it has something to do with the script.

**Comment by JesseRengers** [comment]
Thanks for looking into my problem! ddsperf works between two containers, this is the output of ddsperf sanity check:
```
root@4970ad743a42:/cyclonedds/build/bin# ddsperf sanity
[13] participant 4970ad743a42:13: new (self)
[13] participant 193f82fd5963:14: new
[13] 2.001  193f82fd5963:14 size 12 mean 313.986us min 313.986us 50% 313.986us 90% 313.986us 99% 313.986us max 313.986us cnt 1
[13] 3.001  193f82fd5963:14 size 12 mean 188.761us min 188.761us 50% 188.761us 90% 188.761us 99% 188.761us max 188.761us cnt 1
```

The output of the perftest script is the following:
```
root@4970ad743a42:/cyclonedds/build# ./perftest -d ../cyclonedds/build root@172.17.0.3
cdds-simple.xml                               100%  659   601.8KB/s   00:00    
======== ASYNC 0 MODE listener =========
run-remote.tmp                                100%  802   742.7KB/s   00:00    
size 0
1655125673.488897 [17]    ddsperf: config: //CycloneDDS/Domain/Internal/LeaseDuration: setting moved to //CycloneDDS/Domain/Discovery/LeaseDuration (file:///cyclonedds/build/cdds-simple.xml line 10)
1655125673.488930 [17]    ddsperf: config: //CycloneDDS/Domain/Internal/MinimumSocketReceiveBufferSize: setting moved to //CycloneDDS/Domain/Internal/SocketReceiveBufferSize[@min] (line 11)
1655125673.491191 [17]    ddsperf: failed to increase socket receive buffer size to at least 6291456 bytes, current is 425984 bytes
dds_create_participant(domain -1) failed: -1
```

After that there is a long list of failed test because the `dds_create_participant` function fails each time.
I wanted to use the perftest because it seems like an easy way to test performance (throughput and latency) with different security modes and message rates.

**Comment by eboasson** [comment]
Two of those lines are because I forgot to update the configuration written by the `perftest` script when some changes were made to the configuration 🙄 It isn't much a problem because it still handles the old ones, but it is a bit sloppy.

This:
```
1655125673.491191 [17]    ddsperf: failed to increase socket receive buffer size to at least 6291456 bytes, current is 425984 bytes
```
is because the script writes a configuration file that includes a requirement that the UDP socket receive buffer is at least 6MB:

https://github.com/eclipse-cyclonedds/cyclonedds/blob/a1f1f9cad6ecc96b149d538c07cc8c47fd6b814c/examples/perfscript/perftest#L315

The default limit of a Linux kernel is about 400kB, and so it fails. The default behaviour is to ask for 1MB and to accept whatever it is given.

* Raising the limit is [pretty easy](https://stackoverflow.com/questions/16460261/linux-udp-max-size-of-receive-buffer) and pretty harmless. I usually increase the UDP socket receive buffer size limit on Linux when I try to measure the maximum throughput, but most of the time I use macOS and there the 6MB is acceptable by default ...
* You could also simply comment out the request for 6MB, it won't affect anything for samples smaller than roughly 400kB.
* The proper solution is to update the script to use the new options: you can now also ask for 6MB without failing if you get less — see https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/docs/manual/options.md#cycloneddsdomaininternalsocketreceivebuffersize for some more details
