### ISSUE TITLE
 send big udp packet (400K) has big loss rate in best-effort mode

### ISSUE THREAD

**Issue by fengtuo58** [eclipse-cyclonedds/cyclonedds#1304]

**Comment by fengtuo58** [comment]
anyone knowns how cyclone-dds send big udp packets with good loss rate?

**Comment by eboasson** [comment]
What DDS called "best-effort" is what traditionally was called "send-and-forget" or "unreliable": there is no retransmit of lost packets, and so losing a packet means losing the sample. Typically with modern networks (except multicast over WiFi) the actual packet loss rate at the interface level is very low. Whatever loss you see tends to be caused by buffer overflows.

The most common problem is that the UDP socket receive buffer overflows. The default maximum size of that buffer in Linux is about 400kB. You can raise that limit, see, e.g., https://docs.ros.org/en/foxy/How-To-Guides/DDS-tuning.html#cyclone-dds-tuning

**Comment by fengtuo58** [comment]
@eboasson thanks and  is the function named with "dds_write"  thread-safe ?
