### ISSUE TITLE
How can I get RemoteIP from remote Readers

### ISSUE THREAD

**Issue by Zhang8912** [eclipse-cyclonedds/cyclonedds#1305]
Hi everyone,

I am trying to read DDS and RTPS Protocal, but it is really difficult. So now I am trying to learn it with our Source Codes.

I have a noob question again. Did someone know, how can I find RemoteIP/DestinationIP in our Source Code when I use UDP Protocal?

thanks in advance

![image](https://user-images.githubusercontent.com/103993997/173314560-f1de06f6-7a89-42e4-b699-df2543c03849.png)

**Comment by eboasson** [comment]
Your question is a bit vague, so I can either give a short hint or a TL;DR-style response. 🤔 I'll opt for the first, I think.

The bit of the code you code determines the local address. This address is copied into the "locators" in the SPDP (Simple Participant Discovery Protocol) messages it sends out (see 8.5.3.2 SPDPdiscoveredParticipantData). Processes that receive an SPDP message then use this locator to communicate with it.

You might want to check

* https://github.com/eclipse-cyclonedds/cyclonedds/blob/a1f1f9cad6ecc96b149d538c07cc8c47fd6b814c/src/core/ddsi/src/q_ddsi_discovery.c#L398 where it adds the locators the message
* https://github.com/eclipse-cyclonedds/cyclonedds/blob/a1f1f9cad6ecc96b149d538c07cc8c47fd6b814c/src/core/ddsi/src/q_ddsi_discovery.c#L890 where it looks at the received locators

There is of course more to it, it needs to (de)serialised (for that, see `ddsi_plist.c`) and the `proxy_participant` it constructs based on the received SPDP message needs to store the address somewhere (which is why it constructs an `addrset` and passes it round). This is really just a starting point for digging a bit more.

**Comment by Zhang8912** [comment]
> Your question is a bit vague, so I can either give a short hint or a TL;DR-style response. 🤔 I'll opt for the first, I think.
> 
> The bit of the code you code determines the local address. This address is copied into the "locators" in the SPDP (Simple Participant Discovery Protocol) messages it sends out (see 8.5.3.2 SPDPdiscoveredParticipantData). Processes that receive an SPDP message then use this locator to communicate with it.
> 
> You might want to check
> 
> * https://github.com/eclipse-cyclonedds/cyclonedds/blob/a1f1f9cad6ecc96b149d538c07cc8c47fd6b814c/src/core/ddsi/src/q_ddsi_discovery.c#L398
>    where it adds the locators the message
> * https://github.com/eclipse-cyclonedds/cyclonedds/blob/a1f1f9cad6ecc96b149d538c07cc8c47fd6b814c/src/core/ddsi/src/q_ddsi_discovery.c#L890
>    where it looks at the received locators
> 
> There is of course more to it, it needs to (de)serialised (for that, see `ddsi_plist.c`) and the `proxy_participant` it constructs based on the received SPDP message needs to store the address somewhere (which is why it constructs an `addrset` and passes it round). This is really just a starting point for digging a bit more.

hi，eboasson [eboasson](https://github.com/eboasson). Thank you for reply. Based your answer I have tested it in q_ddsi_discovery.c #L890
There are **numbers** of multicast = 1, **kind = 1** and **port = 7400**. But when I print address, there is no value for address. 
Did I something wrong for this? 

![image](https://user-images.githubusercontent.com/103993997/175224960-e4baf14c-6517-4641-9fbd-dfc667253634.png)
![image](https://user-images.githubusercontent.com/103993997/175225051-153f562c-6a0e-4e13-9716-8e8ea76448a4.png)

**Comment by eboasson** [comment]
Hi @Zhang8912, the `address` field of the locator is not a string, it contains the address in binary (for IPv4 it has the address in the last 4 bytes of the `address` array).

(In general I would suggest converting the locator into a string using the appropriate functions — see https://github.com/eclipse-cyclonedds/cyclonedds/blob/eac87dc822b815de618eb3f2520e636f736fe4bf/src/core/ddsi/src/q_init.c#L1433 for an example — but you could of course also simply print the bytes in the `address` array.)

**Comment by thijsmie** [comment]
Please note that nowadays on the builtin topic DCPSParticipant there is a `__NetworkAddresses` property in the QoS that tells you about the ips of remote participants. The previous strategy Erik outlined also still works.
