### ISSUE TITLE
Multi process optimization when using cyclone dds

### ISSUE THREAD

**Issue by sgf201** [eclipse-cyclonedds/cyclonedds#1314]
I found that when using a, two or three threads will be created in the background. they are "tev" "recvMc" "recvUc".When I have multiple processes using a on the node, the CPU resources occupied by these threads cannot be ignored. Is there any way to reduce their CPU occupation, for example: 1 Increase the query interval of network data 2 Multiple processes share a server, because the local communication actually uses iceoryx. Are there any suggestions or practices of others， thanks alot。
23395     1     25265 TS       -   0  19   5  6.8 Sl   skb_recv_datagram              recvMC
......
23476 23393 23850 TS       -   0  19   5  2.9 Sl   skb_recv_datagram              recvMC
......
23792 23393 24241 TS       -   0  19   0  8.4 Sl   skb_recv_datagram              recvMC

**Comment by eboasson** [comment]
The "tev" thread is used for all almost background processing and can't be eliminated, but the "recv", "recvUC" and "recvMC" thread can be combined into a single one if you want (see https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/docs/manual/options.md#cycloneddsdomaininternalmultiplereceivethreads) but that will only help with thread stacks and other overhead associated with having threads. Whatever work they do as a consequence of receiving a packet is not so easily reduced.

When using Iceoryx, each process is still directly talking to the network and any multicasts it picks up will be processed by those threads. Is this the load you are seeing? I would suspect so, given that you're showing CPU usage by the thread picking up multicasts for application data.

The ultimately solution to that (which we do intend to do one day) is to have a mode where one Cyclone DDS process acts as a gateway to the network. [There is a gateway like that in the Iceoryx distribution](https://github.com/eclipse-iceoryx/iceoryx/tree/master/iceoryx_dds) but I have not yet tried to figure out if that can be pressed into service as a generic network gateway for DDS applications.

The other thing you can look at is using multiple multicast addresses:
* Split discovery and data by changing the [DefaultMulticastAddress](https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/docs/manual/options.md#cycloneddsdomaindiscoverydefaultmulticastaddress)
* Think about the major data flows and make sure that data flows that don't need to go to some machine X are mapped to a unique address using ["network partitions"](https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/docs/manual/config.rst#network-partition-configuration)

This should help because it always joins the "SPDPMulticastAddress" and the "DefaultMulticastAddress" (if not 0.0.0.0), but any multicast addresses configured as network partitions are only joined when there are subscriptions to the data.
