### ISSUE TITLE
Running Helloworld example with custom application. 

### ISSUE THREAD

**Issue by hassanb199** [eclipse-cyclonedds/cyclonedds#1318]
So I want to use the code defined in the the hello world example, specifically in "publisher.c". This is what I changed it to: 

![image](https://user-images.githubusercontent.com/73851790/176096519-34507bdd-f97b-4ed8-927d-1f679a1ba15d.png)

This is what it was defined as originally:

![image](https://user-images.githubusercontent.com/73851790/176096712-9ec416c7-81e7-4252-af59-d698e9bfd91d.png)

Once I do that I get the following error: 

![image](https://user-images.githubusercontent.com/73851790/176096889-3b9a60c9-0dd5-4e7b-8cda-17702c148b5e.png)

So I guess my question would be, how would I use the code from publisher.c in the helloworld example in a way that would not cause this error? Thank you.

**Comment by eboasson** [comment]
That's just one of the things of the "C" language: each application must have one function called `main`, and that's (roughly) where execution starts (see, e.g., page 14 of [The C Programming Language](https://archive.org/details/TheCProgrammingLanguageFirstEdition/page/n13/mode/2up)). So if you take `publisher.c` and rename the function, the [compiler](https://en.wikipedia.org/wiki/Compiler) (*) will start complaining.

I don't want to discourage you, but "C" is not the friendliest of languages. We have this lovely [Python binding](https://github.com/eclipse-cyclonedds/cyclonedds-python) that gives you a much easier path into building applications using Cyclone DDS. (We even have an [interactive tutorial](https://cyclonedds.io/content/guides/interactive-tutorial-chapter-1.html)!)

I'm closing this as really not being a Cyclone DDS issue but a more fundamental question about how to use "C". I think using Python or reading a more recent edition of the book I linked to (just be sure to find a more recent edition, or else one of many other ones books on C published since) will help you more at this stage.

(*) Well, technically, it is the [linker](https://en.wikipedia.org/wiki/Linker_(computing)) that's complaining. The distinction is really important in the long run when you want to use "C" (and many other languages), but in the short run they can also be thrown together as "the software that takes my application source code and turns into something I can run".
