### ISSUE TITLE
Configuration for a ROS2 system with 3 computers

### ISSUE THREAD

**Issue by AndyZe** [eclipse-cyclonedds/cyclonedds#1323]
I'm interested in configuring Cyclone for a ROS2 (Rolling) system with 3 computers. There is an operator station, a computer onboard the robot, and a computer to handle vision.

I'm nervous about doing this from reading the discussion here: https://discourse.ros.org/t/unconfigured-dds-considered-harmful-to-networks/25689

A config file to disable multicast was posted here:  https://discourse.ros.org/t/unconfigured-dds-considered-harmful-to-networks/25689/23?u=andyze

But I don't believe this will work for my system with 3 computers because we have DDS between machines.

Would this be a good idea since it only uses multicast for discovery (if I read correctly):

`<AllowMulticast>spdp</AllowMulticast>`

More background on our system:

- There is not a large amount of data flowing between machines. It is small robot control messages at a high rate
- Latency minimization is important
- Large messages (pointclouds) stay local to the vision machine

(@zflat)

**Comment by AndyZe** [comment]
This was also recommended to me. This is for 2 computers with multicast disabled:

```
<?xml version="1.0" encoding="utf-8"?>
<CycloneDDS xmlns="https://cdds.io/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://cdds.io/config https://raw.githubusercontent.com/eclipse-cyclonedds/cyclonedds/master/etc/cyclonedds.xsd">
  <Domain id="any">
    <General>
      <NetworkInterfaceAddress>TODO_IFCONFIG</NetworkInterfaceAddress>
      <AllowMulticast>false</AllowMulticast>
    </General>
    <Discovery>
      <ParticipantIndex>auto</ParticipantIndex>
      <Peers>
        <Peer Address="TODO_COMPUTER_1_IP_ADDRESS" />
        <Peer Address="TODO_COMPUTER_2_IP_ADDRESS" />
      </Peers>
      <MaxAutoParticipantIndex>120</MaxAutoParticipantIndex>
    </Discovery>
  </Domain>
</CycloneDDS>
```

**Comment by eboasson** [comment]
Well, most people that use the "considered harmful" phrase never actually read the letter to the editor that introduced it in the business and certainly complete ignored the context 🙂

But yes, it is true that multicast *can* bring networks to their knees. Whether it actually does in a given setting is a wholly different matter. I know lots and lots of systems that have huge amounts of multicasting going on all the time without a problem, and I know networks where a tiny typo will crash a router/firewall ... the old one in the office was one of them ...

Using multicast for 1st stage discovery (i.e., (simple) participant discovery (protocol), a.k.a. "SPDP") is almost invariably a good idea, and that holds for all DDS implementations. The alternative is that you have to spell out machines to ping by hand (*) and then you get into the trouble of the "participant index" or "which UDP ports to ping"?

The higher `MaxAutoParticipantIndex` is set, the more port numbers will be pinged, but that really is the same as saying the SPDP bursts simply get bigger and bigger. See also https://github.com/eclipse-cyclonedds/cyclonedds/issues/729#issuecomment-807153175 . I suspect 120 is vastly more than you actually need. Still allowing multicast usually results in the most elegant behaviour, provided the network handles it properly. A few things here are worth noting:

* Don't try to rely on multicast (save for SPDP) on WiFi. WiFi multicast is horrible. (Sadly, because the physics of it exactly match multicast ...)
* A halfway decent switch will do IGMP snooping, and that can make a huge difference by keeping the DDS traffic local to the machine that needs it. Multicast is at the IP level, and so the IGMP snooping doesn't look at port numbers. If you have a DDS domain 0 running somewhere and and a DDS domain 1 running elsewhere, the multicasts'll happily be forwarded, only to be dropped because the port numbers don't match. You can simply configure different addresses to address this.
* Low-rate multicast on wired networks is almost never a problem. I wouldn't worry at all about 1k packets/s, but at 10k packets/s I start getting a little uncomfortable.
* Cyclone is pretty careful in using multicast only when there are multiple subscribed IP addresses. It can be tweaked to separate loopback and the physical network, and at least in the code it can be tweaked to change the point where it switches to multicast.

If you're concerned about the sort of thing those "considered harmful" people are describing, the first thing I'd look at is IGMP snooping and using some unique multicast address. One option you also have is to:

* set a unique SPDP multicast address (`Discovery/SPDPMulticastAddress`)
* clear the "default" multicast address for data (`Discovery/DefaultMulticastAddress` = `0.0.0.0`)
* define ["network partitions"](https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/docs/manual/options.md#cycloneddsdomainpartitioningnetworkpartitions) to map some topics where really want multicast to be used to unique multicast addresses:
  ```
  <Partitioning>
    <NetworkPartitions>
      <NetworkPartition address="239.255.0.3" name="a"/>
      <NetworkPartition address="239.255.0.4" name="c"/>
      <NetworkPartition address="239.255.0.5" name="e"/>
    </NetworkPartitions>
    <PartitionMappings>
      <PartitionMapping DCPSPartitionTopic="*.a" NetworkPartition="a"/>
      <PartitionMapping DCPSPartitionTopic="*.b" NetworkPartition="a"/>
      <PartitionMapping DCPSPartitionTopic="*.c" NetworkPartition="c"/>
      <PartitionMapping DCPSPartitionTopic="*.d" NetworkPartition="c"/>
      <PartitionMapping DCPSPartitionTopic="*.e" NetworkPartition="e"/>
      <PartitionMapping DCPSPartitionTopic="*.f" NetworkPartition="e"/>
    </PartitionMappings>
  </Partitioning>
  ```
  Anything not matched by a mapping will go to the default address, and if that's "empty", it will use unicast.

That's what I'd try first ... or actually, second, the first thing I'd try would be to not worry at all 🙂

(*) Cyclone only needs this in one direction, which makes it quite doable in a hub-and-spoke configuration. But I still hate doing it.
