### ISSUE TITLE
custom serializing structured data support(google protobuf or capnproto)

### ISSUE THREAD

**Issue by xixioba** [eclipse-cyclonedds/cyclonedds#1327]
As mentioned in the title, protobuf is already a more general standard than idl
In order to use it (further, in zero copy, with iceoryx), I ran into some problems
1. I need to transfer data of dynamic length, it depends on how the user pads the protobuf, so obviously no one knows the maximum length and use fixed size
2. The urgent need for zero copy in IPC, in fact, I may have multiple lidar data, I need to combine and transfer them in the computer of the vehicle

For this I tested other solutions,
- ecal, obviously it can support zero copy + protobuf, but unfortunately it is not a standard dds implementation, and has some issues 
https://github.com/continental/ecal/issues/697#issue-1282096599
- fast-dds, it has its own zero copy implementation, but again, it does not support dynamic data lengths
https://github.com/eProsima/Fast-DDS/discussions/2773#discussioncomment-3078714
- zenoh, it seems to already work with zero copy, ~~but I'm not sure yet if it can interact with dds, but I've decided to use it partially on my project~~

**Comment by xixioba** [comment]
Aboud dynamic size types(no fixed size): https://github.com/eclipse-iceoryx/iceoryx/issues/911
ecal describes an zero-copy implementation, and iceoryx seems to already support it too
can it be used？🤔

**Comment by xixioba** [comment]
Thank you very much for your reply.

For the assumption, I need to explain that in a loop, I will obtain rawdata of dynamic length from the outside (protobuf need serialization stage), and then I hope to use dds interprocess communication, there is a stage of copying to load_sample, on the receiving end , I should try to avoid reorganizing the data, especially for tens of megabytes of data

I'm not sure if the application layer data chunking works as intended in the above case (the interprocess stage is only copied once)

I'd love to try mixing iceoryx and dds, but I have a question, how can I determine using dds or iceoryx to send data (assuming the whole system involves M computers * N processes [maybe Z innerprocess])

**Comment by eboasson** [comment]
Apologies for replying so late ...

> I'd love to try mixing iceoryx and dds, but I have a question, how can I determine using dds or iceoryx to send data (assuming the whole system involves M computers * N processes [maybe Z innerprocess])

Yes, that's the tricky bit indeed ... we do it by discovering locations and checking addresses to decide whether Iceoryx can be used, then select the path(s) to use. Having to do that again at the application level kinda defeats the purpose!

> on the receiving end , I should try to avoid reorganizing the data, especially for tens of megabytes of data

This bit I didn't realise before. If it's only on the receiving end ... let's see ... suppose you'd do a topic like:
```C
@topic @final
struct T { sequence<octet> protobuf_data; };
```
then on writing, you could do:
```
t.protobuf_data._length = t.protobuf_data._maximum = <size of protobuf data>;
t.protobuf_data._buffer = <pointer to serialised protobuf message>
t.protobuf_data._release = false; // pro-forma, DDS isn't go to try to free it on writing
```
and call `dds_write(&t)`. It will serialize it (whether for Iceoryx or for network traffic, because of the variable length content), but it forces only a single copy of the raw data. If you own the protobuf payload buffer, can put a small header in front of it and can keep it around for a long time, some more tricks might be possible.

The receiver will store a pointer to the CDR blob. If it comes in over Iceoryx, it will point to the serialized data in shared memory; if it came in over the network, it'll be a consolidated copy of the fragments received over the network. A call do `dds_take` will copy all this, but there is also `dds_takecdr` which returns a pointer to the (refcounted) internal sample representation (a `struct ddsi_serdata *`). From this, you can extract a reference to the CDR payload (`ddsi_serdata_to_ser_ref`/`ddsi_serdata_to_ser_unref`). In the current design, C applications can rely on the CDR being in native byte order and not having any illegal values in there (like a sequence length that overflows the payload).

You'd have to figure out where the payload blob started, though. For a topic this simple it would use XCDR1 and the serialised form would simply be a 32-bit integer containing `protobuf_data._length`, immediately followed by the protobuf data.

For more complicated types and more complicated serialization formats, it'd be a bit different. As long as you avoid `@mutable` and you have the blob at the end, there is always the possibility of defining the type without the blob (just a header, basically), calling the deserializer on that manually and then using the offset where it stopped to extract the payload. You'd be looking at `dds_istream_from_serdata_default` and `dds_stream_read_sample` for that.

Come to think of it, you could even do:
```C++
struct Header { ... };
struct HeaderPlusLength : Header { unsigned long protobuf_data_length; };
struct Payload : Header { sequence<octet> protobuf_data; };
```
and then create two readers, one for `HeaderPlusLength` and one for `Payload`. That should work, they'd share this `ddsi_serdata` and taking data from the `Header` subscription would not trigger deserialization of the payload. `ddsi_serdata_to_ser_ref` would give you the pointer to the start of the CDR plus the length *N*, and so the protobuf payload starts at *N* - `protobuf_data_length`.

I'm not saying this is an ideal solution, or even the best possible at the time, but it is the first trick that comes to my mind for saving a copy on the receiving side.Clearly it relies on some implementation details and some interfaces that are outside the stable API (like the serializer interfaces), but the described behaviour and these interfaces have been pretty stable for quite some time now, and certainly stable enough for an experiment.

**Comment by xixioba** [comment]
Looks great, I'll try some when I have time

**Comment by thijsmie** [comment]
A nice guide was provided by Erik and no more feedback was forthcoming. Open a new issue or join the discord if there are any developments :D.
