### ISSUE TITLE
Communication is broken with ROS2 Rolling

### ISSUE THREAD

**Issue by sumanth-nirmal** [eclipse-cyclonedds/cyclonedds#1328]
## Required information

**Operating system:**
Ubuntu 20.04 LTS

**Version:**
Cyclone - 740552b7efa65bac356258c119a9049cc2710e3a
**Problematic commit** - a01967517cdeb3f90b4d6fc4adbf934023378f72
ROS2 - rolling

**Observed result or behavior:**

Cyclone DDS can't match to writer from ros2 rolling which causes the communication to fail eventually

**Reproducer**

1. Publish a msg on a topic from ROS2 (rolling)

   ```sh
   # source ros2 rolling
   ros2 topic pub tooch std_msgs/String
   ```

2. A subscriber on cyclone which is subscribed to the data published by ROS2 node
    - cyclone dds subscriber logic
    ```cpp
    dds::domain::DomainParticipant participant(domain::default_id());
    dds::topic::Topic<std_msgs::msg::dds_::String_> topic(participant, "rt/tooch");
    dds::sub::Subscriber subscriber(participant);
    dds::sub::DataReader<std_msgs::msg::dds_::String_> reader(subscriber, topic);
    dds::sub::cond::ReadCondition rc(reader, dds::sub::status::DataState::any());
    dds::core::cond::WaitSet waitset;
    waitset.attach_condition(rc);

    while (true) {
      waitset.wait(dds::core::Duration(10, 0));

      auto samples = reader.take();
      for (auto & sample :samples) {
        if (sample.info().valid()) {
          std::cout << "received data: " << sample.data().data_().c_str() << "\n";
        } 
      }
    }
    ```
    - IDL file for the message 
    ```hpp
    # idl file for the message
    module std_msgs {
    module msg {
    module dds_ {
    struct String_ {
    string<255> data_;
    };
    };
    };
    };
    ```

The communication doesn't happen with this setup. \
Log file where communication doesn't happen is here [non-working-log.log](https://github.com/eclipse-cyclonedds/cyclonedds/files/9068226/non-working-log.log)

However, if we try the same setup with the only change that the Cyclone version is something before the problematic commit (I used the [0.9.1 tag](https://github.com/eclipse-cyclonedds/cyclonedds/releases/tag/0.9.1)) and the communication then works, the log file where communication works is here [working-log.log](https://github.com/eclipse-cyclonedds/cyclonedds/files/9068227/working-log.log)

**Details**

We realized that this setup was working before this commit a01967517cdeb3f90b4d6fc4adbf934023378f72 which is merged as part of the MR https://github.com/eclipse-cyclonedds/cyclonedds/pull/1281. I have checked the changes in this commit but was unable to identify the problem except that the property QoS is also now considered for matching.

**Expected result or behavior:**

The communication should also happen with native ros2 nodes

**Comment by eboasson** [comment]
From the log file, I see nothing wrong, but it does appear that the other side is Fast-RTPS. It is conceivable that it rejected the discovery data because of the additional properties — whether rightly or wrongly is irrelevant for now. Is there any way of checking this?

**Comment by sumanth-nirmal** [comment]
@eboasson I was thinking along the same lines, but what I don't understand is that the same setup (Cyclone on one side and FastRTPS on another side) works but before this commit https://github.com/eclipse-cyclonedds/cyclonedds/commit/a01967517cdeb3f90b4d6fc4adbf934023378f72.

Also, the following diff

```diff
-qosdiff = ddsi_xqos_delta (&pp->plist->qos, &ddsi_default_plist_participant.qos, QP_USER_DATA | QP_ENTITY_NAME | QP_PROPERTY_LIST);
+qosdiff = ddsi_xqos_delta (&pp->plist->qos, &ddsi_default_plist_participant.qos, QP_USER_DATA | QP_ENTITY_NAME);
```

makes the communication work again.

Is it possible that somehow this change triggers a behavior in FastRTPS to reject the discovery data?

**Comment by eboasson** [comment]
@sumanth-nirmal I suspect so: in that commit it starts adding a property list QoS to the discovery data, for the first time ... so if (rightly or wrongly) Fast-RTPS is unhappy with that property list, it (w|sh)ould cause it to reject the discovery data

**Comment by sumanth-nirmal** [comment]
@eboasson I looked into FastRTPS code and this part of the code seems to be the problem (or not?) https://github.com/eProsima/Fast-DDS/blob/5c563c612fad602e9ac48ea54dec63d0b1d29509/src/cpp/fastdds/core/policy/ParameterSerializer.hpp#L674-L675

From the logic here https://github.com/eProsima/Fast-DDS/blob/5c563c612fad602e9ac48ea54dec63d0b1d29509/src/cpp/fastdds/core/policy/ParameterSerializer.hpp#L674-L675 and here https://github.com/eProsima/Fast-DDS/blob/5c563c612fad602e9ac48ea54dec63d0b1d29509/src/cpp/fastdds/core/policy/ParameterList.hpp#L73-L140 it seems that the parameter length field should only include the length of the parameters but not the prefix 4 bytes with the Parameter ID and the parameter length

The builtin entity data on the wire for the participant from Cyclone is as below

```hpp
   00 03 00 00     // Identifier
   59 00 68 00     // PID_PROPERTY_LIST parameter id and 104 bytes parameter length
   03 00 00 00     // 3 parameters
   0e 00 00 00     // key-1
   5f 5f 50 72    6f 63 65 73   73 4e 61 6d   65 00 00 00   
   07 00 00 00     // value-1
   74 61 6c 6b   65 72 00 00  
   06 00 00 00     // key-2
   5f 5f 50 69   64 00 00 00   
   05 00 00 00     // value-2
   32 35 31 39   00 00 00 00  
   0b 00 00 00     // key-3
   5f 5f 48 6f   73 74 6e 61   6d 65 00 00   
   11 00 00 00     // value-3
   6e 6f 6e 5f   77 6f 72 6b   69 6e 67 5f   68 61 73 68   00 00 00 00  
```

The actual parameter length is only 100 (ignoring the Parameter-id and the length fields). Do you think this is the issue?
(I didn't find the exact place where this length is update)

**Comment by eboasson** [comment]
Interesting observation @sumanth-nirmal 🤔

Two things that seem relevant to me come to mind immediately:

First is that the length in the parameter header may include additional padding without rendering the parameter malformed, but what is important is that the next parameter header is at the indicated offset, so 100/104 is not per se invalid, just totally against my expectations of Cyclone not doing stupid things like that. 🙂

Not that one has complete freedom in making in longer, because that freedom is intended to be used — and indeed, has been used — for adding additional data to an existing parameter. See, e.g., the evolution of `TypeConsistencyEnforcementQosPolicy` in the various revisions of the XTypes spec.

Second is that I think there are 4 bytes, all 0 missing at the end in your hex dump, because in:
```
11 00 00 00     // value-3
   6e 6f 6e 5f   77 6f 72 6b   69 6e 67 5f   68 61 73 68   00 00 00 00
```
the first `00` is the terminating 0 for the string, the other 3 are padding (all consistent with a string length of 11-including-terminating-0), but the property list as defined in the DCPS spec has undergone a strange evolution as well.
* DDSI 2.0 (of 2008) to 2.5 (of 2021), table 9.18: `PID_PROPERTY_LIST`, 0x0059, `sequence<Property_t>` where `Property_t` is a struct of two strings
* DDS Security 1.1 (of 2018), see section 7.2.1, too long to copy-paste ... but the gist of it is that the the property list parameter is extended to:
  ```
  struct Property_t { string name; string value; @non-serialized boolean propagate; };
  typedef sequence< Property_t > PropertySeq;
  struct BinaryProperty_t { string name; OctetSeq value; @non-serialized boolean propagate; };
  typedef sequence< BinaryProperty_t > BinaryPropertySeq;
  struct PropertyQosPolicy {
    PropertySeq value;
    BinaryPropertySeq binary_value; 
  };
  ```

A generous person might consider this transformation "clever", because the serialization of the "old" property list is a prefix of the serialization of the new one, and if there's no data left where the `BinaryPropertySeq` is expected, then you know you are dealing with the old one, and the value of the `propagate` boolean for is implied by the fact it has been transmitted.

The serializer in Cyclone for this stuff is defined by https://github.com/eclipse-cyclonedds/cyclonedds/blob/9e9815a03d35291d45b9c1ec8df6bd93c00aea54/src/core/ddsi/src/ddsi_plist.c#L1892 and  https://github.com/eclipse-cyclonedds/cyclonedds/blob/9e9815a03d35291d45b9c1ec8df6bd93c00aea54/src/core/ddsi/src/ddsi_plist.c#L1189. The `Xopt` code indicates an optional part (which causes some contortions in the deserializer), but as you can see at https://github.com/eclipse-cyclonedds/cyclonedds/blob/9e9815a03d35291d45b9c1ec8df6bd93c00aea54/src/core/ddsi/src/ddsi_plist.c#L1331-L1332, during serialization it just continues straight in the binary properties list and so outputs 4 zeros to indicate an empty list. This is legal and used to be fine because no-one actually used properties outside of security, but now it is wasting 4 bytes for each participant discovery message which may make it worth the effort of looking ahead to see if any further output would be generated.

The parameter length is computed by https://github.com/eclipse-cyclonedds/cyclonedds/blob/9e9815a03d35291d45b9c1ec8df6bd93c00aea54/src/core/ddsi/src/ddsi_plist.c#L1119 which behaves the same as the actual serializer.

So I would expect the length of the empty binary properties list to show up here as well. I checked locally, the only thing that matters being the lengths of the parameters and those being similar enough to make me think the result is indicative:
```
1657691509.020952 [0] dq.builtin: DDSI_PLIST_INIT (bswap 0)
1657691509.020969 [0] dq.builtin:    0 PID 2c len 36 31,0,0,0,"DDSPerf:0:55293:phantasie.local",0
1657691509.020999 [0] dq.builtin:   28 PID 59 len 100 3,0,0,0,14,0,0,0,"__ProcessName",0,0,0,8,0,0,0,"ddsperf",0,6,0,0,0,"__Pid",0,0,0,6,0,0,0,"55293",0,0,0,11,0,0,0,
"__Hostname",0,0,16,0,0,0,"phantasie.local",0,0,0,0,0
1657691509.021013 [0] dq.builtin:   90 PID 15 len 4 2,1,0,0
1657691509.021022 [0] dq.builtin:   98 PID 16 len 4 1,16,0,0
1657691509.021031 [0] dq.builtin:   a0 PID 2 len 8 10,0,0,0,0,0,0,0
1657691509.021046 [0] dq.builtin:   ac PID 50 len 16 1,16,139,83,66,1,246,49,228,159,19,100,0,0,1,193
1657691509.021056 [0] dq.builtin:   c0 PID 58 len 4 63,252,0,0
1657691509.021064 [0] dq.builtin:   c8 PID f len 4 0,0,0,0
1657691509.021079 [0] dq.builtin:   d0 PID 31 len 24 1,0,0,0,241,207,0,0,0,0,0,0,0,0,0,0,0,0,0,0,127,0,0,1
1657691509.021097 [0] dq.builtin:   ec PID 48 len 24 1,0,0,0,233,28,0,0,0,0,0,0,0,0,0,0,0,0,0,0,239,255,0,1
1657691509.021113 [0] dq.builtin:  108 PID 32 len 24 1,0,0,0,241,207,0,0,0,0,0,0,0,0,0,0,0,0,0,0,127,0,0,1
1657691509.021128 [0] dq.builtin:  124 PID 33 len 24 1,0,0,0,232,28,0,0,0,0,0,0,0,0,0,0,0,0,0,0,239,255,0,1
1657691509.021163 [0] dq.builtin:  140 PID 8007 len 64 0,0,0,0,44,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,37,0,0,0,"phantasie.local/0.10.0/Darwin/Darwin",0,0,0,0
1657691509.021172 [0] dq.builtin:  184 PID 8019 len 4 0,0,16,0
1657691509.021178 [0] dq.builtin:  18c PID 1
1657691509.021239 [0] dq.builtin: data(builtin, vendor 1.16): 0:0:0:0 #1: ST0 /ParticipantBuiltinTopicData:{user_data=31<"DDSPerf:0:55293:phantasie.local">,\
property_list={1:"__ProcessName":"ddsperf",1:"__Pid":"55293",1:"__Hostname":"phantasie.local"}:{},\
protocol_version=2:1,vendorid=1:16,participant_lease_duration=10000000000,\
participant_guid={1108b53:4201f631:e49f1364:1c1},builtin_endpoint_set=64575,\
domain_id=0,default_unicast_locator={udp/127.0.0.1:53233},\
default_multicast_locator={udp/239.255.0.1:7401},\
metatraffic_unicast_locator={udp/127.0.0.1:53233},\
metatraffic_multicast_locator={udp/239.255.0.1:7400},\
adlink_participant_version_info=0:44:0:0:0:"phantasie.local/0.10.0/Darwin/Darwin",\
cyclone_receive_buffer_size=1048576}
```


Note that my hostname is 1 byte shorter than yours, and so where in your case the terminating 0 is in the last group of four and 3 bytes padding are required, in my case the terminating 0 is one earlier and the last group of four is the binary property sequence length.

(That fragment was obtained by running Cyclone with `<Tracing><Cat>trace,plist</>`, which is an almost trivial way to get a dump of the parameter lists, line-splitting in the decoded parameter list by hand, for readability. The decoded parameter list has the properties of the form {b:k:v,...}:{b:k:v,...}, where `b` is the implied `propagate` field, `k` the key, `v` the value, the first list the string properties and the second the binary ones.)

So if those 4 bytes 0 are present, then presumably it is valid (but note the years in which the specs were published ... perhaps one is allowed to serialize the binary properties if and only if security is enabled and no-one told me so?), but it is also plausible that it confuses Fast-RTPS.

Changing the serializer to look ahead is trivial for this case (just check if the following sequence is empty), but not so trivial in the more general case. If think you could, by way of experiment, make the serializer and the function computing the serialized size treat `Xopt` the same as `XSTOP`. It is not a solution, but it might be the easiest way to test the hypothesis.

**Comment by sumanth-nirmal** [comment]
@eboasson Thanks for the informative reply. The last 4 bytes with all 0 are there in the serialized data, but sorry I think I omitted it when posting it here. Below is the builtin participant data

```sh
657763071.244352 [0] dq.builtin: DDSI_PLIST_INIT (bswap 0)
1657763071.244390 [0] dq.builtin:    0 PID 59 len 104 3,0,0,0,14,0,0,0,"__ProcessName",0,0,0,7,0,0,0,"talker",0,0,6,0,0,0,"__Pid",0,0,0,5,0,0,0,"2591",0,0,0,0,11,0,0,0,"__Hostname",0,0,17,0,0,0,"non_working_hash",0,0,0,0...
1657763071.244419 [0] dq.builtin:   6c PID 15 len 4 2,1,0,0
1657763071.244425 [0] dq.builtin:   74 PID 16 len 4 1,16,0,0
1657763071.244455 [0] dq.builtin:   7c PID 2 len 8 10,0,0,0,0,0,0,0
1657763071.244356 [0]     talker: match_writer_with_proxy_readers(wr 1103653:88f795fc:2f69ae8d:103) scanning all prds of topic ros_discovery_info
1657763071.244478 [0] dq.builtin:   88 PID 50 len 16 1,16,54,83,136,247,149,252,47,105,174,141,0,0,1,193
1657763071.244513 [0]     talker: match_writer_with_readers(wr 1103653:88f795fc:2f69ae8d:103) scanning all rds of topic ros_discovery_info
1657763071.244522 [0] dq.builtin:   9c PID 58 len 4 63,12,0,0
1657763071.244537 [0] dq.builtin:   a4 PID f len 4 0,0,0,0
1657763071.244540 [0]     talker: DDSI_PLIST_INIT (bswap 0)
1657763071.244560 [0] dq.builtin:   ac PID 31 len 24 1,0,0,0,68,128,0,0,0,0,0,0,0,0,0,0,0,0,0,0,10,31,133,54
1657763071.244564 [0]     talker:    0 PID 5 len 24 19,0,0,0,"ros_discovery_info",0,0
1657763071.244570 [0] dq.builtin:   c8 PID 32 len 24 1,0,0,0,68,128,0,0,0,0,0,0,0,0,0,0,0,0,0,0,10,31,133,54
1657763071.244571 [0]     talker:   1c PID 7 len 56 52,0,0,0,"rmw_dds_common::msg::dds_::ParticipantEntitiesInfo_",0
1657763071.244581 [0] dq.builtin:   e4 PID 8007 len 60 0,0,0,0,44,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,36,0,0,0,"non_working_hash/0.10.0/Linux/Linux",0
1657763071.244583 [0]     talker:   58 PID 1d len 4 1,0,0,0
1657763071.244589 [0] dq.builtin:  124 PID 8019 len 4 0,128,6,0
1657763071.244596 [0]     talker:   60 PID 15 len 4 2,1,0,0
1657763071.244603 [0] dq.builtin:  12c PID 1
1657763071.244610 [0]     talker:   68 PID 16 len 4 1,16,0,0
1657763071.244625 [0]     talker:   70 PID 5a len 16 1,16,54,83,136,247,149,252,47,105,174,141,0,0,1,3
1657763071.244649 [0] dq.builtin: data(builtin, vendor 1.16): 0:0:0:0 #1: ST0 /ParticipantBuiltinTopicData:{property_list={1:"__ProcessName":"talker",1:"__Pid":"2591",1:"__Hostname":"non_working_hash"}:{},protocol_version=2:1,vendorid=1:16,participant_lease_duration=10000000000,participant_guid={1103653:88f795fc:2f69ae8d:1c1},builtin_endpoint_set=3135,domain_id=0,default_unicast_locator={udp/10.31.133.54:32836},metatraffic_unicast_locator={udp/10.31.133.54:32836},adlink_participant_version_info=0:44:0:0:0:"non_working_hash/0.10.0/Linux/Linux",cyclone_receive_buffer_size=425984}
```

From the logic here https://github.com/eProsima/Fast-DDS/blob/5c563c612fad602e9ac48ea54dec63d0b1d29509/src/cpp/fastdds/core/policy/ParameterSerializer.hpp#L648-L671 I think Fast-RTPS ignores the binary properties sequence in the PropertyQoS.and only checks for the Property sequence. Which I think is the problem for not discovering the participants from 
Cyclone.

**Comment by MiguelCompany** [comment]
@eboasson @sumanth-nirmal Thank you for your thorough analysis.

I've just opened eProsima/Fast-DDS#2837, which should fix this.

**Comment by sumanth-nirmal** [comment]
The problem seems to be in FastDDS and is fixed as mentioned here https://github.com/eclipse-cyclonedds/cyclonedds/issues/1328#issuecomment-1184004440

I will close the issue as there are no issues with Cyclone in this contexyt
