### ISSUE TITLE
Idl recursive data structure

### ISSUE THREAD

**Issue by RomanKapl** [eclipse-cyclonedds/cyclonedds#1347]
Hi, 
I'm trying to generate c code for recursive data structure,

```
struct CompDef
{
 string Name;
 sequence<CompDef> Components;
};

struct Component
{
 string id;
 string SystemName;
 sequence<CompDef> SubComponents;
};
```

seems like it's not generated well, I saw a comment here https://github.com/eclipse-cyclonedds/cyclonedds/issues/131 which implies that it might not work. 

that the issue probably exists but it is quite old so is there any news regarding this topic? 
if not there is a plan to fix it?

Thanks in advance!

**Comment by eboasson** [comment]
Hi @RomanKapl, yes it is quite an old issue but a lot has changed since then. The IDL compiler got replaced, and where the old one couldn't handle recursive types at all, the new one actually can handle it just fine except for generating the "TypeObject" blob that describes the type in a standardised format and allows type checking between readers/writers, type evolution and introspection.

You can tell IDLC not to generate this type information using the `-t` option (of course you lose the things enabled by having it) and then it should work just fine, provided you also add the forward declaration of `struct Component` that the IDL specification requires:
```
struct Component;
struct CompDef
{
  string Name;
  sequence<Component> Components;
};

struct Component
{
  string id;
  string SystemName;
  sequence<Component> SubComponents;
};
```

This one remaining limitation will be lifted as well.

If you want, you could do everything in Python, because our python binding allows you to define the types in python [directly](https://github.com/eclipse-cyclonedds/cyclonedds-python/blob/dd662e38173b7898404a78afa8a586b8400300a6/examples/helloworld/helloworld.py#L25) (instead of in IDL) and then you can get everything today 🙂

**Comment by thijsmie** [comment]
Hi @RomanKapl,

You can use recursive types just fine nowadays, with one caveat: you cannot generate the XTypes typeinformation of recursive types since the algorithm is not implemented. If you do not care about assignibility checking with XTypes or other dynamic typing games in C you can compile your IDL by adding the `-t` flag to the IDL compiler:

```omg-idl
struct Component;

struct CompDef
{
  string Name;
  sequence<Component> Components;
};

struct Component
{
  string id;
  string SystemName;
  sequence<Component> SubComponents;
};
```
```bash
$ idlc -t recursive-type.idl
```

The Python binding does implement the algorithm for generating XTypes typeinformation of recursive types but it remains unverified against other implementations, so for now I only guarantee it is internally consistent :smile:

**Comment by eboasson** [comment]
> Ah! @eboasson beat me to it by a minute!

Haha, yes, we should coordinate better, I suppose. It is not even like there is any meaningful difference between the two answers! 😁

**Comment by RomanKapl** [comment]
Hi, 

I will start by thanking you for the really quick response :)
one of the reasons we porting to Cyclone DDS is the X-type specification compliance (specifically the ability to evolve types from version to version) after using opensplice community implementation for almost 2 years, we are using C implementation as a base for C# and C++ wrappers, I assume we can't give up TypeObject auto-generated code if we want to use x-type type evolving feature? (if I'm wrong to correct me I'm not fully familiar with internal implementation details)
if we can't you have some estimation of when you plan to fix it?

Thanks!!

**Comment by thijsmie** [comment]
You can still use the evolution features, there will just be no verification at runtime that the types are compatible according to the XTypes assignibility rules. If you don't do anything "crazy" with type evolution it "should just work", but you are on your own then, and if you make mistakes you run the risk of garbled data when one type is mistakenly interpreted as another. If that is a risk you're willing to take then nothing stands in your way :smile: 

Implementing the algorithm for recursive types for the TypeObject generation (the so-called strongly-connected-components in the XTypes spec) for C will be a while still, since it is not terribly high on our priority list. If you're up for a challenge we're always up for contributions, we have the [python implementation](https://github.com/eclipse-cyclonedds/cyclonedds-python/blob/master/cyclonedds/idl/_xt_builder.py) of this already and for the rest you just have to follow the spec and implement it in C :wink:. I don't think we'll have time to build it ourselves before Q1 2023.

**Comment by RomanKapl** [comment]
I'm up for the challenge or at least I will try :) but it will be around the end of this year.
there are specific things that we can't use after disabling the TypeObject blob code generation?

Thanks!

**Comment by thijsmie** [comment]
Everything is available with the disabled TypeObject blob generation, except from dynamically discovering and using the type from the network with Python (the python CLI tools `cyclonedds typeof` and `cyclonedds subscribe` will not work). While building a C application these limitations should not bother you.
