### ISSUE TITLE
[Question] Are multiple PublicationMatched/SubscriptionMatched Event condensed into one event?

### ISSUE THREAD

**Issue by Kischy** [eclipse-cyclonedds/cyclonedds#1357]
If an PublicationMatched/SubscriptionMatched Event is triggered the `current_count_change` is `1` or `-1`. What happens if multiple events happen at the same time? Would it be possible for the `current_count_change` to have a value of `0`, `2` or `-2`?

Or in other words: Are multiple PublicationMatched/SubscriptionMatched Event condensed into one event?

Thank you in advance!

**Comment by eboasson** [comment]
It depends on how you are monitoring them:
* If you poll or use a waitset, then you can get other values for `current_count_change`
* If you use a listener, then they may be condensed, but the current behaviour in Cyclone is to immediately invoke the listener when the event happens, and so in practice they won't be.

Immediately invoking the listener is a bit of a pain: it does give you guarantees, it also gives you the lowest possible latency, but there are rather few things you can safely do in a listener without risking a dead lock. (Not unlike Unix signal handlers, therefore.) Because of that it seems like it would be a good idea to change the default listener invocation strategy, queueing the events and calling the listeners on another thread. You don't want unbounded growth of that queue and so you then need to consolidate them if the events occur more often than the listeners can handle them.

The current behaviour should remain available, precisely because it offers something you can't otherwise get. So if you choose to depend on it, and the default invocation behaviour does change, you may need to change something in your code to keep the current behaviour.

**Comment by Kischy** [comment]
I am using a listener at the moment. But I do not think that I want to depend on the current behaviour if it ever changes.

Thank you for the detailed answer!
