### ISSUE TITLE
Segmentation fault (core dumped) error while building on aarch64 Jetson

### ISSUE THREAD

**Issue by automech-rb** [eclipse-cyclonedds/cyclonedds#1358]
Hi,

I am trying to build cyclonedds on Jetson docker, but leads to this error.

```
--- stderr: cyclonedds
Segmentation fault (core dumped)
make[2]: *** [src/tools/ddsperf/CMakeFiles/ddsperf_types_generate.dir/build.make:76: src/tools/ddsperf/ddsperf_types.c] Error 139
make[1]: *** [CMakeFiles/Makefile2:535: src/tools/ddsperf/CMakeFiles/ddsperf_types_generate.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
---
Failed   <<< cyclonedds [1min 46s, exited with code 2]
```

Here are my docker commands (versions correspond to currently being used in ROS2 Humble):
```
RUN apt-get update && mkdir -p ${ROS_ROOT}/src && cd ${ROS_ROOT}/src \
    && git clone -b 1.3.3 https://github.com/ros2/rmw_cyclonedds \
    && git clone -b v2.0.2 https://github.com/eclipse-iceoryx/iceoryx.git \
    && git clone -b 0.9.0 https://github.com/eclipse-cyclonedds/cyclonedds \
    && source ${ROS_ROOT}/setup.bash && cd ${ROS_ROOT} \
    && rosdep install -y -r --ignore-src --from-paths src --rosdistro ${ROS_DISTRO} \
    && colcon build --merge-install --cmake-args -DCMAKE_BUILD_TYPE=RelWithDebInfo \
    && rm -Rf src logs build \
&& rm -rf /var/lib/apt/lists/* \
&& apt-get clean
```

I am not sure where to go with this error.
Here is the docker file on which I am building: [Dockerfile](https://github.com/dusty-nv/jetson-containers/blob/master/Dockerfile.ros.humble)

**Comment by thijsmie** [comment]
Hi @automech-rb,

In the CycloneDDS build process building `ddsperf` is the only part where you need the IDL compiler to process the types it uses. I am not well versed in building with ROS or building for Jetson but I suspect this may be a cross-compilation? If so, it is most probable that the build process is trying to run your freshly built IDL compiler for Jetson on the host architecture and failing? You can remedy this by supplying a separately build `idlc` for the host architecture or turning of the `ddsperf` build if you don't need it, with `BUILD_DDSPERF=OFF`.

If this is not a cross-compilation issue then we'll need to figure out where the error happened. If you build with the address sanitizer and your ros build in verbose mode we should be seeing a trace of where the segfault happened.

**Comment by automech-rb** [comment]
Yeah. The problem was with cross-compiling. Thank you for your quick reply.
Closing the issue!

**Comment by Mr-Lv-BUU** [comment]
I have encountered the same problem. Is there a solution now?

**Comment by Mr-Lv-BUU** [comment]
``> I have encountered the same problem. Is there a solution now? ![Snipaste_2024-05-28_17-02-25](https://private-user-images.githubusercontent.com/77325065/334340923-95ed1f8b-7ca9-4fa0-8117-5d7c26bf7bec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4ODg0NjEsIm5iZiI6MTcxNjg4ODE2MSwicGF0aCI6Ii83NzMyNTA2NS8zMzQzNDA5MjMtOTVlZDFmOGItN2NhOS00ZmEwLTgxMTctNWQ3YzI2YmY3YmVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDA5MjI0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjOWUyNTA5ZGM4ZDNiOWY4ZGE2Mjc1YTA5ZmJhMGE5NjhlNWVhY2EyMjAyZDAwZmQ1MjNkM2RkNWQ5ZDVjNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._5-UrgLLvisxxczamMu-TM2kSLa5G5Oi3RTd-j3QMN8)

The problem is solved, set the LD_LIBRARY_PATH to none
`LD_LIBRARY_PATH=`
