### ISSUE TITLE
The rule of qos_merge is not conform to specifications

### ISSUE THREAD

**Issue by tooyoungtoosimpo** [eclipse-cyclonedds/cyclonedds#1365]
The rule of qos_merge in DDS1.4 is:
writer:
_The special value DATAWRITER_QOS_USE_TOPIC_QOS can be used to indicate that the DataWriter should be created
with a combination of the default DataWriter QoS and the Topic QoS. The use of this value is equivalent to the application
obtaining the default DataWriter QoS and the Topic QoS (by means of the operation Topic::get_qos) and then combining these
two QoS using the operation copy_from_topic_qos whereby any policy that is set on the Topic QoS “overrides” the
corresponding policy on the default QoS. The resulting QoS is then applied to the creation of the DataWriter._
reader:
_Provided that the TopicDescription passed to this method is a Topic or a ContentFilteredTopic, the special value
DATAREADER_QOS_USE_TOPIC_QOS can be used to indicate that the DataReader should be created with a combination
of the default DataReader QoS and the Topic QoS. (In the case of a ContentFilteredTopic, the Topic in question is the
ContentFilteredTopic’s “related Topic.”) The use of this value is equivalent to the application obtaining the default
DataReader QoS and the Topic QoS (by means of the operation Topic::get_qos) and then combining these two QoS using the
operation copy_from_topic_qos whereby any policy that is set on the Topic QoS “overrides” the corresponding policy on the
default QoS. The resulting QoS is then applied to the creation of the DataReader. It is an error to use
DATAREADER_QOS_USE_TOPIC_QOS when creating a DataReader with a MultiTopic; this method will return a ‘nil’
value in that case._

But the present code of cyclonedds will always merge topic_qos while creating writer and reader.
![reader](https://user-images.githubusercontent.com/103105551/184071868-89c03dac-bd7c-4e19-9d2b-63ed03427355.png)
![writer](https://user-images.githubusercontent.com/103105551/184071877-639f34b6-4e5b-4488-bcc5-29e8d932fc02.png)

Mean while, writer and reader do not need to merge the qos of publisher or subscriber. I can't find any rule in DDS1.4 .

**Comment by eboasson** [comment]
You're right that it is — or "appears", see below — different from the specification. That is deliberate: I have had to deal with the standard APIs for about a decade and almost without exception, people define topics with appropriate QoS settings and then want the readers and writers to use the same QoS (or perhaps override something like the history setting). A good API makes the common thing easy, and that's what we did.

The "appears" is there because the DDS specification document gives an interface in IDL that can be machine-translated to an interface in C, C++, Java, ... by following the IDL-to-C/C++/... mappings that the OMG also defined. The result is a very unpleasant API regardless of the language used. That statement in the specification concerns these particular APIs.

Later, the OMG specified a more modern C++ and Java API, and these are very different from the specification. You can still do everything, but you have to do it in different ways. The Cyclone C++ API is that standard, more modern C++ API.

No such improvement ever happened for the C API, so Cyclone simply has its own C API and that has its own details. I am well aware that the documentation does not properly cover all these details and I'm happy that you asked the question.

At some point we've considered whether we should do the standard C API as well, at least to the point that most applications written for it can run. It is just so much tedious work that we keep postponing the decision.

**Comment by tooyoungtoosimpo** [comment]
Now here is a problem:
While I use dds_create_reader (participant, topic, NULL, NULL); or dds_create_writer (participant, topic, NULL, NULL);
Then I use dds_get_qos from writer and dds_qget_reliability, the return value is true.
But if I use  dds_create_topic (participant, &HelloWorldData_Msg_desc, "HelloWorldData_Msg", NULL, NULL);
Then I use dds_get_qos from topic and dds_qget_reliability, the return value is false.

**Comment by eboasson** [comment]
It took quite a bit of effort to get those results 😀 but those are the default QoS settings for topics, readers and writers and somehow it seemed best to follow those when not specifying *any* QoS setting whatsoever. In hindsight, I've doubted that decision many times, because the defaults are so strange ...

The Cyclone (C API) QoS's objects track which QoS's have been set and which have been left unset. When it inherits, it only inherits the QoS's that actually have been set and it only applies the defaults when it really has to. For the topic, that means when you call `get_qos` or when it has to publish a `DCPSTopic` sample; for the reader and writer, it really needs all the QoS's and so it merges the defaults at creation time.

That way, it can handle the (insane) defaults of the DDS spec, where if you specify no QoS settings anywhere, you get an unreliable topic and reader, but a reliable writer.

You should see the reader *and* writer match the topic QoS if you set the reliability on the topic.

**Comment by eboasson** [comment]
It's been so long since I answered that I suppose my answer was satisfactory. Or perhaps it was too confusing, I know that sometimes happens ...
