### ISSUE TITLE
Idl types supported by cylocne DDS. Does it support Map and some unbounded data types?

### ISSUE THREAD

**Issue by shizhuang-li** [eclipse-cyclonedds/cyclonedds#1371]
Hello everyone,I have investigated various DDS such as cylone DDS, Fast DDS and RTI DDS, and I prefer Cyclone DDS which has better performance and lower CPU usage. But I am not very clear what data types Cyclone DDS IDL supports, such as map, unbounded data types (such as vector) that I am interested in.
But I can easily see from the documentation of Fast DSS and RTI DDS what IDL types they support, so you can improve some documentation on this, the latter provides some demos that contain all the idl data types that Cyclone DDS can support to help Users can better understand the data types supported by Cyclone DDS.
![Wzsd5j1coO](https://user-images.githubusercontent.com/107856361/184825000-ef6794b7-c77c-4e8e-911f-8a51db88ee05.png)
![n85hDTQupN](https://user-images.githubusercontent.com/107856361/184825053-148b802c-9f06-469c-ab52-9fcde1ac4233.png)
Fast DDS IDL support types
![vZVESYzXee](https://user-images.githubusercontent.com/107856361/184825243-7d04094e-bc78-4076-91ce-1a53c3ae11da.png)
RTI DDS IDL support types

Best regards
Shizhuang.li

**Comment by eboasson** [comment]
Hi @shizhuang-li, thank you for your kind words!

Cyclone simply follows the IDL mappings, with exceptions documented [here](https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/docs/dev/xtypes_relnotes.md), which was referenced by the release notes but otherwise quite well hidden.

A brief summary of the supported types and their mapping to C/C++ is:
* booleans (`bool`)
* char (`char`), octet (`uint8_t`)
* (`unsigned`) `short`, `long`, `long long` (`int16_t` ... `int64_t`, `uint16_t` ... `uint64_t`)
* `int8` ... `int64`, `uint8` ... `uint64` (`int8_t` ... `int64_t`, `uint8_t` ... `uint64_t`)
* 32- and 64-bit floating point (`float`, `double`)
* bitmasks (mapped to 8, 16, 32 or 64 bit integers depending on positions used and/or `@bit_bound`)
* enums (currently always mapped to 32-bit integers, but see #1359)
* unbounded strings (C: `char *` in C; C++: `std::string` or a user-specified type)
* bounded strings (C: char array; C++: `std::string` or a user-specified type)
* arrays (C: array; C++: `std::array<T>` or a user-specified type)
* bounded and unbounded sequences (C: `struct { length, maximum, release, T *buffer }`; C++: `std::vector<T>` or a user-specified type)
* structs
* unions (C: `struct { discriminant; union { ... } }`; C++: `std::variant` or a user-specified type)

Not implemented yet are:
* map, bitset, wide-strings, char16, float128

There is nothing fundamentally difficult in supporting these, we just haven't gotten around to doing it, based on our perception of the added value they bring. Since you specifically also mentioned the `map` type, the reason we considered it of low added value is because at application level you really want control of the type of map (hash maps, ordered maps, implemented this way or the other) and then on the wire you'd want to use some of that knowledge as well, for faster reconstruction. But as it is, `map<K,T,BOUND>` gets serialized as `sequence<struct{K,T},BOUND>`, without any guarantees on ordering ...

Notes:
* this is all following the usual OMG standards
* the user-specified types in C++ are specified using options to IDLC

**Comment by shizhuang-li** [comment]
Thank you so much @eboasson, Your answer helped me solve a lot of confusion, and I saw your latest example - dynsub. The idl in this example is set like this：
```
struct T {
  short s;
  long l;
};

struct B {
  sequence<T> ts;
};
```
I think this approach can replace some of my need for map data type.Thank you again

Best regards
Shizhuang.li

**Comment by thijsmie** [comment]
Note that now there is also this: https://cyclonedds.io/content/guides/supported-idl.html
