### ISSUE TITLE
Enum type as constants in idl

### ISSUE THREAD

**Issue by mw-senthil** [eclipse-cyclonedds/cyclonedds#1391]
Hello there
I see the following supported in all other idl compilers. Just wondering why idlc is complaining

`module module1

{

   enum mod1_enum_val

   {
      
      value1,
      
      value2
   };  //mod1_enum_val

}; //module1

const module1::mod1_enum_val myConst1 = module1::mod1_enum_val::value1;

const module1::mod1_enum_val myConst2 = module1::mod1_enum_val::value2;
`

@eboasson

**Comment by mw-senthil** [comment]
`
const int32 MAX_COLOR_LEN = 128;
module CycloneNS
{
   struct MyLineType
   {
      int32 length;
   }; //MyLineType
   enum IgnitionModes
   {
      KEYOFF, //0
      CRANK,
      KEYON,
      RUN //255
}; //IgnitionModes
}; //CycloneNS
typedef CycloneNS::MyLineType NSMyLineTypeDef;
typedef CycloneNS::MyLineType NSMyLineTypeArr[5];
struct ShapeType
{
   @key string color;
   int32 x;
   int32 y;
   int32 shapesize;
   CycloneNS::IgnitionModes mode;
   CycloneNS::MyLineType line;
   NSMyLineTypeDef lineseq;
   NSMyLineTypeArr linearr;
}; //ShapeType
`

Another test case
This type the error is confusing:
ShapeExample.idl:2:1: Declaration 'CycloneNS' collides with earlier an declaration of 'CycloneNS'

**Comment by eboasson** [comment]
@mw-senthil yes, that error message is confusing indeed. Given that it reports an error on valid input, perhaps it is only for the better that the message is inscrutable. (Just kidding!)

I think this is a minimal reproducer, the error is triggered by the `typedef`:
```
module X {
  struct Y { long a; };
};
typedef X::Y Z;
```

Regarding the enum constant: the problem is the same.

**Comment by eboasson** [comment]
This: `ShapeExample.idl:2:1: Declaration 'CycloneNS' collides with earlier an declaration of 'CycloneNS'` is fixed now on master.

About the enum, I spoke a bit too soon:
```
module module1 {
   enum mod1_enum_val { value1, value2 };
};
const module1::mod1_enum_val myConst1 = module1::mod1_enum_val::value1;
const module1::mod1_enum_val myConst2 = module1::mod1_enum_val::value2;
```
this is still rejected, but that's because in IDL an enum doesn't form a scope in itself, the symbols are defined in the enclosing scope (like in C, or C++ if you don't do `enum class`). From IDL 7.5.2 "Scoping Rules and Name Resolution":

> The following kinds of definitions form scopes: modules, structures, unions, maps, interfaces, value types, operations, exceptions, event types, components, homes. Scope applies as follows:
[...]
> Enumeration value names are introduced into the enclosing scope and then are treated like any other declaration in that scope. For example:
> ```
> interface A {
>   enum E { E1, E2, E3 }; // line 1
>   enum BadE { E3, E4, E5 }; // Error: E3 is already introduced into the A scope in line 1 above
> };
> interface C {
>   enum AnotherE { E1, E2, E3 };
> };
> interface D : C, A {
>   union U switch (E) {
>     case A::E1 : boolean b; // OK.
>     case E2 : long l; // Error: E2 is ambiguous (notwithstanding the switch type specification)
> }; };

So it seems to me that Cyclone's IDL compiler is correct here.
