### ISSUE TITLE
Can cyclonedds and Fast-RTPS communicate with each other?

### ISSUE THREAD

**Issue by Zhang8912** [eclipse-cyclonedds/cyclonedds#1394]
Hi All,

I have a noob question again. 
Is it possible that CycloneDDS can communicate with FastDDS **right now**？

I saw [eboasson](https://github.com/eboasson) answered "NO" by Issue1020, which was published in **2021.**
https://github.com/eclipse-cyclonedds/cyclonedds/issues/1020

Thanks all

**Comment by eboasson** [comment]
As I wrote on #1020, it gets tested every night in the ROS 2 CI, and it works fine. The error mentioned in #1020:

> I try run cyclonedds.HelloworldSubscriber and fastdds.DDSDynamicHelloWorldExample publisher
> But I receive the following：
> dq.builtin: data(builtin, vendor 1.15): 10fefa5:5ab08909:1000000:3c2 https://github.com/eclipse-cyclonedds/cyclonedds/issues/1: deserialization failed

has an unknown (to me) cause, because no-one ever provided the requested trace/capture ...

**Comment by Zhang8912** [comment]
> As I wrote on #1020, it gets tested every night in the ROS 2 CI, and it works fine. The error mentioned in #1020:
> 
> > I try run cyclonedds.HelloworldSubscriber and fastdds.DDSDynamicHelloWorldExample publisher
> > But I receive the following：
> > dq.builtin: data(builtin, vendor 1.15): 10fefa5:5ab08909:1000000:3c2 #1: deserialization failed
> 
> has an unknown (to me) cause, because no-one ever provided the requested trace/capture ...

Hi [eboasson](https://github.com/eboasson), thanks for reply.

PC1 using IP 172.31.10.100 for cyclonedds/examples/helloworld/publisher.c 
PC2 using IP 172.31.10.120 for app/fastdds/src/fastrtps/examples/cpp/dds/HelloWorldExample/build/ $./DDSHelloWorldExample subscriber

By side of cyclonedds, I changed:
1. DomainID: 0x00000000u
2. TopicName: "HelloWorldTopic"
3. typeName: "HelloWorld"

I think that there is something wrong with Endpoint Discovery, because Topic is not matched.
But I do not know, how to change it. Do you have any advices?

![image](https://user-images.githubusercontent.com/103993997/187687596-706c6b78-9f74-47fc-9aa4-310d2dbcb72d.png)
[cdds.log](https://github.com/eclipse-cyclonedds/cyclonedds/files/9461815/cdds.log)

**Comment by eboasson** [comment]
Hi @Zhang8912, sorry it took me so long to come back to you, it is been a bit crazy here ...

If you look it in your `cdds.log`, this is the Cyclone writer being created:
```
1661949914.960451 [0] Helloworld: WRITER 110f1e4:29a74e7c:bcd97299:202 QOS={user_data=0<>,topic_name="HelloWorldTopic",type_name="HelloWorldData::Msg",topic_data=0<>,group_data=0<>,durability=0,durability_service=0:0:1:-1:-1:-1,deadline=9223372036854775807,latency_budget=0,liveliness=0:9223372036854775807,reliability=1:100000000,lifespan=9223372036854775807,destination_order=0,history=0:1,resource_limits=-1:-1:-1,ownership=0,ownership_strength=0,presentation=0:0:0,partition={},transport_priority=0,data_representation=2(0,2),adlink_entity_factory=1,adlink_writer_data_lifecycle=1}
1661949914.960484 [0] Helloworld: write_sample 110f1e4:29a74e7c:bcd97299:3c2 #1: ST0 DCPSPublication/PublicationBuiltinTopicData:{topic_name="HelloWorldTopic",type_name="HelloWorldData::Msg",data_representation=2(0,2),type_information=[MINIMAL 6e42149eb141a0d72594c650d73c]/[COMPLETE b1a3b1fb8b1a60516014297c3b8a],protocol_version=2:1,vendorid=1:16,endpoint_guid={110f1e4:29a74e7c:bcd97299:202},adlink_entity_factory=1}
```
and a bit later you have the message from FastDDS for their reader:
```
1661949915.966743 [0] dq.builtin: data(builtin, vendor 1.15): 10fc641:980a531f:1000000:4c2 #1: ST0 DCPSSubscription/SubscriptionBuiltinTopicData:{user_data=0<>,topic_name="HelloWorldTopic",type_name="HelloWorld",topic_data=0<>,group_data=0<>,durability=0,durability_service=0:0:1:-1:-1:-1,deadline=9223372036854775807,latency_budget=0,liveliness=0:9223372036854775807,reliability=1:100000000,lifespan=9223372036854775807,destination_order=0,ownership=0,presentation=0:0:0,partition={},type_consistency_enforcement=1:11000,protocol_version=2:2,vendorid=1:15,expects_inline_qos=0,participant_guid={10fc641:980a531f:1000000:1c1},keyhash={010fc641:980a531f:01000000:00000104},endpoint_guid={10fc641:980a531f:1000000:104},unicast_locator={udp/172.31.10.120:7413}}
1661949915.966948 [0] dq.builtin: SEDP ST0 10fc641:980a531f:1000000:104 reliable volatile reader unnamed: (default).HelloWorldTopic/HelloWorld p(open) NEW (as udp/172.31.10.120:7413@2 ssm=0) QOS={user_data=0<>,topic_name="HelloWorldTopic",type_name="HelloWorld",topic_data=0<>,group_data=0<>,durability=0,durability_service=0:0:1:-1:-1:-1,deadline=9223372036854775807,latency_budget=0,liveliness=0:9223372036854775807,reliability=1:100000000,lifespan=9223372036854775807,destination_order=0,history=0:1,resource_limits=-1:-1:-1,ownership=0,presentation=0:0:0,partition={},time_based_filter=0,transport_priority=0,type_consistency_enforcement=1:11000,data_representation=1(0),adlink_reader_lifespan=0:9223372036854775807,adlink_reader_data_lifecycle=9223372036854775807:9223372036854775807,adlink_subscription_keys=0:{}}
```
You're not expected to find it easy to make sense of this 🙂 (but you can [some info](https://cyclonedds.io/content/guides/tracefile.html) on it at least).

The two programs use different type names, and because the FastDDS one doesn't provide type identifiers (presumably they simply don't support XTypes) the type names must match.

By accident (I guess) the types are similar enough that they could communicate, but there is no agreement on the examples between DDS implementations, and so that is pure coincidence. The FastDDS one uses an unsigned int where the Cyclone uses an int, but if you're willing to take risks, they would indeed be able to deserialise each other's data. But even having the same topic name, type name and (probably) mostly compatible QoS's is not enough. If one has key fields and the other doesn't it still won't work. That is the case here ...

I like it that you're trying to do this, but rather than starting with two examples that never were meant to be used together, I think it would be wiser to start with something that is meant to work, and then play around a bit. It is not great, but as far as I know, you should be able to get to something that works much easier with https://github.com/eboasson/i11eperf than with the examples.

**Comment by Zhang8912** [comment]
Hi @eboasson ,
thank you for reply. Amazing! With your scripts CycloneDDS (apub) could connect with FastDDS(fsub) and OpenDDS(osub) by **local**(2 local Linux Terminals by **one PC**). However, they could not connect with each other when I **use 2 Linux PC.**

I did the following Steps for 2 PC Testing.
0. both PC tested your scripts by local(good)
1. Cyclone DDS ./HelloworldPublisher by **first PC IP:172.168.120.50**
2. Cyclone DDS ./HelloworldSubscriber by **second PC IP:172.168.120.30**
3. Cyclone DDS Helloworld works good. (wire and Hardware should be ok)
4. Your script ./apub by **first PC IP:172.168.120.50**
5. Your script ./asub by **second PC IP:172.168.120.30**
6. There is no log on Linux Terminal.
7. I checked Wireshark and found that there is a warning with PID_DOMAIN_ID. (which should be zero?)

In attachment, you can find .zip file from wireshark and asub.log.
Thanks for your help. 

![apub130](https://user-images.githubusercontent.com/103993997/189048839-09daea01-d507-4cc8-a118-969e7052f3fd.PNG)
![apub1302](https://user-images.githubusercontent.com/103993997/189048848-78bbf44a-eddf-488d-b81c-3e436fa84f0b.PNG)

[apub_asub_cannotfound_2PC.zip](https://github.com/eclipse-cyclonedds/cyclonedds/files/9524023/apub_asub_cannotfound_2PC.zip)
[asub.log](https://github.com/eclipse-cyclonedds/cyclonedds/files/9524024/asub.log)

**Comment by eboasson** [comment]
Hi @Zhang8912, this a new one ... you can see some data (the `DATA(m)` ones) going back and forth, along with the corresponding `HEARTBEAT`s and `ACKNACK`s. That proves you have bi-directional, reliable communication. I have no idea just yet why that is all.

The only reason there is no more in the capture that I can think of so far is that the first packet, i.e.:
```
No.	Time	Source	SPort	Destination	DPort	Protocol	Length	Info
1	0.000000000	172.168.120.30	50434	172.168.120.50	47978	RTPS	158	INFO_TS, DATA(m), HEARTBEAT

Frame 1: 158 bytes on wire (1264 bits), 158 bytes captured (1264 bits) on interface ens33, id 0
Ethernet II, Src: VMware_3d:9c:b1 (00:50:56:3d:9c:b1), Dst: HewlettP_19:38:1a (d8:d3:85:19:38:1a)
Internet Protocol Version 4, Src: 172.168.120.30, Dst: 172.168.120.50
User Datagram Protocol, Src Port: 50434, Dst Port: 47978
Real-Time Publish-Subscribe Wire Protocol
    Magic: RTPS
    Protocol version: 2.1
    vendorId: 01.16 (Eclipse Foundation - Cyclone DDS)
    guidPrefix: 0110f2310f730a4eaed69bad
    Default port mapping: domainId=162, participantIdx=34, nature=UNICAST_METATRAFFIC
    submessageId: INFO_TS (0x09)
        Flags: 0x01, Endianness bit
        octetsToNextHeader: 8
        Timestamp: Sep  8, 2022 03:43:00.589648851 UTC
    submessageId: DATA (0x15)
        Flags: 0x05, Data present, Endianness bit
        octetsToNextHeader: 48
        0000 0000 0000 0000 = Extra flags: 0x0000
        Octets to inline QoS: 16
        readerEntityId: ENTITYID_UNKNOWN (0x00000000)
        writerEntityId: ENTITYID_P2P_BUILTIN_PARTICIPANT_MESSAGE_WRITER (0x000200c2)
        writerSeqNumber: 2
        ParticipantMessageData
    submessageId: HEARTBEAT (0x07)
        Flags: 0x01, Endianness bit
        octetsToNextHeader: 28
        readerEntityId: ENTITYID_UNKNOWN (0x00000000)
        writerEntityId: ENTITYID_P2P_BUILTIN_PARTICIPANT_MESSAGE_WRITER (0x000200c2)
        firstAvailableSeqNumber: 2
        lastSeqNumber: 2
        count: 3
```
is the second `DATA(m)` message, and they get sent at about one every 8s. This suggests the capture is missing up to 8s of traffic after initial discovery. Given that this particular data gets sent/acknowledged as expected, I expect the reader/writer discovery also succeeded, but that it simply hasn't been capture because that (usually) happens within the first few milliseconds after the nodes discover each other.

The Cyclone traces could help with that, just crank the verbosity up to "finest" 🙂 (probably best done on both sides just to be sure).

> I checked Wireshark and found that there is a warning with PID_DOMAIN_ID. (which should be zero?)

The DDSI spec version whatever (2.4 or so) and 0 would be the typical default domain id. I suspect your wireshark is a bit old because mine doesn't complain.

**Comment by thijsmie** [comment]
No more feedback was given, I'm assuming the problem was resolved.
