### ISSUE TITLE
idlc crash when process nested idl

### ISSUE THREAD

**Issue by skysky97** [eclipse-cyclonedds/cyclonedds#1399]
version: master

reproduce:

1. dir layout: `origin_sub` symlink to `origin/sub` directory.

```
<path>
  |-- origin
  |    |-- sub
  |        |-- type.idl
  |        |-- nest.idl
  | -- origin_sub -> origin/sub
```

2. type.idl

```
#include "nest.idl"
```

3. nest.idl : keep empty

4. generate code

```sh
cd origin_sub
idlc /home/user/<path>/origin_sub/type.idl  # fine
idlc type.idl   # fine
idlc /home/user/<path>/origin/sub/type.idl   # segmentation fault
```

I'm using `idlc_generate(TARGET type FILES type.idl)` in cmake. It always runs like the 3th case.

**Comment by eboasson** [comment]
I'm sure there is a problem here, but I am so far not succeeding at reproducing it on current master — neither on macOS nor on Linux. I am pretty sure I am following your procedure almost to the letter (changes in the path to idlc, and on macOS there's no /home/user, that but otherwise it is copy-paste).

There's https://github.com/eclipse-cyclonedds/cyclonedds/pull/1271 which at first sight seems to address a related problem. (It seems I have fallen behind by quite a bit and I think that one slipped through the cracks altogether  ... but I'm trying to catch up ...)

Anyway, I'm convinced there's a problem that somehow doesn't happen for me or there was one and it got fixed accidentally and quite recently at that. Would you be willing to retest it to be sure it is still around? And if it still fails, perhaps you could capture a stack trace in gdb so I least have some idea where to look.

Thanks!

**Comment by skysky97** [comment]
Tested again and problem not exist. Close this issue.
