### ISSUE TITLE
Communication between Cyclone and ROS2

### ISSUE THREAD

**Issue by ManuMTS** [eclipse-cyclonedds/cyclonedds#1412]
I would like to use CycloneDDS on a device without a ROS2-Installation to send and recieve messages with a device with ROS2 installed. I have tried to use the Hello World Examples and modify them to communicate with ROS2 but didn't succeed yet. Has someone of the devs done vanilla-CycloneDDS to ROS2 Communication yet and could help me out?

What i have done so far:
- Set ROS2 DDS-Implementation to Cyclone
- Played around with the Hello World Examples
- Set the same domain and topic name as ROS2.
- Played around with the idl File to match the ROS2 Message
- Checked with Wireshark that my non-ROS2-device recieves the multicast from ROS2

Sadly the HelloworldSubscriber never detects any Messages from ROS2.
I ran CycloneDDS on an Ubuntu22.04 VM and the ROS2 on another Ubuntu22.04 VM both being in the same network and connected by a virtual Hyper-V Switch.

**Comment by eboasson** [comment]
> Has someone of the devs done vanilla-CycloneDDS to ROS2 Communication yet

Yes 🙂

> and could help me out?

Hopefully 🙂

Before I start typing a lot: [this](https://github.com/ros2/rmw_cyclonedds/issues/319) was an issue created by someone else trying to do something very similar, and at least for me the bit I wrote there solved the problem. Would you be willing to have a look at that first?

**Comment by ManuMTS** [comment]
Hello eboasson,
first of all thanks for the reply. Sure i will look into the other issue first.

**Comment by ManuMTS** [comment]
The Issue you forwarded me helped me out a bit. Now here is where i'm struggling again:

1. I used the String.idl from [rticommunity/ros-data-types Github](https://github.com/rticommunity/ros-data-types/tree/master/std_msgs/msg) and build a String.c and String.h to use with the HelloWorld Example. This should be the same data type as the ROS2 cpp_pubsub talker example.
```
#ifndef __std_msgs__msg__String__idl 
#define __std_msgs__msg__String__idl 
 
module std_msgs { module msg { 
 
struct String { 
    string data; 
}; 
 
}; };  // module msg::std_msgs 
 
#endif  // __std_msgs__msg__String__idl 
```
2. When running the ROS2 cpp_pubsub talker from the tutorial examples it broadcasts the **rt/topic** topic and also notices the HelloWorldSubscriber listening but complains about the wrong QoS-Policy being used. `ros2 run cpp_pubsub talker` [WARN] [1663680887.072125987] [minimal_publisher]: New subscription discovered on topic '/topic', requesting incompatible QoS. No messages will be sent to it. Last incompatible policy: INVALID_QOS_POLICY
3. I used the ddsls.py tool to display the ROS2 topic:
```{
            "key": "0110af35-2e91-8d27-c94e-de1700001503",
            "participant_key": "0110af35-2e91-8d27-c94e-de17000001c1",
            "topic_name": "rt/topic",
            "type_name": "std_msgs::msg::dds_::String_",
            "qos": {
                "DataRepresentation": {
                    "use_cdrv0_representation": true,
                    "use_xcdrv2_representation": false
                },
                "Deadline": {
                    "deadline": 9223372036854775807
                },
                "DestinationOrder": {
                    "kind": "ByReceptionTimestamp"
                },
                "Durability": {
                    "kind": "Volatile"
                },
                "DurabilityService": {
                    "cleanup_delay": 0,
                    "history": {
                        "depth": 1
                    },
                    "max_samples": -1,
                    "max_instances": -1,
                    "max_samples_per_instance": -1
                },
                "History": {
                    "kind": "KeepLast",
                    "depth": 10
                },
                "IgnoreLocal": {
                    "kind": "Nothing"
                },
                "LatencyBudget": {
                    "budget": 0
                },
                "Lifespan": {
                    "lifespan": 9223372036854775807
                },
                "Liveliness": {
                    "kind": "Automatic",
                    "lease_duration": 9223372036854775807
                },
                "Ownership": {
                    "kind": "Shared"
                },
                "OwnershipStrength": {
                    "strength": 0
                },
                "PresentationAccessScope": {
                    "kind": "Instance",
                    "coherent_access": false,
                    "ordered_access": false
                },
                "Reliability": {
                    "kind": "Reliable",
                    "max_blocking_time": 9223372036854775807
                },
                "ResourceLimits": {
                    "max_samples": -1,
                    "max_instances": -1,
                    "max_samples_per_instance": -1
                },
                "TransportPriority": {
                    "priority": 0
                },
                "WriterDataLifecycle": {
                    "autodispose": false
                }
            }
```
I think I'm close to getting the QoS Settings right in the HelloWorldSubscriber but I don't understand how to configure the QoS Data Representation according to the shown value of the ddsls.py tool.
```
// qos pointer
dds_qos_t* my_qos = dds_create_qos ();

// Data Representation

// Deadline
dds_qset_deadline(my_qos, DDS_INFINITY);

// Destination Order
dds_qset_destination_order(my_qos, DDS_DESTINATIONORDER_BY_RECEPTION_TIMESTAMP);
 
// Durability
dds_qset_durability(my_qos, DDS_DURABILITY_VOLATILE);

// Durability Service
dds_qset_durability_service(my_qos, (dds_duration_t)0, DDS_HISTORY_KEEP_LAST, (int32_t)1, (int32_t)-1, (int32_t)-1, (int32_t)-1);

// History
dds_qset_history(my_qos, DDS_HISTORY_KEEP_LAST, (int32_t)10);

// Ignore Local
dds_qset_ignorelocal(my_qos, DDS_IGNORELOCAL_NONE);

// Latency Budget
dds_qset_latency_budget(my_qos, (dds_duration_t)0);

// Lifespan
dds_qset_lifespan(my_qos, DDS_INFINITY);

// Liveliness
dds_qset_liveliness(my_qos, DDS_LIVELINESS_AUTOMATIC, DDS_INFINITY);

// Ownership
dds_qset_ownership(my_qos, DDS_OWNERSHIP_SHARED);

// Ownership Strength
// dds_qset_ownership_strength(my_qos, (int32_t)0);

// Presentation Access Scope
dds_qset_presentation(my_qos, DDS_PRESENTATION_INSTANCE, false, false);

// Reliability
dds_qset_reliability (my_qos, DDS_RELIABILITY_RELIABLE, DDS_INFINITY);

// Ressource Limits
dds_qset_resource_limits(my_qos, (int32_t)-1, (int32_t)-1, (int32_t)-1);

// Transport Priority
dds_qset_transport_priority(my_qos, (int32_t)0);

// Writer Data Lifecycle
dds_qset_writer_data_lifecycle(my_qos, false);
```


Am I on the right track so far and could you help me out with the QoS-configuration?

**Comment by eboasson** [comment]
Hi @ManuMTS, you are on the right track, but I think you are being bitten by a non-obvious complication.

The problem that I suspect is an incompatibility between the encoding used by the Cyclone RMW layer and the one used by your subscriber. In https://github.com/neil-rti/ros-data-types/blob/master/std_msgs/msg/String.idl, the ROS message is mapped to:
```C++
module std_msgs { module msg { module dds_ {
@appendable struct String_ {
  string data;
};
}; }; };
```
The `@appendable` here is an XTypes thing and indeed relates to the "data representation". Before XTypes, you had straightforward data types with a straightforward serialisation format called CDR (all defined in '90s for CORBA). With XTypes, DDS gained a more flexible type system, and consequently also more complex serialisation formats (XCDR1 and XCDR2). The "data representation" is about which of these serialisation formats are supported by a reader or writer. Because of bugs in the specification, XCDR1 has been abandoned and so we now essentially have CDR and XCDR2.

And here we run into the problem ... `@appendable` can only be represented in XCDR2 and so that is what the subscriber requires. The (Cyclone) RMW layer limits itself to the old model (it's simpler and supports everything that ROS 2 offers, so why not?) This means the ROS 2 writer does not advertise any detailed type information, and the encoding then by definition becomes the simple CDR encoding. In other words: mismatch ...

If all this is correct, then changing the IDL to use `@final` instead of `@appendable` will solve the issue.

On a side note: I know people are debating type evolution in ROS 2, which really amounts to do something similar to XTypes (one wonders if it would not make more sense for ROS 2 to just standardize on DDS, at least for any "advanced" features ...). I suspect this means we'll one day change the Cyclone RMW layer from a "dynamic" one to a "static" one, generating IDL from the ROS 2 message type descriptions and using our IDL compiler. That way we get a smaller RMW layer with more features.

(And in case you are wondering why we didn't go that way in the first place: when I did the original implementation of the RMW layer, I didn't know anything about ROS 2 — its build system, type system, type representation, &c., so I derived the Cyclone one from the Fast-RTPS one and chose the simplest one 🙂)

**Comment by ManuMTS** [comment]
Hi eboasson,
you were totally right. When changing `@appendable` to `@final`, the Cyclone HelloworldSubscriber could read messages from the ROS2 cpp_pubsub talker. Vice versa the ROS2 cpp_pubsub listener was able to recieve messages from the Cyclone HelloworldPublisher.

Thank you for the thorough explanation of the CDR and XCDR2 Situation aswell.

**Comment by ljaniec** [comment]
Can you provide a minimal working example with some README.md in your GitHub / ROS documentation? I think this will be worth reading for future ROS developers

**Comment by gavanderhoorn** [comment]
Having this documented on `docs.ros.org` as a tutorial/guide would be phenomenal.

This topic comes up quite often, and the best answer thus far has always been: "yeah, people are doing this / have done this, there should be some comments / issues here and there".

**Comment by eboasson** [comment]
I think it would be a good idea, I should be able to quickly do a tutorial with a pair of plain DDS programs (ideally both done in C and in C++) that interoperates with talker/listener.

That said, I am perennially running into trouble because I say yes to too many useful or interesting little projects ... so either it happens really quickly or you should assume it got derailed somewhere. At which point, you're of course welcome to ping me 🙂

**Comment by gavanderhoorn** [comment]
To give you a head start:

 - [ros2_documentation](https://github.com/ros2/ros2_documentation/)
 - setup instructions [to build and host it locally](https://docs.ros.org/en/rolling/The-ROS2-Project/Contributing/Contributing-To-ROS-2-Documentation.html#building-the-site-locally) -- it really is rather convenient with the `venv` and everything
 - should probably contribute to the `rolling` branch (it will be backported if/when appropriate)
 - I would suggest to add the tutorial under the [Advanced](http://docs.ros.org/en/rolling/Tutorials/Advanced.html) category ([source](https://github.com/ros2/ros2_documentation/tree/rolling/source/Tutorials/Advanced))

**Comment by nargetdev** [comment]
Ok so i was running into this same thing regarding QoS "mismatch"  with log from my `ros2 topic pub ...` invocation.  (see log of QoS failure below)

I had tried to define and compile a custom type via `CameraControls.msg`

however when i just use an existing std message type my vanilla `cyclonedds-python` is able to receive and send messages... i.e. sent from

;;; working
`ros2 topic pub /camera_0_lens_position std_msgs/msg/Float32 "data: 1.0"`
works fine

reference code:
[https://github.com/nargetdev/pi-camera-in-docker/blob/main/pi_camera_in_docker/main.py](https://github.com/nargetdev/pi-camera-in-docker/blob/main/pi_camera_in_docker/main.py)

;;;broken
`ros2 topic pub /picamera/controls picamera_msg/msg/CameraControls "exposure_time: 1500, analogue_gain: 0.0, lens_position: 20.0, af_mode: 0, ae_enable: 0, awb_enable: 0, brightness: 0.0, contrast: 0.0, saturation: 0.0, sharpness: 0.0"`

`[WARN] [1761070824.173657294] [rmw_cyclonedds_cpp]: Failed to parse type hash for topic 'rt/picamera/controls' with type 'picamera_msg::msg::dds_::CameraControls_' from USER_DATA '(null)'.
[WARN] [1761070824.177116995] [_ros2cli_3212]: New subscription discovered on topic '/picamera/controls', requesting incompatible QoS. No messages will be sent to it. Last incompatible policy: INVALID
publishing #492: picamera_msg.msg.CameraControls(exposure_time=1500, analogue_gain=0.0, lens_position=20.0, af_mode=0, ae_enable=0, awb_enable=0, brightness=0.0, contrast=0.0, saturation=0.0, sharpness=0.0)
`
