### ISSUE TITLE
Questions about Throughput Example

### ISSUE THREAD

**Issue by rsayyidinaa** [eclipse-cyclonedds/cyclonedds#1427]
Hi, 
I'm new to CycloneDDS. 

I want to test the Throughput example by adding more subscribers, publishers, and modify the QoS. But I don't know where to begin. Could you help me with this? Thanks!

**Comment by thijsmie** [comment]
Hi @rsayyidinaa,

It's good to hear you are interested in Cyclone DDS! Fiddling with the examples is a good step to try to get to know the API and behaviours, but you can also check [our website cyclonedds.io](https://cyclonedds.io) for documentation and guides. You can also pop into our Discord (link in the README) to talk with us.

I hope that will help! I'm closing this ticket now since I cannot give a very detailed answer on this broad question, but feel free to open another ticket (or ask on Discord) if you have a problem or question with a specific topic.
