### ISSUE TITLE
Transferring messages from Cyclone DDS to ROS2

### ISSUE THREAD

**Issue by th3g3ntl3m3m** [eclipse-cyclonedds/cyclonedds#143]
This topic has already been touched on a bit, but still there are some incomprehensible moments for me.
I have an application using Cyclone DDS and I want to send a message to another computer with OS Linux and a ROS2 system using OpenSplice DDS.
I tried to do it, but it didn't work out for me.
What was done:
1) created idl messages
2) compiled via the utility that comes with the bundle got * .c and * .h files
3) added this all to the project, compiled it in the framework of one PC and also within the framework of Cyclone DDS everything is great (who would doubt :))
4) Created a similar message in ROS2
Within the framework of ROS2 and local PC, it works as it should, but if I publish a message from Cyclone DDS, then ROS2 does not see this message, it also works in the opposite direction (from ROS2 to Cyclone).
And actually I have a question: what did I do or what did not tune up that the transfer does not work, because the whole DDS is compatible.

**Comment by eboasson** [comment]
Usually, with DDS, when it works in one direction but not in the other direction the problem is a QoS mismatch. If there'd be a more fundamental communication problem, discovery data exchange usually fails already, and so nothing would work.

The ``ddsls`` tool in Cyclone is a little bit primitive but can show you the QoS settings of the readers and writers (a similar one for OpenSplice exists as ``lsbuiltin`` in https://github.com/ADLINK-IST/opensplice-tools, and though it is about as primitive, it does have the advantage that it can filter on topic name).

Latency budget is a classic one to run afoul of, but there are several "request-offered" QoS's that must match (off the top of my head: reliability, durability, destination order, deadline, latency budget, ownership, liveliness, presentation). You should also be getting a QoS mismatch notification on the reader/writer if this problem exists, if you have a listener for it.

Last resort — or first in my case, because I have gotten quite good at reading them from Cyclone and OpenSplice DDSI 😁 — is to enable tracing and look for endpoints (READER, WRITER are local ones; SEDP ... reader/writer are remote ones): those have the topic name in there and the QoS spelled out in detail, if in a somewhat unfriendly format because of just printing the raw numbers.

Or, indeed, even a Wireshark will do fine in this case. Whichever route you feel most comfortable with. And if it doesn't help, or if things don't seem to make any sense, just ask!

**Comment by th3g3ntl3m3m** [comment]
That is, now I have to create a single QoS profile for Cyclone and for ROS2 (more for Opensplice, since ROS2 is just an interlayer)

**Comment by th3g3ntl3m3m** [comment]
I noticed that when DDS is used, Multicast (239.255.0.1) and 3 ports 7400, 7401 and 62963 are used. So I can judge I can send the posted message via WireShark, but I do not see my message in the package. Actually I have 2 questions how to catch the package with my message? And how is each port used?

**Comment by eboasson** [comment]
> That is, now I have to create a single QoS profile for Cyclone and for ROS2 (more for Opensplice, since ROS2 is just an interlayer)

Not sure if this means you have determined that there is a QoS conflict or not ...

> I noticed that when DDS is used, Multicast (239.255.0.1) and 3 ports 7400, 7401 and 62963 are used. So I can judge I can send the posted message via WireShark, but I do not see my message in the package. Actually I have 2 questions how to catch the package with my message?

You will need to look at the discovery data (in Wireshark shown as DATA(p), DATA(r) and DATA(w) for participant, reader and writer) to find the GUID for the your writer, and then you have to look for that GUID in the regular DATA messages. If you have those discovery messages, everything you need is available, and Wireshark's RTPS module then allows you to filter just the packets that contain relevant data, but it is a bit of a pain and you need to know all the magic numbers ...

Just to give you an example of the pain: I've used this to isolate data (sub-message id, so rtps.sm.id == 0x15) and fragmented data (0x16) from a particular source IP address, and a writer with entity id 0x1902, as well as acknowledgement messages going the other way (0x6 is the ACKNACK message, 0x12 is a message for requesting retransmissions of individual fragments of a large sample) that actually do request a retransmit of something (rtps.bitmap.num_bits > 0).
```
(ip.src==192.168.1.2&&(rtps.sm.id==0x15||rtps.sm.id==0x16)&&rtps.sm.wrEntityId==0x1902)||(ip. dst==192.168.1.2&&(rtps.sm.id==0x6||rtps.sm.id==0x12)&&rtps.sm.wrEntityId==0x1902&&rtps.bit map.num_bits>0)
```
In other words: you can do a lot with Wireshark, but it ain't easy and requires digging through the [DDSI specification](https://www.omg.org/spec/DDSI-RTPS/About-DDSI-RTPS/) or through the [header](https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/src/core/ddsi/include/dds/ddsi/q_protocol.h) with those magic numbers and the message formats.

Personally, I much prefer using the Cyclone and OpenSplice DDSI traces for figuring out what is going on, because those give a lot of information about why certain things happen rather than just the messages going in and out. Moreover, they include topic names for each sample, and there's a DDSI trace ["decoder"](https://github.com/ADLINK-IST/opensplice/blob/master/bin/decode-ddsi-log) for OpenSplice as well. It has some limitations and I don't have one yet for Cyclone DDS, but that one can be really helpful as well.

>  And how is each port used?

There is some information in the [documentation](https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/src/docs/config.rst) (chapter 7 of the [PDF](https://raw.githubusercontent.com/eclipse-cyclonedds/cyclonedds/assets/pdf/CycloneDDS-0.1.0.pdf) — with apologies for there still not being a decent on-line documentation …). Very briefly:

* Ports 7400 and 7401 (that's for domain 0 with default settings for the mapping to port numbers) are for multicast discovery data and for multicast application data. These ports are used for receiving data only.
* Each process also has its own unicast address(es). The relevant addresses are exchanged as part of the discovery process, so if multicast discovery works, you can use random port numbers for the unicast ones. This one is used for sending everything, as well as for receiving unicast data.
* The specification goes on-and-on about discovery vs data port numbers, but in reality all data is properly identified by the GUIDs and so when using multicast discovery, Cyclone DDS and OpenSplice DDSI just advertise one port number for everything. You can however configure it to use the "well-known" unicast port numbers instead (this is the scary ``Discovery/ParticipantIndex`` setting). In that case, you will see it use ports 7410 & 7411, or 7412 & 7413, or 7214 & 7415, etc. Again, the even one is for discovery, the odd for application data.

So instead of relying on the GUIDs, you could configure both with ``Discovery/ParticipantIndex`` set to ``auto`` and then look for those port numbers as the source port. With just two processes that trick works reliably.

> I noticed that when DDS is used, Multicast (239.255.0.1)

Also worth noting is that Cyclone DDS and OpenSplice DDSI never use multicast when a single unicast suffices. So if you only have two processes, the only multicast on the wire should be the participant discovery data — so DATA(p) in Wireshark.

> Actually I have 2 questions how to catch the package with my message?

And another thing worth noting is that the data is dynamically packed into messages, so you can end up with large packets with tons of data from different writers in it ... that is tough to wade through using Wireshark ... (It doesn't make life harder when looking at traces.) There is a trick: if you set ``General/MaxMessageSize`` to something ridiculously tiny, say ``1 B`` for a 1-byte limit on message size, it will send messages that are larger than what you configured, but that are as small as it can make them. That way, each independent message gets its own packet.

**Comment by th3g3ntl3m3m** [comment]
And what problems can prevent the establishment of a connection between Cyclone and ROS2

**Comment by th3g3ntl3m3m** [comment]
A tested connection is obtained, but the following error occurs

> 2019-04-03 08:38:16.805 [RTPS_MSG_IN Error] (ID:139674050053888) Bad encapsulation for KeyHash and status parameter list -> Function proc_Submsg_Data
2019-04-03 08:38:16.805 [RTPS_MSG_IN Error] (ID:139674050053888) Bad encapsulation for KeyHash and status parameter list -> Function proc_Submsg_Data

**Comment by th3g3ntl3m3m** [comment]
Everything works as follows while waiting for the subscriber on the Cyclone side on the ROS2 side, nothing happens, I have an assumption that this should be the case if it is wrong and I did something wrong, correct me please. But after sending by Cyclone on the ROS2 side, the above error occurs. I also think to test sending a message from ROS2 and receiving a message on Cyclone.

**Comment by eboasson** [comment]
> And what problems can prevent the establishment of a connection between Cyclone and ROS2

QoS mismatch, different domain ids, topic & type mismatches: that should be about it.

> 2019-04-03 08:38:16.805 [RTPS_MSG_IN Error] (ID:139674050053888) Bad encapsulation for KeyHash and status parameter list -> Function proc_Submsg_Data

That looks identical to this: https://github.com/eProsima/Fast-RTPS/pull/371

As that fix was released only somewhat recently, I can imagine the ROS2 version you are using is referencing an older version of FastRTPS. Perhaps you could double check this before starting further investigations?

> Everything works as follows while waiting for the subscriber on the Cyclone side on the ROS2 side, nothing happens, I have an assumption that this should be the case if it is wrong and I did something wrong, correct me please. But after sending by Cyclone on the ROS2 side, the above error occurs. I also think to test sending a message from ROS2 and receiving a message on Cyclone.

It is difficult to say "yes" or "no" without having the details of what you exactly are doing in this test. I'm certain that if domain, QoS, topic and type match:
* the two should see each other
* you should be able to see that the discovery data
* you should be able to transfer data

From what I understand of the circumstances that cause that particular error message, it should not prevent communication, rather just create a temporary bit of a mess on process termination.

Would it possible for you to share the test, and to add a Cyclone trace (Tracing/Verbosity = finest in the XML file)? That might be enough information to give an answer, and although it has been a while since I last built ROS2 locally — on macOS it is, or certainly was, a bit trickier than on Linux ... — I could give it a go. No guarantees ...

**Comment by th3g3ntl3m3m** [comment]
I did not work out so can you help me in stages? maybe I missed something starting from expanding Cyclone and ROS2 and before sending the message from Cyclone to Ros2 and back, I would be immensely grateful to you.

**Comment by eboasson** [comment]
Hi @th3g3ntl3m3m, I can try. The first step would be to create a Cyclone trace that contains all the interesting details, such as discovery, selected QoS and any regular data traffic. If you know your way around those logs, they are a pretty good way to detect discovery issues, they're easy enough for spotting QoS mismatches (though not as easy as the mechanisms in the API, because with the trace you do need exactly what to look for), and many other issues are also debuggable with them. 

The trick is to use a configuration file like the following:
```XML
<CycloneDDS>
  <DDSI2E>
    <Tracing>
      <Verbosity>trace</Verbosity>
      <OuputFile>cyclonedds.log</OutputFile>
    </Tracing>
  </DDSI2E>
</CycloneDDS>
```
just point the ``CYCLONEDDS_URI`` environment variable at it. When you run the Cyclone program, you should get a file named ``cyclonedds.log`` with tons of details in it. So if you run both the ROS2 program and the Cyclone one, there's a good chance that the resulting log file will help understand the problem.

If you attach it, I'll have a look at it.

**Comment by th3g3ntl3m3m** [comment]
got an error

> 1554794285.241190/Helloworld: config: root/CycloneDDS/DDSI2E/Tracing/Verbosity/#text: 'trace': undefined value
1554794285.241207/Helloworld: config: root/CycloneDDS/DDSI2E/Tracing/#text: OuputFile: unknown element
1554794285.241211/Helloworld: config: root/CycloneDDS/DDSI2E/Tracing/#text: parser error open/close tag mismatch (OutputFile) at line 5
1554794285.241295/Helloworld: dds_create_participant: Unknown return code
Aborted (core dumped)

**Comment by eboasson** [comment]
Apologies ... that's what you get when you rush something ...

``Verbosity`` should be ``finest``, not ``trace``. (There is ``Verbosity`` and ``EnableCategory``. The two get combined but use different formats and I mixed them up, as I have done many times in the past.)

``OuputFile`` should self-evidently have been ``OutputFile``

**Comment by th3g3ntl3m3m** [comment]
[LOG](https://drive.google.com/open?id=1NY8-iJufJb4W9zT_Qi2BMi33zJJVZm76)

**Comment by eboasson** [comment]
Thanks @th3g3ntl3m3m 

This is curious: the ROS2 subscriber receives and acknowledges the sample you wrote with Cyclone. So unless there was a deserialisation problem reported by FastRTPS, it should have shown up.

I'll try to show you the steps:

You should see a local writer (the first) and a remote reader (the second) for the HelloWorldData_Msg topic in the default partition:

grep -E '(SEDP|READER|WRITER).*topic=HelloWorldData_Msg,.*partition=\{\}' ~/Downloads/cyclonedds.log
```
1554804143.384533/Helloworld: WRITER 8b8b19ac:3147:1:102 QOS={topic=HelloWorldData_Msg,type=HelloWorldData::Msg,presentation=0:0:0,partition={},durability=0,durability_service=0.000000000:{0:1}:{-1:-1:-1},deadline=2147483647.999999999,latency_budget=0.000000000,liveliness=0:2147483647.999999999,reliability=1:0.100000000,destination_order=0,history=0:1,resource_limits=-1:-1:-1,transport_priority=0,lifespan=2147483647.999999999,ownership=0,ownership_strength=0,writer_data_lifecycle={1,2147483647.999999999,2147483647.999999999},relaxed_qos_matching=0,synchronous_endpoint=0}
1554804177.217645/dq.builtin: SEDP ST0 8b8b19ac:3152:1:107 reliable volatile reader: (default).HelloWorldData_Msg/HelloWorldData::Msg NEW (as udp/239.255.0.1:7401 udp/172.25.139.139:57739 ssm=0) QOS={topic=HelloWorldData_Msg,type=HelloWorldData::Msg,presentation=0:0:0,partition={},durability=0,deadline=2147483647.999999999,latency_budget=0.000000000,liveliness=0:2147483647.999999999,reliability=1:10.000000000,destination_order=0,history=0:1,resource_limits=-1:-1:-1,transport_priority=0,ownership=0,time_based_filter=0.000000000,reader_data_lifecycle=2147483647.999999999:2147483647.999999999:0:1:1,relaxed_qos_matching=0,reader_lifespan={0,2147483647.999999999},subscription_keys={0,{}},synchronous_endpoint=0}
```
The QoS is not very readable in this form but everything is in there. Apart from some QoS that exist only on a reader or a writer, the only difference is in the second half of "reliability", which is the "max blocking time" setting. That one doesn't play a role in QoS matching, so all should be well.

Given the two GUIDs, it is easy to get everything related to these two entities:

grep -E '8b8b19ac:3152:1:107|8b8b19ac:3147:1:102' ~/Downloads/cyclonedds.log
```
1554804143.384524/Helloworld: new_writer(guid 8b8b19ac:3147:1:102, (default).HelloWorldData_Msg/HelloWorldData::Msg)
1554804143.384527/Helloworld: ref_participant(8b8b19ac:3147:1:1c1 @ 0x55ab0f3028c0 <- 8b8b19ac:3147:1:102 @ 0x55ab0f31f774) user 2 builtin 15
1554804143.384533/Helloworld: WRITER 8b8b19ac:3147:1:102 QOS={topic=HelloWorldData_Msg,type=HelloWorldData::Msg,presentation=0:0:0,partition={},durability=0,durability_service=0.000000000:{0:1}:{-1:-1:-1},deadline=2147483647.999999999,latency_budget=0.000000000,liveliness=0:2147483647.999999999,reliability=1:0.100000000,destination_order=0,history=0:1,resource_limits=-1:-1:-1,transport_priority=0,lifespan=2147483647.999999999,ownership=0,ownership_strength=0,writer_data_lifecycle={1,2147483647.999999999,2147483647.999999999},relaxed_qos_matching=0,synchronous_endpoint=0}
1554804143.384536/Helloworld: match_writer_with_proxy_readers(wr 8b8b19ac:3147:1:102) scanning all proxy readers
1554804143.384539/Helloworld: match_writer_with_readers(wr 8b8b19ac:3147:1:102) scanning all readers
1554804143.384548/Helloworld: sedp: write for 8b8b19ac:3147:1:102 via 8b8b19ac:3147:1:3c2
1554804145.384485/       tev:   8b8b19ac:3147:1:102: dropped 0 samples
1554804177.217645/dq.builtin: SEDP ST0 8b8b19ac:3152:1:107 reliable volatile reader: (default).HelloWorldData_Msg/HelloWorldData::Msg NEW (as udp/239.255.0.1:7401 udp/172.25.139.139:57739 ssm=0) QOS={topic=HelloWorldData_Msg,type=HelloWorldData::Msg,presentation=0:0:0,partition={},durability=0,deadline=2147483647.999999999,latency_budget=0.000000000,liveliness=0:2147483647.999999999,reliability=1:10.000000000,destination_order=0,history=0:1,resource_limits=-1:-1:-1,transport_priority=0,ownership=0,time_based_filter=0.000000000,reader_data_lifecycle=2147483647.999999999:2147483647.999999999:0:1:1,relaxed_qos_matching=0,reader_lifespan={0,2147483647.999999999},subscription_keys={0,{}},synchronous_endpoint=0}
```
after discovering the remote one, it matches the two (so no QoS conflict):
```
1554804177.217654/dq.builtin: match_proxy_reader_with_writers(prd 8b8b19ac:3152:1:107) scanning all writers
1554804177.217659/dq.builtin:   proxy_reader_add_connection(wr 8b8b19ac:3147:1:102 prd 8b8b19ac:3152:1:107)
1554804177.217662/dq.builtin:   writer_add_connection(wr 8b8b19ac:3147:1:102 prd 8b8b19ac:3152:1:107) - ack seq 0
1554804177.217686/dq.builtin: rebuild_writer_addrset(8b8b19ac:3147:1:102): udp/172.25.139.139:57739
1554804177.218805/       tev: heartbeat(wr 8b8b19ac:3147:1:102) suppressed, resched in inf s (min-ack 0!, avail-seq -1, xmit 0)
```
A pre-emptive ACKNACK from the ROS2 reader, asking for information on available sequence numbers arrives (as expected) and gets a response from Cyclone. (The answer is convoluted because of a crazy bit in the DDSI specification prior to version 2.3, and so to be strictly compliant with the specification, Cyclone conjures up a missing sample with sequence number 1 (that's the queueing gap #1), just to able to respond to the request without using malformed messages. This is a complication can at long last be removed because of the fixes in DDSI version 2.3.)
```
1554804177.227583/    recvUC: ACKNACK(#1:1/0: L(:1c1 15469.688565) 8b8b19ac:3152:1:107 -> 8b8b19ac:3147:1:102 preemptive-nack whc-empty force_heartbeat_to_peer: 8b8b19ac:3147:1:102 -> 8b8b19ac:3152:1:107 - whc empty, queueing gap #1 + heartbeat for transmit
```
followed by the write (which ordinarily would have been sequence number 1, but isn't because of that conjured-up missing sample):
```
1554804177.241547/Helloworld: tk=0x7fff20c68a78 iid=44f1a74c6b8dbb36 write_sample 8b8b19ac:3147:1:102 #2: ST0 HelloWorldData_Msg/HelloWorldData::Msg:
1554804177.241568/Helloworld: writer_hbcontrol: wr 8b8b19ac:3147:1:102 multicasting (rel-prd 1 seq-eq-max 0 seq 2 maxseq 0)
1554804177.241574/Helloworld: heartbeat(wr 8b8b19ac:3147:1:102) piggybacked, resched in 0.1 s (min-ack 0!, avail-seq 2, xmit 1)
1554804177.241578/Helloworld: xpack_addmsg 0x55ab0f31bf90 0x55ab0f31fe70 0(data(8b8b19ac:3147:1:102:#2/1)): niov 0 sz 0 => now niov 3 sz 80
```
then the writer is deleted before the ROS2 subscriber even acknowledges the data, which makes the Cyclone writer hang around on the network for a little while (much like TCP does when there is unacknowledged data when you close the socket).
```
1554804177.241628/Helloworld: delete_writer(guid 8b8b19ac:3147:1:102) ...
1554804177.241631/Helloworld: writer_set_state(8b8b19ac:3147:1:102) state transition 0 -> 1
1554804177.241634/Helloworld: delete_writer(guid 8b8b19ac:3147:1:102) - unack'ed samples, will delete when ack'd or at t = 15460.702622
```
then it receives an acknowledgement, ``F#2:3/0:`` means:
* F: final flag set, no need for a response
* 2: acknowledgement sequence number 2 (for protection against multipathing in networks)
* 3: acknowledge all samples with sequence number less than 3
* 0: an empty bitmap indicating samples for which a retransmit is request (as you would expect, because the sample you wrote got assigned sequence number 2

in short, FastRTPS duly acknowledges receipt here. That in turn triggers the pending cleanup.
```
1554804177.241791/    recvUC: ACKNACK(F#2:3/0: L(:1c1 15469.702764) 8b8b19ac:3152:1:107 -> 8b8b19ac:3147:1:102remove_acked_messages: deleting lingering writer 8b8b19ac:3147:1:102
1554804177.241794/    recvUC: delete_writer_nolinger(guid 8b8b19ac:3147:1:102) ...
1554804177.241815/    recvUC: writer_set_state(8b8b19ac:3147:1:102) state transition 1 -> 2
1554804177.241837/        gc: gc_delete_writer(0x7f4b90001720, 8b8b19ac:3147:1:102)
1554804177.241843/        gc: sedp: write for 8b8b19ac:3147:1:102 via 8b8b19ac:3147:1:3c2
1554804177.241863/        gc: unref_participant(8b8b19ac:3147:1:1c1 @ 0x55ab0f3028c0 <- 8b8b19ac:3147:1:102 @ 0x55ab0f31f774) user 1 builtin 15
1554804177.252333/Helloworld: delete_proxy_reader (8b8b19ac:3152:1:107) tk=0x7fff20c687d8 iid=dd05bf4709946873 write_sample 0:0:0:4c2 #30: ST3 DCPSSubscription/org::eclipse::cyclonedds::builtin::DCPSSubscription:
1554804177.253663/        gc: gc_delete_proxy_reader(0x55ab0f324f80, 8b8b19ac:3152:1:107)
```

In short, the problem must be something that prevents FastRTPS or ROS2 from delivering the data to the subscriber application. I'd almost suspect a serialisation error — perhaps ROS2 adds a bit of metadata to a sample? — but I would expect an error message from FastRTPS in that case.

One way to proceed would be to re-run the experiment, while recording the interaction with Wireshark; and then to do the same experiment with a ROS2 subscriber and ROS2 publisher, also while recording the interaction with Wireshark.

That way, it should be possible to check whether there is a difference in data formats.

**Comment by th3g3ntl3m3m** [comment]
So the error is in the interaction of ROS2 and FastRTPS?

**Comment by eboasson** [comment]
> So the error is in the interaction of ROS2 and FastRTPS?

ROS2 works perfectly fine, and I know Cyclone and FastRTPS interoperate. So I suspect it is more that ROS2 uses FastRTPS in a way slightly different than what you and I expected it to do, and that that causes the issue. I'm sure it is one of those things that will turn out to be obvious in hindsight.

So far, I am not suspecting any real problem yet, rather a misunderstanding of what is required to make the two talk.

**Comment by eboasson** [comment]
@th3g3ntl3m3m — https://github.com/atolab/rmw_cyclonedds is now pretty functional and so it is now possible to use ROS2 with Cyclone DDS. I haven't really looked into how well cross-DDS-implementation interoperation with ROS2 works, but it works at least in simple cases (like with the talker/listener demo) and so the problem you ran into has to be solvable, too.

It is only very recently that my Cyclone RMW layer started to work reasonably well. I think by now it works well enough that it can become a contribution to ROS2. That's certainly my plan.

**Comment by eboasson** [comment]
@th3g3ntl3m3m, if the problem is still exists for you, you might want to try it again: I found a troublesome bit in the specs where Cyclone made a different — and I believe, correct, except it doesn't interoperate ... — choice in the mapping to entity kinds. (See #237.)
