### ISSUE TITLE
is there any result in cpu usage comparition with fastdds

### ISSUE THREAD

**Issue by sgf201** [eclipse-cyclonedds/cyclonedds#1441]
I changed commonication to cyclone dds,but every process will occupy 8%-15% of the CPU resources all the time. my partners doubt whether such high CPU occupation is normal. I feel that the current occupation rate has only slightly improved compared with the original scheme, but I'm not sure about this. Have you ever compared the CPU occupation with other implementations such as fastdds? thanks~

**Comment by eboasson** [comment]
I have once compared it with FastDDS, but that was quite some time ago and the results of FastDDS were so horribly bad that I could only assume I had done something wrong. With the recent Galactic/Humble RMW selection process it seemed like they had solved their problems, and now I am no longer sure I did something wrong back then!

Anyway, CPU usage for all DDS implementations is pretty much the same for simple cases, it becomes interesting when packet load becomes really high. That basically comes down to a few cases:
* For very large samples, offloading traffic to shared memory makes a big difference. For Cyclone that means using the Iceoryx integration.
* Pushing high-volume data — so large samples or many small ones — to processes that don't actually need it. Cyclone loves multicast, but it can work against it if you have high-volume data that needs to go to several, but not all, other processes.
* Sending very many really small messages. Currently that still leads to a packet per sample.

For the second point: in the default configuration it uses a single multicast group, and all processes join it. So when there are many processes that but only few processes are actually interested in the data, it will go everywhere. E.g., if you have 10 processes and 3 of them subscribe to some high-volume topic, then the default configuration of Cyclone will multicast that high-volume topic and all 10 processes will process it, instead of just 3 of them. That could be the source of the load you see.

You can configure that problem away:
* by disabling the use of multicast for data altogether (`AllowMulticast` = `spdp`), or
* by disabling the use of multicast by default (`DefaultMulticastAddress` = `0.0.0.0`) and then map the topics where you want to use multicast to addresses of your choosing (`Partitioning/NetworkPartitions` and `Partitioning/PartitionMapping`), or
* you can allow multicast for everything by default and still use those "network partitions" to map *some* topics to different addresses. That way you can prevent high-volume traffic from going to processes that don't need it.

Those things would be my first suggestions ...
