### ISSUE TITLE
[Community feedback] The next CycloneDDS release

### ISSUE THREAD

**Issue by thijsmie** [eclipse-cyclonedds/cyclonedds#1450]
I apologize in advance but I am going to ping a bunch of GitHub accounts here of those who have contributed or have asked in-depth questions in the past, in no particular order.

@MatthiasKillat @clalancette @eboasson @rotu @sumanth-nirmal @evshary @roehling @cottsay
@martinbremmer @alknemeyer @kydos @willstott101 @eunsooan @trittsv @johnflj @sgf201
@sjames @i-and @pscheie @dpotman @reicheratwork @rotu @poetinger @NoxPardalis @ThijsSassen @TheFixer

We (the Eclipse committers of this project) had a chat about the stability of the current API and the question of the major version number. We've always considered CycloneDDS version `0.*` as stable but it is clear that not everyone perceives it that way. We don't want to release a version `1.0.0` as some kind of grand announcement, nothing much in the workings of  the API will change or is planned to change.

Our idea is to release version `11.0.0` and continue from there with our ~twice-yearly release schedule. Effectively we're promoting our minor version to major version.  We would like your feedback on this change and any concerns you may have.

While in API we will make little to no changes, this could be an opportunity to change the file structure which is a long-standing wish. Two examples:

 * lib/libddsc.so -> lib/libcycloneddsc.so 
 * include/dds/dds.h -> include/cyclonedds/dds.h
 
This change would involve some find-and-replace for downstream projects but could resolve some filename conflicts in packaging efforts.

Please let us know your thoughts!

**Comment by alknemeyer** [comment]
I don't have any strong thoughts on how you approach versioning, but whatever you do, I think the most important thing is to document it somehow. Perhaps you could add a section in your README or a file like VERSIONING.md. For example, clarifying that version `0.*` is stable in text could be enough; I don't think you _have to_ bump the major version number.

Otherwise, I just want to mention that I see versioning on two main levels: breaking API changes for components that use cyclonedds (like a renamed function or lib), and communication compatibility between different versions of cyclonedds (eg. can a program with v0.8 communicate with another running v0.10.2?). It could be good to highlight what your approach there is. Maybe also a table mentioning which new features were added in each version (like when XTypes was added, etc).

Lastly, could you clarify why you'd change to version `11.0.0` and not `1.0.0`? The way I see it, you're making a breaking change (renaming `ib/libddsc.so -> lib/libcycloneddsc.so`) so you bump the major version number, but if you keep developing cyclonedds in a stable way, you'd continue with `11.1.0`, `11.2.0`, etc so jumping from version 0 to 11 and staying there seems a little odd.

**Comment by alknemeyer** [comment]
I honestly had no idea the [quality declaration](https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/CYCLONEDDS_QUALITY_DECLARATION.md) exists :sweat_smile: That answers a lot of questions -- thanks. It could be worth mentioning it in the README.

**Comment by poetinger** [comment]
> I honestly had no idea the [quality declaration](https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/CYCLONEDDS_QUALITY_DECLARATION.md) exists 😅 That answers a lot of questions -- thanks. It could be worth mentioning it in the README.

I think this is related to the `"unstable" argument` that @thijsmie mentioned. From what I have heard, there are entities that merely look at a version number to determine whether software is stable or not. I have heard there are certain systems that verify this by merely checking the version number to be `>1.x.x`. Which, unfortunately, would not be resolved by the quality declaration (or any mentions in READMEs for that matter). 

In my own opinion, as a mere SWE, I don't find a jump from `0.10.x` to `11.x.x` to be very strange beyond the initial change. Especially if I looked at the previous releases and noticed that it boils down to just dropping the preceding `0`.

**Comment by roehling** [comment]
I have no objections to your versioning scheme. One thing I consider important from a Linux distribution's perspective is that API and ABI stability are not always the same (for example, adding a new member to the beginning of a struct will not break the API, because existing source code will continue to compile just fine, but it will break the ABI, because all struct members will shift their offsets, so any program using those structs needs to be recompiled).

For this reason, would you consider separating the Stable API and the Evolving API into two different shared libraries? That way, the SOVERSION for the Stable API library could very likely remain fixed for most releases, and the Evolving API library could have its SOVERSION bumped more liberally on breaking changes, without sacrificing binary compatibility for users of the Stable API. This would also simplify downstream packaging, because it makes it very obvious if dependent packages need to be rebuilt.

**Comment by evshary** [comment]
I don't have strong thoughts about this change, but I guess the frequently asked question later will be why the version is from 0.10.x to 11.0.0. After your explanation, it's clear that the reason is to remove the original major version 0.
If this explanation can be easily found somewhere (README or release note...), I think it might not be a problem.

And I also think bumping the version from `11.0.0` to `12.0.0` is better than from `11.0.0` to `11.1.0`. This won't cause confusion, but maybe need to clarify when to bump the major version in [quality declaration](https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/CYCLONEDDS_QUALITY_DECLARATION.md).

**Comment by thijsmie** [comment]
@roehling I think that building two separate libraries with Stable and Evolving is going too far for us. I do think we can do a better job in doing the ABI homework. By doing "more major releases" and running automated tools like [ABI Compliance Checker](https://lvc.github.io/abi-compliance-checker/) between these releases in CI we should be able to give better directions on changes. This also comes with the homework of actually informing you what the Stable and Evolving API's are, because I think actually the ABI of what I consider the Stable API has not changed in a couple years. This is also helped by the fact we actually have very few structs in our API (by my quick grep: `dds_sample_info`, `dds_builtintopic_*`, `dds_allocator`, `dds_sequence`, `dds_key_descriptor`, `dds_type_meta_ser` and the listener callback status structs).

 Would a regular major release with an automated "this release is ABI compatible with the release x.x.x" or "this release breaks ABI compatibility _here_, _here_ and _here_" statements added be helpful for you @roehling?

And @evshary, yes, we will need to document our versioning policy and update the quality declaration to reflect that.

**Comment by thijsmie** [comment]
Thanks all for your feedback. We'll soon go for the release.
