### ISSUE TITLE
The sample of take has been changed which is assigned by me

### ISSUE THREAD

**Issue by sgf201** [eclipse-cyclonedds/cyclonedds#1459]
@eboasson
using [eboasson@eff7e82](https://github.com/eboasson/cyclonedds/commit/eff7e8208ea5c02dda72f206e5561748961b8334)
Recently, the environment in which dds is used has become more complex, and the pressure has increased. A strange problem has arisen. I think the time is when the process dds_ruthless_reset_for_child_after_fork ,The sample of take has been changed which is assigned by me. Is it possible that this is caused by this operation? I generally do this:

my_dds_read(reader, buf* msg)
{
sample[0] = msg;
dds_take(reader,sample,1,1);
}

writer is not ready or ready but write nothing, read get no data bug msg is changed

**Comment by eboasson** [comment]
I'm not sure I follow completely, let's see:
* you have some data in `msg` (in the parent process before forking)
* then you fork after which nothing relevant happens in the parent, and in the child:
* you call `dds_ruthless_reset_for_child_after_fork`
* create new participant, reader
* (nobody publishes anything new & there's no data in `reader`)
* then you call `my_dds_read` on the same `msg`
* since there was no data to read, you would expect the contents of `msg` to remain unchanged but it actually did change

did I get that right?

Looking at the code, that does seem strange. `dds_take` maps to `dds_read_impl`, and with `sample[0]` non-null, "nodata_cleanups" is 0 (nothing to be done if no data is returned). It gets passed straight to the RHC, which does nothing if there is no data ...

Perhaps you could try making a small reproducer? Or perhaps you could try running it in [`rr`](https://rr-project.org) and reverse execute with a watchpoint set on the part in `msg` that changes?

**Comment by sgf201** [comment]
> I'm not sure I follow completely, let's see:
> 
> * you have some data in  (in the parent process before forking)`msg`
> * then you fork after which nothing relevant happens in the parent, and in the child:
> * you call `dds_ruthless_reset_for_child_after_fork`
> * create new participant, reader
> * (nobody publishes anything new & there's no data in `reader`)
> * then you call  on the same `my_dds_read``msg`
> * since there was no data to read, you would expect the contents of  to remain unchanged but it actually did change`msg`
> 
> did I get that right?
> 
> Looking at the code, that does seem strange. maps to , and with non-null, "nodata_cleanups" is 0 (nothing to be done if no data is returned). It gets passed straight to the RHC, which does nothing if there is no data ...`dds_take``dds_read_impl``sample[0]`
> 
> Perhaps you could try making a small reproducer? Or perhaps you could try running it in [`rr`](https://rr-project.org) and reverse execute with a watchpoint set on the part in that changes?`msg`

you are right
![image](https://user-images.githubusercontent.com/5253415/201527728-24d7c0fa-da37-4be0-861e-1e1b088882e5.png)

Let me describe a detail. I use this judgment to determine whether any data is received. I also judge the validity when the rc confirms that it is not 0, I don't know whether it is possible to receive data, but it is valid_data does not meet the conditions. Do I check the valid_data in wrong way?

**Comment by eboasson** [comment]
Apologies for the the slow response ...

Assuming `rc` is always the result of calling `dds_read` or `dds_take`, then this should be totally fine. I checked the code again, and I am pretty sure all `infos[0 .. rc-1]` will be filled properly when `rc`>0.

Is `valid_data` true when you expected false, or is it false when you expected true?

If it is unexpectedly false, then it could perhaps be that you ran into an instance state change (`instance_state` flipping from `ALIVE` to `NO_WRITERS` or to `DISPOSED`) when all samples for the instance had been read already. The question then is whether you should have expected that or not, &c.

**Comment by sgf201** [comment]
> 

![image](https://user-images.githubusercontent.com/5253415/204840536-2966e71a-1b4b-4365-b9ef-3dfbac8f2b6f.png)
my_dds_read(reader, buf* msg)
{
sample[0] = msg;
dds_take(reader,sample,dds_sample_info_t *si,xx,1);
}
I try to reduce the copy when reading data by using the buf of the actual parameter as the sample. The current "valid_data" mechanism may lead to the "invalid_data" filled in when "invalid_data" exists in the reader. That is, the external representation is that when take no data, but the data in the actual parameter buf is modified. So, is it impossible for me to use buf as the sample to "dds_take" to reduce data copy in the current cyclonedds scheme?

**Comment by sgf201** [comment]
@eboasson thank you so much
