### ISSUE TITLE
Repeated samples sent out for Transient Local Durability Qos.

### ISSUE THREAD

**Issue by stillsimon** [eclipse-cyclonedds/cyclonedds#146]
Hi, I've been testing Cyclone with Transient Local Durability Qos and I found there is a high probability that a Transient Local writer may resend samples to late join readers.

Here is the situation where I found the problem. I created one Transient Local writer (reliable set) and one Transient Local reader (reliable set) in each node. The writer will write out a HelloWorld message (userID equals the nodeID) soon after it is created. An on_data_available listener is set on the reader and wait for upcoming data.

For the test, 10 nodes will be created one after another (1 second interval). After ten nodes created, what I expected was that each reader in one node would receive 10 data samples exactly(from node 1 ~ 10). However, I found that some nodes received more than 10 data samples. The exceeding data samples are sent by the writer and using dds_take with  DDS_NEW_VIEW_STATE can suppress this issue.

Here is the code and script for testing. 
```
#include "ddsc/dds.h"
#include "HelloWorldData.h"
#include <stdio.h>
#include <stdlib.h>

int nodeID = 999;
int sample_received = 0;

#define MAX_SAMPLES 1

void reader_on_data_available(dds_entity_t reader, void *arg)
{
    HelloWorldData_Msg *msg;
    void *samples[MAX_SAMPLES];
    dds_sample_info_t infos[MAX_SAMPLES];
    dds_return_t ret;

    ret = dds_take(reader, samples, infos, MAX_SAMPLES, MAX_SAMPLES);
    //ret = dds_take_mask(reader, samples, infos, MAX_SAMPLES, MAX_SAMPLES, DDS_NEW_VIEW_STATE);
    // dds_take_mask with DDS_NEW_VIEW_STATE will not result this error.
    DDS_ERR_CHECK (ret, DDS_CHECK_REPORT | DDS_CHECK_EXIT);

    /* Check if we read some data and it is valid. */
    if ((ret > 0) && (infos[0].valid_data)) {
        /* Print Message. */
        msg = (HelloWorldData_Msg *) samples[0];
        printf("=== [Node %d] Received : ", nodeID);
        printf("Message (%d, %s)\n", msg->userID, msg->message);
        sample_received++;
    }

    if (sample_received > 10) {
        printf("ERROR! Node: %d message received sample num: %d\n", nodeID, sample_received);
    }
}

int main(int argc, char **argv)
{
    dds_entity_t participant;
    dds_entity_t topic;
    dds_entity_t writer;
    dds_entity_t reader;
    dds_qos_t *writer_qos = NULL;
    dds_qos_t *reader_qos = NULL;
    dds_listener_t *reader_listener = NULL;
    dds_return_t ret;
    HelloWorldData_Msg msg;
    (void) argc;
    (void) argv;

    if (argc == 2) {
        nodeID = atof(argv[1]);
    }

    /* Create a Participant. */
    participant = dds_create_participant(DDS_DOMAIN_DEFAULT, NULL, NULL);
    DDS_ERR_CHECK (participant, DDS_CHECK_REPORT | DDS_CHECK_EXIT);

    /* Create a Topic. */
    topic = dds_create_topic(participant, &HelloWorldData_Msg_desc,
                             "HelloWorldData_Msg", NULL, NULL);
    DDS_ERR_CHECK (topic, DDS_CHECK_REPORT | DDS_CHECK_EXIT);

    /* Create a Writer. */
    writer_qos = dds_create_qos();
    dds_qset_reliability(writer_qos, DDS_RELIABILITY_RELIABLE, DDS_MSECS (100));
    dds_qset_durability(writer_qos, DDS_DURABILITY_TRANSIENT_LOCAL);
    writer = dds_create_writer(participant, topic, writer_qos, NULL);
    DDS_ERR_CHECK (writer, DDS_CHECK_REPORT | DDS_CHECK_EXIT);

    /* Create a Reader. */
    reader_qos = dds_create_qos();
    dds_qset_reliability(reader_qos, DDS_RELIABILITY_RELIABLE, DDS_MSECS (100));
    dds_qset_durability(reader_qos, DDS_DURABILITY_TRANSIENT_LOCAL);
    reader_listener = dds_create_listener(reader);
    dds_lset_data_available(reader_listener, reader_on_data_available);
    reader = dds_create_reader(participant, topic, reader_qos, reader_listener);
    DDS_ERR_CHECK (reader, DDS_CHECK_REPORT | DDS_CHECK_EXIT);

    /* Create a message to write. */
    msg.userID = nodeID;
    msg.message = "Hello World";

    printf("=== [Publisher]  Writing : ");
    printf("Message (%d, %s)\n", msg.userID, msg.message);

    ret = dds_write(writer, &msg);
    DDS_ERR_CHECK (ret, DDS_CHECK_REPORT | DDS_CHECK_EXIT);

    dds_sleepfor(DDS_SECS(15));

    /* Deleting the participant will delete all its children recursively as well. */
    ret = dds_delete(participant);
    DDS_ERR_CHECK (ret, DDS_CHECK_REPORT | DDS_CHECK_EXIT);

    dds_delete_qos(reader_qos);
    dds_delete_qos(writer_qos);
    dds_delete_listener(reader_listener);

    return EXIT_SUCCESS;
}
```
Test Script
```
for i in {1..10}
do
  ./TransientLocalTest $i &
  sleep 1
done
```
![issue](https://user-images.githubusercontent.com/49296783/55600863-a5cb9300-5790-11e9-8def-0eb6a91f96c0.PNG)

**Comment by eboasson** [comment]
Thanks @stillsimon !

Given the right amount of background knowledge of the code and a set of Cyclone traces generated by your reproducer (it is timing dependent, but pretty easily reproduced with the tracing enabled), it is rather obvious what the problem is. That "right amount of background knowledge" might be a somewhat tricky requirement … so, let me try to explain in the hope that it will prove useful or interesting to you and/or others. If not, fear not: the patch below addresses the problem. I’ll do a pull request later, I am still wondering if there is a more elegant way.

```diff
diff --git a/src/core/ddsi/src/q_receive.c b/src/core/ddsi/src/q_receive.c
index d09c89d..4f92bf5 100644
--- a/src/core/ddsi/src/q_receive.c
+++ b/src/core/ddsi/src/q_receive.c
@@ -2172,6 +2172,14 @@ static void handle_regular (struct receiver_state *rst, nn_etime_t tnow, struct
 
   /* Shouldn't lock the full writer, but will do so for now */
   ddsrt_mutex_lock (&pwr->e.lock);
+
+  if (!pwr->have_seen_heartbeat)
+  {
+    ddsrt_mutex_unlock (&pwr->e.lock);
+    DDS_TRACE(" %x:%x:%x:%x -> %x:%x:%x:%x: no heartbeat seen yet", PGUID (pwr->e.guid), PGUID (dst));
+    return;
+  }
+
   if (ut_avlIsEmpty (&pwr->readers) || pwr->local_matching_inprogress)
   {
     ddsrt_mutex_unlock (&pwr->e.lock);
```

The communication model described in the DDSI specification is very simple: once a reader discovers a writer, it is to deliver data in order of increasing sequence number. For a volatile reader, the starting point is the "current" sequence number of the writer (in itself a vague concept because the communication and discovery latencies may result in the writer having a different idea than the reader); for a transient-local reader, the starting point is the oldest sample still available in the writer history cache.

What happens in your test is that — with some oversimplification — the reader accepts the first sample it receives, even before it has received a Heartbeat message from the writer informing it of the range of sequence numbers the writer has available in its history cache. Once it gets that heartbeat, it starts requesting historical data, eventually resulting in the second copy.

The trace fragment below (edited for clarity) shows this. First is discovery of the remote writer, and the note that the reader is effectively out-of-sync with the writer (the huge number is a placeholder sequence number until a Heartbeat message comes in):
```
1554452145.732674/dq.builtin: SEDP ST0 665d10ac:6180:1:102 reliable transient-local writer: (default).Msg/Msg NEW …
1554452145.732686/dq.builtin: match_proxy_writer_with_readers(pwr 665d10ac:6180:1:102) scanning all readers
1554452145.732702/dq.builtin:   reader_add_connection(pwr 665d10ac:6180:1:102 rd 665d10ac:6158:1:207)
1554452145.732708/dq.builtin:   proxy_writer_add_connection(pwr 665d10ac:6180:1:102 rd 665d10ac:6158:1:207) - out-of-sync 9223372036854775807
```
it then receives a multicasted copy of the data, which it delivers (can’t be any data before it, it being sequence number 1). The piggy-backed heartbeat tells it the writer has samples [1..1] available, so the end of the "transient-local sequence" is sequence number 1. This triggers a NACK requesting the sample to be retransmitted:
```
1554452145.745334/    recvMC: DATA(665d10ac:6180:1:102 -> 0:0:0:0 #1)
1554452145.759079/    recvMC: HEARTBEAT(#6:1..1  665d10ac:6180:1:102 -> 0:0:0:0: end-of-tl-seq(rd 665d10ac:6158:1:207 #1) 665d10ac:6158:1:207@0/NAK)
```
followed by a unicast retransmit of the data, also delivered because it is in sequence for the retrieval of historical data. Receipt of that sample changes the state of the reader to consider itself completely in sync with the writer.
```
1554452145.779501/    recvUC: DATA(665d10ac:6180:1:102 -> 665d10ac:6158:1:207 #1 msr_in_sync(665d10ac:6158:1:207 out-of-sync to tlcatchup))
1554452145.799134/    recvUC: HEARTBEAT(#8:1..1  665d10ac:6180:1:102 -> 665d10ac:6158:1:207: 665d10ac:6158:1:207@1(sync))
```

Obviously, it makes little sense to deliver sample 1 and then request sample 1 *again* for catching up on historical data. Of course it would be easy to treat 1 specially, but there is no guarantee that this first copy of sequence number 1 is a freshly published piece of data. (I’d like a flag in the messages to be able to distinguish fresh data from retransmits, but that’s another subject …) The trouble is, it can also be a delayed copy, and so one can’t really base any conclusions on it (other than that delivering it twice is plain wrong).

The easy solution (and the patch above) simply drops all data until a Heartbeat has been received, completing the handshake. The unfortunate side-effect is that data published immediately after creating a writer is quite likely to result in a retransmit … that should be solvable by getting a Heartbeat in the same packet as the data, but that is a bit more work and something I’d like to think about a little bit.

You may have the uncomfortable feeling that the above also means Cyclone is handling the historical data as a separate sequence of samples from the live data, to be delivered in parallel, instead of delivering all samples from the writer in strict sequence number order  — and you would be correct 😁. There are good reasons to favour such a model, chiefly among them:

* eventual consistency in combination with transient data and reconnecting after a disconnection leaves you little choice but to sometimes deliver data out-of-order, and the suggestion of the RxO QoS matching of DDS is that "transient" is simply a better "transient-local" and so shouldn’t weaken any guarantees (apologies for the very brief and cryptic statement, but this is a discussion that should probably be held outside the context of this particular bug — but I have to say that I disagree with this particular view of "transient" vs "transient-local"!);
* if you have a system where a transient(-local) reader and writer have a "keep all" history with resource limits and a durability service QoS setting with a "keep last" history setting, requiring that the historical data be delivered strictly before any new samples could block the writer (e.g., one might want an error logging service with a history of 1000 historical samples for late-joining readers, while also ensuring that all existing readers get everything).

Arguments against it also exist:

* out-of-order delivery may be fine with "by source timestamp" ordering, but is definitely somewhat nasty with "by reception timestamp" ordering;
* even with "by source timestamp" ordering, you can have order reversal of a "write" and a "dispose" that brings additional problems: you could have a writer send a "dispose instance X" straight to a late-joining reader but after that reader requested a retransmit of a historical sample for instance X.

In my opinion the answer to the riddle lies in considering DDS as the amalgamation of an eventually shared data space (typically by-source timestamp, volatile or transient — my métier) and publish-subscribe message queueing (typically by-reception timestamp, volatile or transient-local — a mere implementation detail). In the case of the former, parallel delivery of historical data is perfectly fine (provided one handles the disposes with care), but for the latter, it is not.

And so Cyclone will need fixing to really start doing strict in-order delivery.

**Comment by stillsimon** [comment]
Thank you so much for explanation!

I've modified a little bit for the test case to test the Transient Local Writer's delivery for data samples. What I found is that the Transient Local Writer will only send out the latest sample for the instance it got. Here is the case. One Transient Local Writer is created and write (1, "HelloWorld 1"), (2, "HelloWorld 2"), (1, "HelloWorld 1 again") into its whc. Then a remote Transient Local Reader joins and receives data. What the reader receives is only (2, "HelloWorld 2"), (1, "HelloWorld 1 again"). The (1, "HelloWorld 1") message seems updated(because of the same key 1) and not sent to the remote writer. Is it a bug or is it designed deliberately?

Here is the code!
Pub code:
```
#include "ddsc/dds.h"
#include "HelloWorldData.h"
#include <stdio.h>
#include <stdlib.h>

int main(int argc, char **argv)
{
    dds_entity_t participant;
    dds_entity_t topic;
    dds_entity_t writer;
    dds_qos_t *writer_qos = NULL;
    dds_return_t ret;
    HelloWorldData_Msg msg;

    /* Create a Participant. */
    participant = dds_create_participant(DDS_DOMAIN_DEFAULT, NULL, NULL);
    DDS_ERR_CHECK (participant, DDS_CHECK_REPORT | DDS_CHECK_EXIT);

    /* Create a Topic. */
    topic = dds_create_topic(participant, &HelloWorldData_Msg_desc, "HelloWorld", NULL, NULL);
    DDS_ERR_CHECK (topic, DDS_CHECK_REPORT | DDS_CHECK_EXIT);

    /* Create a Writer. */
    writer_qos = dds_create_qos();
    dds_qset_reliability(writer_qos, DDS_RELIABILITY_RELIABLE, DDS_MSECS (100));
    dds_qset_durability(writer_qos, DDS_DURABILITY_TRANSIENT_LOCAL);
    dds_qset_history(writer_qos, DDS_HISTORY_KEEP_ALL, 10);
    writer = dds_create_writer(participant, topic, writer_qos, NULL);
    DDS_ERR_CHECK (writer, DDS_CHECK_REPORT | DDS_CHECK_EXIT);

    /* Create a message to write. */
    msg.userID = 1;
    msg.message = "HelloWorld 1";
    printf("=== [Publisher]  Writing : ");
    printf("Message (%d, %s)\n", msg.userID, msg.message);
    ret = dds_write(writer, &msg);
    DDS_ERR_CHECK (ret, DDS_CHECK_REPORT | DDS_CHECK_EXIT);

    /* Create a message to write. */
    msg.userID = 2;
    msg.message = "HelloWorld 2";
    printf("=== [Publisher]  Writing : ");
    printf("Message (%d, %s)\n", msg.userID, msg.message);
    ret = dds_write(writer, &msg);
    DDS_ERR_CHECK (ret, DDS_CHECK_REPORT | DDS_CHECK_EXIT);

    /* Create a message to write. */
    msg.userID = 1;
    msg.message = "HelloWorld 1 again";
    printf("=== [Publisher]  Writing : ");
    printf("Message (%d, %s)\n", msg.userID, msg.message);
    ret = dds_write(writer, &msg);
    DDS_ERR_CHECK (ret, DDS_CHECK_REPORT | DDS_CHECK_EXIT);

    /* Create a message to write. */
    msg.userID = 1;
    msg.message = "HelloWorld 1 again again";
    printf("=== [Publisher]  Writing : ");
    printf("Message (%d, %s)\n", msg.userID, msg.message);
    ret = dds_write(writer, &msg);
    DDS_ERR_CHECK (ret, DDS_CHECK_REPORT | DDS_CHECK_EXIT);

    dds_sleepfor(DDS_SECS(10));

    /* Deleting the participant will delete all its children recursively as well. */
    ret = dds_delete(participant);
    DDS_ERR_CHECK (ret, DDS_CHECK_REPORT | DDS_CHECK_EXIT);

    dds_delete_qos(writer_qos);

    return EXIT_SUCCESS;
}
```
Sub code:
```
#include "ddsc/dds.h"
#include "HelloWorldData.h"
#include <stdio.h>
#include <stdlib.h>

#define MAX_SAMPLES 1

void reader_on_data_available(dds_entity_t reader, void *arg)
{
    HelloWorldData_Msg *msg;
    void *samples[MAX_SAMPLES];
    dds_sample_info_t infos[MAX_SAMPLES];
    dds_return_t ret;

    ret = dds_take(reader, samples, infos, MAX_SAMPLES, MAX_SAMPLES);
    DDS_ERR_CHECK (ret, DDS_CHECK_REPORT | DDS_CHECK_EXIT);

    /* Check if we read some data and it is valid. */
    if ((ret > 0) && (infos[0].valid_data)) {
        /* Print Message. */
        msg = (HelloWorldData_Msg *) samples[0];
        printf("Message (%d, %s)\n", msg->userID, msg->message);
    }
}

int main(int argc, char **argv)
{
    dds_entity_t participant;
    dds_entity_t topic;
    dds_entity_t reader;
    dds_qos_t *reader_qos = NULL;
    dds_listener_t *reader_listener = NULL;
    dds_return_t ret;

    /* Create a Participant. */
    participant = dds_create_participant(DDS_DOMAIN_DEFAULT, NULL, NULL);
    DDS_ERR_CHECK (participant, DDS_CHECK_REPORT | DDS_CHECK_EXIT);

    /* Create a Topic. */
    topic = dds_create_topic(participant, &HelloWorldData_Msg_desc, "HelloWorld", NULL, NULL);
    DDS_ERR_CHECK (topic, DDS_CHECK_REPORT | DDS_CHECK_EXIT);

    /* Create a Reader. */
    reader_qos = dds_create_qos();
    dds_qset_reliability(reader_qos, DDS_RELIABILITY_RELIABLE, DDS_MSECS (100));
    dds_qset_durability(reader_qos, DDS_DURABILITY_TRANSIENT_LOCAL);
    dds_qset_history(reader_qos, DDS_HISTORY_KEEP_ALL, 10);
    reader_listener = dds_create_listener((void *) reader);
    dds_lset_data_available(reader_listener, reader_on_data_available);
    reader = dds_create_reader(participant, topic, reader_qos, reader_listener);
    DDS_ERR_CHECK (reader, DDS_CHECK_REPORT | DDS_CHECK_EXIT);

    dds_sleepfor(DDS_SECS(100));

    /* Deleting the participant will delete all its children recursively as well. */
    ret = dds_delete(participant);
    DDS_ERR_CHECK (ret, DDS_CHECK_REPORT | DDS_CHECK_EXIT);

    dds_delete_qos(reader_qos);
    dds_delete_listener(reader_listener);

    return EXIT_SUCCESS;
}
```
![image](https://user-images.githubusercontent.com/49296783/55703570-8fca0680-5a0c-11e9-9b55-238ff3c62918.png)
![image](https://user-images.githubusercontent.com/49296783/55703594-9ce6f580-5a0c-11e9-94e8-2d72c4e8ee2c.png)

**Comment by eboasson** [comment]
Hi @stillsimon 

> I've modified a little bit for the test case to test the Transient Local Writer's delivery for data samples. What I found is that the Transient Local Writer would only send out the latest sample for the instance it got. Here is the case. One Transient Local Writer is created and writes (1, "HelloWorld 1"), (2, "HelloWorld 2"), (1, "HelloWorld 1 again") into its whc. Then a remote Transient Local Reader joins and receives data. What the reader receives is only (2, "HelloWorld 2"), (1, "HelloWorld 1 again"). The (1, "HelloWorld 1") message seems updated(because of the same key 1) and not sent to the remote writer. When I change the third message to (3, "HelloWorld 1 again"). All three samples can be received by the reader. Is it a bug or is it designed deliberately? Thanks!

Yes, that's deliberate: Cyclone uses the "durability service" QoS for all non-volatile data, so including "transient-local". Most implementations ignore it for transient-local, but thereby lose a degree of freedom that actually does matter. In my first comment on this issue I mentioned a case of requiring "keep all" behaviour for live data and yet wanting to provide some historical data to a new reader.

If, like most implementations, you only look at the writer history for deciding what data to retain as historical data, you are forced between choosing "keep all" and (likely) running out of resources because of historical data, or "keep last" and (potentially) overwriting some data if the readers can't keep up with the writer. (I suppose with "keep last 1000" it would be unlikely, but there is the formal possibility.)

By separating the history for reliability from the history for late-joining readers, you can solve that problem. The idea that there might be a difference is something that was clearly realised for "transient" and "persistent" data at the time the DDS specification was written, but strangely enough it has been mostly ignored for "transient-local".

So ... the short answer is: Cyclone uses the history setting of the "durability service" QoS to determine what to keep for the late-joining ones. Setting the regular "history" QoS of the writer has no effect on this. As the default history setting is "keep last 1", that's all you got. Things should start to change if you add
```C
dds_qset_durability_service(
  writer_qos,
  0,
  DDS_HISTORY_KEEP_LAST, 10,
  DDS_LENGTH_UNLIMITED, DDS_LENGTH_UNLIMITED, DDS_LENGTH_UNLIMITED);
```

Note that it currently only uses the history part. It is somewhat cavalier in its treatment of the resource limits within the durability service QoS ...

P.S. By the way: in
```C
dds_qset_history(writer_qos, DDS_HISTORY_KEEP_ALL, 10);
```
you do realize that the "10" is pretty much ignored because of the "ALL", right?

**Comment by stillsimon** [comment]
Thank you! That solves the problem! ^_^
