### ISSUE TITLE
Segment Fault in ddsi_serdata_from_ser

### ISSUE THREAD

**Issue by stillsimon** [eclipse-cyclonedds/cyclonedds#147]
Hi, when I was using cyclone, sometimes I could encounter a strange problem shown below. In userdata receiving thread, the thread can be killed by segment fault in ddsi_serdata_from_ser. This thread is not controlled by the user so I have no idea what causes it. Can you please have a look at this problem? Thanks!
![image](https://user-images.githubusercontent.com/49296783/55710686-bfcdd580-5a1d-11e9-9bc9-7ed5aa48e36c.png)
![image](https://user-images.githubusercontent.com/49296783/55710399-1e468400-5a1d-11e9-907d-227bc1c2470b.png)
![image](https://user-images.githubusercontent.com/49296783/55710419-2b637300-5a1d-11e9-8f8e-458585ce8674.png)

**Comment by eboasson** [comment]
I absolutely **hate** segfaults — or any other kind of bug in my code, really — so you've found the best way to get my attention quickly! 😁

Unfortunately, I don't have much time today ... so if it is reproducible and you have some time to do some digging that would be helpful. The first screenshot (crash in line 145) I could understand if topic->serdata_ops is a null pointer or if topic is a bogus pointer, though I have no idea yet how that could be the case. It should be pretty easy to dump the contents & dig around a bit to see whether the pointers make sense or result in garbage.

The second stack trace is weird: I can't find any calls to ``printf`` anywhere near ``ddsi_serdata_from_ser``, and that function doesn't really do anything other than forward the call via ``topic->serdata_ops`` ...

Finally, have you seen it only on ARM64 or also on other platforms?

Thanks

**Comment by stillsimon** [comment]
Yes, it only happens on ARM64, will this influence the code execution? Thanks!

**Comment by eboasson** [comment]
Thanks for the printf details — and yes, that indeed suggests ``topic`` is pointing someplace weird. That gives a starting point at least.

If ``topic`` were a null pointer, I'd say the lazy setting of the topic in proxy endpoints would be the culprit. As it isn't, one wonders if I missed a reference count ... but that is something I can and will look into.

> Yes, it only happens on ARM64, will this influence the code execution?

I was just wondering because I have never seen it go wrong, and the platform can make a difference. Usually when something appears to be platform-specific, it is really just a race condition that only gets hit by the particular timing on that one platform.

There are some subtle differences between the various processor families — e.g., x86/x64, ARM, SPARC — in their memory subsystem, in the ordering of changes in memory and observing those changes from other CPUs. It is quite a fascinating subject — if you have never looked into it in any detail and you have a few hours to spare, then [what every programmer should know about memory](https://people.freebsd.org/~lstewart/articles/cpumemory.pdf) and chapter 5 of the [Alpha architecture handbook](https://www2.cs.arizona.edu/projects/alto/Doc/local/alphahb2.pdf) are quite interesting reads. 😁

**Comment by jwcesign** [comment]
This happens when I delete and create the writer in pub repeatedly

**Comment by eboasson** [comment]
A perhaps stupid question: but which commit are you on? The reason I'm asking is that the crash sounds eerily familiar to this commit: c61c880fd2de28ed04d1dd137ca6b12b67d18745 

Your screenshot has a call to ``get_serdata`` on line 1821 of q_receive.c, which was last the case a few commits later, so the timing suggests it is at least possible that you haven't got that commit in.

**Comment by jwcesign** [comment]
oh, Thanks! It works. I will try use the newest version.

**Comment by eboasson** [comment]
@stillsimon, I presume the problem has been "disappeared" for you as well?
