### ISSUE TITLE
RTI DDS vs Cyclonedds-CXX

### ISSUE THREAD

**Issue by wjbbupt** [eclipse-cyclonedds/cyclonedds#1474]
hi, I use RTI DDS and Cyclonedds-CXX to use the same idl, perform a pub|, a sub, and use the packet capture to find that there is only the data(p) of the first stage, and then there is no following data(w), data(r ); suspect that there is a problem with serialization and deserialization,
But I see that opendds, FastDDS, RTI DDS can communicate,
question:
1. The RTPS specification is used between them. In theory, it should be possible to communicate. Is it wrong for me to use it?
2. Is there a way to communicate between RTI DDS vs Cyclonedds-CXX?

Thank you very much, this is very important to me

**Comment by eboasson** [comment]
Certainly it should work, but there are some tricky problems with the specifications and bugs in all implementations — e.g. all we ran into a spectacular bug in [Connext](https://github.com/eclipse-cyclonedds/cyclonedds-cxx/issues/218), some subtle type information issues with [OpenDDS](https://github.com/eclipse-cyclonedds/cyclonedds/issues/1345#issuecomment-1211430041), and [FastDDS](https://github.com/eclipse-cyclonedds/cyclonedds/issues/1328) mishandling discovery data. I'm sure Cyclone has its share of bugs, too ...

If you don't see any DATA(w) or DATA(r), then it already fell apart at the participant discovery. That's unusual, but the good news is that it involves very little data to study.

For us to help you, you'll have to provide some more information: we can't go anywhere near RTI's products because of the license they use, and so any interoperability issue needs to be studied through some captures/traces and some guesswork.

In this case, it would help to have the packet capture and a Cyclone trace file (`CYCLONEDDS_URI="<Tr><C>trace,plist</><Out>cdds.log.\${CYCLONEDDS_PID\}</>"` in the environment should suffice). Would you be able to provide those? (If you don't want to upload them to GitHub, you can email them instead.)

**Comment by neerja123-gupta** [comment]
Hello, I am having a similar issue. I would like to publish using rti connext and subscribe using cyclone dds.  I tried Helloworld example. I used HelloWorld.idl and created same in rti connext. But I am not able to subscribe any data in cyclone. Just wanted to ask were you able to solve it? Thanks. Any help would be highly appreciated.
