### ISSUE TITLE
Failed to find a free participant index for domain 0

### ISSUE THREAD

**Issue by sgf201** [eclipse-cyclonedds/cyclonedds#1475]
for SIL test I add the xml below:
export CYCLONEDDS_URI='<CycloneDDS><Domain><General><NetworkInterfaceAddress>lo</NetworkInterfaceAddress></General></Domain></CycloneDDS>'

one of programs  create participaint faild
Failed to find a free participant index for domain 0
![647ab5ee-cc07-483c-b9a9-e223ed90a9f4](https://user-images.githubusercontent.com/5253415/201266665-52703212-51bf-43f9-8e71-a48ed9fe120f.jpeg)

**Comment by eboasson** [comment]
I am not sure what a "SIL" test is, but I don't think it really matters for now 😄 . The trouble is that by default it will only use a "participant index" in 0 .. 9 (https://cyclonedds.io/docs/cyclonedds/latest/config/cyclonedds_specifics.html#controlling-port-numbers, https://github.com/eclipse-cyclonedds/cyclonedds/issues/729#issuecomment-807153175). Raising that should solve it.

That said, it is really a silly thing: Linux has *no problem whatsoever* doing multicast on the loopback interface, it is just Ubuntu that decides to not set the `IF_MULTICAST` flag on the interface. If you set it using `ifconfig lo multicast`, it works fine. Indeed, if you just join a multicast group and send it to it, it works fine. No kernel or interface changes/config needed. Why Canonical configures it so that the kernel lies to the applications is beyond me ...

You're not the only running into that, by the way: https://github.com/eclipse-cyclonedds/cyclonedds/issues/1400

**Comment by sgf201** [comment]
3Q so much
