### ISSUE TITLE
Interoperability between CycloneDDS & FastDDS

### ISSUE THREAD

**Issue by JaylinYu** [eclipse-cyclonedds/cyclonedds#1477]
First Thank you for this straightforward and efficient DDS implementation. After spending couples of days digging various DDS library, I got some questions regarding the interoperability that I think cyclonedds is the best place to fire.

I manage to get cycloneDDS to talk to FastDDS by manually writing IDL files for them. but encounter the same issues as https://github.com/eclipse-cyclonedds/cyclonedds/issues/1394.  

I can make FastDDS on Linux PC 1 talk to CycloneDDS on Linux PC 2, However, I cannot make two cycloneDDS example work, I assume I made some mistakes, but just don't know exactly where. Is there anything I can check to fix this problem

Considering whole FastDDS project is based on C++, and the same as OpenDDS, It would be much more convenient if there is a whitepaper or handbook that tells what data type is not compatible between C and C++.

Even further, like QoS policy might also be a problem when using different implementations together, Is there any official report/practice about the Interoperability between CycloneDDS & FastDDS & OpenDDS?

**Comment by eboasson** [comment]
@JaylinYu it should work just fine, and certainly there should be no issue whatsoever between languages (that's the whole point of the standardised serialisation format), so:

> Considering whole FastDDS project is based on C++, and the same as OpenDDS, It would be much more convenient if there is a whitepaper or handbook that tells what data type is not compatible between C and C++.

there isn't any, because all supported IDL is supposed to communicate just fine. If it doesn't, it is a bug.

> Even further, like QoS policy might also be a problem when using different implementations together, Is there any official report/practice about the Interoperability between CycloneDDS & FastDDS & OpenDDS?

The tricky QoS policies are the XTypes additions, esp. `data_representation`, because the spec unnecessarily broke backwards compatibility and different vendors have made different choices in dealing with that. The other tricky bit is type information sharing between implementations, where we consistently see other implementations falling short of implementing the spec (though it seems to be improving slowly).

Otherwise, you should be ok as long as you tell Connext to play by the rules for key serialisation and are mindful of the differences in meaning ascribed to the "auto dispose unregistered instances" setting on the data writers. (I'll go into the details if you want me to.)

For the issues you are currently facing, we'd love to help you but it is a bit hard to say something meaningful without further information (which Cyclone examples don't communicate; what did you run into that required you to write IDL by hand, etc.).

**Comment by JaylinYu** [comment]
Sure. Thanks for your reply.
But as far as I check with FastDDS, they are using fastddsgen to parse IDL to C++ code with STL template. I don't find similar tool in CycloneDDS, does it means cycloneDDS will generate type info each time I compile the code?

As for the Issue, I am running on a machine got multiple network interfaces, perhaps that's the reason? Because I don't have same issue with fastDDS

**Comment by eboasson** [comment]
> But as far as I check with FastDDS, they are using fastddsgen to parse IDL to C++ code with STL template. I don't find similar tool in CycloneDDS, does it means cycloneDDS will generate type info each time I compile the code?

We generate code using a tool called `idlc` and it also uses STL templates. If you're using CMake, chances are you're using the `idlcxx_generate` CMake macro that we provide.

> As for the Issue, I am running on a machine got multiple network interfaces, perhaps that's the reason? Because I don't have same issue with fastDDS

That could be, it certainly has caused some problems in the past. Cyclone defaults to using only one interface that it selects using some heuristics, but you can configure it to use a specific interface (or several; see, e.g., https://cyclonedds.io/docs/cyclonedds/latest/config/cyclonedds_specifics.html#network-and-discovery-configuration or https://github.com/eclipse-cyclonedds/cyclonedds#run-time-configuration). It is certainly worth a try, if that doesn't help, then I am afraid it may be time to look at packet captures and/or Cyclone trace files.

**Comment by JaylinYu** [comment]
Thx! Gonna try it first
