### ISSUE TITLE
Timeplan for XTypes Dynamic Language Binding

### ISSUE THREAD

**Issue by reasokde** [eclipse-cyclonedds/cyclonedds#1482]
In the release notes of 0.9 it writes, that XTypes Dynamic Language Binding is not supported.
Is there in general a plan for supporting it? If so, when will it be?

kr, Robert.

**Comment by eboasson** [comment]
We had hopen to get away with not supporting it, because that API is not nearly as nice as what we can do in Python, but too many people have expressed a need for it. We have decided to give some priority to doing "an" API for this, because this is needed for ROS 2's type evolution plans.

We also haven't decided yet whether or not we're willing to implement the OMG spec: those tend to be woolly and not-so-nice. Would it be important for you whether the interface follows the OMG spec or not?

Looking at the schedule, while before the end of the year would be nice, with the holidays that's probably a bit over optimistic ... Aiming for mid-Q1 2023 seems more reasonable.

**Comment by reasokde** [comment]
Of cause, it would be nice, if cyclone conformed with the spec. I not sure whether it is a must for me - I tend to no.
