### ISSUE TITLE
Memory leak when ddsi_serdata.statusinfo contains NN_STATUSINFO_UNREGISTER

### ISSUE THREAD

**Issue by binbowang1987** [eclipse-cyclonedds/cyclonedds#1487]
I found `whc_idxnode` refed `ddsi_tkmap_instance`, but the refed `ddsi_tkmap_instance` was not unrefed when deleting `whc_idxnode`. As `ddsi_tkmap_instance` is not unrefed, it will never be freed. So, this may lead to a memory leak of `ddsi_tkmap_instance`.

`ddsi_tkmap_instance`refed here when creating `whc_idxnode`.
https://github.com/eclipse-cyclonedds/cyclonedds/blob/9995905bce6c4cf9f740d6438bbf7fcfd1c83dfd/src/core/ddsc/src/dds_whc.c#L1346-L1357

`whc_idxnode`deleted here, but `ddsi_tkmap_instance` is not unrefed.
https://github.com/eclipse-cyclonedds/cyclonedds/blob/9995905bce6c4cf9f740d6438bbf7fcfd1c83dfd/src/core/ddsc/src/dds_whc.c#L1279-L1295

**Comment by eboasson** [comment]
😳 🙈 😔

@binbowang1987 thank you very much from a very embarrassed me!

I'll do a PR (probably tomorrow), but this is what I think is the change:
```diff
diff --git a/src/core/ddsc/src/dds_whc.c b/src/core/ddsc/src/dds_whc.c
index 9694ba35b..deb22abb7 100644
--- a/src/core/ddsc/src/dds_whc.c
+++ b/src/core/ddsc/src/dds_whc.c
@@ -520,7 +520,10 @@ void whc_default_free (struct ddsi_whc *whc_generic)
   struct ddsrt_hh_iter it;
   struct whc_idxnode *idxn;
   for (idxn = ddsrt_hh_iter_first (whc->idx_hash, &it); idxn != NULL; idxn = ddsrt_hh_iter_next (&it))
+  {
+    ddsi_tkmap_instance_unref (whc->tkmap, idxn->tk);
     ddsrt_free (idxn);
+  }
   ddsrt_hh_free (whc->idx_hash);
 
   {
@@ -667,6 +670,7 @@ static void free_one_instance_from_idx (struct whc_impl *whc, ddsi_seqno_t max_d
       }
     }
   }
+  ddsi_tkmap_instance_unref (whc->tkmap, idxn->tk);
   ddsrt_free (idxn);
 }
 
```
I'm not doing a PR right away, in part because I tried it out on a copy of #1483, which with a bit of luck will be merged tomorrow as well, but also because I want to see if I can replace the `unref` on shutdown https://github.com/eclipse-cyclonedds/cyclonedds/blob/d37952bd64007e5412f1a1eb734dbefc645086cf/src/core/ddsi/src/ddsi_tkmap.c#L108 with an assert that the table is empty. It should be, and with this change it is at least in the simple case that I tried.

**Comment by binbowang1987** [comment]
Yes, I agree with you, thank you for great work.
