### ISSUE TITLE
symbol_export can not find ddsi_serdata_unref in windows（compile with mingw64）

### ISSUE THREAD

**Issue by johnflj** [eclipse-cyclonedds/cyclonedds#1497]
![image](https://user-images.githubusercontent.com/103733687/203754752-4239660e-a148-4eb2-bbb9-b8266febfda5.png)
hello，i meet a prolem:
symbol_export can not find ddsi_serdata_unref in windows（compile with mingw64）
is it a problem？

**Comment by eboasson** [comment]
> symbol_export can not find ddsi_serdata_unref in windows（compile with mingw64）
> is it a problem？

Yes, because I don't know why it wouldn't be able to find it 😂 I think I once managed to do a mingw64 build on an old Windows PC I have, I'll see if I can give it a try.

Practically speaking, if the only thing not building is `symbol_export_test.exe`, then just do `make -k` so it continues past the error and use it. We — well, @dpotman, really — have done a lot of work to stop exporting all symbols from the library, and this test we added to check that all things that we expect to be exported really are exported, and also that nothing that we *don't* expect to be exported is added by accident. In other words, a very simplistic but very useful ABI stability check.

(`ddsi_serdata_unref` is an inline function for which a regular function definition should be defined and exported as well, but maybe on mingw64 these things get blurry and the tooling keels over?)
