### ISSUE TITLE
IOS Support

### ISSUE THREAD

**Issue by jc211** [eclipse-cyclonedds/cyclonedds#1508]
Hi, does cyclonedds compile for ios?

**Comment by eboasson** [comment]
I once did that, but I had difficulty getting CMake to generate what I needed and manually constructed an XCode project instead, and that obviously didn't make it into the repository. (No doubt this is because *my* brain is incompatible with CMake.)

We're perhaps using a few more functions in the OS, but I bet they're all optional, so I see no reason why it wouldn't work today if you're willing to put some effort into getting the build process to do something at all.

I could probably salvage the test application (which was somewhat compatible with the "shapes" demo that various DDS vendors use — I think some kind souls even made one for Cyclone, but it is not part of the Cyclone repositories), but I am sure that you're not asking for information on building an ios application, only on building Cyclone for ios 😂

**Comment by jc211** [comment]
Would be great to see the test application! 

Re: Compiling for iOS
This header could not be found https://github.com/eclipse-cyclonedds/cyclonedds/blob/46eda2d7786b55ca9704470b58c15cff3b93621f/src/ddsrt/src/netstat/darwin/netstat.c#L13.

**Comment by eboasson** [comment]
> Re: Compiling for iOS
> This header could not be found [..] `if_types.h` in `netstat.c`

This is really exists only so `ddsperf` can gather some information on network loads, and it is a no-op on some other platforms. So a bit of `#ifdef`ing so that this "netstat" thing gets built on macOS but stubbed on iOS is a perfectly sensible trick. I'd be happy with a PR that does that, too.

> Would be great to see the test application!

I'm sure it won't build or work like this, it is 5 years old! But here it is:

[iosshapes.zip](https://github.com/eclipse-cyclonedds/cyclonedds/files/10139444/iosshapes.zip)

On a side note: as I am a mac user and do all my Cyclone development work on it (except for the rare occasion where I have no choice to use Windows as well as when Linux happens to be too different), and have an iPhone, I'm quite interested in your project ☺️

**Comment by jc211** [comment]
Thanks for your help and for sharing the project! 

I got the library compiling for iOS but haven't integrated it into a project yet. 
FYI: I had to disable this section of the code: 
https://github.com/eclipse-cyclonedds/cyclonedds/blob/7fb79b81456a203d02878aa4f9ef53f60fb202fa/src/ddsrt/src/ifaddrs/posix/ifaddrs.c#L82
since if_media.h does not exist for iOS. 

I'm not sure what impact that has or if there is a better way of doing it. 

I'll update this thread as I progress.

**Comment by jc211** [comment]
I'm also having trouble compiling when ENABLE_SECURITY is on. I get this cmake error: CMake Error: install(EXPORT "CycloneDDS" ...) includes target "ddsc" which requires target "security_core" that is not in any export set.

**Comment by jc211** [comment]
Here is my build code so far:

```
set -e
export ROOT_PATH=$(cd $(dirname $0); pwd)
BUILD=$ROOT_PATH/build

buildLibrary() {
    local BUILT_PRODUCTS_DIR=$1
    cmake -B $BUILT_PRODUCTS_DIR/build -S cyclonedds \
        -G Xcode \
        -D ENABLE_SECURITY=0 \
        -DCMAKE_SYSTEM_NAME=iOS \
        -D BUILD_SHARED_LIBS=NO \
        -D CMAKE_CONFIGURATION_TYPES=Release \
        -D CMAKE_OSX_DEPLOYMENT_TARGET=16.0 \
        -D CMAKE_INSTALL_PREFIX=$BUILT_PRODUCTS_DIR/install
    
    cmake --build $BUILT_PRODUCTS_DIR/build --config Release --target install
}

buildLibrary $BUILD/iphoneos 

xcodebuild -create-xcframework \
-library $BUILD/iphoneos/install/lib/libddsc.a \
-headers $BUILD/iphoneos/install/include \
-output CycloneDDS.xcframework

```

I had to disable this section:
https://github.com/eclipse-cyclonedds/cyclonedds/blob/7fb79b81456a203d02878aa4f9ef53f60fb202fa/src/ddsrt/src/ifaddrs/posix/ifaddrs.c#L82

I also had to comment this line: 
https://github.com/eclipse-cyclonedds/cyclonedds/blob/7fb79b81456a203d02878aa4f9ef53f60fb202fa/src/core/xtests/CMakeLists.txt#L18

Creating the xcframework fails with the following message and I can't figure out why:
error: unable to find any architecture information in the binary at '.../build/iphoneos/install/lib/libddsc.a': Unknown header: 0xb17c0de

**Comment by eboasson** [comment]
> I got the library compiling for iOS but haven't integrated it into a project yet.

🥳

> FYI: I had to disable this section of the code:
> https://github.com/eclipse-cyclonedds/cyclonedds/blob/7fb79b81456a203d02878aa4f9ef53f60fb202fa/src/ddsrt/src/ifaddrs/posix/ifaddrs.c#L82
> 
> since if_media.h does not exist for iOS.
> I'm not sure what impact that has or if there is a better way of doing it.

Nothing to worry about: that code is for determining whether a network interface is a WiFi interface or not.

We learnt the hard way not to blindly trust the "multicast capable" flag from the kernel, because WiFi does support multicast but at a very high risk of losing packets (from my understanding, unicast gets retried by the WiFi hardware, multicast is send and forget, so the slightest bit of interference means it is lost). We do want to use multicast for discovery, and we didn't want to stop using multicast for data on Ethernet ... and so now we guess what type of interface it is.

If that doesn't work (for now) on iOS, well, there's always an override among the gazillion configuration options 😀

**Comment by eboasson** [comment]
> I'm also having trouble compiling when ENABLE_SECURITY is on. I get this cmake error: CMake Error: install(EXPORT "CycloneDDS" ...) includes target "ddsc" which requires target "security_core" that is not in any export set.

That looks like it is caused by `BUILD_SHARED_LIBS=NO`. It is only an "interface library" so I would not have expected a difference depending on whether one builds shared or static libraries, but CMake is of a different opinion. I'm sure we can find a way of fixing that, but for a PoC it shouldn't be a show-stopper.

**Comment by eboasson** [comment]
> Here is my build code so far:
> [...]

Works for me as well! ☺️ Including the error message you quote at the end

> I also had to comment this line:
> https://github.com/eclipse-cyclonedds/cyclonedds/blob/7fb79b81456a203d02878aa4f9ef53f60fb202fa/src/core/xtests/CMakeLists.txt#L18

That thing exists to verify we're not inadvertently adding/removing symbols that are exported by the library. Skipping it seems like the practical thing to do.

> Creating the xcframework fails with the following message and I can't figure out why: error: unable to find any architecture information in the binary at '.../build/iphoneos/install/lib/libddsc.a': Unknown header: 0xb17c0de

Maybe creating a framework requires a `.dylib`? I am just guessing ... but when I try building a dynamic library, I get:
```
/Users/erik/C/IOS/build/iphoneos/build/CycloneDDS.xcodeproj: error: Signing for "ddsc" requires a development team. Select a development team in the Signing & Capabilities editor. (in target 'ddsc' from project 'CycloneDDS')
```

According to [this](https://stackoverflow.com/questions/40664125/cmake-and-code-signing-in-xcode-8-for-ios-projects) you can set the things xcodebuild requires for signing. Not that I know what to put in ...

If I use the Xcode GUI to do the build using the CMake-generated project (instead of trying to do a build using `cmake --build`) I do get a `libddsc.dylib`, and then the `xcodebuild -create-xcframework` step also works (after some fiddling with paths).

So while I don't know exactly how to fix it, it looks fixable 😀

**Comment by jc211** [comment]
I think you only need to sign the target if its an executable or if its dynamic. We can get around that by setting some cmake variables:
```cmake
set(MACOSX_BUNDLE_GUI_IDENTIFIER "com.cyclonedds")
set(CMAKE_MACOSX_BUNDLE YES)
set(CMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_REQUIRED "NO")
set(CMAKE_XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY "")
```

 I've been basically replicating what DimaRU did for FastDDS: https://github.com/DimaRU/FastDDSPrebuild. He compiles the static libraries into an xcframework so it should be possible. If we can do that, then we can release a swift package for cyclonedds that works in the swift package manager. 

I was also under the impresssion that you cannot dynamically link libraries in iOS. I'll have to test that. 

Here are some other people having problems with this xcode framework error: https://developer.apple.com/forums/thread/714324 

Most of the threads I've found just report the error but no one has a resolution to it or even mentions what it even means. 

I'll try and use the C library directly and see if that works.

**Comment by jc211** [comment]
Happy days. To get the xcframework to work you need to disable link time optimization when building. New CMake instructions are:

```cmake
set -e
export ROOT_PATH=$(cd $(dirname $0); pwd)
BUILD=$ROOT_PATH/build

buildLibrary() {
    local BUILT_PRODUCTS_DIR=$1
    cmake -B $BUILT_PRODUCTS_DIR/build -S cyclonedds \
        -G Xcode \
        -D ENABLE_SECURITY=0 \
        -D ENALBE_LTO=0 \
        -D CMAKE_SYSTEM_NAME=iOS \
        -D BUILD_SHARED_LIBS=NO \
        -D CMAKE_CONFIGURATION_TYPES=Release \
        -D CMAKE_OSX_DEPLOYMENT_TARGET=16.0 \
        -D CMAKE_INSTALL_PREFIX=$BUILT_PRODUCTS_DIR/install
    
    cmake --build $BUILT_PRODUCTS_DIR/build --config Release --target install
}

buildLibrary $BUILD/iphoneos 

xcodebuild -create-xcframework \
-library $BUILD/iphoneos/install/lib/libddsc.a \
-headers $BUILD/iphoneos/install/include \
-output CycloneDDS.xcframework
```

**Comment by jc211** [comment]
Everything seems to be working well in iOS so far. Do you have any idea how I might be able to pass the xml config file to the app? Would that even be possible?

**Comment by eboasson** [comment]
> Do you have any idea how I might be able to pass the xml config file to the app? Would that even be possible? At the moment, cyclone is defaulting to using the cellular interface. Disabling cellular forces it to choose wifi.

What I did back in the day in my PoC application was to add the XML in the application bundle and then get the path via something that seemed to work and modify the environment:
```
    NSString *uri = [@"file://" stringByAppendingString:[[NSBundle mainBundle] pathForResource:@"config" ofType:@"xml"]];
    setenv("CYCLONEDDS_URI", [uri UTF8String], 1);
    setenv("PEER", [address UTF8String], 1);
```

Since then, Cyclone has gained `dds_create_domain` where you can pass in the configuration XML as a parameter and that should solve your problem more easily, I'd think. It so happens I wrote something about in response to a question (that I misunderstood, but that doesn't affect the relevance of that answer for your question): https://github.com/eclipse-cyclonedds/cyclonedds/issues/1513#issuecomment-1343005648

**Comment by jc211** [comment]
The dds_create_domain works beautifully

**Comment by jc211** [comment]
When running idlc to generate a c file from an idl, we get a struct called HelloWorldData_desc. Is it possible to have idlc also create and export a pointer to that struct? That would make the interop with swift a lot cleaner:
```swift
 topic = dds_create_topic(participant!, HelloWorldData_desc_ptr, topic_name, nil, nil)
```

rather than 

```swift
withUnsafePointer(to: HelloWorldData_desc) { desc in
 topic = dds_create_topic(participant!, desc, topic_name, nil, nil)
}
```

Its always possible to add the pointers in the bridging header which is what I'm currently doing. But it might be something to consider to take advantage of the implicit conversions in swift.

**Comment by eboasson** [comment]
That's a reasonable feature to add. Easy enough, too: https://github.com/eclipse-cyclonedds/cyclonedds/blob/7fb79b81456a203d02878aa4f9ef53f60fb202fa/src/tools/idlc/src/types.c#L239 and https://github.com/eclipse-cyclonedds/cyclonedds/blob/7fb79b81456a203d02878aa4f9ef53f60fb202fa/src/tools/idlc/src/types.c#L323 are the places where the `dds_topic_descriptor_t` gets generated.

It might be nice to always generate it, but it'd also be possible to add an option to only generate it if you require it, see, e.g., https://github.com/eclipse-cyclonedds/cyclonedds/blob/7fb79b81456a203d02878aa4f9ef53f60fb202fa/src/tools/idlc/src/generator.c#L358, https://github.com/eclipse-cyclonedds/cyclonedds/blob/7fb79b81456a203d02878aa4f9ef53f60fb202fa/src/tools/idlc/src/generator.c#L401 and https://github.com/eclipse-cyclonedds/cyclonedds/blob/7fb79b81456a203d02878aa4f9ef53f60fb202fa/src/tools/idlc/src/types.c#L249

I'd be happy to consider a PR (which is probably the quicker route than me doing it, given that I have to start paying attention to a meeting again! 😂)

**Comment by jc211** [comment]
Made a swift package for this here: https://github.com/jc211/CycloneDDSPrebuild

**Comment by jc211** [comment]
Here is an example of how CycloneDDS can be used in Swift for anyone reading this thread: https://github.com/jc211/NeRFCapture

Thanks @eboasson  for all your help. This library is quite streamlined and is a pleasure to use. 

I will close the thread although note that I haven't been able to compile this with security features yet.
