### ISSUE TITLE
dds_writecdr and dds_takecdr usage.

### ISSUE THREAD

**Issue by stillsimon** [eclipse-cyclonedds/cyclonedds#151]
Hi, I find there are dds_writecdr and dds_takecdr API in dds.h. How can I use them and how to create topic when I want to send cdr message? Is there any example of it? Thank you!

**Comment by eboasson** [comment]
One of the reasons those two exist are for ROS2 support, but there are currently no stable interfaces to construct or interpret the "serdata" type, and the header files that you need are not yet getting installed. So at the moment, the only thing you can do with them without some hacks is calling ``takecdr`` on a reader and then feeding that data to another writer via ``writecdr``.

Soon there'll be a pull-request that adds the header files in util and core/ddsi to the installed set of header files, and then it should become a bit easier. Once that's done I'll update https://github.com/atolab/rmw_cyclonedds to have at least my PoC-level support for ROS2 back up and running. (That thing currently uses the old types and besides uses copy-pasted function and type declarations ... that was a quick hack.)

If you look closely, there are also some cases not quite supported by those two functions, but that's a simple case of me being lazy while doing a PoC at some point (even before the creation of the Eclipse project). They will progress (at some point) to being properly supported interfaces.

That said, I'm somewhat annoyed by #95 still being open and having a 99% fix for it ... so that work I need to complete first.

**Comment by stillsimon** [comment]
Oh cool, just keep your pace!

**Comment by eboasson** [comment]
Sorted ... since about a week, https://github.com/atolab/rmw_cyclonedds seems to work well with ROS2 Dashing, and it partially relies on these functions. The interface is still evolving, so an update of Cyclone might break things a bit ... but not in too significant a manner. In between this RMW layer and the explanation on #162, I think it best to close this issue.
