### ISSUE TITLE
IPC communication

### ISSUE THREAD

**Issue by reasokde** [eclipse-cyclonedds/cyclonedds#1521]
Dear yous.
I wonder if there are any options to let two local instances on a Linux computer communicate by IPC other than using Iceoryx? Can I program my own data backend using unix domain sockets while leaving the discovery to the standard method?
kr, Robert.

**Comment by eboasson** [comment]
Currently you can't easily plug in another backend in the same manner as Iceoryx, but that'll change going forward. The hard work's been done, it is just stuck with me somewhere primarily because it changed some stuff in externally visible things, and that would unnecessarily break backwards compatibility.

That said, adding unix domain sockets support should be fairly easy (it is not unlike UDP/TCP, after all). While I have never tried running two protocols in parallel, the code has slowly been evolving to allow that. I'd wager that if you'd "somehow" make an interface using UDP and another one using UDS during network interface selection, it'll magically spring to life.

**Comment by reasokde** [comment]
Thanks for the support.
