### ISSUE TITLE
Building with cmake in python setup file misses symbol link file

### ISSUE THREAD

**Issue by hongdami** [eclipse-cyclonedds/cyclonedds#1527]
I try to build cyclonedds in a python wheel. I wrote a setup.py to install the cyclonedds by cmake. But I cannot copy the symbol link for the library(The symbol link files will loss) to the python install path

It seems that there isn't a CMake args to avoid building/installing symbol link.

Can you provide an option to build skip the namelink?

A cmake file is as  this:
---------------start------------------
cmake_minimum_required(VERSION 3.14)
include(ExternalProject)
ExternalProject_Add(
  cyclonedds
  GIT_REPOSITORY https://github.com/eclipse-cyclonedds/cyclonedds.git
  GIT_TAG 0.10.2
  SOURCE_DIR ${CMAKE_BINARY_DIR}/cyclonedds
  CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${COMMON_DDS_DESTINATION}
)
ExternalProject_Add(
  cyclonedds-cxx
  GIT_REPOSITORY https://github.com/eclipse-cyclonedds/cyclonedds-cxx.git
  GIT_TAG 0.10.2
  SOURCE_DIR ${CMAKE_BINARY_DIR}/cyclonedds-cxx
  CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${COMMON_DDS_DESTINATION}
)
-----------------end------------------

**Comment by poetinger** [comment]
@hongdami Are you still having an issue with this? If you did find a work around, or added something to cmake that is useful, feel free to open a pull request. We always appreciate contributions (especially since we have been extremely busy lately) 😃 I will close this for now, since there has not been any activity for a long time. If you are still having issues please don't hesitate to re-open this issue.
