### ISSUE TITLE
Build cyclone DDS for android 

### ISSUE THREAD

**Issue by easonccwang** [eclipse-cyclonedds/cyclonedds#1537]
Follow[ Android port](https://github.com/eclipse-cyclonedds/cyclonedds/tree/master/ports/android) and modify symbol_export.c as below

![image](https://user-images.githubusercontent.com/13759547/211445486-d3f41f6d-516f-407a-b360-92e0f88fc9bf.png)

`mkdri build.android
 cd build.android
 cmake -DCMAKE_TOOLCHAIN_FILE=/home/eason/Android/Sdk/ndk/25.1.8937393/build/cmake/android.toolchain.cmake - DANDROID_ABI=arm64-v8a -DANDROID_NATIVE_API_LEVEL=28 ..`

adb push lib/libddsc.so to /system/lib64
adb push bin/symbol_export_test to /system/bin

![image](https://user-images.githubusercontent.com/13759547/211445714-eed534d9-e7cc-4470-b174-226a9e92aa7c.png)
Could you help ?

Thanks,

**Comment by eboasson** [comment]
Hi @easonccwang,

It is hard to say something sensible: the "symbol_exp: selected interface ..." line means it is waking up, so presumably it crashes somewhere in the startup code. If I know *where* in that code it crashes, perhaps I can make an educated guess. Is there a way you can attach a debugger and get some more information about where it crashes?

On a side note: `symbol_export` is not an actual application to be executed, it exists solely to check that we don't accidentally stop exporting a symbol from the library. That's why its main function simply consists of a function call to each exported function with dummy parameters — and all we require is that the compiler/linker accepts it. Personally, I would not use it as a basis for a new application.

**Comment by easonccwang** [comment]
Hi @eboasson  
Could you help to guide how to catch cyclone DDS log?
Thanks,

**Comment by eboasson** [comment]
Hi @easonccwang, you can enable the trace by setting `<Tracing><Category>trace</Category></Tracing>` in the configuration. By default it'll then write it to a file name `cyclonedds.log`. If you add `<OutputFile>stdout</OutputFile>` it'll write it to the standard output instead, and if neither is an option, you can have it call a callback function instead (but I imagine that won't be necessary).

Hopefully this will give a bit more information on where it crashes. Some platforms (like macOS) write crash information to a standard place. I know some Linux distributions do something similar by default, so there is also the possibility that the system already recorded a crash log. I just don't know where to go look for that in Android.

Finally, I do expect it is possible to attach `gdb`, but again, I don't know how that works if you're dealing with Android.

**Comment by easonccwang** [comment]
Hi @eboasson 
After set correct ANDROID_ABI, it can work well.
Thanks.

**Comment by eboasson** [comment]
Good to hear that!

I didn't even know that exists ... hopefully I'll remember checking the Android ABI next time someone runs into such a strange problem. I assume it is ok if I close it now, if not feel free to reopen it or to create a new issue.
