### ISSUE TITLE
Memory leak when cdr failed

### ISSUE THREAD

**Issue by skysky97** [eclipse-cyclonedds/cyclonedds#1540]
When serialization failed (for example a boolean object has a value of 2 other than 0/1), `dds_write` returns error code `-3`. If I ignore this error and go on calling `dds_write`, memory comsumption grows.

After debug with valgrind, it shows `serdata_default_from_sample_cdr_commo` has memory leak. When `dds_stream_write_sample` returns NULL, the ostream buffer or the serdata object is not freed.

**Comment by eboasson** [comment]
Thanks for catching that!

The fix is quite [obvious](https://github.com/eclipse-cyclonedds/cyclonedds/compare/master...eboasson:cyclonedds:fix-memleak-write-invalid-data?expand=1) but now my reproducing test fails on `dds_write` not giving return code -3 on only one platform and that all seems rather platform independent code, so I'll need to dig into it a bit further before doing a PR.
