### ISSUE TITLE
Malformed RTPS submessage can trigger heap buffer overflow in ddsi_plist_quickscan

### ISSUE THREAD

**Issue by squizz617** [eclipse-cyclonedds/cyclonedds#1555]
Hi. ASAN reports a heap buffer overflow in `ddsi_plist_quickscan` while processing a malformed RTPS submessage. Could you have a look? Thank you.

## Environment
* CycloneDDS 0.10.2 (9995905bce6c4cf9f740d6438bbf7fcfd1c83dfd)
  * Compiled with `clang-12` and ASAN
* Ubuntu 20.04

## Reproduction
* Get CycloneDDS 0.10.2
```
$ git clone https://github.com/eclipse-cyclonedds/cyclonedds.git -b 0.10.2 ~/cyclonedds-0102-clang
```
* Modify CMakeLists.txt to enable ASAN
```
$ cd ~/cyclonedds-0102-clang
$ sed -i '143 i add_compile_options(-fsanitize=address)\nadd_link_options(-fsanitize=address)' CMakeLists.txt
```
* Build
```
$ mkdir build
$ cd build
$ export CC=clang CXX=clang++
$ cmake -DBUILD_IDLC=ON -DBUILD_TESTING=ON -DBUILD_SHARED_LIBS=OFF -DBUILD_EXAMPLES=YES -DENABLE_SECURITY=NO -DENABLE_SSL=NO ..
$ make -j16
```
* Download and compile PoC
```
$ cd /tmp
$ wget https://gist.githubusercontent.com/squizz617/2adceaff36bea11af177b1b0c9d1e291/raw/899f18685c7764b6f7cc62caf66ee0600a158604/poc_cyclonedds_01.c
$ wget https://gist.githubusercontent.com/squizz617/bc090d7b2c8890c6c7434e6ed3e72e59/raw/5c47bf2a0b3bb5bddad0a7aa8aeed74773d5e4ad/Makefile_poc_cyclonedds_01 -O Makefile
$ make cyclonedds
```
* Run
```
$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/cyclonedds-0102-clang/build/lib
$ ./poc_cyclonedds_01
=================================================================
==2283624==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x7f2591afe830 at pc 0x0000005746ce bp 0x7fff5a1b9560 sp 0x7fff5a1b9558
...
```

## Full ASAN report
```
=================================================================
==2283624==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x7f2591afe830 at pc 0x0000005746ce bp 0x7fff5a1b9560 sp 0x7fff5a1b9558
READ of size 2 at 0x7f2591afe830 thread T0
    #0 0x5746cd in ddsi_plist_quickscan /home/seulbae/cyclonedds-0102-clang/src/core/ddsi/src/ddsi_plist.c
    #1 0x4f9d45 in validate_Data /home/seulbae/cyclonedds-0102-clang/src/core/ddsi/src/q_receive.c:410:16
    #2 0x4f9d45 in handle_submsg_sequence /home/seulbae/cyclonedds-0102-clang/src/core/ddsi/src/q_receive.c:3107:19
    #3 0x4ef873 in handle_rtps_message /home/seulbae/cyclonedds-0102-clang/src/core/ddsi/src/q_receive.c:3214:7
    #4 0x4c8f5c in main /tmp/poc_cyclonedds_01.c:117:3
    #5 0x7f2595145082 in __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16
    #6 0x41c5cd in _start (/tmp/poc_cyclonedds_01+0x41c5cd)

0x7f2591afe830 is located 0 bytes to the right of 1048624-byte region [0x7f25919fe800,0x7f2591afe830)
allocated by thread T0 here:
    #0 0x49782d in malloc (/tmp/poc_cyclonedds_01+0x49782d)
    #1 0x53bcc1 in ddsrt_malloc_s /home/seulbae/cyclonedds-0102-clang/src/ddsrt/src/heap/posix/heap.c:20:10
    #2 0x53bcc1 in ddsrt_malloc /home/seulbae/cyclonedds-0102-clang/src/ddsrt/src/heap/posix/heap.c:26:15

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/seulbae/cyclonedds-0102-clang/src/core/ddsi/src/ddsi_plist.c in ddsi_plist_quickscan
Shadow bytes around the buggy address:
  0x0fe532357cb0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe532357cc0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe532357cd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe532357ce0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe532357cf0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0fe532357d00: 00 00 00 00 00 00[fa]fa fa fa fa fa fa fa fa fa
  0x0fe532357d10: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0fe532357d20: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0fe532357d30: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0fe532357d40: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0fe532357d50: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==2283624==ABORTING
```

## Analysis
It seems that the while loop at `src/core/ddsi/src/ddsi_plist.c:3350` loops infinitely while parsing a sequence of invalid parameters.

Thank you.

**Comment by eboasson** [comment]
I've adapted your test to the current master (that was easy, all I needed was to update it based on the [message fuzzer](https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/fuzz/fuzz_handle_rtps_message/fuzz_handle_rtps_message.c) we use on OSS-Fuzz), and I noticed that line 117 of your reproducer actually passes an uninitialised `size` into `ddsi_handle_rtps_message`.

So I played around a bit and found that reproducing the ASAN error requires me to pass a value for the `size` parameter that is larger than the input buffer (`gv.config.rbuf_size`). So for this input (with hand-decoding added):

```
     00     0x52, 0x54, 0x50, 0x53, // RTPS
     04     0x02, 0x04, 0x01, 0x10, // version 2.4, vendor 1.16
     08     0x01, 0x03, 0x3c, 0xec, // GUID prefix 0..3
     12     0xef, 0x6f, 0x12, 0xdb, // GUID prefix 4..7
     16     0xe5, 0xa5, 0xc3, 0x32, // GUID prefix 8..11
     20     0x15, 0xf2, 0x00, 0x00, // DATA; flags = 0xf2 = inline QoS present, big-endian + some undefined flags, octetsToNextHeader = 0
     24     0x00, 0x00, 0x00, 0x00, // extraFlags = 0, octetsToInlineQos = 0
     28     0x00, 0x13, 0x70, 0x00, // readerId
     32     0x00, 0x00, 0x00, 0x00, // writerId
     36     0x01, 0x00, 0x00, 0x00, // sequenceNumber (some of it, anyway)
     40     0
```

The `octetsToNextHeader` = 0 means this DATA sub message ends at the end of the RTPS message. The `octetsToInlineQoS` = 0 in combination with the "inline QoS present flag" means that the Inline QoS starts at offset 28.

The size passed in to the `nn_rmsg_setsize` (line 116) is only used in the buffer administration, the size used in the message interpretation is the (uninitialised) one passed into `ddsi_handle_rtps_message` (line 117). To be honest, I am now wondering why I didn't just use the size from line 116, but that's how it is. As a consequence, it passes the first check because enough bytes are (claimed to be) available for a full DATA sub message header.

With a very large message and `octetsToNextHeader` that basically allows `ddsi_plist_quickscan` to scan a huge section of memory. It starts scanning at offset 28, which of course is totally weird (it's where the reader id is, not where the inline QoS would actually start) but it is not forbidden by the spec. I suppose there might even be a case where the beginning of the inline QoS (or the payload) happens to match the bytes starting at that offset, so ... fine, we'll try.

`0x00, 0x13, 0x70, 0x00` maps to an ignored parameter id (0x13), with a value size of 0x7000. The limit is far away, so it simply continues scanning at offset 28704. Then what will happen?

In my case, the remainder of the allocated buffer is all zero. Not so strange, considering that we've hardly done anything and made only a handful of allocations, and so this probably comes from pages freshly allocated (and thus zeroed) by the OS kernel. Parameter id 0 is for padding, and because the number of octets to the next parameter is also 0, the rest of the buffer is filled with minimally-sized "pad" parameters.

And then, because the limit is bogus, it continues scanning all the way until it reaches the end of the buffer and ASAN kills it because of a heap buffer overflow.

I'd be interested whether you see the same behaviour when you replace the uninitialised `size` parameter with a few interesting different sizes (say, actual size, something large enough to actually contain the full DATA sub message but not ridiculously large, some values around the 28704 point, &c.).

From this analysis, it looks like this is an artefact of the test program, not a bug in the Cyclone code. That said ... this looks like some message that came out of a fuzzer and this uninitialised `size` parameter may well have been a small copy-paste error in translating a fuzzer test case into something that can be shared. Because of that I'll keep the issue open for now 🙂

**Comment by squizz617** [comment]
Hi @eboasson, I really appreciate your quick response and deep dive. 

> line 117 of your reproducer actually passes an uninitialised `size` into `ddsi_handle_rtps_message`

Ah, you're right. I've totally missed it. With `size` initialized to the length of the message / buffer, this issue is gone. Also, since it's unlikely that `sz` remains uninitialized in `do_packet` before invoking `ddsi_handle_rtps_message`, I think this issue won't be reproducible in real use cases. Thank you!

**Comment by eboasson** [comment]
Thanks for confirming!
