### ISSUE TITLE
How to test writer_data_lifecycle?

### ISSUE THREAD

**Issue by jwcesign** [eclipse-cyclonedds/cyclonedds#156]
Hi,
Recently, I want to test writer_data_lifecycle, but I am confused about this qos specification. Can u give me one example to show how to use this and what;s the phenomenon of this qos?

**Comment by eboasson** [comment]
Hi,

The only "writer data lifecycle" setting is "auto-dispose unregistered instances" … so …

The DDS specification says that each time you write or dispose a sample (so call ``dds_write``, ``dds_dispose`` or ``dds_writedispose``), your writer gets a "registration" for the instance with the key values you just wrote/disposed. You could think of the instance as an object that is modelled in the system. These objects can be quite tangible: if you look at [Spencer](https://www.youtube.com/watch?v=ir_Ku4rCOO8), a robot from KLM at Schiphol (not that I have ever seen it myself, despite having passed through Schiphol many times 🤔), it needs to keep track of all the people around it, so it seems reasonable to assume that it will have an "instance" for each person in its vicinity and that its sensors publish samples that describe the location and movement of each person.

The idea is twofold: partly it is the "meaning" for the application, and partly it is what the DDS implementation should do with it.

* That "meaning" is simple: having a "registration" means the writer has the _intent_ of publishing more samples for that instances in the future (whether it actually does so is a completely different subject);
* What DDS does with it is to keep the information on the instance around if there is still a "registration". One of the things you can do this way is use ``dds_take`` to take the incoming updates, while knowing that DDS will keep track of the most recent instance taken. This for example prevents older data (by timestamp) from being delivered to the application if the "destination order" QoS is set to "by source timestamp".

It is therefore quite useful, though perhaps not quite as useful as it seems at first, because the usefulness really depends on limitations in using the sample info in a query condition. But I digress …

The ``dds_dispose`` operation, or more precisely, the "not alive disposed" state of an instance has quite the opposite meaning: it generally means the application has no further use for that instance. In the Spencer example, when someone it observed disappears from view, that person is no longer relevant to it and so it can be removed from the system. The "disposed" state encodes this. (I generally view it as a indication that the data may be garbage collected.)

Then, there is the ``dds_unregister_instance`` operation, which drops a registration. Technically it only means the writer informs DDS that there will be no updates forthcoming and no information on the instance needs to be kept once there are no samples left. (At this point, order reversal with old timestamps alluded to above becomes a possibility.) When a writer crashes or gets disconnected, DDS automically unregisters all the data on its behalf.

But when would a writer actually call ``dds_unregister_instance``?

Usually it is because the object is actually end-of-life. So, you usually see ``dispose`` and ``unregister`` in pairs. Thhe "auto-dispose unregistered instances" simply makes this easier. (One could wonder why it isn't the other way around: "auto-unregister disposed instances" … but it isn't.) In Cyclone, it does this regardless of why the unregister happened — you can call ``dds_unregister_instance``, can kill the process or pull the plug, it doesn't matter. [*]

For volatile or transient-local data (which are the only ones implemented by Cyclone today), the difference between disposing something and unregistering something is pretty small. You can easily deal with it either way in the application logic. The real difference comes when you use "transient" or "persistent" data: the only transient or persistent data that gets removed from the system are the instances that are in the "not alive disposed" state.

Then again, auto-dispose on transient data is quite meaningless … why would you require the data to remain available even when the writer is no longer there, if you then simultaneously state that the data can be thrown away when the writer disappears …

So that's what it does. I'm sure you have no use for an example that shows you how to set the QoS … and a meaningful example would be quite involved. If you'd like to play with it, ``bin/pubsub`` could be your friend: ``-qw:u=y`` enables the "auto dispose" setting. Then you can write with "w" followed by a key value, dispose with: "d" followed by a key value, unregister with "w" — or you can kill the process with ``^C``.

Does that help … or have I done another one of my TL;DR ones that don't actually answer the question … ?

[*] There'll probably a subtle change in the behavior, but only when you have multiple writers having registrations for the same instance. That's pretty unusual, but we need to worry about the edge cases as well …
