### ISSUE TITLE
Best-Effort reader lose 1 more samples when network packet lost occurs

### ISSUE THREAD

**Issue by skysky97** [eclipse-cyclonedds/cyclonedds#1561]
When writer writes samples (1, 2, 3, 4), while sample 2 was lost due to network packet lost. The unique best-effort reader only receives sample 1 and sample 4. The log file shows sample 3 is discarded as "too old". Is this the expected behavior?

Other qos settings are default. 

And when I debug the code of reorder part, I found `nn_reorder_rsample` always called twice. The first call it returns 1 sample in chain and try deliver data to readers and this time it only deliver data to so called SYNC readers. My best-effort reader seems to be a out-of-sync reader and don't get the sample. The second call it returns -1 which means too old. After that it tries to update sync state of reader, but the state always stays at out-of-sync as have_seen_heartbeat is 0. So I searched have_seen_heartbeat and found it is set to 1 at handle_Heartbeat but only for reliable readers. Is a best-effort reader always out-of-sync?

**Comment by eboasson** [comment]
Good questions ...

I dare say it wasn't my intent that best-effort readers are always out-of-sync. Going from out-of-sync to in-sync by design requires catching up with historical data (or similar), and doing that requires a reliable reader because of the way the protocol is designed. That means a best-effort reader can never become "in sync" and so has to start out that way.

I would therefore expect it to be taken care of here: https://github.com/eclipse-cyclonedds/cyclonedds/blob/de27a112cf673d9479d096ce4a9ac17f9d280434/src/core/ddsi/src/ddsi_endpoint_match.c#L1006, by also unconditionally setting it to `PRMSS_SYNC` if `!rd->reliable`.

Would you be ok with trying that out? You seem to be able to reproduce it quickly, and so if you can confirm that this indeed solves the problem, then doing a PR will be very easy.

**Comment by skysky97** [comment]
Yes, I had tested it and it did solve the problem.
