### ISSUE TITLE
discovery of RTPS

### ISSUE THREAD

**Issue by wjbbupt** [eclipse-cyclonedds/cyclonedds#1567]
The automatic discovery of RTPS, in the actual test on two computers:
1. It can only be discovered by configuring ip or binding network card
2. If the ip address is not configured, it cannot be found;
My understanding is that cyclonedds qos only supports static discovery and does not support RTPS automatic discovery. Is that right?

**Comment by eboasson** [comment]
I don't know why you closed it, I presume because you found the answers to your questions before I got around to responding, but for anyone else who lands here:

1. Yes, you obviously need to have a working network between the two computers to carry the RTPS messages;
2. Cyclone DDS fully supports RTPS dynamic discovery.
