### ISSUE TITLE
assert(i < x->n_readers) in local_reader_ary_remove

### ISSUE THREAD

**Issue by stillsimon** [eclipse-cyclonedds/cyclonedds#159]
Hi, When I'm using cyclone in multiple nodes, sometimes the dds will abort in 
```
assert(i < x->n_readers);
```
in q_entity.c. 
In which situation will violate this assertion? Thanks!

**Comment by eboasson** [comment]
I'm lucky that that assertion is unique :smile: (in other words, next time, please give the line number as well)

It will be violated if you try to unmatch the same reader/proxy-writer pair twice: the first time will completely remove the reader from the proxy-writer, the second time will incorrectly redo some of it once again because it doesn't make _all_ the work conditional upon the reader being among those in the proxy-writer's set of matching readers.

Doing it twice is possible, because the matching/unmatching is not single-threaded by design (I've wondered whether for various reasons it would not be better to just serialise them all, though not because of this particular issue), and so if you delete the reader at the same time the proxy-writer is being deleted, you can have two threads doing this at the same time.

If it happens also without both entities being deleted simultaneously, then my understanding of conditions is still incomplete.

**Comment by eboasson** [comment]
I'm pretty sure this is fixed — if not please reopen.
