### ISSUE TITLE
How to get participant's info in SPDP

### ISSUE THREAD

**Issue by neptune-wind** [eclipse-cyclonedds/cyclonedds#1590]
Hello, 

I want to know a particpant's infomation when it's status changes in the same domain. the infomation includes GUID, state of this participant such as DISCOVERED/REMOVED. Does CycloneDDS provide a callback?

Thanks!

**Comment by eboasson** [comment]
Hi @neptune-wind, it does.

I think what you want to do is create a data reader for the (pre-defined) `DDS_BUILTIN_TOPIC_DCPSPARTICIPANT` topic, and then monitor that for new data and for "disposes" (the "dispose" operation indicates that some object has reached the end of its lifecycle, and so roughly corresponds to removing data). Once you have this data reader, you can simply read/take every now and then, or you can have a waitset block until new data is available, or install a listener that triggers when new data is available.

In terms of examples, there is not a really nice example just for this particular topic, but there is [one](https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/examples/listtopics/listtopics.c) that looks at the built-in topics describing readers and writers for a different reason. You could also have a look at "ddsperf", which does monitor participants, just start at
https://github.com/eclipse-cyclonedds/cyclonedds/blob/f663cb17460c1202b8b069173c8fb786346623d9/src/tools/ddsperf/ddsperf.c#L2315
and follow the thread — that is, look at what it does that involves `rd_participants`, such as setting a listener at https://github.com/eclipse-cyclonedds/cyclonedds/blob/f663cb17460c1202b8b069173c8fb786346623d9/src/tools/ddsperf/ddsperf.c#L2328

**Comment by neptune-wind** [comment]
Thanks for you reply.

I try to create a data reader for `DDS_BUILTIN_TOPIC_DCPSPARTICIPANT` topic, I take `dds_builtintopic_participant_t` msgs from it and I get some participants' GUID when they are created, but no msgs received when they destroyed. How could monitor the data for "disposes", timing of participants' destruction is what I need.

Here is my code:
```
dds_builtintopic_participant_t *builtin_msg;
void *builtin_samples[MAX_SAMPLES];
dds_sample_info_t builtin_infos[MAX_SAMPLES];
dds_return_t builtin_rc;

// ! Create builtin topic reader to get DCPSParticipant infos.
builtin_reader = dds_create_reader(participant, DDS_BUILTIN_TOPIC_DCPSPARTICIPANT, NULL, NULL);
if (builtin_reader < 0) {
  DDS_FATAL("dds_create_reader[builtin_reader]: %s\n", dds_strretcode(-builtin_reader));
}

while (true) {
  int i;
  dds_guid_t guid;
  builtin_rc = dds_take (builtin_reader, builtin_samples, builtin_infos, MAX_SAMPLES, MAX_SAMPLES);
  if (builtin_rc < 0)
    DDS_FATAL("dds_take: %s\n", dds_strretcode(-builtin_rc));
  
  for (i = 0; i < builtin_rc; i++) {
    if (builtin_infos[i].valid_data) {
      builtin_msg = (dds_builtintopic_participant_t*) builtin_samples[i];
      printf ("=== [Builtin DataReader] Received : ");
      for (int j = 0; j < 16; j++) {
        printf ("%02x", ((builtin_msg->key).v)[j]);
      }
      printf ("\n");
      fflush (stdout);
    }
  }
}
```
![image](https://user-images.githubusercontent.com/68287373/222623202-0730bf4d-1975-4717-9b3f-7e9e6f000c5b.png)

**Comment by eboasson** [comment]
That looks good, except for the one thing that is causing the problem and a lack of releasing the data you read (because `dds_take` gives you private copies).

In DDS, a *topic* consists of any number of *instances*, as determined by the key values (if there is no key field, then there is only one instance), and then for each instance, you have *samples* containing data you write with `dds_write`. The number of samples your history caches will store for you is determined by the "history" QoS setting. (So topics & instances map well to relational database tables and rows; the samples are trickier, to map nicely.)

For each *instance* DDS maintains some state information, and what is really particular the *instance state*. The instance state indicates whether there "currently" (*) are writers that have indicated they are updating this particular instance (a.k.a. `ALIVE`) or no such writers (a.k.a. `NOT_ALIVE_NO_WRITERS`) or whether the instance has been marked as ready for deletion by a writer using the `dds_dispose` operation (a.k.a. `NOT_ALIVE_DISPOSED`). This state is made available to the reader in the `instance_state` field of the sample info that you get along with the data (and from which you are currently checking the `valid_data` flag).

Note that merely marking an instance as "disposed" doesn't make it disappear all by itself. You still have to take it from the cache. (There are more complications, but I don't think those are helpful right now.)

When a participant shows up, (Cyclone) DDS calls `dds_write` to publish a *sample* of this "DCPSParticipant" topic. These you are reading. When the participant disappears, it calls `dds_dispose` to mark the *instance* as no longer relevant. The distinction between *instance* and *sample* here is important, because this `dds_dispose` operation doesn't provide you with a full sample, and so the application needs to be warned to not to look at any non-key field in the data. Hence you usually see them as `valid_data == false`.

Usually, because it depends on timing, on whether there is a unread, valid sample available, and on whether the user used `dds_dispose` or `dds_writedispose`, because the latter actually publishes a full sample while simultaneously marking it as "disposed" and so never needs to clear `valid_data`.

In short, you could do something like this (untested and no-doubt containing typos):
```C
  for (i = 0; i < builtin_rc; i++) {
    if (builtin_infos[i].instance_state == DDS_NOT_ALIVE_DISPOSED_INSTANCE_STATE || builtin_infos[i].valid_data) {
      builtin_msg = (dds_builtintopic_participant_t*) builtin_samples[i];
      printf ("=== [Builtin DataReader] Received %s: ", (builtin_infos[i].instance_state == DDS_NOT_ALIVE_DISPOSED_INSTANCE_STATE) ? "dispose" : "new/update");
      for (int j = 0; j < 16; j++) {
        printf ("%02x", ((builtin_msg->key).v)[j]);
      }
      printf ("\n");
      fflush (stdout);
    }
  }
  dds_return_loan (builtin_reader, builtin_samples, builtin_rc);
```

(*) "Currently" is hand-waving. There are delays all over the place in a distributed system, and so just like in real life, whatever information you have about a remote node may already have been invalidated by events on that remote node.

**Comment by neptune-wind** [comment]
Sorry for not replying for so long. Thank you for telling me the usage of instance. According to your suggestion, I got the participant's info when this participant's process is killed. This issue could be closed. By the way, how can I configure the time from when a participant is delete to receiving the sample with `DDS_NOT_ALIVE_DISPOSED_INSTANCE_STATE`?

**Comment by eboasson** [comment]
> Thank you for telling me the usage of instance. According to your suggestion, I got the participant's info when this participant's process is killed. This issue could be closed.

Thanks!

> By the way, how can I configure the time from when a participant is delete to receiving the sample with DDS_NOT_ALIVE_DISPOSED_INSTANCE_STATE?

The default is set by `Discovery/LeaseDuration` in the configuration. You can also set it for an individual participant you create by setting the "liveliness" QoS to "automatic" with the desired lease duration, e.g.:
```
dds_qset_liveliness (qos, DDS_LIVELINESS_AUTOMATIC, DDS_SECS(5));
pp = dds_create_participant (DDS_DOMAIN_DEFAULT, qos, NULL);
```
