### ISSUE TITLE
It has memory leak running on 32-bit linux OS（armv7l）, leaking at 4K rank, which can be observed through the RssAnon of roundtrip process.

### ISSUE THREAD

**Issue by caojiebao** [eclipse-cyclonedds/cyclonedds#1598]
[memleak.docx](https://github.com/eclipse-cyclonedds/cyclonedds/files/10926823/memleak.docx)

**Comment by caojiebao** [comment]
@eboasson

**Comment by eboasson** [comment]
Memory leaks are serious things that we really do want to look at, but surely it would possible to put the information in the issue without requiring me to open a word file? That way the information is easily available to anyone.

And that's leaving aside the security risks involved in opening word files!

So would please update the ticket with the description and directly in the comment and any graph embedded as PNGs? That works very well on GitHub.

**Comment by caojiebao** [comment]
![image](https://user-images.githubusercontent.com/72638389/224286997-0796631b-8a97-4751-8542-6931cbb56c2b.png)

OS：
Linux sa515m 4.14.206-perf #1 PREEMPT Wed Sep 21 09:32:05 +08 2022 armv7l

**Comment by eboasson** [comment]
Thanks @caojiebao !

And 180MB RssAnon indeed doesn't sound right!

**Comment by eboasson** [comment]
This the `cxxRoundtripPing` program?

Then it looks to me like it is simply because it records timing information for each sample in `writeAccessOverall`, `readAccessOverall` and `roundTripOverall` and only releases it at the very, when it prints the final
```
# Overall  436880 |       24      20      37  587163 |        9       7      16 1174172 |        3       2       9     876
```
line.

At (order-of-magnitude) 100k round-trips per second (over loopback), that adds up ...

That would also mean it isn't a really a bug and necessary to produce accurate median and 99% percentile over the entire run-time. The value of that is probably lower than the pain it inflicts.

@hansvanthag or @reicheratwork do either of you remember *why* we collect all this data? It seems to me that without losing anything meaningful we can just not do the overall thing at the end at all, leave the median and 99% percentile out, or use one of the various estimators for them that have constant state.

It also turns out the C version avoids the problem by not collecting all the timing data that it suggests it is collecting. If it actually did what it suggests it is doing, it, too, would have monotonically growing memory use.

As an aside: `ddsperf ping` + `ddsperf pong` doesn't suffer from this 😎

**Comment by caojiebao** [comment]
thanks
