### ISSUE TITLE
Interoperability with a FastDDS variant

### ISSUE THREAD

**Issue by squizz617** [eclipse-cyclonedds/cyclonedds#1605]
Hi,
I have a slight variant of FastDDS (let's call it FakeDDS) and experiencing weird issues when operating it with CycloneDDS. 
Here's the situation. I modified the "helloworld" example a bit to match topic and msg type with those of FastDDS (download: [helloworld.zip](https://github.com/eclipse-cyclonedds/cyclonedds/files/10963973/helloworld.zip)).
* Case 01: Run the subscriber (`HelloworldSubscriber`) and then a FastDDS publisher
* Case 02: Run the subscriber and then a FakeDDS publisher

Taking a look at the captured RTPS packets, i.e., [cyclonedds-sub-fastdds-pub.pcap.zip](https://github.com/eclipse-cyclonedds/cyclonedds/files/10963941/cyclonedds-sub-fastdds-pub.pcap.zip) for Case 01 and [cyclonedds-sub-fakedds-pub.pcap.zip](https://github.com/eclipse-cyclonedds/cyclonedds/files/10963942/cyclonedds-sub-fakedds-pub.pcap.zip) for Case 02, I noticed three weird things.
1. Both FastDDS and FakeDDS send the same (identical except for `PID_PARTICIPANT_GUID`) PDP packet to `239.255.0.1:7400`. Then, CycloneDDS sends a discovery packet to `128.61.240.207:7412`, followed by three HB packets. So far so good. However, I do not understand why CycloneDDS sends three extra ACKNACKs (bitmapBase: 1, numBits: 0) right after the HBs only to FakeDDS, even though the prior interactions with both FastDDS and FakeDDS were pretty much identical.
2. CycloneDDS communicates seamlessly with FastDDS (Case 01). It sends DATA(r), receives DATA(w), and eventually receives the user data as expected. This is not the case with FakeDDS; CycloneDDS never sends DATA(r) to FakeDDS (Case 02), but it's hard to understand why.
3. Still, CycloneDDS receives the user data sent by FakeDDS, even though it never sends DATA(r) to FakeDDS. I am not sure if this is considered legitimate behavior.

Also attaching the execution logs for both cases:
* Case 01: [cyclonedds-sub-fastdds-pub.txt](https://github.com/eclipse-cyclonedds/cyclonedds/files/10964049/cyclonedds-sub-fastdds-pub.txt)
* Case 02: [cyclonedds-sub-fakedds-pub.txt](https://github.com/eclipse-cyclonedds/cyclonedds/files/10964051/cyclonedds-sub-fakedds-pub.txt)

I'm having hard time wrapping my head around the differences in the behaviors of CycloneDDS. It would be great if you could shed some light on these. Thank you.

**Comment by eboasson** [comment]
Hi @squizz617, the difference is this (excerpts from the Cyclone trace for FastDDS and FakeDDS respectively):
```
1678745121.462724 [0]     recvUC: HDR(10f45d2:8d5deab:1000000 vendor 1.15) len 68 from udp/127.0.0.1:53983
1678745121.462752 [0]     recvUC: INFODST(1106414:a740a766:ef99b7db)
1678745121.462841 [0]     recvUC: ACKNACK(#1:1/1:1 L(:1c1 6918096.093033) 10f45d2:8d5deab:1000000:4c7 -> 1106414:a740a766:ef99b7db:4c2 complying RX1non-timed queue now has 1 items
```
vs
```
1678745092.920659 [0]     recvUC: HDR(10f45d2:b3f558b9:1000000 vendor 1.15) len 52 from udp/128.61.240.207:1337
1678745092.920688 [0]     recvUC: ACKNACK(#2:1/1:1 L(:1c1 6918067.550964) 10f45d2:b3f558b9:1000000:4c7 -> 0:0:0:4c2 not a connection)
```
That is: FastDDS adds an `INFODST` submessage where FakeDDS doesn't. Under the default settings of Cyclone, it is incorrect to assume that only a single participant can be reachable via a unicast locator, and so in the default configuration it *requires* an `INFODST` submessage. Without it, it complains that there is no with a writer with GUID `0:0:0:4c2`.

This used to cause a problem in interoperating with TwinOaks' CoreDX, but they have long since started always including `INFODST` submessages because it is beneficial also in other circumstances. The compatibility option still exists (set [`ManySocketsMode`](https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/docs/manual/options.md#cycloneddsdomaincompatibilitymanysocketsmode) to `many`).

In most cases, there will only be a single participant even in the default configuration. One could argue that it therefore makes sense to accept the `ACKNACK` without an `INFODST` in that case, but I'm quite sure that it would allow for aliasing problems. The best solution is to always send an `INFODST` submessage when a single entity is being addressed. Recognising the particular problem and logging a warning would perhaps be better than silently discarding it.

Re:

> Still, CycloneDDS receives the user data sent by FakeDDS, even though it never sends DATA(r) to FakeDDS. I am not sure if this is considered legitimate behavior.

That is quite surprising indeed. Cyclone is correct in accepting it, the surprise to me is that FakeDDS sends it.

**Comment by squizz617** [comment]
@eboasson, thanks for your timely response (as always)!

> it is incorrect to assume that only a single participant can be reachable via a unicast locator

Makes sense. Now I see where this design decision is coming from. I have follow-up questions then; is this requirement documented anywhere, and do you happen to know of any other DDS that has the same requirement on the inclusion of `INFODST` submessages?

> Recognising the particular problem and logging a warning would perhaps be better than silently discarding it.

I agree. I actually assumed that the issue would be at the earlier stages of the communication, so did not carefully look at that part of the trace. 

Also, what's your opinion on my first question/observation of extra ACKNACKs?

**Comment by eboasson** [comment]
> I have follow-up questions then; is this requirement documented anywhere

Probably not ...

> and do you happen to know of any other DDS that has the same requirement on the inclusion of INFODST submessages?

I only that ZettaScale's OpenSplice DDS has the same requirement. It seems I'm the only one who thinks it normal to handle hundreds of participants in a single process, which is really where this behaviour comes from. As mentioned, I do know that everyone these days includes the `INFODST` submessages for reasons of their own. I suspect in all those cases, the reason is that it makes routers that forward data straightforward.

> Also, what's your opinion on my first question/observation of extra ACKNACKs?

It looks to me like a timing detail: it sends some pre-emptive `ACKNACK`s to FakeDDS because it scheduled them before the `HEARTBEAT`s from FakeDDS came in. With FastDDS this appears to be reversed.
