### ISSUE TITLE
cyclonedds core dumped when deadline is set to 0

### ISSUE THREAD

**Issue by binbowang1987** [eclipse-cyclonedds/cyclonedds#1609]
In `examples/helloworld/publisher.c`, I set deadline to 0. Run HelloworldPublisher/HelloworldSubscriber, the HelloworldPublisher core dumped.

```c
  ......
  dds_qos_t *pubQos = dds_create_qos ();
  dds_duration_t deadline = 0;
  dds_qset_deadline(pubQos, deadline);

  /* Create a Topic. */
  topic = dds_create_topic (
    participant, &HelloWorldData_Msg_desc, "HelloWorldData_Msg", pubQos, NULL);
  ......
```
https://github.com/eclipse-cyclonedds/cyclonedds/blob/1ae6bb9985c05f8742cb31c0bd46f3c7bd8777bd/examples/helloworld/publisher.c#L23

![图片](https://user-images.githubusercontent.com/8586061/225247658-aac58653-8f5e-4185-b73d-92e704e7def0.png)

**Comment by eboasson** [comment]
If I am not mistaken, the linked PR addresses the problem. The problem I have with it is that it feels a bit brutish to just reject the case instead of handling it correctly (by continually triggering the deadline missed notification and always returning the best approximation of ∞ for the number of missed deadlines that the standard allows).

**Comment by binbowang1987** [comment]
Besides found this problem. I have another qustion when using dynsub.

I use the above code set writer's deadline to 1. In `dynsub.c`, I added some code to print the deadline. Then run `HelloworldPublisher` and `dynsub HelloWorldData_Msg` . And, the output is `deadline: 1`, I think this behavior is wrong, as the writer's deadline shall not incfluence the reader's.
```c
// some code to print dynsub reader's deadlone qos
    {                                                                                                                                                                                                                         
      dds_qos_t *qos_reader = dds_create_qos();                                                                                                                                                                               
      dds_get_qos(reader, qos_reader);                                                                                                                                                                                        
                                                                                                                                                                                                                              
      dds_duration_t deadline;                                                                                                                                                                                                
      dds_qget_deadline(qos_reader, &deadline);                                                                                                                                                                               
                                                                                                                                                                                                                              
      printf("deadline: %ld\n", deadline);                                                                                                                                                                                     
                                                                                                                                                                                                                              
      dds_delete_qos(qos_reader);                                                                                                                                                                                             
    }         
```

**Comment by eboasson** [comment]
That's because the call to `dds_create_reader` in dynsub passes a null pointer for the QoS settings, which makes it inherit the QoS settings from the topic. The topic QoS on the subscriber depends on the configuration:
* it identical to that of the writer's topic QoS if topic discovery is enabled,
* it is derived from the writer's QoS otherwise

In all likelihood, if you set it on the topic in the writing application, then you also passed a null pointer in for the writer QoS in the call to `dds_create_writer`. In that case, the writer would have inherited it from its topic QoS, and so in that case the result would be the same regardless of this configuration setting for topic discovery.

Just a side note: a deadline of 1 here means a deadline of 1 *nanosecond*. It is supported, but it doesn't provide much useful information because publishing data takes several 100ns ...

**Comment by binbowang1987** [comment]
I get it, thank you for your explaination.   
I'm very agree with you, 1 *nanosecond* is meaningless, I just use it for test.
