### ISSUE TITLE
How to  transmit samples with custom serialization algorithm (not CDR)

### ISSUE THREAD

**Issue by i-and** [eclipse-cyclonedds/cyclonedds#162]
Please advise how in the CycloneDDS can effectively transmit samples with custom serialization algorithm (not CDR).  The obvious solution is to use the following type for all topics: 
~~~
struct DataType
  {
    sequence<octet> payload;
  };
  #pragma keylist DataType
~~~
At the same time, at the application level using the standard read()/write() to perform the reception/sending of samples using QOS (including a reliable). And perform the necessary additional serialization/deserialization at the higher level.

But how efficient will it be in terms of CPU and memory usage by the Cyclone library? Maybe it makes sense to use some low-level functions of Cyclone?

**Comment by eboasson** [comment]
Hi @i-and,

I postponed responding a little bit to be able to say something slightly more solid, but it did take a little longer than I had hoped. My apologies.

Cyclone does allow custom sample representations and serialisation. The interface for this is not quite stable, but it probably won't change very much either. The one caveat that currently exists is that the message validation code requires one of the predefined encodings, so if you want to do a custom one, then, at least for now, you'll have to either represent it on the wire as a CDR octet sequence — i.e., prepend the data by the number of bytes — or you'll have to lie and claim that it is CDR even though in fact it is not.

Basically, you have to define two things:
* your own subtype of ``struct ddsi_sertopic``, which brings some allocation/deallocation routines and is referenced by topics, readers and writers, and
* your own subtype of ``struct ddsi_serdata``, which is the sample representation along with a bunch of operations to work with them.

How you construct your new ``sertopic`` is entirely up to you. To create a DDS topic out of one, you will have to call the (oddly-named) function ``dds_create_topic_arbitrary`` where you provide your own ``sertopic`` instead of a topic descriptor.

Calling, e.g., ``dds_write`` simply calls the ``from_sample`` function you define with the sample pointer passed into ``dds_write`` as the argument. What that function does exactly is absolutely irrelevant, as long as it produces a new (refcounted) instance of your subtype of ``struct ddsi_serdata`` that correctly represents the contents of the sample.

To actually transmit the data on the wire, the DDSI stack uses the ``get_size`` operation to get the size of the serialized representation and uses the ``to_ser_ref``/``to_ser_unref`` pair to embed the contents (or part of the contents) in an IO vector passed to the actual networking code. (On Unix, these map to ``struct iovec`` and ``sendmsg``.) There is also a ``to_ser`` that should make a copy, but I believe that one is currently not used.

For reliable data, these ``serdata`` things get stored in the writer history caches and the contents should be reproducible. For best-effort data, it really is fire-and-forget, so to reference a subject discussed much earlier (#99), you can probably get away with an trivial ``from_sample`` and a ``to_ser_ref``/``to_ser_unref`` pair that interacts directly with a frame grabber.

Reading/taking data is essentially the same story, but run in reverse: ``from_ser`` has to turn the raw data into a sample, then ``to_sample`` copies it out to the application. Where exactly you do the serialisation or deserialisation is up to you.

You could therefore replace the (de)serialiser, by, e.g., Google Protocol Buffers. That way, the samples you read/write through the API would simply be GPB messages. This is incidentally also the reason why I keep claiming that XTypes in principle is something that hardly affects the core of Cyclone, it is just another representation.

I spent some effort on upgrading my old PoC for a ROS2 interface layer at https://github.com/atolab/rmw_cyclonedds. The update I just pushed makes it compile with ROS2 "Crystal Clemmys" and the current state of Cyclone DDS, and uses this interface to (de)serialise ROS messages.

I assume the code doesn't work, I simply haven't had a chance yet to see where and why it fails because of trouble building ROS2 on macOS, presumably because I'm using the latest version and have Apple's System Integrity Protection enabled to boot. I would expect it fails at least because it is lacking some functions that I presume are required by the changes in the ROS2 interface introduced in "CC". Similarly, I would expect some serialisation issues because of changes to ROS2's internal message types, &c. But those should minor and now that it compiles again I have a better chance of getting a helping hand from someone 😁.

**Comment by i-and** [comment]
@eboasson, thank you for clarifying the (de)serialization procedure in the Cyclone.

**Comment by thijsmie** [comment]
This is possible with current Cyclone, although not super ergonomic. The structure of the interface might need another evolution down the line.
