### ISSUE TITLE
lwIP does not support the SO_SNDBUF option

### ISSUE THREAD

**Issue by ex-purple** [eclipse-cyclonedds/cyclonedds#1623]
Hi,
our current implementation of lwIP marks the SO_SNDBUF option as not Unimplemented: 
https://github.com/RT-Thread/realboard-stm32f4/blob/master/software/programs/rt-thread/components/net/lwip/src/include/lwip/sockets.h#L93

So I can't create a DomainParticipant because dds_create_participant returns an error.

Is it possible to skip the SO_SNDBUF settings steps? Or such lwIP and cyclonedds are not compatible?

**Comment by eboasson** [comment]
I'd simply skip it if it is not supported. Or, if I were trying to be really nice, I'd try it and accept `UNSUPPORTED` if and only if the configuration uses `<SocketSendBuffer min="default" max="default"/>` because that is documented as using the system default.

It already avoids setting `SO_SNDBUF` for this setting, so accepting an error that the `SO_SNDBUF` is unsupported on `getopt` seems reasonable.

(See this [hiding place for gremlins](https://github.com/eclipse-cyclonedds/cyclonedds/blob/fea1f6d0671d54886403b034189b8737c1536314/src/core/ddsi/src/ddsi_udp.c#L279))

**Comment by ex-purple** [comment]
Thanks for the help!
I'm just skipping SO_SNDBUF, but now I have a similar problem with the SO_REUSEADDR option.

**Comment by eboasson** [comment]
Same :)

`SO_REUSEADDR` is only relevant for multicast, which you don't have to use. You might also want to check `SO_REUSEPORT`.

**Comment by ex-purple** [comment]
Ok, thanks 🙂
Next problem is [assert](https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/src/core/ddsi/src/ddsi_entity_index.c#L299) failed 

What could be wrong here?

**Comment by eboasson** [comment]
> Next problem is [assert](https://github.com/eclipse-cyclonedds/cyclonedds/blob/0.10.2/src/core/ddsi/src/ddsi_entity_index.c#L299) fail

Oy!

Either it is because different threads get the same id (and so two threads are manipulating the same "thread state" instead of having their own copies), or something goes wrong in the handling of thread-local storage (a.k.a. thread-specific data, a.k.a., the `__thread` keyword).

I remember that the latter caused someone else some headaches way back when the FreeRTOS port was initially done. In my recollection it involved something called ["emutls"](https://github.com/gcc-mirror/gcc/blob/master/libgcc/emutls.c) but I can't provide you with any details ...

I'd start digging by checking what `ddsi_create_thread` does, what is in the thread table (see `thread_states`; there should also be the main thread which gets added via `lazy_create_thread_state`), and what's happening in `ddsi_lookup_thread_state` and `ddsi_lookup_thread_state_real`. I expect that'll help narrow things down a bit.

**Comment by ex-purple** [comment]
Thanks for your help again
For now, we have decided not to port the cyclones to our board.
