### ISSUE TITLE
CycloneDDS does not communicate with OpenDDS when a union is in the IDL

### ISSUE THREAD

**Issue by smnrgrs** [eclipse-cyclonedds/cyclonedds#1627]
Testing with the current Cyclone master, i11eperf and OpenDDS 3.22.

If I add to the topic in i11eperf.idl something like:
````
  enum weebleType_t
  {
    TYPEA,
    TYPEB
  };

  union weebleDataUnion_t switch (weebleType_t)
  {
    case TYPEA:
      long aValue;
    case TYPEB:
      float bValue;
  };

  @topic @final @data_representation(XCDR1)
  struct ou {
    weebleDataUnion_t someData;
    unsigned long long ts;
    unsigned long s;
  };
````
I get Sedp::match_continue - WARNING Data types of topic Data does not match (inconsistent) from OpenDDS.

apub->asub and opub->osub work.
I can only see this now int8 types are fixed!

**Comment by eboasson** [comment]
Hi @smnrgrs, you're doing a superb job finding issues in the XTypes interoperability! Thanks! ☺️

There are a few issues at play here:
* Cyclone and OpenDDS set the extensibility of the `weeble`s differently, and the extensibility difference trivially makes the types not assignable. Cyclone here intentionally deviates from the spec[^1]. This is easily solved by annotating all relevant types as `@final` — but read on
* In the `enum` Cyclone is not setting the `default_literal` flag on the first symbol. This is a bug, fixed in #1630, and results in a different type identifier
* Because the enum's type identifier is different, checking assignability for the union after marking it `@final` requires an additional type lookup to get the full type definition. This turns out to hit a bug in Cyclone in the type lookups. This is a bug, fixed in #1631
* Cyclone sets the `must_understand` flag on the union discriminator per 7.2.2.4.4.4.6 in the XTypes spec, OpenDDS doesn't. That's quite similar to #1544 which I have been told has been discussed at an OMG meeting last week.
* The union is marked `@nested` in the type object published by OpenDDS, but not in that published by Cyclone. This is a difference in interpretation (or a misreading) of the spec. My current assumption is that Cyclone is correct here, but who knows, there might be some arcane rule that makes it different for unions ...
* These two flags on the union and the flag on the enum are generally not a big deal, except that for `@final` there is some rule that requires the fields to be "strongly assignable" (7.2.4.3 in the spec) and that requires the type identifiers to be identical, and so any difference in how these flags get set prevents assignability for final types.

With appendable types, it changes, and so
```
  @appendable enum weebleType_t
  {
    TYPEA,
    TYPEB
  };
  @appendable union weebleDataUnion_t switch (weebleType_t)
  {
    case TYPEA:
      long aValue;
    case TYPEB:
      float bValue;
  };
  @topic @appendable @data_representation(XCDR2)
  struct ou {
    weebleDataUnion_t someData;
    unsigned long long ts;
    unsigned long s;
  };
```
works fine (at least it does with #1630 and #1631 in place). Note that XCDR2 and appendable are the "modern" defaults anyway.

I used XCDR1 and final in the `i11eperf` repository because of OpenSplice and FastDDS. If you don't care for those, then it seems to me that you're actually better off with XCR2 and appendable. 🙂

[^1]: We default to `@final` where the type is supported without XTypes because we consider it essential that taking a system running using a pre-XTypes implementation and upgrading half of it to use an XTypes-capable implementation should work without changing IDL and source code.

**Comment by smnrgrs** [comment]
Thanks for the reply @eboasson. I've updated my Cyclone and I11eperf to get everything up to date. The default setup works (default idl), but switching the idl to appendable/XCDR2, when I run opub I get a seg fault. That's before I start trying to use unions!
What version of OpenDDS did you use in your test?

**Comment by smnrgrs** [comment]
So Cyclone C to OpenDDS is looking ok, having followed your advice above.
I'm seeing problems with cyclone Python and unions, will provide details when I can.
