### ISSUE TITLE
dds_delete_impl fail for datareader/datawriter

### ISSUE THREAD

**Issue by stillsimon** [eclipse-cyclonedds/cyclonedds#163]
Hi, I occasionally encounter a  failure when using dds_delete on a DataWriter/DataReader. The return code shows that it fails on 
https://github.com/eclipse-cyclonedds/cyclonedds/blob/6227fe00b330bd9c157149d752152d7899ab1535/src/core/ddsc/src/dds_entity.c#L147
When I look inside dds_entity_lock, it seems that the code failed to claim the entity. Can you explain the reason for that?

I find some FIXME information in dds_entity_lock function. Is it related to the bug I find above?
https://github.com/eclipse-cyclonedds/cyclonedds/blob/6227fe00b330bd9c157149d752152d7899ab1535/src/core/ddsc/src/dds_entity.c#L782-L788

**Comment by eboasson** [comment]
I have studied it a bit, and it kinda makes sense:

The API allows you to create (e.g.) a reader without explicitly creating a subscriber entity first, instead allowing you to pass the participant in. Internally, it does require that subscriber entity and so if you pass a participant handle to ``dds_create_reader`` (or ...writer) it automatically creates a default subscriber (or publisher).

When you delete a reader that was created in this manner, it should automatically delete the subscriber: one can't require a user to delete a subscriber that he/she never created and that has an unknown handle. So that's the reason for calling ``dds_delete_impl`` on the parent entity in ``dds_reader_delete`` (and analogously for writers):
https://github.com/eclipse-cyclonedds/cyclonedds/blob/6227fe00b330bd9c157149d752152d7899ab1535/src/core/ddsc/src/dds_reader.c#L70-L82

(That also explains why the "keep_if_explicit" parameter is true in this case: if the subscriber was created explicitly by calling ``dds_create_subscriber`` it shouldn't be deleted.)

The error occurs when instead of calling ``dds_delete`` on the reader, you call it on the subscriber or on the participant. The recursive delete goes down the tree of entities, first blocking access and then deleting the child entities. Thus, when it gets to deleting the reader and it tries to delete the subscriber it fails because the subscriber is already being deleted and past the call to ``dds_close_handle`` in ``dds_delete_impl``. It indeed has to do with the FIXME you referenced.

I must say I don't particularly like blindly calling ``dds_delete_impl`` like this and then ignoring the error code. Still, the call always happens before the subscriber (or publisher) handle becomes available again for reuse because deleting the children happens before calling ``dds_handle_delete``, so aliasing is avoided and it should be safe
