### ISSUE TITLE
Questions about Porting QoSProvider from Vortex Opensplice

### ISSUE THREAD

**Issue by tez1szh** [eclipse-cyclonedds/cyclonedds#1646]
We'd like to port QosProvider from opensplice to cyclonedds.

We tried to replace os abstraction with ddsrt as much as possilble, using infrastructure from ddsrt.
Initial attempt seems working. But still many points need to be clarified:

- Are we allowed to use codes from Vortex Opensplice?
  - If so, is there any guidelines/documents on the rules & principles?
  - How the copyright should look like?
- For the porting details, 
  - we probably need `cmn_qosProvider` and its suporting module database & config as shown in the picture below 
  -  ![image](https://user-images.githubusercontent.com/20858916/230807259-47b208f5-7d65-4abc-9570-50a4d787c46f.png)
     - Folder structure: Should we put all these files directly under ddsrt folder or any suggestion on how to organize them?
     - Naming convention: Should we rename the files and the function names in each file?
     - If some functions are not used in those supporting files, shall we remove the unused functions?  `cmn_qosProvider` might need only a few functions from the supporting files
  - Is there any formatter-config file for the cyclonedds project (e.g. .clang-format)? 
  - Any other points we need to pay attention?

Thanks!

BR,
tez1szh

Related to https://github.com/eclipse-cyclonedds/cyclonedds-cxx/issues/104

**Comment by eboasson** [comment]
@tez1szh Wow, that's a really nice initiative. As you write there are some hurdles ...

> Are we allowed to use codes from Vortex Opensplice?
> If so, is there any guidelines/documents on the rules & principles?
> How the copyright should look like?

It is possible, it would be a bit on the side, but I think the code that we pulled in so far all was BSD licensed. In any case I think there is a good chance ZettaScale would be willing to relicense the relevant parts as EPL2+EDL1 for this purpose. I am not the one who can make that call, but I can find out.

If that route were to be followed, then the copyright would be ZettaScale for the existing parts, and yourself (or your company) for any changes. (In practice, probably something like "(ancient history) - 2020 © ZS, 2023 © you". This is obviously shortened beyond recognition, but I think you know what I mean.) The Eclipse Foundation expressly leaves the copyright with the original authors.

> For the porting details,
> we probably need cmn_qosProvider and its suporting module database & config as shown in the picture below

That I am not so keen on. It is easiest way, that's clear, but that pulls in an insane amount of stuff. I can see that it might be necessary to avoid a lot of rework in the actual qos provider, but if all that gets pulled in, then I wouldn't want to merge it in the core repository. What could still be worth considering is creating an additional repository under the eclipse-cyclonedds organization.

I do wonder though. It is really just a bit of XML parsing and QoS object manipulation with some QoS inheritance. Cyclone's QoS representation supports inheritance directly, so are you sure that it makes more sense to copy so much from OpenSplice versus using the XML parser in Cyclone to (partially) fill QoS objects and put them in a hierarchical structure with an index for looking them up?

To be honest, I've never really looked into the details of the QoS provider myself, so I may be wildly off base here.

> Folder structure: Should we put all these files directly under ddsrt folder or any suggestion on how to organize them?

In my view the qos provider is a separate component, and it would be the only one using these supporting things, so I would think that if we decide that this is the best approach, then my current thinking is that it would all end up somewhere in `src/qosprovider` or similar. I haven't really thought this through yet.

> Naming convention: Should we rename the files and the function names in each file?

If it ends up in a separate repository, then it doesn't matter much. Otherwise yes, but within reason. It isn't very strict as it is, and there is no reason to suddenly become very strict when a significant body of code from OpenSplice would show up.

> If some functions are not used in those supporting files, shall we remove the unused functions? cmn_qosProvider might need only a few functions from the supporting files

If it turns out that stripping the code removes most of the code and only a reasonable amount remains, then the above of course changes.

> Is there any formatter-config file for the cyclonedds project (e.g. .clang-format)?

I've never managed to make a clang-format or uncrustify configuration that I like, but (at least for uncrustify) it is not so hard to do something that fits well enough. Two spaces, braces on their own line in code (except when you get an excessive amount of lines containing nothing but braces), generally no braces around single statements unless in an if/else if/else chain and the preceding one has braces, space also after a function name in a call, ... 

```
  (c-set-style "GNU")
  (c-set-offset 'substatement-open 0)
  (c-set-offset 'case-label '+)
  (c-set-offset 'arglist-intro 8)
  (c-set-offset 'brace-list-intro '+)
```

does most of the trick — whatever it is called in uncrustify 😀 Don't sweat over it, I really dislike these strict mechanical formatters and the price one pays is to deal with some inconsistencies.

> Any other points we need to pay attention?

I think especially the bit about having a good look first at how much work it would be to rebuild it using Cyclone's XML parser, data structures and QoS objects. If that turns out to be realistic, then it should definitely become part of the core repository.

**Comment by tez1szh** [comment]
Thanks @eboasson for the detailed answer!!

I'm not a big fan of all those dependencies comes from OpenSplice neither.
And the current implementation from OpenSplice seems too heavy and complicated.

I do have the feeling that rebuilding it is the right way.
Might come back to this when got some ideas after having a deeper understanding of Cyclone xmlparser, data structure and Qos objects.
