### ISSUE TITLE
RELIABILITY mode

### ISSUE THREAD

**Issue by lambdaprime** [eclipse-cyclonedds/cyclonedds#1663]
Hi,

Purpose of this test is to make sure that Cyclone DDS behaves accordingly with respect to RTPS Specification v2.3 (in particular 8.4.1.1 Example Behavior section 9a):

    For a RELIABLE DDS DataReader, changes in its RTPS Reader’s HistoryCache are made visible to the user
    application only when all previous changes (i.e., changes with smaller sequence numbers) are also visible

For test I use modified HelloWorld example from Cyclone DDS:

publisher.c
```
#include "dds/dds.h"
#include "HelloWorldData.h"
#include <stdio.h>
#include <stdlib.h>

int main (int argc, char ** argv)
{
  dds_entity_t participant;
  dds_entity_t topic;
  dds_entity_t writer;
  dds_return_t rc;
  HelloWorldData_Msg msg;
  uint32_t status = 0;
  (void)argc;
  (void)argv;

  /* Create a Participant. */
  participant = dds_create_participant (DDS_DOMAIN_DEFAULT, NULL, NULL);
  if (participant < 0)
    DDS_FATAL("dds_create_participant: %s\n", dds_strretcode(-participant));

  dds_qos_t *qos;
  qos = dds_create_qos ();
  dds_qset_reliability (qos, DDS_RELIABILITY_RELIABLE, DDS_SECS(10));

  char* cstr = getenv("RTPS_TopicName");

  /* Create a Topic. */
  topic = dds_create_topic (
    participant, &HelloWorldData_Msg_desc, "HelloWorldData_Msg", qos, NULL);
  if (topic < 0)
    DDS_FATAL("dds_create_topic: %s\n", dds_strretcode(-topic));

  /* Create a Writer. */
  writer = dds_create_writer (participant, topic, NULL, NULL);
  if (writer < 0)
    DDS_FATAL("dds_create_writer: %s\n", dds_strretcode(-writer));

  printf("=== [Publisher]  Waiting for a reader to be discovered ...\n");
  fflush (stdout);

  rc = dds_set_status_mask(writer, DDS_PUBLICATION_MATCHED_STATUS);
  if (rc != DDS_RETCODE_OK)
    DDS_FATAL("dds_set_status_mask: %s\n", dds_strretcode(-rc));

  while(!(status & DDS_PUBLICATION_MATCHED_STATUS))
  {
    rc = dds_get_status_changes (writer, &status);
    if (rc != DDS_RETCODE_OK)
      DDS_FATAL("dds_get_status_changes: %s\n", dds_strretcode(-rc));

    /* Polling sleep. */
    dds_sleepfor (DDS_MSECS (20));
  }

  for (uint32_t i = 0; i < 3; ++i) {
    /* Create a message to write. */
    msg.userID = i + 1;
    msg.message = "HelloWorld";

    printf ("=== [Publisher]  Writing : \n");
    printf ("Message (%"PRId32", %s)\n", msg.userID, msg.message);
    fflush (stdout);
    rc = dds_write (writer, &msg);
    if (rc != DDS_RETCODE_OK)
      DDS_FATAL("dds_write: %s\n", dds_strretcode(-rc));
  }

  /* Deleting the participant will delete all its children recursively as well. */
  rc = dds_delete (participant);
  if (rc != DDS_RETCODE_OK)
    DDS_FATAL("dds_delete: %s\n", dds_strretcode(-rc));

  return EXIT_SUCCESS;
}
```

subscriber.c
```
#include "dds/dds.h"
#include "HelloWorldData.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

int main (int argc, char ** argv)
{
  dds_entity_t participant;
  dds_entity_t topic;
  dds_entity_t reader;
  HelloWorldData_Msg *msg;
  void **samples;
  dds_sample_info_t *infos;
  dds_return_t rc;
  dds_qos_t *qos;
  (void)argc;
  (void)argv;
  int numOfSamples = 1;
  if (argc >= 1)
    numOfSamples = atoi(argv[1]);
  printf("Num of samples: %d\n", numOfSamples);

  /* Create a Participant. */
  participant = dds_create_participant (DDS_DOMAIN_DEFAULT, NULL, NULL);
  if (participant < 0)
    DDS_FATAL("dds_create_participant: %s\n", dds_strretcode(-participant));

  /* Create a Topic. */
  topic = dds_create_topic (
    participant, &HelloWorldData_Msg_desc, "HelloWorldData_Msg", NULL, NULL);
  if (topic < 0)
    DDS_FATAL("dds_create_topic: %s\n", dds_strretcode(-topic));

  /* Create a reliable Reader. */
  qos = dds_create_qos ();
  dds_qset_reliability (qos, DDS_RELIABILITY_RELIABLE, DDS_SECS (10));
  reader = dds_create_reader (participant, topic, qos, NULL);
  if (reader < 0)
    DDS_FATAL("dds_create_reader: %s\n", dds_strretcode(-reader));
  dds_delete_qos(qos);

  printf ("\n=== [Subscriber] Waiting for a sample ...\n");
  fflush (stdout);

  samples = malloc(numOfSamples * sizeof(void*));
  /* Initialize sample buffer, by pointing the void pointer within
   * the buffer array to a valid sample memory location. */
  for (int i = 0; i < numOfSamples; i++) {
    samples[i] = HelloWorldData_Msg__alloc ();
  }

  infos = malloc(numOfSamples * sizeof(dds_sample_info_t));
  
  /* Poll until data has been read. */
  while (true)
  {
    /* Do the actual read.
     * The return value contains the number of read samples. */
    rc = dds_read (reader, samples, infos, numOfSamples, numOfSamples);
    if (rc < 0)
      DDS_FATAL("dds_read: %s\n", dds_strretcode(-rc));

    /* Check if we read some data and it is valid. */
    if ((rc > 0) && (infos[0].valid_data))
    {
      for (int i = 0; i < numOfSamples; i++) {
        /* Print Message. */
        msg = (HelloWorldData_Msg*) samples[i];
        printf ("=== [Subscriber] Received : ");
        printf ("Message (%"PRId32", %s)\n", msg->userID, msg->message);
        fflush (stdout);
      }
      break;
    }
    else
    {
      /* Polling sleep. */
      dds_sleepfor (DDS_MSECS (20));
    }
  }

  /* Free the data location. */
  HelloWorldData_Msg_free (samples[0], DDS_FREE_ALL);

  /* Deleting the participant will delete all its children recursively as well. */
  rc = dds_delete (participant);
  if (rc != DDS_RETCODE_OK)
    DDS_FATAL("dds_delete: %s\n", dds_strretcode(-rc));

  return EXIT_SUCCESS;
}
```

Test 1 OK:

```
HelloworldPublisher 3
=== [Publisher]  Waiting for a reader to be discovered ...
=== [Publisher]  Writing : 
Message (1, HelloWorld)
=== [Publisher]  Writing : 
Message (2, HelloWorld)
=== [Publisher]  Writing : 
Message (3, HelloWorld)
```

```
HelloworldSubscriber 2
Num of samples: 2

=== [Subscriber] Waiting for a sample ...
=== [Subscriber] Received : Message (1, HelloWorld)
=== [Subscriber] Received : Message (2, HelloWorld)
```

Test 2 FAIL:

Remove @key annotation from HelloWorldData.idl

```
HelloworldSubscriber 2
Num of samples: 2

=== [Subscriber] Waiting for a sample ...
=== [Subscriber] Received : Message (3, HelloWorld)
=== [Subscriber] Received : Message (0, (null))
```

For some reason order of messages is not respected anymore.

If I understand correctly RELIABLE QOS should guarentee ordering whether @key present or not.

Running Test 2 in FastDDS produce expected result.

**Comment by eboasson** [comment]
> For some reason order of messages is not respected anymore.

I assume you're referring to the line

```
=== [Subscriber] Received : Message (0, (null))
```

That's not an out-of-order message, that's an "invalid sample". You're not the only one running into this nasty little detail in DDS, see, e.g., https://github.com/eclipse-cyclonedds/cyclonedds/issues/1595#issuecomment-1458427597 and https://github.com/eclipse-cyclonedds/cyclonedds/issues/1590#issuecomment-1453105811.

Your code is printing this "invalid sample" because of a bug in the subscriber side application code. This:
```C
    rc = dds_read (reader, samples, infos, numOfSamples, numOfSamples);
    if (rc < 0)
      DDS_FATAL("dds_read: %s\n", dds_strretcode(-rc));
    if ((rc > 0) && (infos[0].valid_data))
    {
      for (int i = 0; i < numOfSamples; i++) {
        /* Print Message. */
        msg = (HelloWorldData_Msg*) samples[i];
        printf ("=== [Subscriber] Received : ");
        printf ("Message (%"PRId32", %s)\n", msg->userID, msg->message);
        fflush (stdout);
      }
      break;
    }
```
was presumably meant to be something like (with apologies in advance for the likely presence of a typo because I've typed this in the comment box without trying it first):
```C
    rc = dds_read (reader, samples, infos, numOfSamples, numOfSamples);
    for (int i = 0; i < rc; i++) {
      if (! infos[i].valid_data) continue;
      msg = (HelloWorldData_Msg*) samples[i];
      printf ("=== [Subscriber] Received : ");
      printf ("Message (%"PRId32", %s)\n", msg->userID, msg->message);
      fflush (stdout);
    }
    if (rc > 0) break;
```
Note that there *two* changes: the first is to use the return value from `dds_read` as the loop bound, the second is to check `valid_data` for each sample. DDS read operations are non-blocking, so you simply receive all available samples up to the limit of `numOfSamples`.

Another detail is that `dds_read` leaves the samples in the reader history cache, it just marks them as read. If you'd call it in a loop (to deal with the non-blocking behaviour) you'd end up reading the same samples over and over again. That can be remedied by reading only "unread" samples using `dds_read_mask`, but generally speaking, this type of test is best done with `dds_take` and in a loop (see, e.g., https://github.com/eclipse-cyclonedds/cyclonedds/blob/d6906ebdea2021e693577788b1e5cb96cc758557/src/tools/ddsperf/ddsperf.c#L1192 and
https://github.com/eclipse-cyclonedds/cyclonedds/blob/d6906ebdea2021e693577788b1e5cb96cc758557/src/tools/ddsperf/ddsperf.c#L1025 — incidentally that code also checks the order).

Then there is one more thing, which is that the reader history cache only stores multiple samples of a single key value if it is configured to do so by using `KEEP_LAST` with a `depth` > 1 or `KEEP_ALL`. The default is `KEEP_LAST` with a depth of 1, and that means it stores only the most recent sample for each key value. If there is no key field, then there is simply one instance. See "2.2.1.2.2 Overall Conceptual Model" in the spec (formatting following the spec):

> In case a set of instances is gathered under the same topic, different instances must be distinguishable. This is achieved by means of the values of some data fields that form the **key** to that data set. The **key** description (i.e., the list of data fields whose value forms the key) has to be indicated to the middleware. The rule is simple: *different data values with the same key value represent successive values for the same instance, while different data values with different key values represent different instances.* If no key is provided, the data set associated with the **Topic** is restricted to a single instance.

So you probably also want to set the history QoS differently in your test.

**Comment by lambdaprime** [comment]
Hi @eboasson 

Thank you for your answer.

After I fixed subscriber based on your comments **AND** added:

```
dds_qset_history (qos, DDS_HISTORY_KEEP_ALL, 0);
```

I could see the order of the messages is respected properly
```
=== [Subscriber] Received : Message (1, HelloWorld)
=== [Subscriber] Received : Message (2, HelloWorld)
```

Thank you for reference to DDS specification describing @key behavior.
