### ISSUE TITLE
Minor Grammar Mistakes in README

### ISSUE THREAD

**Issue by OliverHeilmann** [eclipse-cyclonedds/cyclonedds#1678]
# Description
Hello! Just suggesting a couple minor grammar changes to the [README.md](https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/README.md) file. 

Initially, I cloned the repository, made a branch and tried to open a pull request with the proposed changes.... then realised there were more steps when looking through the [CONTRIBUTING](https://github.com/eclipse-cyclonedds/cyclonedds/blob/53a92b1e6643d9818b741898b95e698aba5016d9/CONTRIBUTING.md) file. 

Instead of going through the contributor process, perhaps someone can throw these changes into an open pull request? If I have larger suggestions, perhaps I'll take the plunge! Thanks.

## Change 1
<img width="1190" alt="Screenshot 2023-05-01 at 18 08 18" src="https://user-images.githubusercontent.com/49697817/235494179-87a8a3e5-d9e8-480a-8cd3-a3092b33d532.png">

## Change 2
<img width="1190" alt="Screenshot 2023-05-01 at 18 08 25" src="https://user-images.githubusercontent.com/49697817/235494230-b29b71ce-836d-47ed-a30a-ad6a4f150631.png">

**Comment by eboasson** [comment]
Thanks for pointing it out @OliverHeilmann. Maybe I should have another look at the README and the CONTRIBUTING file anyway, because some things are bound to be out of date 🙂 Indeed, this requirement:

> Commits that are provided by non-committers must have a Signed-off-by field in the footer indicating that the author is aware of the terms by which the contribution has been provided to the project.

has been removed some time ago by the Eclipse Foundation. I am still adding time by force of habit ...

So I guess I have found the perfect vehicle for throwing these small changes into some other PR!
