### ISSUE TITLE
The length of string in code generated by idlc.

### ISSUE THREAD

**Issue by neptune-wind** [eclipse-cyclonedds/cyclonedds#1684]
In cyclonedds C, if I define a message field in idl as string, the generated code will denote the field with char*, but no length information. If the byte stream I want to transfer contains '\0', will there be a situation where the message cannot be sent in its entirety?

**Comment by eboasson** [comment]
Hi @neptune-wind, what you're looking for is the "sequence" type. In particular `sequence<octet>`, which is mapped to
```C
struct {
  uint32_t _maximum;
  uint32_t _length;
  uint8_t *_buffer;
  bool _release;
}
```
`_buffer[0]` .. `_buffer[_length-1]` is the current value, `_maximum` ≥ `_length` is the amount of memory currently allocated.

`_release` is about ownership: Cyclone owns the memory and will allocate/reallocate/free as needed if `_release` is true or if all fields are 0. Otherwise the application owns the memory and Cyclone will only change the contents.

**Comment by neptune-wind** [comment]
Thank you. I can solve it by "sequence". This issue could be closed.
