### ISSUE TITLE
What is the function of the dq.user thread

### ISSUE THREAD

**Issue by beiduofenkuaipao** [eclipse-cyclonedds/cyclonedds#1709]
I can see from the code that the dq.user thread is related to processing data, but I added print information in the test program, except when exiting the program to enter the thread, the other whole process did not call this thread. I wanted to ask what this thread was for, because I couldn't find the answer I was looking for in the documentation.

**Comment by eboasson** [comment]
Hi @beiduofenkuaipao!

Cyclone by default delivers data from the network to the readers synchronously, with the thread taking the packet from the socket also updating the reader history caches. It can also deliver the data to the readers on a separate thread, with a queue in between. There are some advantages and disadvantages to both options, with the default generally being the one that causes the least surprises.

It can in principle handle many of these queues, each with its own thread. In practice it only has two, the one for "user" data, and one for "builtin" protocol messages, primarily discovery data. The built-in messages always go through this asynchronous route, to ensure the discovery processing doesn't interfere with delivering user data.

The only thing that the "dq.user" thread does in the default configuration is a tiny bit of processing whenever a proxy writer is deleted, but of course that is not actually useful because nothing of that writer ever got processed on that thread.
