### ISSUE TITLE
Listener called back when the reader is not ready

### ISSUE THREAD

**Issue by stillsimon** [eclipse-cyclonedds/cyclonedds#174]
Hi! I encounter a serious bug when creating a reader with a on_data_available listener. When the reader is being created, if some data samples come, the listener will still be called and the code will dump in the listener callback(reader is still being created). Here is the code:

```
#include "ddsc/dds.h"
#include "HelloWorldData.h"
#include <stdio.h>
#include <stdlib.h>

int nodeID = 999;
int sample_received = 0;

#define MAX_SAMPLES 10

void reader_on_data_available(dds_entity_t reader, void *arg)
{
    HelloWorldData_Msg *msg;
    void *samples[MAX_SAMPLES] = {0};
    dds_sample_info_t infos[MAX_SAMPLES];
    dds_return_t ret;

    ret = dds_take(reader, samples, infos, MAX_SAMPLES, MAX_SAMPLES);
    //ret = dds_take_mask(reader, samples, infos, MAX_SAMPLES, MAX_SAMPLES, DDS_NEW_VIEW_STATE);
    // dds_take_mask with DDS_NEW_VIEW_STATE will not result this error.
    DDS_ERR_CHECK (ret, DDS_CHECK_REPORT | DDS_CHECK_EXIT);

    if(ret > 0) {
        for (int i = 0; i < ret; i++) {
            /* Check if we read some data and it is valid. */
            if (infos[i].valid_data) {
                /* Print Message. */
                msg = (HelloWorldData_Msg *) samples[i];
                printf("=== [Node %d] Received : ", nodeID);
                printf("Message (%d, %s)\n", msg->userID, msg->message);
                sample_received++;
            }
        }
    }
}

int main(int argc, char **argv)
{
    dds_entity_t participant;
    dds_entity_t topic;
    dds_entity_t writer;
    dds_entity_t reader;
    dds_qos_t *writer_qos = NULL;
    dds_qos_t *reader_qos = NULL;
    dds_listener_t *reader_listener = NULL;
    dds_return_t ret;
    HelloWorldData_Msg msg;
    (void) argc;
    (void) argv;

    if (argc == 2) {
        nodeID = atof(argv[1]);
    }

    /* Create a Participant. */
    participant = dds_create_participant(DDS_DOMAIN_DEFAULT, NULL, NULL);
    DDS_ERR_CHECK (participant, DDS_CHECK_REPORT | DDS_CHECK_EXIT);

    /* Create a Topic. */
    topic = dds_create_topic(participant, &HelloWorldData_Msg_desc,
                             "HelloWorldData_Msg", NULL, NULL);
    DDS_ERR_CHECK (topic, DDS_CHECK_REPORT | DDS_CHECK_EXIT);

    /* Create a Writer. */
    writer_qos = dds_create_qos();
    dds_qset_reliability(writer_qos, DDS_RELIABILITY_RELIABLE, DDS_MSECS (100));
    dds_qset_durability(writer_qos, DDS_DURABILITY_TRANSIENT_LOCAL);
    writer = dds_create_writer(participant, topic, writer_qos, NULL);
    DDS_ERR_CHECK (writer, DDS_CHECK_REPORT | DDS_CHECK_EXIT);

    /* Create a message to write. */
    msg.userID = nodeID;
    msg.message = "Hello World";

    printf("=== [Publisher]  Writing : ");
    printf("Message (%d, %s)\n", msg.userID, msg.message);

    ret = dds_write(writer, &msg);
    DDS_ERR_CHECK (ret, DDS_CHECK_REPORT | DDS_CHECK_EXIT);

    /* Create a Reader. */
    reader_qos = dds_create_qos();
    dds_qset_reliability(reader_qos, DDS_RELIABILITY_RELIABLE, DDS_MSECS (100));
    dds_qset_durability(reader_qos, DDS_DURABILITY_TRANSIENT_LOCAL);
    reader_listener = dds_create_listener(reader);
    dds_lset_data_available(reader_listener, reader_on_data_available);
    reader = dds_create_reader(participant, topic, reader_qos, reader_listener);
    DDS_ERR_CHECK (reader, DDS_CHECK_REPORT | DDS_CHECK_EXIT);
    dds_sleepfor(DDS_SECS(15));

    /* Deleting the participant will delete all its children recursively as well. */
    ret = dds_delete(participant);
    DDS_ERR_CHECK (ret, DDS_CHECK_REPORT | DDS_CHECK_EXIT);

    dds_delete_qos(reader_qos);
    dds_delete_qos(writer_qos);
    dds_delete_listener(reader_listener);

    return EXIT_SUCCESS;
}
```

**Comment by eboasson** [comment]
Hi @stillsimon,

Not to worry, that one I fixed 3 weeks ago :smile:, when I ran into it with a subscription to the built-in topics: see a6b5229510dc62df239edeb93f38e01df10cae31. I admit I did not immediately realise that it also affects all late-joining readers for which historical data is locally available.

Note: the major abstraction layer rewrite of some time ago shuffled things around and moved the "ddsc/dds.h" to "dds/dds.h" and also eliminated the DDS_ERR_CHECK macro, as it is much better to handle it yourself with a one-liner. For backwards compatibility, there is still a "ddsc/dds.h" file that simply includes the real file from the new location. (So that requires no additional work.)

What I now see I overlooked is that no definition for DDS_ERR_CHECK got added in the "ddsc/dds.h" for backwards-compatibility. That's a bit of a shame ...

My recommendation would be to just change the code and simply test whether ret is negative (always an error), but I'd be happy to re-add the definition in "ddsc/dds.h". It's just that you'd have to wait a little while for that to happen. If you decide to add it yourself, please consider doing a pull-request for it!

**Comment by stillsimon** [comment]
I see! I have been using the release version for a long time. It seems the release version is behind the master for a long distance. Is there any plan to update the release version?

**Comment by k0ekk0ek** [comment]
@stillsimon, this is really up to @eboasson, but I believe we're aiming to release a 0.2.0 soonish (nothing is set in stone yet). The bits and pieces we'd like to have in that release are starting to get finished. So, I can't give you an eta, but I can tell it's in the works.

**Comment by eboasson** [comment]
@stillsimon, there'll definitely be a new release. I have to make up my mind what exactly it will bring and start the process. It being half May and it taking some time, I would say sometime in June is reasonable expectation.

Is there a particular constraint that made you keep using the release version? Just trying to understand because doing an official release is fairly heavyweight and involves the effort from volunteers outside the project to check it out and decide whether it is in sufficient shape to allow the release to continue. So that can't be done too often.

**Comment by stillsimon** [comment]
That's fine! I just thought the release version would be more stable. It seems the release version suppresses the assert function after install.

**Comment by eboasson** [comment]
> I just thought the release version would be more stable.

A rather reasonable assumption 😁 I did put some additional effort into checking out various things for the release — and intend to do so again for the next — but at this stage in the project, it is probably not really much of a difference.

> It seems the release version suppresses the assert function after install.

It only depends on the CMAKE_BUILD_TYPE: "Release" and "RelWithDebInfo" (the default) will get you an optimized build without assertions, and "Debug" will get you an unoptimized one with assertions. You can install any kind of build.

I don't know CMake well enough to give you good advice on how to change these settings properly ... I have on occasion simply edited the generated make/ninja files. For "make" there are various "flags.make" files in the build directory that have the compiler settings (and so also the "-DNDEBUG"), but you'd really only have to edit ``core/CMakeFiles/ddsc.dir/flags.make``. With ninja it is even easier: just delete all occurrences of "-DNDEBUG" in build.ninja.

Thanks to a code change induced by #125 the performance consequence of having assertions enabled is pretty minor now, but as I think people have expectations of what those CMake build types mean and I don't think the default behaviour should be change.

**Comment by stillsimon** [comment]
OK, got it! Thank you!

**Comment by eboasson** [comment]
Guess I can close this ...
