### ISSUE TITLE
How to shorten the recovery time of cyclonedds after network disconnection during data transmission?

### ISSUE THREAD

**Issue by FantasticSaltedFish** [eclipse-cyclonedds/cyclonedds#1764]
Hi friends:
There is an experiment where the publisher is sending data to the subscriber and everything is normal. However, when unplugging the internet cable and then inserting it again (about 1 second), the subscriber needs to wait for about 40 seconds to resume receiving the publisher's data. The disconnection time for this data transmission is too long. Is there any way to shorten the recovery time for this transmission?

**Comment by eboasson** [comment]
It would be interesting to know what takes so long. 1 second is usually not long enough to cause a lease to expiry by itself, so that suggests it is caused by the network stack of the OS or the switches. I know of systems where this DDSI protocol stack runs and has been subjected to hundreds (if not thousands) of physical cable disconnections of various durations during testing, and this behaviour didn't show up.

Can you repeat the experiment while capturing network traffic on both sides with wireshark and Cyclone DDS tracing enabled as well?

The tracing is only interesting because it is the easiest way (for me anyway) to check whether lease expiry occurred inside Cyclone DDS, without having to infer it from packet captures. Less work and fewer assumptions is always a good thing when analysing misbehaviours.

Assuming no lease expiry, then hopefully the capture will be enough to infer where the packets went that Cyclone would've been sending. One thing in particular that might be of interest (also captured in Wireshark) are IGMPv3 packets dealing with multicast group membership at the network level.

**Comment by FantasticSaltedFish** [comment]
here is the captured image of publisher:
![publisher_wireshark](https://github.com/eclipse-cyclonedds/cyclonedds/assets/43626760/451dbcb9-5613-4be9-91c2-a0e45ce59ef8)

here is the captured image of subscriber:
![subscribe_wireshark](https://github.com/eclipse-cyclonedds/cyclonedds/assets/43626760/b9eca3cf-07b6-4163-b02d-0d17051d6722)

**Comment by FantasticSaltedFish** [comment]
The above situation I mentioned occurred on one computer, and the network recovery time of other computers is relatively fast, which may be related to the system status. This issue is temporarily closed.
