### ISSUE TITLE
watermark in XML file

### ISSUE THREAD

**Issue by Titikshaaaa** [eclipse-cyclonedds/cyclonedds#1777]
<Watermarks><WhcAdaptive>false</WhcAdaptive><WhcHigh >3B</WhcHigh>
  <WhcHighInit >2B</WhcHighInit>
   <WhcLow >1B</WhcLow>
  </Watermarks>

In this I have set WhcHigh 3B 

My msg struct is as below

module HelloWorldData
{
  struct Msg
  {
    @key
    long userID;
    string message;
    long test1;
    long test2;
  };
};
 According to me the writer should be suspended but it is working. Can you tell me where i am going wrong?

**Comment by eboasson** [comment]
Hi @Titikshaaaa the watermarks (currently) only apply to reliable writers with a `KEEP_ALL` history kind set in their QoS.

Obviously for unreliable ("best-effort") writers, it doesn't apply because there is nothing to acknowledge, and for `KEEP_LAST` I stopped using it in b5251d03908cffb864e807ac5bc65502c7b61995. That was after a bit of deliberation. A big part of the reason DDS is put together the way it is, is to have minimal coupling between the readers and writers, and in particular to allow writers to publish updates much faster than a reader can keep up with. With that in mind, it seemed to be the least-bad way to prevent blocking just because the readers can't keep up.

That doesn't mean there isn't a good argument to also (or optionally) using it for `KEEP_LAST` writers. We might put it back in. 🙂

There's one more catch. I built it to allow sending data that makes it overrun the high limit, it only disallows sending data once the limit has been reached. Otherwise dealing with point clouds of 15MB would be tricky.

If you use reliable, keep-all and write quicker than the reader can ACK (or you prevent the ACKs from reaching the writer) it should block.

**Comment by Titikshaaaa** [comment]
Thanks @ebassoon for the information it was usefull. I would like to know form where can i get to know the consolidate list of working configurations for the cyclone features as i am seeing exhaustive features are supported in cyclonedds.I am able to see the list of configurations here. But out of these how will we know that what is supported in what versions as you have informed above.
https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/docs/manual/config/config_file_reference.rst

**Comment by eboasson** [comment]
Hi @Titikshaaaa, an exhaustive list of features doesn't really exist and what there is only very spottily lists how they interact. Most of the time I know these things quite well, but that's not a scalable solution. And even if I do know quite well, I get it wrong every now and then, too, like just now with that commit I referenced. If only I'd more carefully checked the commit message because it said:

> Internal/AggressiveKeepLastWhc: changing the setting from the default made no sense whatsoever in Cyclone -- it would only add flow-control and potentially block a keep-last writer where the spec forbids that.

So what that commit did was remove the option for something that wasn't practically useful ...

Adding such documentation would really improve the project but it just never seems to happen. There is a lot of information hidden inside GitHub comments (like what is happening just now, on this particular issue), and we did make an effort to [index](https://cyclonedds.io/content/deep-dives.html) them a bit, but we have never really found the time to consolidate it all and maintain it as proper documentation. Indeed, that index hasn't even been updated recently.

To me, it seems this is an area where anyone interested could really help. I suspect most people would be like me: run into a problem, somehow find a solution and happily continue with the next problem without leaving proper documentation for other people ... But perhaps not everyone is like that.

**Comment by Titikshaaaa** [comment]
Thanks @eboasson I understand. I also had another doubt. I am setting CycloneDDS/Domain/Compatibility/ExplicitlyPublishQosSetToDefault to true
How can I observe that default qos are explicitely published in discovery protocol

**Comment by eboasson** [comment]
The easiest way is to look at a packet capture with Wireshark.

**Comment by Titikshaaaa** [comment]
Yes @eboasson  I was looking in that only but not able to figure the difference when it is set to true

**Comment by eboasson** [comment]
You would typically see far more QoS entries in the discovery data when it is set to true. I don't think you'll see a big difference for a participant because it doesn't have many QoS settings, but you should see it you look at a reader/writer (what wireshark shows in the summary as `DATA(r)` and `DATA(w)`).

An easy way to do that would be to run `ddsperf sanity` twice while capturing packets. (You need two processes, otherwise no reader/writer discovery data is sent over the network.)

**Comment by Titikshaaaa** [comment]
Okayy  .. For /CycloneDDS/Domain/Internal/BuiltinEndpointSet
One of: full, writers, minimal

This element controls which participants will have which built-in endpoints for the discovery and liveliness protocols. Valid values are:
full: all participants have all endpoints;
writers: all participants have the writers, but just one has the readers;
minimal: only one participant has built-in endpoints.

How can i capture the difference when it is set to full or minimal??
