### ISSUE TITLE
Update UserData Qos Dynamically

### ISSUE THREAD

**Issue by stillsimon** [eclipse-cyclonedds/cyclonedds#179]
Hi, I have a requirement to do userdata updating for participant and writer in my project. It seems Cyclone doesn't support for this function right now. Is there any plan to add this function? Thanks!
https://github.com/eclipse-cyclonedds/cyclonedds/blob/dba4e6d391a75440654b740f389e72256858a3bf/src/core/ddsc/src/dds_participant.c#L119-L135

https://github.com/eclipse-cyclonedds/cyclonedds/blob/dba4e6d391a75440654b740f389e72256858a3bf/src/core/ddsc/src/dds_writer.c#L266-L312

**Comment by eboasson** [comment]
Hi @stillsimon, yes, it will be. It is just that no one ever got around to doing it ... It is as simple as updating the actual QoS (but it has to be done both in the ddsc/... and in the ddsi/... stuff, because the latter is the bit that drives the discovery — the two should be a bit more integrated, at least with respect to the QoS anyway).

The practical thing about changing user data is that it has no meaning to the DDS code and so only involves updating the state and the corresponding built-in topics. A quick hack to do just the user data should be pretty straightforward and not cause muh trouble in the rest of the code. So I might opt for that — or for suggesting you might want to give it a try :smile: — if it needs to be addressed in the short term. 

For the participant QoS, I think simply triggering a write of the participant discovery message (``spdp_write``) will trigger an update of the QoS at the receivers and a subsequent update of the built-in topics. It isn't that simple for readers and writers because you might change QoS that affect the reader/writer matching. That complication is also the reason it still hasn't been done.

**Comment by stillsimon** [comment]
Thanks! This requirement is not urgent. Keep your pace and notify me when you finished!:smiley:

**Comment by stillsimon** [comment]
Hi, it seems the userdata qos update function is urgent in my project. Can you upload a patch for this function first? Or give me some hints for doing it. I can have a try. Thanks!

**Comment by eboasson** [comment]
I'll see what I can do ... would supporting it just for the participant be sufficient at first?

**Comment by stillsimon** [comment]
Yes! That will be sufficient! :smile:

**Comment by eboasson** [comment]
I think this will probably do the trick: 0644bb717f97915422c0548ef03e5d3289ef122b (I did try it, but only once 😁)

I won't merge it into master like this: the way it keeps track of the sequence number of the SPDP message is far too hacky, and I've also not worried at all about doing it somewhat elegantly. The principle would be the same, though: change the QoS, publish the built-in topic and push the discovery data out. On the receiving side, if it has a higher sequence number than the last one seen, take the new values for the QoS and publish the built-in topic.

Don't mind the two failing tests that make all builds fail: that's just because I haven't updated the tests that expect set_qos to fail ...

**Comment by stillsimon** [comment]
Thank you so much! I will try with the patch provided!

**Comment by eboasson** [comment]
@stillsimon full support for user/group/topic data has been in the master branch for some time now, so I'm closing the issue.
