### ISSUE TITLE
Using cyclonedds in multiprocess/multithreaded code

### ISSUE THREAD

**Issue by alknemeyer** [eclipse-cyclonedds/cyclonedds#1795]
Hello,

Could you mention whether any precautions need to be taken when using cyclonedds in multiprocess/multithreaded code?

For example, say a topic writer is created and then used across two threads. Do we as API users need to put a lock on the writer, to ensure publication is done one at a time, or is that handled by cyclonedds behind the scenes? Does this ever change depending on the way cyclonedds is configured?

Sorry if this has already been described somewhere. I have a feeling I've been searching the wrong terms. Based on references to mutexes and so on in these GitHub issues, I assume cyclonedds handles this already. But clarification would be great :)

**Comment by eboasson** [comment]
It may very well be that your question isn't answered anywhere in the documentation because I've always considered support for multi-threaded processes a given.

(I went for multi-thread safe on day one, now more than 25 years ago—not quite DDS, but an ancestor. That's even before Linux had decent multithreading 🙂)

**Comment by alknemeyer** [comment]
Just what I needed to hear :slightly_smiling_face: Thank you!
