### ISSUE TITLE
Using RTPS reserved field cause unpredictable problem

### ISSUE THREAD

**Issue by skysky97** [eclipse-cyclonedds/cyclonedds#1805]
The cdr code using CDRHeader.options to store pad lenght of serialized data. The `options` filed after PL_CDR_LE is reserved in rtps 2.2 and should not be parsed.

This causes problems when we are writing a tool converting ros2 bags bewtten different versions of msg, because the length maybe wrong if pad is not re-calculated.

**Comment by eboasson** [comment]
Be careful with OMG specifications!

XTypes 1.3 7.6.3.1.2 states:
> The RTPS specification does not define any settings for the 2 byte options field and further states that a receiver should not interpret it when it reads the options field. This DDS-XTYPES specification changes this defining the use of some bits in the options field.
> Implementations of this specification shall set the least significant two bits in the second byte of the options field to a value that encodes the number of padding bytes needed after the end of the serialized payload in order to reach the next 4-byte aligned offset. Specifically, the least significant two bits shall be set to binary 00 if no padding bits would be needed and binary 01, 10, or 11 if, respectively, there would be one, two, or three bytes of padding needed. These bits in the options field shall be interpreted by the receiver to determine where the serialized data exactly ended.

We implement XTypes 1.3, so that's what we do ...

Given that you're running into this with `rosbag` the `PL_CDR_LE` you're seeing almost certainly refers to discovery data. This data should never have any padding because it necessarily ends in a "sentinel" parameter of 4 bytes that itself must be 4-byte aligned. And so options should always be 0 for this type of data.

For non-discovery data, the Cyclone RMW layer uses a custom serializer because the ROS 2 in-memory representation differs from the OMG spec'd one. I believe that one always set the two padding bits to 0 (arguably correctly so as that one isn't implementing XTypes).

In short, I am somewhat surprised you're running into an issue with the padding bits.

That said, whichever version of DDS you're dealing has to support data where the padding bits are 0 even when there is some padding at the end, because of non-XTypes implementations (including backwards compatibility) and they all ignore any payload bytes not needed for deserializing the data. So simply resetting those two bits to 0 is actually not going to do any real harm.

As a historical note: the padding information was added because an early version of XTypes (the one that introduced the `XCDR1` encoding) has a problem if the writer publishes `struct { octet x; };` while the reader expects `struct { octet x,y; };` while type-widening is permitted: then the first padding byte added by the writer would get misinterpreted as data because there would be no way for the reader to know it was padding. This also solved the problem that existed pre-XTypes for such cases, because back then there was no type checking at all.

Later versions of the spec have deprecated `XCDR1` and require `XCDR2` instead because the older encoding can't support appending fields to a nested struct. In `XCDR2` there is explicit length information available in the cases where it matters, and so the padding information is now required but superfluous. (With the small caveat that there are so many options and variations that I am only almost sure it is superfluous, not exactly sure.)

**Comment by skysky97** [comment]
Thanks, I totally missed xtypes!

> In short, I am somewhat surprised you're running into an issue with the padding bits.

We have many rosbag files recorded before, while msgs are always changed and without a good evolution mechanism. So we have to pickup values from old rosbags and write to new rosbags so that it can be replayed with latest version of msg.  And because of misunderstanding of options,  pad value are copied to new rosbags too.

But I don't know how `ros2 bag replay` works, it seems the wrong pad value got send out and then lead to "length too short" error at reader side. E.g. old rosbag samples may have a pad of 2 and coping this value 2 to the new rosbag which actually have pad of 0. Reader is cyclonedds too and it cares pad value.

> For non-discovery data, the Cyclone RMW layer uses a custom serializer because the ROS 2 in-memory representation differs from the OMG spec'd one. I believe that one always set the two padding bits to 0 (arguably correctly so as that one isn't implementing XTypes).

Cyclonedds support XTypes, I must get the correct padding right? Or set to 0 is enought?

**Comment by eboasson** [comment]
Cyclone certainly doesn't care if there are leftover bytes after deserializing. Always setting it to 0 should work.

Still, it surprises me that you are dealing with some that have something other than 0 in this specific context. Do you have a (minimal/compact) reproducer that I could take a look at just so I understand where reality differs from my expectations?

**Comment by skysky97** [comment]
> Still, it surprises me that you are dealing with some that have something other than 0 in this specific context.

The pub and sub running on device are using cyclone standalone, not ROS2 node. I think that's the gap. 

And thanks again for your patient explanation.

**Comment by eboasson** [comment]
> The pub and sub running on device are using cyclone standalone, not ROS2 node. I think that's the gap.

Ah yes! Thanks for letting me know ☺️
