### ISSUE TITLE
Keyed and Keyless Topic

### ISSUE THREAD

**Issue by Titikshaaaa** [eclipse-cyclonedds/cyclonedds#1808]
Acoording to me 
struct TempSensorType

{ short id; float temp; float hum;  TemperatureScale scale; }
;
#pragma keylist TempSensorType id

Here it is a keyed topic as id is the key
The main difference between Keyed and Keyless topics is their number of instances. 
Keyless topics have only once instance, thus can be thought as singletons. Keyed 
topics have once instance per key-value.
Now i want to see practically how keyed and keyless topic gives different result. I am not able to figure out how

**Comment by eboasson** [comment]
I'm afraid I don't understand your question, it is too general.

But maybe this is something you could do:
* create a reader with keep-last-1 history and a writer with keep-all (for good measure, it won't really affect the experiment)
* publish 2 samples, one with `id` = 0, and one with `id` = 1
* read all that is available in the reader

In the version where there is no key, you'd expect to only see one sample, the one with `id` = 1. In the other version you'd expect to see two, one for `id` = 0 and one for `id` = 1.

The crucial difference this makes is that in the keyed version, if the reader application doesn't keep up with what the writer publishes it is nonetheless certain to see updates to all key values whenever it does look. In the version without key values, there is no guarantee it will see all the key values, let alone get updates regularly.

There is also a relationship to historical data (so with "durability" QoS set to something other than "volatile"), but that's very much like the above taken to the extreme where the starts late instead of just being slow. Only in the case where you use keys will it see at least some data for each key value.

By the way, the `#pragma keylist` trick dates back to the time that there was no standardized way for specifying which fields are key fields. These days there is one and I would recommend using it:
```
struct TempSensorType {
  @key short id;
  float temp;
  float hum;
  TemperatureScale scale;
}
```

**Comment by Titikshaaaa** [comment]
Thanks @eboasson.
