### ISSUE TITLE
shm transport

### ISSUE THREAD

**Issue by yanxiaochun1005** [eclipse-cyclonedds/cyclonedds#1819]
After configuring the shared memory transfer method, I found that when the network cards of the publisher and Dingyue end were inconsistent, the publisher sent one copy of data, and the subscriber received two copies. One is shared memory data, and the other is network card data.

**Comment by eboasson** [comment]
Hi @yanxiaochun1005, I should've read more closely when I first saw your issue: then I would have responded straightaway instead of first finding some time to check some things ... Sorry ...

We're short-circuiting the communication via shared memory, completely avoiding the network protocol stack when possible, but this has some consequences. In particular: the sequence number checking that is part of the network protocol is also skipped. This is fine, as long as the paths are carefully kept apart.

What you ran into is that doing all this requires us to come up with a "locator" (DDS protocol speak for an address) for the machine when you use Iceoryx, and we default to the MAC address of the interface. If a reader and writer have the *same* Iceoryx locator we rely on Iceoryx for that pair, otherwise on the network. If you configure two different network interfaces, then the Iceoryx locators will be different, and it'll send the data via both. Then, because of the short-circuiting, you get it twice.

There is a configuration option to override the Iceoryx locator for cases like this: `SharedMemory/Locator`. This way you can force it to be the same one on a machine, also when you use different network interfaces.

**Comment by yanxiaochun1005** [comment]
thanks
