### ISSUE TITLE
Hey, i am using CycloneDDS and CycloneDDS-CXX on Android successfully for x86_64, x86, armv8, armv7.

### ISSUE THREAD

**Issue by wuyanze0226** [eclipse-cyclonedds/cyclonedds#1828]
Hey, i am using CycloneDDS and CycloneDDS-CXX on Android successfully for x86_64, x86, armv8, armv7.
I have no idea what `Soong` is but in my case i just use cmake and the android ndk to cross-compile the cyclone libs for android, pretty easy.
Later i link my Qt based Android-App (C++) against the android-cyclonedds-libs.
So i can help you out if you have specific build questions/problems during the Android crosscompile of the cyclonedds libs.

_Originally posted by @trittsv in https://github.com/eclipse-cyclonedds/cyclonedds/issues/1705#issuecomment-1564386662_

would you mind telling me how to use CycloneDDS and CycloneDDS-CXX on Android ? Thank you very much. I meet some problems. such as:

            
![屏幕截图 2023-09-15 201442](https://user-images.githubusercontent.com/78069913/268278291-c3b1eec3-c298-49ab-a5dd-6a03cfd6d4ea.png)

what should i do now?

**Comment by trittsv** [comment]
@wuyanze0226 you are trying to execute a binary which is not compatible with the architecture/os of your computer (because Cross-compiling).

You first have to compile idlc with your computers architecture and os, for example Linux/gcc and x86_64.

Then use this idlc binary to generate to code from your idl files.

Use the generated source files in your android cross-compile.

In the cyclone android build you can deactivate the build of idlc via cmake options.
