### ISSUE TITLE
Questions about symbol removal

### ISSUE THREAD

**Issue by nabetetsu** [eclipse-cyclonedds/cyclonedds#1833]
I guess the ddsc symbols have been hidden since [this commit](https://github.com/eclipse-cyclonedds/cyclonedds/commit/bcdaf065083da970b5a976bf29fd76bb68e943ac), and this has caused the analysis tool we are developing, CARET, to stop working.

CARET repository: https://github.com/tier4/caret
CARET document: https://tier4.github.io/CARET_doc/latest/

CARET is one of the performance analysis tool dedicated with ROS 2 applications. CARET hooks into the characteristic functions of ROS 2 and DDS layers to add Lttng trace points without changing the existing process. CARET uses this tracepoint to trace the transmission of a topic in ROS 2 applications and build an end-to-end path.

The important symbol in cyclonedds to construct a path is `dds_write_impl()` ; if this symbol cannot be hooked, the path cannot be ocnstructed.
It would be very helpful if you could leave symbol of `dds_write_impl()` in some way.

**Comment by eboasson** [comment]
Hi @nabetetsu, the quickest fix would be to do `-DBUILD_TESTING=1`: then all symbols are exported, like they used to be. There are no additional dependencies to build the tests, it only takes a few seconds longer. Would that work for you?

**Comment by nabetetsu** [comment]
Hi @eboasson, thank you for your suggestion.
Your suggestion were very useful for the purpose of checking the operation at hand.

On the other hand, we are considering to build farm support of CARET in the future, and we are concerned that if we have to rebuild cyclonedds in that case, the convenience will be reduced.
It would be the most desirable for us/users to be able to refer to symbols of cyclonedds which is installed by apt, but would it be unacceptable to cancel the modification of symbol removal?

**Comment by nabetetsu** [comment]
@eboasson 
An alternative solution is to add Lttng trace points in the code of cyclonedds.
However, this is not a very practical solution as it creates a dependency with Lttng.

**Comment by eboasson** [comment]
Hi @nabetetsu, I'm sorry I have been so bad at responding to issues on GitHub lately. First off, I do want to support the needs of those who want to do performance analysis, especially also in the context of ROS 2.

From my perspective it would obviously be best if you relied on the `dds_write`, `dds_writedispose`, `dds_write_ts`, &c. symbols instead of `dds_write_impl`, because those are the entry points in the stable API, but I can see that having so many entry points to deal with is not very pleasant. While it would be manageable just for ROS 2, but I suspect your instrumentation might also be of interest outside ROS 2.

Exporting `dds_write_impl` in normal builds would be easy enough and there is precedent for exporting some symbols that are not strictly part of the API for one reason or another. I think there would be not any harm in also exporting `dds_write_impl` but that does not mean we will promise it stays around or keeps doing exactly the thing. (It's been there forever, doing the same thing; not promising doesn't mean there'll be a change affecting your using `dds_write_impl` anytime soon.)

If that is good enough for you and @dpotman also thinks that exporting this particular non-API function brings sufficient value, then let's change Cyclone to always export it.

**Comment by dpotman** [comment]
Exporting the `dds_write_impl` function (and similar cases in the future) for this goal is fine with me; it's not in an installed header, so there's no chance of accidentally using this non-API function. How about using a macro alias for this, e.g. 'DDS_EXPORT_INTERNAL_API', to make clear this is a special case? We can add the rationale for exporting this in a comment on this macro definition.
