### ISSUE TITLE
Does these code useless?

### ISSUE THREAD

**Issue by binbowang1987** [eclipse-cyclonedds/cyclonedds#1872]
I searched `dds_builtintopic_participant` and `dds_builtintopic_endpoint` in the whole codebase, but not found any place writing both. Also, can not enter `ddsi_serdata_builtin_from_sample` when in gdb. So, is this code snippet useless? Hope for your help @eboasson, thank you.
https://github.com/eclipse-cyclonedds/cyclonedds/blob/49f87b5623f9a994a588c7f046a9ed443840f6be/src/core/ddsc/src/dds_serdata_builtintopic.c#L255-L296

**Comment by eboasson** [comment]
Your confusion is probably caused by all this being rather indirectly. It is all roughly the same, the first one that popped up in my scrolling through the source is the one for writers:
* `dds_create_writer` (in `ddsc`) calls `ddsi_new_writer_guid` (in `ddsi`), which then calls [`ddsi_builtintopic_write_endpoint`](https://github.com/eclipse-cyclonedds/cyclonedds/blob/49f87b5623f9a994a588c7f046a9ed443840f6be/src/core/ddsi/src/ddsi_endpoint.c#L1520)
* then you end up [here](https://github.com/eclipse-cyclonedds/cyclonedds/blob/49f87b5623f9a994a588c7f046a9ed443840f6be/src/core/ddsi/include/dds/ddsi/ddsi_builtin_topic_if.h#L50) which in a "normal" Cyclone build ends up in [`dds__builtin_write_endpoint`](https://github.com/eclipse-cyclonedds/cyclonedds/blob/49f87b5623f9a994a588c7f046a9ed443840f6be/src/core/ddsc/src/dds_builtin.c#L323) because [that's the target of the indirect call](https://github.com/eclipse-cyclonedds/cyclonedds/blob/49f87b5623f9a994a588c7f046a9ed443840f6be/src/core/ddsc/src/dds_builtin.c#L382)
* there, it invokes [`dds__builtin_make_sample_endpoint`](https://github.com/eclipse-cyclonedds/cyclonedds/blob/49f87b5623f9a994a588c7f046a9ed443840f6be/src/core/ddsc/src/dds_builtin.c#L265)
* which brings you to [`dds_serdata_builtin_from_endpoint `](https://github.com/eclipse-cyclonedds/cyclonedds/blob/49f87b5623f9a994a588c7f046a9ed443840f6be/src/core/ddsc/src/dds_serdata_builtintopic.c#L211)

At that point you it starts constructing a sample using the code in `dds_serdata_builtintopic.c`.

That *still* doesn't get you to `ddsi_serdata_builtin_from_sample`, though. In fact, for some time I mistakenly believed that you couldn't get there at all! See this commit: 23678edad535b0bb76a0e52127bd13a93248aeff. The commit message also tells you how to get there: you have to call [`dds_lookup_instance`](https://github.com/eclipse-cyclonedds/cyclonedds/blob/49f87b5623f9a994a588c7f046a9ed443840f6be/src/core/ddsc/src/dds_instance.c#L243)

If you wonder why the built-in topics are obscured behind two layers of interfaces: it is firstly because the types of samples are abstracted behind the `serdata`/`sertype` interfaces, and secondly because the DDSI component needs to trigger the generation of samples of these built-in topics for discovered entities, but the representation of the built-in samples is not something the network stack should be concerned with. (That the DDSI component also triggers it for local entities is a choice, but I think it makes sense to have all paths essentially the same.)

Hopefully this helps you in your quest 😀

**Comment by binbowang1987** [comment]
I got it , you help so much. I agree with you that it should keep all paths the same.
