### ISSUE TITLE
Why the BYTES_PER_SEC_TO_MEGABITS_PER_SEC defined in throughput example is 125000

### ISSUE THREAD

**Issue by tooyoungtoosimpo** [eclipse-cyclonedds/cyclonedds#1885]
Why the BYTES_PER_SEC_TO_MEGABITS_PER_SEC defined in throughput example is 125000?
It probably be (1024 * 1024 / 8) = 131072 ?

**Comment by eboasson** [comment]
I am trying to catch up with the issues but I have had so many interruptions lately that I am woefully behind. Thank you for asking a straightforward question with perfect timing ☺️. At least I can now make *some* progress on my wish to help the community!

The reason is simple: traditionally bandwidths in communications systems are given in SI units, so a 1 Mb/s is 10^6 bits/s, rather than 2^20 bit/s. Try filling a GbE to capacity, you should see 10^9 bits/s.

**Comment by tooyoungtoosimpo** [comment]
Thanks for your reply and that helps me a lot.
