### ISSUE TITLE
Question: Is is it possible to control when the background threads run?

### ISSUE THREAD

**Issue by Aposhian** [eclipse-cyclonedds/cyclonedds#1891]
From my understanding, when CycloneDDS is initialized, it spawns one or more background threads to receive or send data in the background. Is it possible to explicitly control when and how those background processes run?

The context is a system where timing needs to be strictly controlled. I suppose I could control the background thread's OS rt priority, but I would like to have explicit calling control from the application.

I know that thread properties can be configured from CycloneDDS config: https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/docs/manual/options.md#cycloneddsdomainthreadsthreadname but am wondering if there is a way to bypass these threads being spawned automatically by functions like `dds_create_participant`, and instead invoke their functions manually?

**Comment by eboasson** [comment]
They weren't really implemented with that in mind, but you could go quite a long way with some minimal modifications, as long as you are allowed to have multiple threads (not always the case).

For receiving data, if you set `MultipleRecvThreads` to `false` you know you have one thread that multiplexes its input using `ddsi_sock_waitset_wait` (e.g., https://github.com/eclipse-cyclonedds/cyclonedds/blob/85261c15492307a5d05bcb0837faafa1cc8893c7/src/core/ddsi/src/ddsi_sockwaitset.c#L825; beware: there are multiple variants, it is somewhat platform specific). If you make that one non-blocking by setting the timeout to 0, the network reception code effectively switches from input-triggered to polling. Then you would just have to add some "scheduling barrier" thing at https://github.com/eclipse-cyclonedds/cyclonedds/blob/85261c15492307a5d05bcb0837faafa1cc8893c7/src/core/ddsi/src/ddsi_receive.c#L3569.

The timed-event handling is built on the assumption that it wakes up too late anyway, so you could add the same hypothetical "scheduling barrier" at https://github.com/eclipse-cyclonedds/cyclonedds/blob/85261c15492307a5d05bcb0837faafa1cc8893c7/src/core/ddsi/src/ddsi_xevent.c#L604 and skip https://github.com/eclipse-cyclonedds/cyclonedds/blob/85261c15492307a5d05bcb0837faafa1cc8893c7/src/core/ddsi/src/ddsi_xevent.c#L616-L638

Lease checking and garbage collection/deferred freeing is in a similar state, add that "scheduling barrier" to https://github.com/eclipse-cyclonedds/cyclonedds/blob/85261c15492307a5d05bcb0837faafa1cc8893c7/src/core/ddsi/src/ddsi_gc.c#L113 and skip https://github.com/eclipse-cyclonedds/cyclonedds/blob/85261c15492307a5d05bcb0837faafa1cc8893c7/src/core/ddsi/src/ddsi_gc.c#L137-L146 and https://github.com/eclipse-cyclonedds/cyclonedds/blob/85261c15492307a5d05bcb0837faafa1cc8893c7/src/core/ddsi/src/ddsi_gc.c#L181.

The `dq.*` threads block at https://github.com/eclipse-cyclonedds/cyclonedds/blob/85261c15492307a5d05bcb0837faafa1cc8893c7/src/core/ddsi/src/ddsi_radmin.c#L2528 and also can deal with spurious wakeups. So it should work if you do the same thing once again. (If "asynchronous" delivery is not used—which is the default—the `dq.user` thread is not used for anything other than step in deleting things so you could even consider eliminating it altogether to reduce the number of threads you have to schedule.) Alternative, perhaps you could run these at a low priority so they just operate in spare cycles. I think that would make the most sense.

If you want to run them all on a single thread instead, it'll be a bit trickier. I suspect you would have to modify those thread functions so that they contain a loop that does two things: wait and call a new function that does the actual work. If you look at the above code references, that's a pretty trivial transformation. (I haven't thought it through, but I suspect I wouldn't even mind merging a change like that.)

Then you could modify it to not spawn those threads, that's just not making the calls to `ddsi_create_thread`/`ddsi_create_thread_with_properties`/`ddsi_join_thread` (or do something with the thread properties to suppress the actual thread creation) and instead create one thread that calls the functions that do the work that's now being done on the thread.

I'm sure I'm overlooking some nasty detail and stopping it might cause trouble, but overall I think it would work and not require much effort to get to a PoC stage. But I can't do it right now, much as it seems like an interesting exercise ... If you feel like it is worth a try, I can still try to help you when you run into trouble.

**Comment by Aposhian** [comment]
Thanks for the in-depth response. For my application, I'm going to first take a hand at controlling the rt priorities. But if that proves unreliable for my application then I may come back and try to make these modifications. Thanks for the direction on where to look!
