### ISSUE TITLE
About topic

### ISSUE THREAD

**Issue by luzizheng** [eclipse-cyclonedds/cyclonedds#1898]
in local domain,I used dds_create_topic() to create topic "topic01" and got handle a, then called dds_find_topic() to find "topic01" and got handle b. Now I have a few questions, why are a and b different? I used dds_delete() to delete a, then called dds_find_topic() again to find "topic01", why does it still return a valid handle? What is the logic of the behavior of these functions?

**Comment by luzizheng** [comment]
Another question, I sometimes get stuck with this function when i call dds_delete() to delete publisher or subscriber, maybe it's blocking internally,what's the general reason?

**Comment by luzizheng** [comment]
I found somtimes will get stuck with this function call chain: dds_delete() -> dds_delete_impl_pinned() -> really_delete_pinned_closed_locked() -> dds_entity_deriver_close().  eventually getting stuck at dds_entity_deriver_close(). Please take a look at what's wrong, thx~

**Comment by eboasson** [comment]
> in local domain,I used dds_create_topic() to create topic "topic01" and got handle a, then called dds_find_topic() to find "topic01" and got handle b. Now I have a few questions, why are a and b different? I used dds_delete() to delete a, then called dds_find_topic() again to find "topic01", why does it still return a valid handle? What is the logic of the behavior of these functions?

It is my belief that one of the nice things of DDS is that you can build a complicated system from many simple components that take repeatedly sample a data space and (periodically) yield some output based on the data it read. If you've chosen the topics and the QoS settings well, you can then adjust this computational graph while it is running. (Those adjustments could be for recovering from failures, or for extensions or updates to the system.)

In that case, composing the system involves dividing these simple components over processes and I am of the opinion that this composition step should be independent of the development and the testing of the components. That in turn means one must avoid unnecessary global state.

Therefore, calling `dds_create_topic` twice must be allowed. DDS entities come with listeners and status flags/masks, and so those should be independent, because otherwise you one component could interfere with another component through these bits of state in the topic entities.

You can use `dds_find_topic` to get access to topics that were created elsewhere, which in Cyclone includes topics discovered over the network (if you enable topic discovery in the configuration). So in some cases `dds_find_topic` needs to act like `dds_create_topic`, and for consistency, it should then always act like that.

Hence every successful call to `dds_create_topic` and `dds_find_topic` results in a new entity with a new handle, but referencing the same underlying topic object and the associated QoS settings.

> Another question, I sometimes get stuck with this function when i call dds_delete() to delete publisher or subscriber, maybe it's blocking internally,what's the general reason?

Are you deleting it inside a listener callback, by any chance? Because those get called from deep inside the stack to minimise the overhead—but the price you pay is that you can't do everything. (You can do simple things like read/write data, but you often can't safely create/delete entities. This detail, and what you can or cannot do exactly, is not clearly documented and it has caused enough people—[including myself](https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/src/tools/ddsperf/async_listener.c)—enough pain that the default behaviour should be different.)

Otherwise, it should never get stuck. If it does, it is a bug.

**Comment by luzizheng** [comment]
I see. Thanks for the answer.

> > in local domain,I used dds_create_topic() to create topic "topic01" and got handle a, then called dds_find_topic() to find "topic01" and got handle b. Now I have a few questions, why are a and b different? I used dds_delete() to delete a, then called dds_find_topic() again to find "topic01", why does it still return a valid handle? What is the logic of the behavior of these functions?
> 
> It is my belief that one of the nice things of DDS is that you can build a complicated system from many simple components that take repeatedly sample a data space and (periodically) yield some output based on the data it read. If you've chosen the topics and the QoS settings well, you can then adjust this computational graph while it is running. (Those adjustments could be for recovering from failures, or for extensions or updates to the system.)
> 
> In that case, composing the system involves dividing these simple components over processes and I am of the opinion that this composition step should be independent of the development and the testing of the components. That in turn means one must avoid unnecessary global state.
> 
> Therefore, calling `dds_create_topic` twice must be allowed. DDS entities come with listeners and status flags/masks, and so those should be independent, because otherwise you one component could interfere with another component through these bits of state in the topic entities.
> 
> You can use `dds_find_topic` to get access to topics that were created elsewhere, which in Cyclone includes topics discovered over the network (if you enable topic discovery in the configuration). So in some cases `dds_find_topic` needs to act like `dds_create_topic`, and for consistency, it should then always act like that.
> 
> Hence every successful call to `dds_create_topic` and `dds_find_topic` results in a new entity with a new handle, but referencing the same underlying topic object and the associated QoS settings.
> 
> > Another question, I sometimes get stuck with this function when i call dds_delete() to delete publisher or subscriber, maybe it's blocking internally,what's the general reason?
> 
> Are you deleting it inside a listener callback, by any chance? Because those get called from deep inside the stack to minimise the overhead—but the price you pay is that you can't do everything. (You can do simple things like read/write data, but you often can't safely create/delete entities. This detail, and what you can or cannot do exactly, is not clearly documented and it has caused enough people—[including myself](https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/src/tools/ddsperf/async_listener.c)—enough pain that the default behaviour should be different.)
> 
> Otherwise, it should never get stuck. If it does, it is a bug.
