### ISSUE TITLE
How to use a waitset

### ISSUE THREAD

**Issue by luzizheng** [eclipse-cyclonedds/cyclonedds#1902]
If I have to unsubscribe to some topics on a subscriber callback, but considering that CycloneDDS can't delete the dds entities in the callback, I need to use a WaitSet, but how can I use a WaitSet to implement a data read listening function? I found that Throughtput example uses waitset to block to the writer and reader connection, but it doesn't play a role of data listening, so that dds_take() is called frequently in polling, which feels like it consumes more system resources, is there a better way?

**Comment by hansvanthag** [comment]
Like for a 'select' statement in Linux, you can add a set of conditions to a waitset where you can block on either a timeout or any of those conditions to be 'triggered'.
In DDS those conditions include '_guardcondition_' (to 'manually' trigger the waitset), '_readcondition_' (that triggers on specific '_sample_-', '_view_-' or '_instance_-'  lifecycle states of the data) or '_querycondition_' (that triggers on specific content of the data)
By exploiting a specific/dedicated thread for a waitset that then executes the proper function upon being triggered, the behavior is somewhat similar to a callback yet where all actions are performed on 'user-level' rather than user-code being called from middleware-level (as is the case for a listener).

Finally w.r.t. y/n polling, a waitset is basically a blocking-call that prevents the need for polling. Without such a waitset, you can still exploit this 'filtering' on either lifecycle or content by providing such a 'filter' to the read/take call directly but that indeed often consumes more resources (yet without implying threading)..

hope this helps a little, I'd also like to refer to the OMG-DDS specification for more details on patterns for waitsets in DDS
