### ISSUE TITLE
Question: what is thread-safe?

### ISSUE THREAD

**Issue by Aposhian** [eclipse-cyclonedds/cyclonedds#1913]
I'm having trouble finding documentation about what parts of the dds API are thread-safe. I've seen the doc comments noting that configuring topic filters is not thread-safe. But in general:
- Is creating new participants thread-safe?
- Is reading from multiple readers thread-safe?

I can look at the code and see where it is synchronizing, but I was wondering if people could shed some light on what is explicitly intended to be thread-safe (or not).

**Comment by eboasson** [comment]
In principle everything is thread-safe (that includes creating/deleting domains and entities, reading/writing on the same or different entities, waiting for data or events, attaching/detaching entries from waitsets, messing around with changeable QoS settings and listeners, ...).

The topic filters are a really rare deviation from this general rule. This is mostly because fixing it doesn't seem to be worth the trouble: the filtering really should be implemented on the reader directly instead of on the topic, and changing topic filters is not such a useful operation (or so it seems to me).

I may, of course, be wrong in my assumptions 🤔😂

**Comment by Aposhian** [comment]
Ok, thanks for the clarification!
