### ISSUE TITLE
Some questions about "dds_stream_write_keyBE" 

### ISSUE THREAD

**Issue by gongqinpeng** [eclipse-cyclonedds/cyclonedds#1958]
The 211 line of "dds_cdrstream.h"  "dds_stream_write_keyBE" have five  parameters， but in the 3983 line of "dds_cdrstream.c" have four parameters, I want to know why this is based on the big end and small end mentioned above， thank you very much!

**Comment by eboasson** [comment]
I think you've found a bug in code that exists for big-endian machines, and that doesn't get compiled on the CI or locally because big-endian machines are so rare these days (you're really looking at older Power(PC), SPARC and MIPS).

Fixing this one thing is easy enough, but who knows what else may have slipped through. Cross-compiling and `qemu` it is then ...

**Comment by gongqinpeng** [comment]
Okay thank you very much




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月2日(星期二) 下午5:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [eclipse-cyclonedds/cyclonedds] Some questions about &quot;dds_stream_write_keyBE&quot;  (Issue #1958)














 
I think you've found a bug in code that exists for big-endian machines, and that doesn't get compiled on the CI or locally because big-endian machines are so rare these days (you're really looking at older Power(PC), SPARC and MIPS).
 
Fixing this one thing is easy enough, but who knows what else may have slipped through. Cross-compiling and qemu it is then ...
