### ISSUE TITLE
Add support for multiple simultaneous domains

### ISSUE THREAD

**Issue by joxoby** [eclipse-cyclonedds/cyclonedds#205]
This should enable the usage of ROS_DOMAIN_ID in _rmw_cyclonedds_cpp_

**Comment by eboasson** [comment]
Still need to do one more thing before I will properly enable ROS_DOMAIN_ID: make it possible to have waitsets and guard conditions outside the scope of a process, because then I can also remove the "extra" participant in the RMW implementation. Without that step, there is a risk of having two domains instead of just one, and that increases the footprint quite a bit.

**Comment by eboasson** [comment]
Addressed by #246 (corresponding changes went into the RMW implementation as well).
