### ISSUE TITLE
Proxy reader or proxy writer info will not be updated when the topic delete and recreate  

### ISSUE THREAD

**Issue by cxduan** [eclipse-cyclonedds/cyclonedds#207]
In the case:
Sub create a topic A and a reader, and then it delete the topic and the reader and recreate them again. When the Sub create the topic A and reader at the first time, the proxy writer which used the topic A parameters is established.  However, when it recreate them again, the proxy writer info will not be updated even if  the address pointer of the topic A has been changed.
Does it has any way to fix this problem?

**Comment by eboasson** [comment]
Hi @cxduan , 

Yes, that should be fixed. It shouldn't even be too difficult to do so: if the proxy writer (or reader) topic pointer is reset to ``NULL`` when there are no matching readers (writers) anymore in ``proxy_writer_drop_connection`` (``proxy_reader_drop_connection``), it will be set again when another reader (writer) is created.

The one thing to be careful about is that when resetting the topic pointer in a proxy writer, all pending data of that proxy writer has to be deleted. That's probably a little tricky: there is the defragmenter and the reorder stuff, but you can simply drop all that data; and there is the delivery queue if asynchronous delivery is enabled (which it isn't by default), and that needs some thinking.

So it is certainly fixable.

Good point — thanks!

**Comment by cxduan** [comment]
Thank you  for your reply! Your suggestion is not very suitable for my situation. I have an idea, but there are some problems that make me confused.
I find _st->c.refc_ in _dds_create_topic_. If the new proxy writer (or reader) can add 1 to this parameter when it is created, then at the time the topic is deleted, the _dds_delete_impl_ function will be call to judge _if (--e->m_refc != 0)_. If the value is above to zero, the topic address will not be deleted actually. Finally, when I create the topic again, the old address will be returned in _dds_create_topic_arbitrary_.
However, the address of _st->c.refc_ in _dds_create_topic_ is different from e->m_refc in _dds_delete_impl_ in my test, it is not the same parameter. I don't even know how to get and set this parameter in _new_proxy_writer_ (or _new_proxy_reader_). What should I do to realize this method?

**Comment by eboasson** [comment]
> I find st->c.refc in dds_create_topic. If the new proxy writer (or reader) can add 1 to this parameter when it is created, then at the time the topic is deleted, the dds_delete_impl function will be call to judge if (--e->m_refc != 0). If the value is above to zero, the topic address will not be deleted actually. Finally, when I create the topic again, the old address will be returned in dds_create_topic_arbitrary.

That matches my understanding.

> However, the address of st->c.refc in dds_create_topic is different from e->m_refc in dds_delete_impl in my test, it is not the same parameter.

The  "e->m_refc" is the topic's refcount among the API objects — basically the topic entity and the number of local readers/writers that use that topic. The st->c.refc is the refcount on the "sertopic" (which is really just the type nowadays, I should rename it) that is shared between the API object and the DDSI stack. The topic you get when you call dds_create_topic has a reference to this "sertopic", and it is this "sertopic" that the readers/writers and proxy readers/writers in the DDSI stack reference.

> I don't even know how to get and set this parameter in new_proxy_writer (or new_proxy_reader). What should I do to realize this method?

The sertopic in the proxy reader/writer is set lazily: it is set to NULL on creation (in proxy_endpoint_common_init, called by new_proxy_{reader,writer}), then set to the sertopic of the first matching local reader/writer (in proxy_{reader,writer}_add_connection). All local reader/writers ultimately have the same sertopic, so that is safe (as long as you don't delete & recreate the topic).

The thing is to undo that when the last match disappears. Once the local readers, writers and topic entity have been deleted, the only references to that sertopic are those in the proxy readers/writers. So dropping those references results in completely removing it from the administration. The next time you then create a local matching reader/writer, the proxy one will be updated.

The change would be in proxy_{reader,writer}_drop_connection: if ``prd->writers``/``pwd->readers`` is empty after removing the match from the set, you'd have to call ``ddsi_sertopic_unref`` and set it to a null pointer.

The only issue with that is that there may still be some data in some queue, ``deliver_user_data`` currently expects the topic pointer in the proxy writer to not be a null pointer and moreover reads it without locking the proxy writer. Those things are safe because there is no way any data can ever get there before there is a matching reader, but if you reset it and data is still in the queue, then things change.

Now, in the default configuration that problem won't occur, because the default configuration doesn't rely on the asynchronous delivery. So it is certainly worth doing it and verifying that things start working as you expect.

Before I would be able to merge your fix into the master, that one problem would have to be solved however. Obviously you can lock things and solve the issue that way, but there are other tricks as well, for example, pushing a callback entry through the queue that resets it. I would propose doing it in two phases.

(Or you could decide to wait until I get around to fixing it 😊 I totally agree it needs fixing.)
