### ISSUE TITLE
How to communicate with ROS2 and cyclonedds?

### ISSUE THREAD

**Issue by shjeong00** [eclipse-cyclonedds/cyclonedds#2081]
Hello everyone,
Sorry for my noob question..

I have just started DDS. 
And i want to know that if it's possible to subscribe the topic of 'ros2's demo_nodes_cpp talker' using cyclone dds HelloWorld subscriber.
I tried to make qos and message type same, and used the rmw_implementation as cyclone dds, but its not working.
Is there any example or method to take a look?

thanks

**Comment by eboasson** [comment]
Hi @shjeong00 when trying to get a DDS application and ROS 2 one to work together, usually the problem is the "name mangling" in ROS 2. The topic names are prefixed by `rt/`, and the type name gets an additional `dds_::` module and an extra underscore at the end:

So ROS2 turns what looks like `rcl_interfaces::msg::Log` in the message definition into `rcl_interfaces::msg::dds_::Log_` at DDS level. The most practical thing to do is to mimic this in the IDL use for DDS.

If you install Cyclone's [python binding](https://github.com/eclipse-cyclonedds/cyclonedds-python) you also get a CLI tool called `cyclonedds`, and if run that with the `ls` (and maybe `--qos`) argument you get to see the ROS2 world the way DDS sees it. Perhaps even easier: our new [insight](https://github.com/eclipse-cyclonedds/cyclonedds-insight) tool, it is still in its infancy, but it does enough for this purpose and you can download a [self-contained application](https://dev.azure.com/eclipse-cyclonedds/cyclonedds-insight/_build/results?buildId=6383&view=artifacts&pathAsName=false&type=publishedArtifacts).

(If you're on our discord server, [this comment]( https://discord.com/channels/960814229844291604/960834398784221194/1278063329612660828) is about the same earlier this week and there too Insight proved valuable.)

**Comment by eboasson** [comment]
I assume the problem went away. If not, please reopen.
