### ISSUE TITLE
Confusion regarding DDS_DOMAIN_DEFAULT

### ISSUE THREAD

**Issue by Dominik-38** [eclipse-cyclonedds/cyclonedds#2088]
Hello, 
I am a little bit confused when working with the DDS_DOMAIN_DEFAULT.
There is following statement about it:
```
* The domain id may be specified as DDS_DOMAIN_DEFAULT, in which case the behaviour
* depends on whether some domain entity already exists or not.  If there is at least one,
* the one with the lowest id will be used.  If there are none, one is created with the
* domain id taken from the first domain id specified in the configuration file (i.e.,
* with a Domain element with the id attribute not "any"), and if no domain id is
* specified in the configuration file, domain id 0 is used.
```
Why is this behavior like this? Mybe I am naive here but when I want to design my system why don't I just configure it with explicit set Domain IDs so I know whats going on.
For example if I understand it right I have Domain IDs 0,1,2 set explicitly. And then another participant set on DDS_DOMAIN_DEFAULT.  This participant would be in Domain ID 0 am i right?
But for me this is a little bit confusing and I dont really understand why I just dont configure this participant on Domain 0 or 1,2... 

It would be great to get a better understanding behind this concept.
Thank you very much!

Regards,
Dominik

**Comment by hansvanthag** [comment]
What I remember is that the main reason to have a DDS_DOMAIN_DEFAULT value in your source-code (rather than a specific domain-number) is that it results in more generic-code where the actual domain to be used can be specified in the configuration-file (where personally I wouldn't use the 'any' value there as its then like 'combatting wildcards' but instead specify the actual/plain domain_id number there. In that way you can use the same application (code) to be deployed in several domains just be switching config-files (or using an environment-variable in that domain element)

**Comment by Dominik-38** [comment]
@hansvanthag Thank you very much for the explanation. It helped me to get a better understanding!
