### ISSUE TITLE
Add shared memory transport

### ISSUE THREAD

**Issue by joxoby** [eclipse-cyclonedds/cyclonedds#211]
Is the addition of a _shared memory transport_ in the roadmap of CycloneDDS? 

We have a use-case in which large messages (~1MB) are being transferred between two processes in the same machine, and we think that shared memory would help to reduce the latency.

**Comment by eboasson** [comment]
Support for simultaneously using multiple transports is definitely on the roadmap, and a transport abstraction is already in place (even if it is a little bit leaky still), so I expect few difficulties in adding a shared memory transport. That means the benefits need not be very large for it to be a worthwhile addition.

There is a curious route to sending a message larger than 64kB over RTPS by making it the final one in the message and setting the offset to the next header to 0 (...) and exploiting that in an otherwise naive implementation would mean 4 copies. At something like 20GB/s that'd be around 200µs, where I get a minimum of 450µs with the current fragmenting and loopback interface. So I guess it'd be worth it.

I don't know when I'd get around to it, but any contribution towards it (even one that merely replaces the loopback interface with the shared memory only on, e.g., Linux, without worrying about exploiting that "curious route") would be very welcome.

**Comment by kortstee** [comment]
@joxoby in the meanwhile (or alternatively) you may also want to consider using the commercial version of OpenSplice that has shared memory support today. You can download an eval here https://www.adlinktech.com/en/vortex-data-distribution-service-dds-software-evaluation.aspx.

**Comment by eboasson** [comment]
@kortstee, this is the Eclipse Cyclone DDS forum. This is _not_ the place for promoting commercial products.

**Comment by samnardoni** [comment]
Any update on implementation of a shared memory transport for Cyclone DDS? Thanks.

**Comment by eboasson** [comment]
@samnardoni I know people working on funnelling "local" traffic through https://github.com/eclipse/iceoryx but I don't have an ETA or anything.

**Comment by samnardoni** [comment]
Apologies for being slightly off-topic, but...

Are there are plans for intraprocess optimisation?

I have a (potential) use-case where the vast majority of data would stay in the same process, while only occasionally being sent out via e.g. Ethernet. Performance would be a priority, as I would want to send on the order of a million messages per second with a small payload size. But, ultimately, the higher the message rate, the better. I'm not sure if this is a use-case that Cyclone DDS is necessarily trying to support.

I noticed that `ddsperf` does perform better with pub/sub on the same process compared to pub/sub in different processes (on the same machine); however, I wasn't sure if this is a Cyclone DDS optimisation or something happening lower down in the OS.

**Comment by eboasson** [comment]
> Apologies for being slightly off-topic, but...

No worries.

> Are there are plans for intraprocess optimisation?

Cyclone's been designed from day 0 to avoid the protocol stack for intra-process communication. The handful of design decisions that do negatively impact intra-process performance (like storing samples in serialised form) have slowly been pushed out to the margins and could now be revisited without impacting the core code, if needed. 

Incidentally, a 1MS/s threshold (for reliable transport of small samples over GbE using modern, non-exotic hardware) is what I use as a benchmark that I really want Cyclone to handle. So I'd say your use-case is very much in scope.

**Comment by samnardoni** [comment]
That’s great to hear! Thanks for the reply @eboasson!

**Comment by joespeed** [comment]
@samnardoni able to test it yet? @eboasson loves to get results, issues, even a reproducer. Here's the[ 2.4x throughput improvement](https://github.com/eclipse-cyclonedds/cyclonedds/pull/558) Erik did last week for a Robotec.ai and another user.

**Comment by sjames** [comment]
> @samnardoni I know people working on funnelling "local" traffic through https://github.com/eclipse/iceoryx but I don't have an ETA or anything.

I noticed the https://github.com/eclipse/iceoryx page mentioning that cyclonedds uses iceoryx.   I'm curious to know who is working on this.

**Comment by evshary** [comment]
> I noticed the https://github.com/eclipse/iceoryx page mentioning that cyclonedds uses iceoryx. I'm curious to know who is working on this.

@sjames #597 is the first integration of Cyclone DDS with iceoryx. This is from [ADLINK Advanced Robotics Platform Group](https://github.com/adlink-ROS/).
It's still something to work on before completion. Feel free to try and give your advices!

**Comment by sjames** [comment]
This is great!  I will check it out.

**Comment by TobiPristupin** [comment]
Hello! Just curious about the support in 2022 for shared memory communication. I see it on the roadmap as an objective for the 0.9 release. What is the state of it now, and are there any opportunities to contribute? 
For context, I'm an undergraduate researcher working on finding ways to make reduce max latency (or manage to provide an upper bound) for shared memory multi-core systems. I believe that using shared memory instead of the loopback interface could yield dramatic improvements. Thanks

**Comment by thijsmie** [comment]
We support Iceoryx as shared memory transport, with more work in this space to come.
