### ISSUE TITLE
The dds_find_topic() behaviour changed

### ISSUE THREAD

**Issue by martinbremmer** [eclipse-cyclonedds/cyclonedds#215]
Previously, dds_find_topic() would return a topic if anywhere in the system a topic was found with the given name. This means that if I created a topic on participant A and do a dds_find_topic() on participant B (with the proper name), it would return a topic.

Now, dds_find_topic() will only return topics that are created on the given participant.

To my knowledge, the previous behaviour is the correct one. Am I correct in assuming that the new behaviour is incorrect (hmm, a lot of correctness)?

**Comment by eboasson** [comment]
@martinbremmer, good catch ... its behaviour certainly changed, and it is certainly the case that find_topic should ultimately work for creating a topic when a topic with that name has been created somewhere in the system, but the current absence of topic discovery provides a loophole in the need to actually implement this across participants.

Come to think of it, the same modification that caused ``find_topic`` to change also caused the behaviour of ``dds_create_topic`` to change, in that it should now be possible to create incompatible topic definitions in two separate participants in the same process. Arguably that is perfectly sensible for referential transparency, but perhaps it is not quite so desirable in practice ...

My view, in short, is not so much that it went from correct to incorrect, as that it slid a bit in the wrong direction on the desirability spectrum. Almost as bad.

The change in any case was introduced by a fix that addresses both a potential deadlock and crashes caused by a topic entities leaking from one participant into the other, breaking things on deleting the one participant. But I do think *searching* other participants and cloning it is acceptable. Of course the type is kept consistent already (by keeping track of the types in ``dds_domain``), so a perhaps even more sensible approach would be to also store the QoS in there.

Fortunately, neither approach to restoring the old behaviour is complicated.

How much of an issue is it in the short term? I'd prefer to keep focussed on multi-domain support — I can now have my multiple domains existing at the same time, but the logging is still messed up and there are some more things to clean up.

As always, you're more than welcome to fix it, but it was my change that broke it ...

**Comment by martinbremmer** [comment]
@eboasson, it's not really much of an issue in the short term. I'd rather have it fixed properly then quickly.

I don't know if I have time to take a look in the near future...
