### ISSUE TITLE
ROS2 Eloquent Release Version

### ISSUE THREAD

**Issue by mjcarroll** [eclipse-cyclonedds/cyclonedds#262]
As we look forward to the Eloquent release, it would be helpful to know which version of `cyclonedds` you would like to be released.

Currently, we are rolling releases for the alpha (Monday, Sept 30th), so I'm going to release the tip of the master branch, but if there is a specific set of features or version to be released with the Eloquent release on November 22, please let me know.

**Comment by eboasson** [comment]
@mjcarroll, thanks for the heads up! The tip of the master branch is good.

I'll start the paperwork to make an official release — that takes some time because of the Eclipse review processes, but shouldn't be more than a month. I hope to get it done in time that the Eloquent release can use that official Cyclone release.
