### ISSUE TITLE
Missing features noted during some experimental use

### ISSUE THREAD

**Issue by rburchell** [eclipse-cyclonedds/cyclonedds#309]
I took a look around cyclone with some existing DDS stuff I have lying around, and immediately ran into some missing features/problems.

* idlc does not appear to cope with struct member names that are also a keyword (e.g. `double module`). causes an error: `no viable alternative at input 'module'`
* multiple enums with the same named value (`enum A { Bar } enum B { Bar }`) in the same module cause errors (`Internal inconsistency, multiple definitions for ModuleName::Bar`). I presume that this might be a problem when doing interop with some languages, but at least for C++ I would expect this to be possible to work around (using class enums in generation for instance). Similarly, it seems to be possible to clash with different things sharing the same name (e.g. a named enum value Foo, and a struct Foo in the same module).
* `bounded sequences not supported in CycloneDDS`

I don't know how useful this is, but figured I'd file it anyway for feedback's sake. Feel free to close it if you don't find it useful.

**Comment by rburchell** [comment]
Okay, so looking at it further, I see that the generated code - even with -forcpp, is still essentially C (and not using typed enums). I guess that explains the scoping issues. This is a little unfortunate I think, as it means that the result is a lot weaker in terms of typing.

**Comment by eboasson** [comment]
> I don't know how useful this is, but figured I'd file it anyway for feedback's sake. Feel free to close it if you don't find it useful.

All considered feedback is valuable!

It is an "open secret" that idlc is a mess, doesn't support all the relevant bits of IDL and can't generate proper C++ types. Someone started developing a new preprocessor with the aims of supporting all the relevant bits of IDL, supporting XTypes, making it easy to add backends and allowing online use as a library for "fun things". Those working on it seem to have shited their attention elsewhere, though. Such is life.

I know of the existence of the C++11 language binding on top of the C API of Cyclone and that the intent is to donate it to Cyclone, but that unfortunately hasn't happened yet. Word is that the workarounds for the idlc limitations are a factor in the delay. I am quite confident that the end result will be both a binding and a working preprocessor.

And otherwise ... it really can't be _that_ hard to do one, e.g., in Python that covers enough of the stuff ...

**Comment by i-and** [comment]
@rburchell, implementation of DDS-XTypes and C++ was also discussed in  #53 

> ...Such is life.

@eboasson, given the realities of today and given the hanging query  #226 , it may make sense at this stage, instead of developing an IDL file parser, to switch to using more structureborne XML descriptions (see https://www.omg.org/spec/DDS-XML/) and corresponding ready to use XML-parsers? At the same time, at the first stage of the work it would be nice on the basis of https://www.omg.org/spec/DDS-XML to develop an XML schema (XSD) for CycloneDDS (approach with adaptation /spec/DDS-XML/ I met in several commercial implementations of DDS).

For preprocessing, lexical, parsing, and building an AST tree of an IDL file, it may make sense to use separate adapted files from the clang project (https://github.com/llvm-mirror/clang)?

I would like to point out that clang is written using the C++ language, which in my opinion is a factor that speeds up development and raises the attractiveness for developers.

**Comment by rburchell** [comment]
> It is an "open secret" that idlc is a mess, doesn't support all the relevant bits of IDL and can't generate proper C++ types

Yes, after I filed this, I did a bit more research, found the xtypes branch, and noted that things are not really functional - in different ways - there. Seems like a pain point indeed.

> I know of the existence of the C++11 language binding on top of the C API of Cyclone and that the intent is to donate it to Cyclone, but that unfortunately hasn't happened yet.

Great, that's nice to hear! I'm comfortable dealing with C, but since I prefer to write C++ - and the majority of my code uses it - it's not really something I am comfortable using without some kind of wrapping, and obviously generating that in some automated fashion would be ideal :)

> And otherwise ... it really can't be that hard to do one, e.g., in Python that covers enough of the stuff ...

I have toyed with writing the (basics) of [an IDL parser in Go](https://github.com/CrimsonAS/idlparser) in the past if it could be of use somehow, though I never got it anywhere near production-ready, and it does not support things like preprocessing. Probably not useful, but mentioning it just in passing.

**Comment by rburchell** [comment]
> given the realities of today and given the hanging query #226 , it may make sense at this stage, instead of developing an IDL file parser, to switch to using more structureborne XML descriptions

For my own opinion, I am most familiar with RTI's XML based type description rather than IDL. I wasn't aware that there was a standard spec working on something similar, so I am unfamiliar with it at present, but assuming that it is similar in intent/scope then I tend to personally think it's a better choice as it can be more easily slotted into other types of tooling (e.g. custom code generation).

So consider that a +1 from me :)

**Comment by eboasson** [comment]
@i-and and @rburchell both: I think the proposal of supporting XML as an alternative to IDL is a very good suggestion. For XTypes it would have to happen eventually, but doing so earlier makes sense.

As to choice of implementation language: I believe the core of Cyclone should remain C code, if simply because of the size. Processing IDL or XML in a separate code generator is an entirely separate matter. There ease of implementation should come first. C++ is definitely a reasonable choice there — as would be Haskell or OCaml, if only those were somewhat widely supported languages.

Whether depending on LLVM code for this is sensible, is something someone would have to look at rather closely. LLVM is huge, and it might well pull in tons of different dependencies. There go my believed build times of a score of seconds ... (I'm somewhat joking: that's not an all overriding concern, but it is something to keep in mind.)
