### ISSUE TITLE
Is `watermarks` set the mem usage of DDS process?

### ISSUE THREAD

**Issue by qqqshengwei** [eclipse-cyclonedds/cyclonedds#314]
Hi. As we know, the DDS has history Qos and resource limits qos which can be set to KEEP_ALL and UNLIMITED respectively. So in this vein, for a transient_local writer, it may store all the samples it sent. Howevenr, here in cyclone, I found the operation `remove_acked_messages` still can be called due to watermrks setting.
I wonder if `watermarks` set the mem usage of DDS process whose priority is higher than the resource limits QoS? 
Thx.

**Comment by eboasson** [comment]
Hi @qqqshengwei,

> I wonder if watermarks set the mem usage of DDS process whose priority is higher than the resource limits QoS?

The watermarks thing is only about the amount of _unacknowledged_ data and basically provides a simple flow-control mechanism. It doesn't care about samples in the writer history that have already been acknowledged by all matching readers. So it doesn't limit the amount of memory the process can use as much as it limits the rate at which the memory use can grow.

Also you are correct in suggesting that there is no point in calling ``remove_acked_messages`` if the writer is configured to retain everything forever, but that is an optimisation that hasn't been implemented. I'm not sure how much impact that optimisation would have.

And on a side note: I just realised that for ``VOLATILE`` writers it retains more data than necessary. There is no point in keeping any samples that have been acknowledged by all matching readers, regardless of history depth. Good! Memory use can come down a bit further! 😁

> As we know, the DDS has history Qos and resource limits qos which can be set to KEEP_ALL and UNLIMITED respectively. So in this vein, for a transient_local writer, it may store all the samples it sent.

This is true, but there is a difference between what history you keep for reliability and what you keep for late-joining readers — that's why there is also the ``DURABILITY_SERVICE`` QoS setting. If you set the writer's ``HISTORY`` to ``KEEP_ALL`` but leave the ``DURABILITY_SERVICE`` at ``KEEP_LAST`` 1, then what you get is:
* all data goes to all matched readers (so it is like a queue, just like with volatile data);
* a late-joining reader gets the most sample of each instance immediately upon matching the writer (and everything from then on).

If you _really_ want to keep all samples ever written also for late joining readers, then you also have to set ``DURABILITY_SERVICE`` history to ``KEEP_ALL``.

**Comment by qqqshengwei** [comment]
Thank you very much for your reply. This is very helpful for me to understand the practicality of QoS.
