### ISSUE TITLE
build static library fails

### ISSUE THREAD

**Issue by dirk-thomas** [eclipse-cyclonedds/cyclonedds#317]
When build with the CMake define `-DBUILD_SHARED_LIBS=OFF` it outputs the following to `stderr`:

```
You have called ADD_LIBRARY for library ddsc without any source files. This typically indicates a problem with your CMakeLists.txt file
```

I assume as a consequence it doesn't install the following file which fails downstream packages: `share/CycloneDDS/CycloneDDSTargets.cmake`

**Comment by eboasson** [comment]
Thanks @dirk-thomas — another option that doesn't get tested properly. For shared libraries the warning is but a nuisance warning (and removed in the more recent versions of CMake) but considering your observation perhaps it is different for static libraries. Will look into it …

**Comment by eboasson** [comment]
An update (which means I am stupefied how to fix it): one needs to generate the ``...Targets.cmake`` file explicitly and that step is skipped when a static library is generated, and most likely because CMake refuses to generate it:

```
CMake Error: install(EXPORT "CycloneDDS" ...) includes target "ddsc"
  which requires target "ddsrt" that is not in the export set.
```

This appears to be a long-standing issue with interface libraries and static linking in CMake, e.g.: https://gitlab.kitware.com/cmake/cmake/issues/15415#note_333595. I've tried the hack proposed there, but that gives me

```
CMake Error at src/core/CMakeLists.txt:25 (add_library):
  Target "ddsc" links to target "Threads::Threads" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
```

and so and so forth. My preference by now would be to ditch CMake after "ritually removing it from my laptop" and use a proper makefile instead, but then I would get into real trouble with the rest of the world as well as on Windows, so that's not a really realistic solution.

Perhaps I could generate the ```CycloneDDSTargets.cmake``` by hand, that seems to be the most realistic proposition right now.

How badly do you need it?

**Comment by dirk-thomas** [comment]
> How badly do you need it?

Not urgent at all.

**Comment by thijsmie** [comment]
Superseded by https://github.com/eclipse-cyclonedds/cyclonedds/issues/1313. It is possible to build statically but it needs proper documentation.
