### ISSUE TITLE
Where dose the `HEARTBEAT.firstSN` come from?

### ISSUE THREAD

**Issue by qqqshengwei** [eclipse-cyclonedds/cyclonedds#337]
Hi. If the history depth of a writer has been set to 20 and it has 10 samples with SN from 1 to 10 in its WHC already, then it finds a new reader, I wonder the HEARTBEAT.firstSN from this writer to the new reader should be set to 1 or 10.
In OMG RTPS-2.3:8.3.7.5.2:page 56/189, it states a conception of avaibale state for the samples of the writer. How can I judge a sample of a writer is available or not?

**Comment by eboasson** [comment]
You ask good questions :)

The answer is: you don't for ``volatile`` and you do for ``transient-local``:

* A transient-local writer has to retain the historical data as specified by the QoS (note that Cyclone interprets that as the history specification from the ``durability service`` QoS setting), and so it will have sequence numbers from 1 .. 10 available, and all are relevant to a transient-local reader. So that's easy: the answer is 1.
* For a transient-local writer and a volatile reader, it is more complicated: the writer must keep the data, but the reader is not interested in historical data, so, arguably it should ignore all that data. Then, the answer is: the oldest available is 1, but the oldest available that is relevant _for that reader_ is 11 (so firstSN = 11 and lastSN = 10 to indicate there is nothing of interest).
* For a volatile writer, it depends on whether the data has been acknowledged by all existing readers. Because it is volatile, there is no such thing as historical data and the writer can remove all acknowledged samples from its WHC. So I could be anything between 1 (some existing reader had not acknowledged anything yet) to 11 (all existing readers have acknowledged everything already).

I believe the heartbeat should always simply specify all that is available — and I also believe that is what is meant by the spec — and so for a transient writer, it is always firstSN=1, and for a volatile writer, it is whatever it is.

That works beautiful for transient-local readers but it is a mess for volatile readers: without additional measures they have to ignore the first sequence number and instead focus on the last sequence number, or they'd start requesting historical data (from a transient-local writer, but also from a very high rate volatile writer). However, considering only the last sequence number means you might lose some data that was published just after the writer discovered the new reader. For a request-reply implementation, that could easily mean losing the response ...

I don't know an easy way out. Cyclone deals with it using some implementation-specific behaviour: for a Cyclone/Cyclone pair, even the volatile reader _always_ asks for the oldest available sample, but it does this knowing that the writer will respond with a GAP message telling it to ignore everything up the first sequence number written after matching the new reader. This way, the volatile reader always starts at the exact right sequence number.

(Allt this basically amounts to a full 3-way handshake like TCP does — and because of that 3-way handshake the first sample can take a bit longer and that makes some people unhappy 🤷‍♂️.)

**Comment by eboasson** [comment]
I suppose the question was answered by my response
