### ISSUE TITLE
Is it possible to send all instances of a Topic at once?

### ISSUE THREAD

**Issue by yakuporhan** [eclipse-cyclonedds/cyclonedds#373]
Hi !

First of all, i am new to using DDS. So my questions can be ridiculous :)

I try to design software infrastructure with using DDS architecture. I have already created some topics and adjusted qos parameters. That's all ok. I have data stream working properly.

This software runs on hardware which have many physically inputs and outputs on it. Input values are written to input Topics and published to other units, output values are read from output Topics which subscribed.

I have created Topics according to hardware specifications. For example; Outputs_1A, Outputs_5A, Outputs_20A etc..( A: ampere)
Each group has physically pins. I mean there are 8 outputs for 20 Ampres, 10 outputs for 5 Ampres etc..
First question is that should i create topics for each physically pin separately (Outputs_20A_1, Outputs_20A_2, Outputs_20A_3 ... Outputs_5A_1, Outputs_5A_2, Outputs_5A_3 ...) or group pins like I  currently did?( Outputs_20A, Outputs_5A  )

Each physically pin is a key value for my design. It means each pin is an instance. You can see idl structure below.
Struct
{
long channel_id; //key
long value;
}
So, let's say I have 3 Topics (Outputs_20A, Outputs_5A and Outputs_1A) and each topic has instances as many as the number of its pins. When I try to control a pin, i have to publish Topics for each key. It means that I have to call write() function for each instance. My second question is if it is possible to send all instances of a Topic at once?( Also, take/read all instances of a Topic at once? )

Thanks

**Comment by eboasson** [comment]
Hi @yakuporhan, thanks for asking a rather good question!

It is a difficult one to answer because it there are so many factors that play a role in deciding what the best combination of partitions, topics and key values is. I would say that generally, having many topics with only one a single instance is probably not a good idea. There are two reasons for that:
* You can't create a data reader/writer that deals with multiple topics (I might extend Cyclone so that you can have multiple data readers feeding a single history cache, but don't hold your breath). So if you split your data into too many topics, you end up have to create tons of data readers and writers, and that in turn will probably end up being really annoying when writing code.
* There is also overhead associated with topics, readers and writers: topics simply take a bit of memory, but the readers and writers all need to be discovered and stored, and that doesn't come for free. Whether you have 3 or 30 readers is not a big deal, but 300 vs 3000 probably is. Instances have some overhead, but not nearly as much.

If you smash everything together (the other extreme), you'll have all data going everywhere, all the time. Several DDS implementations have really nice support for content filtering, where the writer only sends a sample to those readers that are really interested in that particular sample (based on the content), but that comes with some complications. And in any case, Cyclone doesn't support that yet (the security branch already has most of the support for that in place). That may or may not be an issue ...

You can also use partitions to separate the data even though you are using a single topic. The nice thing about that is that you can have multiple partitions and wildcard partitions for a single reader or writer. For example you could create a "global" partition as well as "device1", "device2", ..., partitions. Then you can let all readers on "device1" subscribe in partitions {global,device1}, those on "device2" in partitions {global,device2}, &c. And then you can publish to a single device or to all of them by using a writer for the correct partition. That is a completely standard DDS feature that is fully supported by all implementations (and that plays nicer with multicast as well than content filtering).

The mappings I would initially consider are:
* group them by type (like you describe, with, e.g., Outputs_20A), or to
* group them by what they represent (say you are controlling pairs of engines and you always have to update two Outputs_20A, it might be nicer to instead control Engine), 
* group them by device type (e.g., device type A has 2 Outputs_20A and 1 Output_5A),
* group them by how they are physically divided over boxes (box 1 contains a device of type A and a device of type B).

And then look at what data flows are needed, and how many topics/readers/writers that requires (because the smallest number is best), and how much data would go to machines that don't need it (because that's a waste). Sending data for no good reason is usually cheap enough that you don't really have to worry about it 🙂.

Long story short: knowing next-to-nothing of your system, my guess would be that you've made a sensible choice.

> My second question is if it is possible to send all instances of a Topic at once?( Also, take/read all instances of a Topic at once? )

The DDS specification offers a way of doing that (look for the "presentation" QoS) and the network protocol for it was standardised really recently. However, Cyclone doesn't implement it yet. If you have to be absolutely certain that they always arrive at the same time, then for now, you'll either have to put those instances in a single topic, or you'd have to check you have a complete set before applying the changes.

I know that's a bit of a disappointment, but if your environment is somewhat benign, you could actually just publish all 3 topics, call ``dds_wait_for_acks`` and then publish another topic to signal that all pins should be updated.

Perhaps that would be a workable technique?

**Comment by yakuporhan** [comment]
@eboasson Thanks for quick response. 

I have already used partitions to seperate data. Yes, it's really nice support, but I just wonder that even if I use partitions, all data are published to all readers that subscribes releated Topic, right? So, partitions have no effect on network load? 

> Sending data for no good reason is usually cheap enough that you don't really have to worry about it

You absolutely right :+1: 

Thanks for your advice! I think that I am on right way.

**Comment by eboasson** [comment]
> Yes, it's really nice support, but I just wonder that even if I use partitions, all data are published to all readers that subscribes releated Topic, right? So, partitions have no effect on network load?

How exactly this works varies between DDS implementations, but for Cyclone it is as follows:
* if multicast is disabled, everything is sent via unicast to just the processes that have readers
* if there is only one IP address the data needs to go to, it is sent via unicast, unless "PreferMulticast" is set
* otherwise it will use multicast
* (in the case where some refuse to use multicast and some don't, you'll obviously get some sort of a mixture)

Then comes the question: which addresses? By default there is only 239.255.0.1, but you can specify "network partitions" that map topic name + partition name to multicast addresses (see the [here](https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/docs/manual/config.rst#network-partition-configuration) and [here](https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/docs/manual/options.md#cycloneddsdomainpartitioning)). In the DDSI-RTPS protocol, the readers determine which addresses the writers should publish to, so it should work even if you have inconsistent configurations.

It has a special mode for IPv4 multicast that is quite nice if you have few machines and tons of data. Basically it allows you to have to specify a block of N bits in a base multicast address, and then say to which bit a machine corresponds. Then it will automatically subscribe to all multicast addresses in those (2^N-1) ones that have that particular bit set. You in theory make that work by listing all those addresses, but you'd go mad 😄 . (This is not a standard thing and uses some non-standard locator type code on the wire.)

E.g.:
```XML
  <Partitioning>
    <IgnoredPartitions>
      <IgnoredPartition DCPSPartitionTopic="LOCAL.*"/>
    </IgnoredPartitions>
    <NetworkPartitions>
      <NetworkPartition Name="global" Address="239.255.0.2"/>
      <NetworkPartition Name="weird" Address="224.226.0.4;8;4;${NODEIDX:-0}"/>
    </NetworkPartitions>
    <PartitionMappings>
      <PartitionMapping DCPSPartitionTopic="GLOBAL.*" NetworkPartition="global"/>
      <PartitionMapping DCPSPartitionTopic="*.*" NetworkPartition="weird"/>
    </PartitionMappings>
  </Partitioning>
```
Drops all traffic in partition LOCAL, maps partition GLOBAL to 239.255.0.2, and maps all data traffic to multicast addresses of the form 224.226.X.4, where in X in 0 .. 15. Here, 8 is the position of the least significant bit in the block, 4 is the number of bits. Then you just set NODEIDX to correspond to the bit in the range of 0 .. 3.

It was actually a proof-of-concept/experiment, and the specification may well change a bit in the future, but the feature will stay. High-end switch can handle 8 or 9 nodes before switching to flooding the network, and that's enough to be interesting. This way, it multicasts to exactly the right set of nodes.

The third option is to use source-specific multicast (SSM), but that requires you have fairly few sources of data, or you'll run into kernel limits on how many SSM addresses you can subscribe to. (On Linux those can be raised quite easily.)

So you actually have some options there.
