### ISSUE TITLE
Atomic functions don't look atomic

### ISSUE THREAD

**Issue by rotu** [eclipse-cyclonedds/cyclonedds#409]
`ddsrt_atomic...` functions don't look atomic.
1. Their arguments are marked volatile which doesn't seem to serve a purpose
2. Loading and storing is definitely *not atomic*.
3. The gcc implementation uses the "legacy" `__sync_...` functions which have been superceded by `__atomic_...` functions since gcc 4.7.4

https://github.com/eclipse-cyclonedds/cyclonedds/blob/6f33dc0e6d48110fa96fce001e4a6477cecc4f9c/src/ddsrt/include/dds/ddsrt/atomics/gcc.h#L29-L33

see https://stackoverflow.com/questions/25647710/atomic-get-load-and-set-store-with-older-gcc-sync-builtins for discussion of what synchronization looks like for plain loads and stores (which we don't do)

**Comment by rotu** [comment]
@eboasson, is this a problem? Anywhere where atomicity is causing problems today?

**Comment by eboasson** [comment]
Hi @rotu, extra pairs of eyes looking at the gory details are always welcome, but I doubt there is actually an issue here in the *definitions* — there may well be in the *use* because getting this stuff right is a notoriously hard part in this business where doing things right is notoriously hard to begin with ...

That said:

> 1. Their arguments are marked volatile which doesn't seem to serve a purpose

The purpose of doing a volatile-qualified access is to tell the compiler that it may not discard any of the loads or stores written in the source (this is actually the only thing that ``volatile`` does in C if one excludes Microsoft's clever extension of giving volatile accesses acquire/release semantics).

C compilers (paraphrasing from memory — and you might want to check the spec to be sure) are allowed to assume strictly sequential execution, and therefore may assume two subsequent dereferences of the same pointer will yield the same value if there is provably no intervening assignment through that pointer. Function calls where the body of the function is invisible can potentially change any memory location taking the global variables as a starting point (if one wants to avoid the dreaded undefined behaviour), and so a in program like (beware of typos, didn't try it):
```C
void *f(void *arg) { *(int *)arg = 1; return 0; }
void g(void) {
  pthread_t tid;
  int x = 0;
  pthread_create(&tid, NULL, f, &x);
  while(x == 0) {}
  pthread_join(tid, NULL);
}
```
``x`` "escapes" in the call to ``pthread_create`` so immediately following that call, one cannot assume anything about the value of x and so a test is needed to see whether the loop body must be entered or not. However, the loop body provably does not affect the value of ``x`` and on the sequential execution assumption, the compiler is free to assume ``x`` cannot change from one iteration to the next. It may therefore optimise the loop to:
```C
if(x==0) { while(1) {} }
```
Using a ``volatile``-qualified access means the compiler no longer make that assumption/is required to faithfully execute exactly the number of loads/stores written (well, that would be executed by the abstract machine), and each iteration in the loop will read the value from memory.

So it isn't nonsensical. (But it doesn't impose any ordering constraints for non-``volatile``-accesses, so quite a weak primitive.)

> 2. Loading and storing is definitely not atomic.

They're is no guarantee that they are atomic, but I have yet to see any compiler that deliberately changes a volatile load/store of an X-bit object into multiple loads/stores for platforms that have hardware atomic loads/stores of X-bit objects. Given a compiler primitive to force this would be preferable.

> 3. The gcc implementation uses the "legacy" __sync_... functions which have been superceded by __atomic_... functions since gcc 4.7.4

I suppose the ``__atomic_...`` ones are well-supported by other compilers (clang, icc, &c.) these days, so while I don't see much of a benefit to replacing the old ones, I am also not opposed to it (especially not if it gives compiler primitives for loading/storing).

However, C11 has standardised primitives for doing all this, and abandoning the compiler-specific ones and simply using the standard ones would really be an improvement. Last time I looked, year, perhaps two, ago, the support for it was still woefully lacking on most platforms, despite having been standardized almost a decade ago. Maybe now the situation is better, or someone feels like doing the grunt work of implementing that in terms of the older compiler built-ins ...

> @eboasson, is this a problem? Anywhere where lack of expected atomicity is causing problems today?

Nope. But any issues with it would show up only very rarely and in very vague ways, so there not having been any issues hardly is a solid argument for correctness ...

**Comment by rotu** [comment]
You're right. Whether this is correct depends more on consumption patterns than the API. I'm gonna close the PR until I can nail down an issue where I can identify a real problem.
