### ISSUE TITLE
DCPSTopic built-in topic support still lacking

### ISSUE THREAD

**Issue by eboasson** [eclipse-cyclonedds/cyclonedds#42]
Support for built-in topics is missing, which makes all sorts of things impossible. It is also a showstopper for properly supporting ROS2.

**Comment by eboasson** [comment]
Participants, readers and writers are implemented, it is now just the topics that are still missing. Updating the title to reflect that.

**Comment by ithier** [comment]
Any movement on this issue ? Is anything blocking it or is it just a matter of priorities ?

**Comment by eboasson** [comment]
@ithier It's just a matter of priorities, but with a twist: there is actually a trivial way to do this and there is/was some support in the code that could have been extended. It would be easy to let each participant publish a sample via the discovery protocol for each topic it has created, and for each participant to pick these up and make them available as DCPSTopic samples. The discovery protocol is half-specified, but it is sort-of clear how that was intended to be done.

The first problem I have with that model lies in the fact that the same topics are typically created by several participants and that there can be quite a few of them, too. That means the above model scales badly. The second problem is that of exchanging type descriptors: what good is knowing a topic definition if you don't have a type descriptor? The IDL preprocessor does generate an XML description of the type, but that one is in a format only understood by OpenSplice (you can see the legacy ...).

DDS XTypes specifies (interoperable) representations and protocols for doing topic and type discovery. Clearly that's the right way to do it, and that's always been the plan. Some people were working towards contributing XTypes support in Cyclone but went off and started doing other things.

But it'll come.

**Comment by dennis-adlink** [comment]
An update on this ticket: I'm currently working on the type discovery protocol, as defined in 7.6.3.3 of the DDS XTypes spec. A fair bit of the implementation is already in a reasonable state I think, but it is not yet reviewed and there are some bugs that I need to sort out. The initial implementation will be using custom type identifiers, which are basically an MD5 hash of the serialized type descriptor. The type identifier, which is available as a parameter in DCPSPublication/DCPSSubsription, can be used by the application to resolve the type descriptor, which on its turn can be used to create a topic. So this allows creating readers at runtime for dynamically discovered topics. 

Our plan is to release this functionality (with custom type identifiers) before we have full XTypes support. As soon as we have the implementation of the XTypes type system ready, we can easily plug that in into the type discovery, so that the type lookup built-in endpoints will be exchanging messages that are conform the spec. At that stage we'll also implement assignability checking in the endpoint matching.

**Comment by ithier** [comment]
That's great news ! Thanks for the update.

**Comment by dennis-adlink** [comment]
The implementation of type discovery is in PR #559, and is currently being reviewed. Topic discovery, including support for the DCPSTopic built-in topic, is in PR #615.

**Comment by thijsmie** [comment]
All of the issues mentioned here were resolved. 🥳
