### ISSUE TITLE
idlc do not support IDL files with operations and attributes in a interface scope.

### ISSUE THREAD

**Issue by qqqshengwei** [eclipse-cyclonedds/cyclonedds#44]
Hi, I have found that idlc do not support IDL files with operations and attributes in an interface scope. For the upper layer application (such as rpc) based on dds middleware we need to define the interface with operations and attributes in the IDL file. What should we do if I encounter this situation?  Or should we enhance idlc support for interface statements?

**Comment by k0ekk0ek** [comment]
Hi @qqqshengwei. The grammer (src/idlc/src/org/eclipse/cyclonedds/parser/grammar/IDL.g4) should at least recognize the interface keyword, but in generating the symbol table it seems nothing is generated for it (src/idlc/src/org/eclipse/cyclonedds/GenSymbolTable.java). Should not be all that hard to fix, but it doesn't currently have high priority as we're working on a different compiler. Feel free to provide a patch though, we'll happily apply it.

**Comment by eboasson** [comment]
Hi @qqqshengwei, just a little crazy thing: if you would prefer a quick hack to tide you over — let's say you don't have anything really complicated going on in the IDL, don't require any complications in the code generation, don't really want to invest in extending the old preprocessor, would be happy to help work on the new one but can't wait for it to come online, _and_ you happen to be comfortable with perl and are in need of a bit of hacking of the good ol' kind ...

If all that is the case, feel free to consider reworking an old perl hack I once did to map the entire DDS API into ``node.js``, by taking the OMG IDL specification and generating ``ffi`` imports in ``node.js``: https://gist.github.com/eboasson/eaea70e54bed9d9700f7f107519e1834. Absolutely no warranties of any kind!

**Comment by qqqshengwei** [comment]
Cool！I should say I am starting to learn perl now (:-D). IDL compiler is really a good programming parter to DDS app developer. Yes, by parsing the "op_decl" in IDL.g4 we can solve this problem and obtain all the designed language files we need via antlr and ST. I am curious about what can IDL compiler do more to accelerate data transformation as he is the first guy who know the data the app developer want to communicate based on IDL files.

**Comment by thijsmie** [comment]
It's been a while since this was posted, and quite a lot has changed in the `idlc` landscape, fully removing the Java-based one. We still do not support the `interface` keyword and have no real intention of doing so anytime soon. I personally recommend you use pre-compiler `#ifdef` macros to exclude the interfaces from your IDL and compile with `idlc` as normal.

While not technically "fixed" it is also not an "open issue" due to the fact we perfectly well know what is going on and there exists a workaround. Therefore, I am delegating this issue to a new class I dub "knowledge-base" and closing it. We'll might revisit this under a new issue if there is a great need to implement interfaces.
