### ISSUE TITLE
How to bind wireless NIC during communication between two machine?

### ISSUE THREAD

**Issue by sparkskraps** [eclipse-cyclonedds/cyclonedds#451]
Hi  :)
I installed cyclonedds in a docker environment (both docker network is host mode) on two machines (my localhost and Raspi), and I want to test the stability of cyclonedds by sending/receiving data in a wireless environment.

The Info of cyclonedds during test as below
```
...
[ssh-1] 1585221918.438194 [28]     sender: using network interface eno2 (udp/192.168.0.86) selected arbitrarily from: eno2, wlo1, docker_gwbridge, docker0

[ssh-2] 1585221794.597834 [28]   receiver: using network interface enp2s0 (udp/192.168.0.53) selected arbitrarily from: enp2s0, docker0, wlx00258618e58c, docker_gwbridge
...
```
I tried to turn off the wired network card of one of these two computers. But it failed because docker0 was selected instead of the wireless NIC to send/receive data. I tried to edit the file **/etc/netplan/configure.yaml** to allow the specified network segment to communicate through the wireless NIC, but since DDS does not choose the IP of wireless NIC for communication, it certainly does not work.

Then i looked throught the source code, it truely will parse the configuration file to configure cyclonedds. my cyclonedds.xml file as below:
```
root@skylake-desktop:~/workspace/test_stability_nodes/launch_test# cat cyclonedds.xml 
<?xml version="1.0" encoding="UTF-8" ?>
<CycloneDDS xmlns="https://cdds.io/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://cdds.io/config https://raw.githubusercontent.com/eclipse-cyclonedds/cyclonedds/master/etc/cyclonedds.xsd">
    <Domain id="any">
        <General>
            <NetworkInterfaceAddress>wlo1</NetworkInterfaceAddress>
            <AllowMulticast>spdp</AllowMulticast>
            <MaxMessageSize>65500B</MaxMessageSize>
            <FragmentSize>4000B</FragmentSize>
        </General>
        <Internal>
            <Watermarks>
                <WhcHigh>500kB</WhcHigh>
            </Watermarks>
        </Internal>
        <Tracing>
            <Verbosity>config</Verbosity>
            <OutputFile>stdout</OutputFile>
        </Tracing>
    </Domain>
</CycloneDDS>

root@skylake-desktop:~/workspace/test_stability_nodes/launch_test# echo $CYCLONEDDS_URI
file:///root/workspace/test_stability_nodes/launch_test/cyclonedds.xml
```
And i installed the cyclonedds by command :
```sudo apt install ros-eloquent-rmw-cyclonedds-cpp```
the version is  **0.4.4-1bionic.20200121.221538** 

So i wonder why does the configuration not work.
If anyone know something about this, that would be appreciate.
Thanks.

**Comment by eboasson** [comment]
Good question — and I am sure one that other people may run into as well. Apologies for not yet having gotten around to fixing it picking a single interface and not always picking the desired one (but at least the warning seems to have done its job).

I don't have the equipment at home that would allow me to try to reproduce this and so I can only do some educated guesses. The protocol does two phases of discovery before dealing with application data. The first, participant discovery, provides the addressing information for the second phase, endpoint discovery, during which reader/writer information is exchanged between the participants.

So if it doesn't work, it can be: participant discovery not working, endpoint discovery not working, or application data transfer not working. The likelihood that application data doesn't work when endpoint discovery *does* work is pretty small, so it makes the most sense to look at the discovery phases first.

Participant discovery is very simple: each participant announces its presence by periodically sending a multicast to 239.255.0.1:7400 (default settings). Receipt of that message is enough for another participant to learn of the first. The response is to send a participant discovery message back to the unicast address contained in received message and to start endpoint discovery.

So the first question is: does that multicast message make it through to the other side? Wireshark can help (filter on "rtps" and look for "DATA(p)"), or set the verbosity level of Cyclone to "fine" and see what happens. If it doesn't, there's some sort of a multicast routing problem. The probable cause is a configuration of the network stack; the practical solution is often to just disable multicast and see what happens if you use unicast instead.

That can done by:
```XML
<General>
  <AllowMulticast>false</AllowMulticast>
</General>
<Discovery>
  <ParticipantIndex>auto</ParticipantIndex>
  <Peers>
    <Peer address="a.b.c.d"/>
    <Peer address="e.f.g.h"/>
  </Peers>
</Discovery>
```
(apologies for the need for "<ParticipantIndex>auto</ParticipantIndex>")

This way they will send the participant discovery message to a.b.c.d:7410, a.b.c.d:7412, ..., e.f.g.h:7410, e.f.g.h:7412, ... i.e. all unicast. If that doesn't work ...

If all that works, but the problem appears later, it may be (seen it a few times) a problem with large datagrams. Setting
```XML
<General>
  <MaxMessageSize>1472B</MaxMessageSize>
  <FragmentSize>1280B</FragmentSize>
```
should make all datagrams fit in individual network packets - so no IP fragmentation/reassembly.

If with multicast disabled and forced to use only small packets, it still doesn't work ... that would simply be crazy. Or a firewall ...

Hope this helps a bit — I'd appreciate it if you let me know what you discover.

**Comment by friendsocket** [comment]
@eboasson Thank you for your reply. Maybe my question was not express clearly enough. The problem is that I want to test the communication between two dockers existing on two machines. The communication between the two machines can work normally based on the wired NIC.(It seems cyclonedds will preference the wired NIC to communicate  because I didn't set the cyclonedds.xml file at the beginning), so PTP/EDP should work normally. 

Then I tested the communication based on wireless NIC and found that it always chooses the wired NIC. Even if I turn off the wired NIC of one of the machines, it will choose docker0 for communication. Therefore, I checked the source code and then remind of the cyclondds.xml configuration file. As you can see above, I modified cyclonedds.xml to specify the wireless NIC as follows:
```
...
<NetworkInterfaceAddress>wlo1</NetworkInterfaceAddress>
<AllowMulticast>spdp</AllowMulticast>
...
```
But the output of cyclonedds indicates that the wired NIC is still selected for communication. So i opened this issue to figure out why the configuration didn't take effect.

Today, i just find the reason, my test script was writen by someone else, It will connect to the peer docker via ssh and then run the test code. Because i set the environment variable **CYCLONEDDS_URI** throught the **export** command, not wirte it in ~/.bashrc file, so when connected to the remote machine, the new terminal has no **CYCLONEDDS_URI** environment variable obviously, After write it to ~/.bashrc file, the problem solved, i can choose the desired NIC to communicate.

Anyway, Thanks for your time and reply, Appreciate :)

**Comment by thijsmie** [comment]
Ah what a classic, a config file written but not used at runtime. It is actually an issue I've run into myself on multiple occasions. For future readers: try putting a syntax error into your config file and rerunning, you'll figure out _real_ quick wether it is actually loaded!
