### ISSUE TITLE
UDP make_socket failed for transmit port 0

### ISSUE THREAD

**Issue by yakuporhan** [eclipse-cyclonedds/cyclonedds#474]
Hi,
I have been using v.0.5.0 release of CycloneDDS. It is working well. But when I tried to use v.0.5.1, it fails anymore.  I attached the output of console below:

**4.088972 [0]  main_thrd: SOCKET socket
4.092454 [0]  main_thrd: UDP make_socket failed for transmit port 0**

I compiled CycloneDDS for FreeRTOS and LWIP. I tested it on target which has same configurations with v0.5.0 
I suspect the following commit:
"Create a separate socket for transmitting data #427"
Do you have any idea?

Thanks

**Comment by k0ekk0ek** [comment]
Hi @yakuporhan. I recall lwIP has a maximum number of sockets configured. I can't really tell if that's the problem here with the amount of information provided, but the failed creation of a socket icw Eclipse Cyclone DDS now creating additional socket(s) may just trigger you running into the configured hard limit. I'm not sure what the option is called again, but a quick Google turned up `MEMP_NUM_NETCONN`. You can try increasing that number to see if it solves the problem (be generous in the test build, tune it down a little if it solves the problem).

**Comment by yakuporhan** [comment]
Hi @k0ekk0ek 
You are right. I changed LwIP settings. But increasing **MEMP_NUM_NETCONN** option did not solve the problem. It is about  **MEMP_NUM_UDP_PCB** (Number of active UDP PCBs. One per active UDP connection) I increased it 4 to 8 for now. Thanks for your helping.
But I wonder something that if CycloneDDS opens udp socket dynamically after initialization. Actually I want to know how many udp sockets do I need? Is that possible to say it?

Thanks.

**Comment by k0ekk0ek** [comment]
It depends on the configuration. You're probably using the default configuration? In that case the number is static (as long as no extra sockets are created by default like in the commit you mentioned). Extra sockets are created if you introduce extra connections, but the number of sockets required can always be calculated. There may be some mention of this in the documentation (not sure, otherwise we'd have to update it, but it'll take some time).
