### ISSUE TITLE
Porting Cyclone to FreeRTOS+lwip on embedded ARM target

### ISSUE THREAD

**Issue by krm-int** [eclipse-cyclonedds/cyclonedds#481]
I'm trying to port cyclonedds to my FreeRTOS+lwip project to be used to build dds application.

The controller: STM32F407ZGT6 - specifically the[ Olimex-stm32-e407 development board.](https://www.olimex.com/Products/ARM/ST/STM32-E407/open-source-hardware)
I'm generating my freeRTOS application with STM32CubeMx.
Toolchain: [Gnu Arm Embedded](https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm/downloads)
The ultimate goal is to have the board sending messages via dds to the network containing sensor data.

I've been trying to follow the guide for porting to FreeRTOS+Posix, but hit some bumbs on the way (may be for a different issue).

The steps to build Cyclone for embedded targets seems a bit vague.
- Should i just build a toolchain.cmake from scratch?
- What is needed in term of FreeRTOS/lwip includes?
- Do I need to compile my freertos project into libraries (like libfreertos-sim/loader)?
- Does cyclone require any specific c/linker flags?

An in depth guide would be much appreciated if at all possible.

**Comment by k0ekk0ek** [comment]
Hi @krm-mir! It's been a while since I did the FreeRTOS port, but:
1. Yes, definitely create your own toolchain.cmake. This one's just an example.
2. For FreeRTOS, the FreeRTOS+POSIX guide should be pretty complete. For lwIP a quick look in `ddsrt/sockets/posix.h` shows at least `lwip/sockets.h` and `lwip/netdb.h` are required. Be sure to compile for lwIP too, by specifying `-DWITH_LWIP=on` as well as `-DWITH_FREERTOS`.
3. The way I constructed it is to view `FreeRTOS+lwIP` as just another operating system. You don't necessarily need to compile into separate libraries as a static `cyclonedds.a` is constructed that can be linked in your binary, but if you want to compile the example applications (very useful for testing), that's probably easiest. So (FreeRTOS and lwIP lib, aka the bsp) + (Cyclone DDS lib) + application code = binary. That way, you can easily create binaries for RoundTrip and Throughput to verify Cyclone DDS runs as expected.
4. I think they're added automatically, but I'm not exactly sure anymore

The plan always was to put up an example for the Xilinx toolchain (that's what I used back then), but haven't gotten around to that so far. Let me know if you need more help.

**Comment by krm-mir** [comment]
@k0ekk0ek  Thanks for the quick response - ill take another stab at it over the next days
Are there any requirements for the toolchain?

**Comment by k0ekk0ek** [comment]
It all depends. As long as you keep the basics in mind and follow the approach above it should be pretty straightforward. One tip with the STM32 (Cortex-M4) is to write the proper linker configuration. I did a port for an M4 and someone provided the wrong linker script. That cost me many hours.

**Comment by krm-mir** [comment]
@k0ekk0ek I've made cyclone build (something).
I just want to double check I'm on the right track.

I've done the following:
- Setup my toolchain:
```
include(CMakeForceCompiler)

set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_CROSSCOMPILING 1)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_SYSROOT /workspaces/freertos-olimex-e407-port)
# set(CMAKE_STAGING_PREFIX /home/devel/stage)

set(port_ws /workspaces/freertos-olimex-e407-port)
set(tools /workspaces/toolchain/bin/arm-none-eabi-)
set(CMAKE_C_COMPILER ${tools}gcc)
set(CMAKE_CXX_COMPILER ${tools}g++)

set(ARCH_CPU_FLAGS "-mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=hard -DUSE_HAL_DRIVER -DSTM32F407xx -Og -Wall -fdata-sections -ffunction-sections")
set(ARCH_OPT_FLAGS "")

#set(ARCH_CPU_FLAGS -mcpu=cortex-m4)
#set(ARCH_OPT_FLAGS -mthumb)

#set(CMAKE_FIND_ROOT_PATH ${CMAKE_SYSROOT})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
#set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_C_FLAGS "${ARCH_CPU_FLAGS} ${ARCH_OPT_FLAGS}" CACHE STRING "" FORCE)
#set(CMAKE_EXE_LINKER_FLAGS "-T${port_ws}/@LINKER_SCRIPT@")
set(CMAKE_EXE_LINKER_FLAGS "-mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=hard -specs=nano.specs -T/workspaces/freertos-olimex-e407-port/STM32F407ZGTx_FLASH.ld  -lc -lm -lnosys  -Wl,-Map=/workspaces/freertos-olimex-e407-port/build/freertos_lwip.map,--cref -Wl,--gc-sections")
set(CMAKE_C_STANDARD_LIBRARIES "-lc -lm -lnosys")

set(CMAKE_CXX_FLAGS_INIT "-std=c++14 ${ARCH_CPU_FLAGS} ${ARCH_OPT_FLAGS} " CACHE STRING "" FORCE)
#set(CMAKE_CXX_STANDARD_LIBRARIES "-lstdc++")

include_directories(SYSTEM 
	    /workspaces/freertos-olimex-e407-port/include
 /workspaces/freertos-olimex-e407-port/Inc
 /workspaces/freertos-olimex-e407-port/Middlewares/Third_Party/LwIP/src/include
 /workspaces/freertos-olimex-e407-port/Middlewares/Third_Party/LwIP/system
 /workspaces/freertos-olimex-e407-port/Drivers/STM32F4xx_HAL_Driver/Inc
 /workspaces/freertos-olimex-e407-port/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy
 /workspaces/freertos-olimex-e407-port/Middlewares/Third_Party/FreeRTOS/Source/include
 /workspaces/freertos-olimex-e407-port/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2
 /workspaces/freertos-olimex-e407-port/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F
 /workspaces/freertos-olimex-e407-port/Middlewares/Third_Party/LwIP/src/include/netif/ppp
 /workspaces/freertos-olimex-e407-port/Drivers/CMSIS/Device/ST/STM32F4xx/Include
 /workspaces/freertos-olimex-e407-port/Middlewares/Third_Party/LwIP/src/include/lwip
 /workspaces/freertos-olimex-e407-port/Middlewares/Third_Party/LwIP/src/include/lwip/apps
 /workspaces/freertos-olimex-e407-port/Middlewares/Third_Party/LwIP/src/include/lwip/priv
 /workspaces/freertos-olimex-e407-port/Middlewares/Third_Party/LwIP/src/include/lwip/prot
 /workspaces/freertos-olimex-e407-port/Middlewares/Third_Party/LwIP/src/include/netif
 /workspaces/freertos-olimex-e407-port/Middlewares/Third_Party/LwIP/src/include/compat/posix
 /workspaces/freertos-olimex-e407-port/Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa
 /workspaces/freertos-olimex-e407-port/Middlewares/Third_Party/LwIP/src/include/compat/posix/net
 /workspaces/freertos-olimex-e407-port/Middlewares/Third_Party/LwIP/src/include/compat/posix/sys
 /workspaces/freertos-olimex-e407-port/Middlewares/Third_Party/LwIP/src/include/compat/stdc
 /workspaces/freertos-olimex-e407-port/Middlewares/Third_Party/LwIP/system/arch
 /workspaces/freertos-olimex-e407-port/Drivers/CMSIS/Include 
 /workspaces/freertos-olimex-e407-port/Drivers/CMSIS/Include

    )
    
set(__BIG_ENDIAN__ 0)
```
The build flags are copied from the STM32CubeMX generated Makefile.

- commented out the tools from the cyclone build in file :
https://github.com/eclipse-cyclonedds/cyclonedds/blob/b46bd7ffff53a86375f36010049bbc19294e7d0d/src/CMakeLists.txt#L27
as i couldn't link the _pubsub_ proper.
- Build commands from the cyclonedds/build directory:
`cmake -DCMAKE_TOOLCHAIN_FILE=../../arm_toolchain.cmake -DWITH_FREERTOS=ON -DWITH_LWIP=ON -DBUILD_IDLC=OFF -DCMAKE_INSTALL_PREFIX=$(pwd)/../../../include/cyclonedds ..`

`cmake --build . --target install`

Invoking the last command will install the following:
cyclonedds
├── include
│   ├── dds
│   │   ├── ddsc
│   │   ├── dds.h
│   │   ├── ddsi
│   │   ├── ddsrt
│   │   ├── export.h
│   │   └── version.h
│   └── ddsc
│       └── dds.h
└── lib
    ├── cmake
    │   └── CycloneDDS
    └── libddsc.a
(only descends 3 levels).

Does this make sense?
Thanks for the help.

**Comment by k0ekk0ek** [comment]
You probably don't want to pass `--target install` initially(?) Not including the tools sounds about right, we should actually include those for host builds only. The toolchain file looks about right, I definitely recognize some of the flags, but it's really hard to tell (and it has been a while since I did the port). The list of include directories looks a little exhaustive, in theory you'd only need lwIP and FreeRTOS, but if it works that's fine. I take it you copied most of the flags from a working demo application that comes with the board, that's a really good way to figure out which flags to pass. Since you have a `.a` file I gather compilation was successful, so the next step is linking. You probably want to start with the roundtrip and throughput examples. Easiest way to do it is to write a wrapper main that does initialization and then calls the example main (you can define the example main to something else), `loader.c` in the ports directory has an example.

One additional tip: ensure multicast is working on the board. lwIP has some filters installed by default and they block broadcast and multicast traffic (I believe).

Also, from the text I gather that you're using [this board](https://www.olimex.com/Products/ARM/ST/STM32-E407/open-source-hardware)? It may not have enough memory to (comfortably) run Eclipse Cyclone DDS. I haven't tried lately, but the Cortex-M4 platform I used had additional SDRAM installed, from the looks of it, this one doesn't(?) You definitely want to ensure you're not running from flash and make sure the code that's most used is loaded from SRAM (rest from SDRAM). All of that is done using the linker scripts.

**Comment by joespeed** [comment]
@krm-mir we're trying to record the [community's support for cyclonedds](https://iot.eclipse.org/adopters/?#iot=.cyclonedds), if you're willing to [add](https://github.com/EclipseFdn/iot.eclipse.org/issues/new?template=adopter_request.md), that'd be wonderful

**Comment by krm-mir** [comment]
A small follow up.

When compiling cyclonedds for a STM32 target configured with STM32CubeMx (Cube), you might ass well include all drivers, middleware and CMSIS in the toolchain.

When passing the `--install target` when buidling I can include the libddsc.a and all headers in my Cube-generated Makefile/project.

Note: I've only made it work with `_DBUILD_IDLC=OFF`

**Comment by krm-mir** [comment]
@k0ekk0ek 
I've been battling with cyclonedds again, and it still doesn't run on the board (I've secured one with amble memory).

To elaborate my previous (updated) comment:
I'm compiling cyclonedds with FREERTOS & LWIP on separately from my Actual FreeRTOS application. Then I want to link the compiled `libddsc.a` to my executable application afterwards.
This might be reverse of the FreeRTOS+POSIX example on the repo, It just made sense in my head to compile the lib first and then my app.
When I examine the libddsc.a with `arm-none-eabi-ar -t lib/libddsc.a` I don't see any `ddsrt` objects, and I have a slight feeling this could be the issue?
Was Cyclone designed to be used in this way?
- if yes, I'm I doing it right?

Also, is the library supposed to expose both headers and source or just the source (so I need to include the headers in my FreeRTOS app-build)?

Regards

**Comment by k0ekk0ek** [comment]
Hi @krm-int. You may compile and link the application as you like, there's no incorrect way. The reason why I'm doing it like this is so that I can verify with one of the examples that Eclipse Cyclone DDS works without worrying about application code. If you want to just build Cyclone and then link it into the application that's of course fine, but I can tell you from experience that it might be a good idea to verify Cyclone works properly without having to worry about application logic. In your case you'd only need to tell the build system where the headers are location (and of course point to the right compiler etc).

You should definitely be able to see `ddsrt` symbols. Does the compiler report creating object files for `ddsrt/*` when building `ddsc`?

Actually, you can verify `ddsrt` works on your platform without building the entirety of `ddsc`. I specifically constructed it that way to verify the platform abstraction works before verifying if the DDS stack works properly. It's a lot simpler because there's much less code involved etc, but you'd have to link your bsp and system initialization routines like in the example.

Headers are enough.

FYI, I'm planning on making a better example available at some point in the future. One that actually targets an embedded platform. Won't happen in the near future though...

**Comment by krm-int** [comment]
@k0ekk0ek - thanks for the quick repsonse.

Btw, I'm using cyclonedds/0.6.0 tag.

The cyclonedds/build does contain a `cyclonedds/build/src/core/CMakeFiles/ddsc.dir/__/ddsrt/src/*.obj` and I see them being build during compile. I just don't see them when "expanding" `libddsc.a`, so I reckon the CMake goes wrong at some point?
```
...
[ 84%] Building C object src/core/CMakeFiles/ddsc.dir/__/ddsrt/src/ifaddrs.c.obj
[ 85%] Building C object src/core/CMakeFiles/ddsc.dir/__/ddsrt/src/ifaddrs/lwip/ifaddrs.c.obj
[ 86%] Building C object src/core/CMakeFiles/ddsc.dir/__/ddsrt/src/random.c.obj
[ 87%] Building C object src/core/CMakeFiles/ddsc.dir/__/ddsrt/src/random/posix/random.c.obj
[ 88%] Building C object src/core/CMakeFiles/ddsc.dir/__/ddsrt/src/rusage/freertos/rusage.c.obj
...
```

In regards to verifying `ddsrt`, how do I do that. I'm fairly new to more complex CMakeLists, and the project is a bit confusing.

**Comment by k0ekk0ek** [comment]
If you enable testing, a binary is generated (normally cunit_ddsrt I think), that binary, if properly linked etc can flashed to the embedded target.

**Comment by krm-int** [comment]
@k0ekk0ek 
I can't make the BUILD_TEST work with the arm toolchain, but probably its just a nice-to-have to be able to build the tests..

I realized I set `set(CMAKE_SYSTEM_NAME Generic)` in my toolchain, and removing that enabled me to compile cyclonedds as a shared object (`libddsc.so`). I can see it contains all the ddsrt source. Problem is that the arm-none-eabi-gcc cannot link shared object - only static libraries (as far as I know).
Anyway I can force libddsc to link/include the ddsrt objects?

**Comment by hroachewilson** [comment]
As part of a proof-of-concept project I'm investigating the feasibility of linking to a dds lib from FreeRTOS (v9.0) + LwIP (v1.4.1) running on an embedded ARM target. Since my LwIP implementation is a bare metal port, netconn and socket APIs are not available. Building a shim to get BSD sockets (or porting that functionality from LwIP source) is non-trivial. Nonetheless, I can't see a way around it for an LwIP implementation. Another option would be to discard my LwIP and use a FreeRTOS + TCP stack similar to [this](http://loszi.hu/works/ti_launchpad_freertos_demo/), developed by Lovas Szilárd at Széchenyi István University, Győr - Hungary. My hardware is a TMS570LC4357 HDK with 512KB of data RAM and 8mb SDRAM. Before I make a decision on what to do next, it would be great if I could get some more information:

1. [freertos.md](https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/docs/dev/freertos.md) states: 

> FreeRTOS+lwIP is currently supported by Eclipse Cyclone DDS. Support for other network stacks, e.g. FreeRTOS+TCP, may be added in the future.

Which FreeRTOS version and LwIP version is/was supported?

2. In the more recent FreeRTOS-POSIX/README.md, it is stated: 

> lwIP can also be used in combination with both UNIX and Windows targets, but the simulator does not yet have integration. Once integration between both is figured out, this document should be updated accordingly.

Is there any progress on this?

3. In the opinion of those on this thread, would it be better to write a BSD socket layer for my hardware or start fresh with a FreeRTOS+TCP stack?

**Comment by k0ekk0ek** [comment]
> Which FreeRTOS version and LwIP version is/was supported?

The initial port I did was for FreeRTOS v9.0. It has been a while, but I don't believe much changed between v9.0 and v10.0 in terms of API's. Both should work fine. lwIP comes with a socket layer that can simply be enabled. The configuration file that comes with it allows you to specify `LWIP_SOCKET` (I believe it was called that) and you'll get a BSD compatible socket layer. I haven't tried FreeRTOS+TCP yet, but that too comes with a BSD compatible socket layer. I believe the functions don't have the exact same name, so you'll have to update `socket.c` to use the FreeRTOS+TCP functions instead based on some define.

In short: If you have the luxury of being able to update the BSP, lwIP is known to work. Both 1.4.x and 2.0.x. Enabling sockets for lwIP seems the easiest option (consider the drivers too). If you must switch to FreeRTOS+TCP, that shouldn't give you too many issues wrt Cyclone DDS. If you go with the latter, getting the network part to work would involve replacing the function names with FreeRTOS+TCP equivalents and porting `ddsrt_getifaddrs`. Both FreeRTOS v9.0 and v10.0 are know to work.

> Is there any progress on this?

A colleague of mine noticed that there's currently decent simulators on both Linux and Windows and [from the looks](https://www.freertos.org/FreeRTOS-Plus/FreeRTOS_Plus_TCP/examples_FreeRTOS_simulator.html) of it, FreeRTOS+TCP can be used with that too. That at least makes porting a lot easier. I still haven't found the time to set the simulator up with lwIP, but back when I worked on it, the situation was a lot bleeker. e.g. there was no official Linux simulator etc. The situation has improved considerably and running the official simulator with lwIP maybe a lot easier now. No guarantees though.

Not really. There's certainly more parts involved with running FreeRTOS on an embedded target, but if you have that working, then running Cyclone DDS shouldn't be to hard. I'd try to get a sample application running, then get lwIP to do multicast correctly and then try running the ddsrt tests. If that works, you should be able to use the entire stack, aka the ddsc library, without problems.

**Comment by zhangyaothu** [comment]
@k0ekk0ek do you have any progress in the sample application? I port cyclone dds on FreeRTOS + LwIP + Stm32h7, the applicaiton runs, but malformed packets are caught. The log is detailed [here](https://github.com/eclipse-cyclonedds/cyclonedds/issues/1051#issuecomment-988609043). I wonder if there are sample configurations for FreeRTOS and LwIP.

**Comment by k0ekk0ek** [comment]
Hi @zhangyaothu, I don't think the problem is configuration related. At least, I never had to provide a custom configuration, but it has been some time. Basically if you have the test cases for ddsrt running, you should be good to go. From the pcap file you attached I can also see that for every message a "Port unreachable" response is generated. I could be wrong (of course :slightly_smiling_face:), but if you ask me there's still something wrong with the setup(?)

**Comment by zhangyaothu** [comment]
Thanks @k0ekk0ek , there is only one participant on the network and this participant is configured to find a peer using unicast address. So you can see it publish its participant information on the network and no other peers listening on the port which leads to the "port unreachable" response. I think this is correct for my setup. 

But what confuses me is that unkonwn submessage occurs occasionally and I think all submessage should be same except timestamp or others. 

I think this problem is related with FreeRTOS or LwIP porting, and seems the heap is corrupted somewhere, but I cannot find it. @eboasson gives helpfull informations [here](https://github.com/eclipse-cyclonedds/cyclonedds/issues/1051#issuecomment-988118289). This issue may be more appropriate to talk about this problem.

**Comment by k0ekk0ek** [comment]
Heap corruption might very well be the problem. I remember that for the stm32 port I did, the client provided a faulty linker script, causing allocations to wrap around and basically corrupting everything. Before we continue though, It's really a good idea to first ensure the `cunit_ddsrt` binary runs without problems. Embedded targets like this are basically why `ddsrt` (platform abstraction and basic utilities) is a separate target. Can you verify that binary runs without problems?

**Comment by thijsmie** [comment]
These embedded platforms always take some elbow grease to get working, but we appreciate all the effort people go through to run Cyclone! No further problems popped up in here, so I assume everyone got their setup working 😇.

**Comment by rizahmad** [comment]
Is there a guide to build cyclone dds on embedded platforms? Proven steps that work would really help.
