### ISSUE TITLE
MiB and MB should not be synonymous.

### ISSUE THREAD

**Issue by rotu** [eclipse-cyclonedds/cyclonedds#492]
In the config file, we interpret IEC binary prefixes the same as decimal prefixes. This is somewhat confusing. We should either allow "MB" to refer to the colloquial (though incorrect) meaning of 2<sup>20</sup> bytes and disallow "MiB", or switch "MB" to the correct meaning 10<sup>2</sup> bytes

**Comment by eboasson** [comment]
I deliberately mapped the SI prefixes in the way that is customary in computing: for bandwidths, they're powers of 10, for sizes they're powers of 2. Essentially any time in computing you encounter a buffer size of 32kB, it (almost invariably) means 32768 bytes, and when you encounter a data rate of 10Mb/s it (almost invariably) means 10,000,000 bits/second. It is illogical, it is weird, but it is the custom.

I'll grant you that hard disk manufacturers never played by this rule and that Apple decided to change their interface, but those are the only cases I know of. I believe Cyclone should follow custom in interpreting these.

**Comment by rotu** [comment]
Hmm... I usually expect MB to *actually* mean mebibyte. But in a context where *both* are used (options.md), it comes as a big surprise that we *don't* use the pedantic meaning.

I would be in favor of either (1) changing it to be technically correct or (2) omitting mention of KiB, MiB altogether from the docs.

**Comment by eboasson** [comment]
The only context where it interprets k, M and G as powers of 10 is in bandwidths, and I certainly would get angry if those were changed. The way it is, it follows historical precedent (always good for intuitiveness) and allows those who want to avoid ambiguity for sizes to use MiB etc. I'm sure there are some people out there who insist that specifying a buffer of 4kB should mean 4000B instead of 4096B, and that group is the one that is out of luck if they actually are trying to specify that 4000B buffer ...

But I know from experience that what I find intuitive isn't always the same as what others find intuitive (and then I'm probably being charitable to myself), so if there are others willing to chime in, then please do!

And if we change it, we have to change it by deprecating something, we can't just change the multiplication factor ...

**Comment by poetinger** [comment]
Discussion about this topic appears to have ended, so I will close this.
