### ISSUE TITLE
atomic pointer operations in gcc.h

### ISSUE THREAD

**Issue by dodsonmg** [eclipse-cyclonedds/cyclonedds#515]
`atomics/gcc.h` has several atomic pointer operations such as:

https://github.com/eclipse-cyclonedds/cyclonedds/blob/6f33dc0e6d48110fa96fce001e4a6477cecc4f9c/src/ddsrt/include/dds/ddsrt/atomics/gcc.h#L85-L87

I'm cross-compiling for a research system using a modified version of Clang that doesn't currently support atomic fetch and add on pointers.

Searching through the whole repository, it doesn't appear that cyclonedds actually uses any of the functions with atomic fetch and add, so I've been able to fork the project and simply remove them.  It compiles and runs fine.

If I'm right (that they aren't used), would you be amenable to a PR removing them?  Catering to a research system isn't on anyone's priority list, but on the 'less code, fewer bugs' principle...

**Comment by eboasson** [comment]
To a non-insignificant extent, the set of functions is the result from expanding a few primitives without worrying too much about what is needed and what not. It appears the `uintptr_t` functions aren't used directly and the `void *` ones only for load/store/cas. That's been the case for a decade or so.

I don't think it likely this will change anytime soon, so, yes, I'd be amenable to such a PR. Partially on the "less dead code" principle, partially because I do think research systems should be given consideration :)

**Comment by dodsonmg** [comment]
Thanks for considering!

How do you want me to handle the function prototypes in `atomics.c`, such as:

https://github.com/eclipse-cyclonedds/cyclonedds/blob/761ffa6db2ee1e4c6d22e495e609179a5ec5b22f/src/ddsrt/src/atomics.c#L32

If I remove them, then presumably I need to remove the corresponding functions not only in `atomics/gcc.h`, but also `atomics/msvc.h`, `atomics/arm.h`, and `atomics/sun.h`.

If I leave them in, I'll get warnings.  I could fix them with some kind of preprocessor conditionals around each one, similar to the `DDSRT_HAVE_ATOMICS64` conditionals you're already using.

**Comment by eboasson** [comment]
I'd like all variants to provide the same set of functions, otherwise it becomes a complicated mess (and besides `gcc.h` is the one most used). They're in the way and not used, so let's rip them out 😄

**Comment by dodsonmg** [comment]
Sounds good.  Thanks!  

Note that I can only test the gcc one locally...

Submitted PR #521.  Closing.
