### ISSUE TITLE
Communicating between embedded  Cyclone & ROS2

### ISSUE THREAD

**Issue by krm-int** [eclipse-cyclonedds/cyclonedds#518]
I'm currently working with DDS on embedded (see #481 ) and I'm wondering what's needed for an embedded device running pure Cyclone DDS to communicate with ROS2 (maybe not necessarily Cyclone RMW)

Does it needs some sort of bridge?
Message considerations?

It's DDS on both sides, so it must be possible somehow?

Regards

**Comment by eboasson** [comment]
It's pretty straightforward: it really comes down to getting the right type definition, the right topic/type name and a matching QoS.

You need to use IDL that matches the ROS2 message types. ROS2 has a `.msg` to `.idl` conversion tool that is used by some RMW implementations, but I don't quite know how to run it as Cyclone doesn't use it and it is all automated by cmake when it generates the typesupports for Fast-RTPS or Connext. For simple types it is trivial and you could even do it by hand.

You also have to choose whether or not to follow the ROS2 naming conventions for the topics/types. If you do, you'll have to mangle the topic names and type names on the Cyclone side. For example, on the wire, the ROS2 "minimal publisher example" publishes "rt/topic" with type name "std_msgs::msg::dds_::String_". To get Cyclone to use the same type name is somewhat tricky because it takes the name from the IDL, and so you end up having to modify the IDL or to modify the output of `idlc`. (The DDS spec allows overriding the type name, that's not (yet) implemented in Cyclone but adding that is certainly an option.)

Alternatively, you can set the `avoid_ros_namespace_conventions` QoS for the publishers and subscriptions in ROS2 that you want to communicate with the device. The only thing this affects are the topic and type names. As I understand it, that should result in more "normal" names and exists specifically to make this type of scenario easier.

Sill, for integration with tooling, making the device follow the ROS2 naming conventions might make sense.

**Comment by thijsmie** [comment]
This question was answered 😄

**Comment by weipengyiyu** [comment]
> 
This policy is enabled when creating a topic on the ROS2 side, but it still cannot receive cyclonedds messages
Here is my setup on the ros2 side：
rclcpp::QoS qos_profile = rclcpp::QoS(rclcpp::KeepLast(10)).avoid_ros_namespace_conventions(true)

At present, I set the same message format as the ros2 side on the cyclonedds side std_msgs::msg:String, only the topic of rt/ prefix published on the cyclonedds side can receive data by the ros2 side, didn't I set the conversion of the domain name to true? Why do I still need to add rt/ prefix to communicate, and now how do I think? Communicate without RT/prefix!!!

reference：https://github.com/eclipse-cyclonedds/cyclonedds/issues/518

Thank you very much for your reply！！！
