### ISSUE TITLE
[Question] Can Durability QoS be assured if the data writer disconnects?

### ISSUE THREAD

**Issue by msmcconnell** [eclipse-cyclonedds/cyclonedds#528]
In the DDS standard, Durability defines what data is sent to newly connected subscribers. I am wondering how this is applied when the DataWriter disconnects. If I had a durability of TRANSIENT, I believe the data is meant to be published to any new data reader regardless of the presence of the original data writer. Am I interpreting that correctly? Will the old data be available to the new reader? If so, who publishes the old data? Is it one of the previous data readers?

**Comment by TheFixer** [comment]
When a datawriter becomes disconnected (and more importantly reconnected at some later time) then a datareader may have missed transient data that has been published in the disconnected period. When the reconnect occurs, DDS should then make the missing data available to the readers that missed this data in such a way that the reader eventually becomes  "eventual consistent". In short, eventual consistency means that a transient reader that has missed data (either because it was a late joiner, or because it has experienced a disconnect) must eventually end up in the same state as an imaginary reader that supposedly received all data from the writer. 

You are correct that transient data survives the lifecycle of its publisher.  And yes, this means that transient data that has been published by a writer must still be made available to late joiners even if the writer itself does not exist anymore. The logical consequence of this is that somebody or something else must take up the responsibility to provide this data to late joiners, because the original writer cannot do it anymore.

There can be different ways to implement and eventual consistent data distribution system, and historically different DDS vendors have chosen different directions. For example, another writer can do as if it was the original writer and republish the data, or a service can be implemented that collects the transient data that is published in the system and that provide it to late joiners. And I am sure there are plenty of other options to implement eventual consistency in the context of disconnects and reconnects. 

As far as Cyclone is concerned, the feature is not yet supported, but I know that this feature is being worked on.

**Comment by msmcconnell** [comment]
@TheFixer Thank you for the detailed response! I have a better grasp now on how Transient data is meant to be handled.
