### ISSUE TITLE
Wishlist: idlc as a stand-alone self-contained application?

### ISSUE THREAD

**Issue by photex** [eclipse-cyclonedds/cyclonedds#539]
Howdy!

For folks who aren't interested in setting up a java development environment it would be really helpful if idlc could be built as a stand-alone executable (as is done with a project like bazel).

In an even more exciting future, would be to port idlc to C++ (or C or Rust). Having idlc be a native tool built as part of the cmake build opens some interesting doors for helping automate code generation for projects that want to use cyclone (probably mostly if you were to vendor cyclone directly into your repo).

If the latter were ever considered I'd be very happy to join the effort in anyway I could. :D

**Comment by k0ekk0ek** [comment]
Hi @photex. Making idlc a standalone application is exactly what we're starting work on this week :smile:. There's some work done already on the xtypes branch and PR #365 makes the work found there an actual tool. We'll be using (some of) that as the base for the future idl compiler. Keep an eye on the xtypes branch (perhaps we'll make and idlc branch too, it's a bit unsure) for updates, or open/continue an issue. If you want to help out, that'd be much appreciated, maybe study the aforementioned PR (not sure if we're sticking with `re2c`) a bit. We'll use `mcpp` as the preprocessor, a hand-crafted scanner (probably) and Bison for parsing. If you have an area that interests you, any ideas/contributions are welcome, but before going off on a lengthy coding spree, maybe check if it fits with what we're trying to do? Would be a shame to waste your (or our) time. Thanks for the interest!

**Comment by photex** [comment]
🤩 wow, what timing!

I'll get familiar with everything with an eye out for anything that might seem helpful and follow up here then.

Also, if there is anything seen by the existing contributors that could be nice to have some contributions on then perhaps tag some issues and folks such as myself might be able to more quickly hop on board.

**Comment by sjames** [comment]
This is great to hear.  I'm quite tired having to fix my Java issues before I can get the IDLC working.  I just did a clean install of Ubuntu and have to deal with the Java errors again.

There is an rtps-idl-grammar crate available on rust. https://crates.io/crates/rtps-idl-grammar. This is for the pest parser.

**Comment by joespeed** [comment]
> This is great to hear. I'm quite tired having to fix my Java issues before I can get the IDLC working. I just did a clean install of Ubuntu and have to deal with the Java errors again.
> 
> There is an rtps-idl-grammar crate available on rust. https://crates.io/crates/rtps-idl-grammar. This is for the pest parser.

if only we know a sailor that'd contribute rust binding ... 🤔😁

**Comment by photex** [comment]
I'm entirely willing and able to contribute Rust bindings actually!

We're using Rust for nearly everything at kopernikusauto.com and are currently evaluating our DDS options.

At the moment I've put together a binding for eCAL (yes, not a full DDS) and some preliminary work on RTI (but only for the pubsub functionality).

If there is an option to have a tighter solution which included code generation that would be ideal for us.

The existing rtps code gen crate could be a good starting point for both a C and Rust capable idlc.

**Comment by eboasson** [comment]
Cyclone totally needs Rust bindings. I know of the beginnings of one here https://github.com/atolab/cdds-rust and I am sure they'll be happy to work with you on completing them.

@k0ekk0ek is looking after the new IDL compiler. It'll get a backend per language in separate libraries, so as soon as the interface for the backend is somewhat stable a Rust backend would be a possibility as well. I'm hoping he'll chime in on when he hopes to reach that point.

**Comment by sjames** [comment]
I have made some decent progress with Rust bindings and I'm working on getting approvals in place to open it up.  I hope this happens soon.  Features that are working so far.

1. publish and subscribe topics in a type safe manner
2. use closures for callbacks. This was an interesting challenge for me.
3. IDLs are maintained as library crates. Use the convenience of Cargo to distribute IDLs.  You just have to add a dependency to the IDL crate and you're ready to publish or subscribe data.  Codegen happens on the fly transparently using the Jave IDLC.
4. Qos configuration

Cyclone dds has a lot of APIs and I have just scratched the surface.  I hope I will be able to open it up for other contributors once I have the paperwork done.

Regards,
Sojan

**Comment by photex** [comment]
> IDLs are maintained as library crates. Use the convenience of Cargo to distribute IDLs. You just have to add a dependency to the IDL crate and you're ready to publish or subscribe data. Codegen happens on the fly transparently using the Jave IDLC.

Very much looking forward to the idlc updates because I'm fairly prejudiced against using any Java tools in my builds at the moment (they tend to become "sticky" and we aren't that invested into any particular DDS solution to warrant the mess). 

>  It'll get a backend per language in separate libraries, so as soon as the interface for the backend is somewhat stable a Rust backend would be a possibility as well.

I'm happy to hop on that asap. I've been loosely checking in to find out where the work on the idlc rewrite is happening. Is that planned to be moved to this repo or will it continue living in a fork someplace?

In order to improve my life on Windows, I've made a couple of changes to the cyclone cmake setup: https://github.com/kopernikusai/cyclonedds/commit/a3403d69d783604c6704518e75a3cd0dd9fa4e17

I'm just building ddsc as a static library and ignoring idlc for the moment.

**Comment by k0ekk0ek** [comment]
@photex, yes It's definitely going to be in this repository. I'm rebasing the `xtypes` branch so the people working on the C++ backend can move their code to the `cyclonedds-cxx` repository (it's currently in a clone/fork of my [parser-next](https://github.com/k0ekk0ek/cyclonedds/tree/parser-next) branch). Once the basics are all in place (give it a couple more weeks) the new and improved `idlc` will get merged to `master`.

**Comment by photex** [comment]
@k0ekk0ek super cool! Looking forward to it.

**Comment by photex** [comment]
Just a heads up on a potential issue I've seen while playing around with the various branches related to this.
`src/parser.y:134.18-21: syntax error, unexpected identifier` is the error on the parser-next branch in @k0ekk0ek fork, and it's line 95 in master iirc.

On Windows, the most recent version of bison that I've been able to find is 2.4.1. On WSL my bison version is 3.0.4 and the build works.

**Comment by photex** [comment]
Ok, so I found `scoop install winflexbison` and this gets a bit further. But now it fails looking for `getopt.h`.

**Comment by k0ekk0ek** [comment]
Hi @photex, thanks for trying it out! I'm aware of the `getopt.h` issue, there's some others as well, they'll get fixed, but I should note that it's not ready for general consumption yet. The branch is mainly there for colleagues working on the C++ backend for *cyclonedds-cxx*. I'm currently getting support for constant expressions into place, so there's going to be some changes yet, but after that's in, I expect to be able to cover all types of expressions/declarations. I'll start polishing everything after that and I'm planning to move on to write/rewrite a C backend myself. There's a `getopt.h` we ship with Cyclone DDS, we'll reuse that, but the idea is to have `libidl` as a standalone library so we can use it in tooling, perhaps other projects can (re)use it too. If you really want to contribute, for let's say a rust binding, I could be persuaded to make the branch compile cleanly on all platforms first, let me know.

The idea is that `idlc` (the compiler, `src/tools/idlc`), which includes preprocessing (`src/tools/idlpp`), uses `libidl` (`src/idl`) to generate a tree (with constant expressions resolved etc) and passes the tree along to the backend. The backend should be a dynamic library that exports a function with a predetermined signature that `idlc` calls. After completion, `idlc` will take care of freeing the tree etc. I thought about it a little myself and I think it would be helpful to make a loosely versioned api for future backends. So the backend should export something like `idl_backend_version` so that the compiler can tailor the arguments towards the version supported by the backend. This is probably very helpful if a future backend requires more input than existing backends. We can implement the new features in `idlc` without having to update all existing backends.

What I'd be really interested in is what other options the backend needs apart from the tree. Maybe an output directory is enough at first, but for e.g. the C++ backend, we could decide that the C++ standard is useful input etc.

Again, if you'd like to start on a custom backend or something, let me know and I'll see what I can do to get it working on Windows and Xcode too. `winflexbison` is definitely a requirement on Windows, I should really make the `find_package` call require version `3.0.4` or higher...

**Comment by photex** [comment]
Thanks @k0ekk0ek, I'm certainly interested in contributing but I wouldn't want to rush anyone along. I've just been periodically checking in and trying to build or get familiar with things and I thought I'd report any troubles I had.
At Kopernikus we use Windows and Linux for development, but our application is currently entirely running on Linux. We have to build for x86_64, aarch64, and ppcle64. Building the library itself is working great. We're using eCAL, and a custom message bus at the moment. I'm anxious to get us on an actual DDS implementation. To that end, I've been evaluating Connext in order to really see how much effort it is to use with Rust. Given the open source nature of Cyclone, the fact that it's built with C, and the fact that idlc is being rebuilt with extensibility in mind, I'm naturally rather excited to see it come together and have Rust sitting at the table.
I think that, given the way we work currently, we should be able to use Cyclone without the new idlc though. So please pardon any impatience on my part. :D

For a Rust backend, being able to specify the output directory is certainly important. I'm not sure what Rust specific options I'd suggest to add to idlc. I'm fine using the environment to control some parts of this if I really consider it. With Rust you can take a couple of approaches for enums for example. You also might not want to use serde for serialization, and you might want to be able to specify whether you want to have some common traits automatically derived for any types. It might also be desirable to avoid using the std crate.

**Comment by sjames** [comment]
Hi All,

I've published my cyclonedds-rs crate at https://github.com/sjames/cyclonedds-rs .

I really wanted to have namespaces in the generated types and was not happy using bindgen on the Java IDLC generated C code. 

I spun my own partial IDLC at https://github.com/sjames/cyclonedds-idlc, using code from the crate https://crates.io/crates/rtps-idl-grammar. This is partial because it only generates the rust structure and the reference to the IDLC generated code.  I still rely on the generated C file for the ops and topic structure.

For I while, I was was heading down the path of a full idlc using Rust.  The cyclonedds-idlc also has the code to generate the keys and the ops for the topic, but that is now disabled as I realized that I was entering unknown territory and was a rabbit hole I did not want to explore right now.  I used the Java IDLC as a reference so you will find some similarities there.

For now, I use the Rust IDLC to generate the Rust struct and the Java IDLC for keys and ops for the topics.  It seems to work at least for simple IDLs and it is glued together with Cargo build scripts. All the action for code-generation happens here https://github.com/sjames/cycloneddscodegen. 

Cheers!
Sojan

**Comment by eboasson** [comment]
@sjames that is so cool! (I only had a quick look at the code, I should play with it instead 😄)

**Comment by photex** [comment]
Bravo @sjames !

**Comment by k0ekk0ek** [comment]
@sjames, the new compiler has been merged this afternoon. Some time ago we talked about your efforts with regards to cyclondedds-idlc. There's one difference that I can think of that might impact your work and that's sequence names. Previously implicit sequences used the name of the struct member. That has been changed to use the name of the type instead and put the definition in an `#ifdef ... #endif` block. It slipped my mind to update you before merging it to the master branch. I'm closing this particular issue, but let me know if you need help.

@photex, you can mark this one of your whishlist :slightly_smiling_face:

**Comment by photex** [comment]
Very exciting to see this arrive. Well done!

**Comment by sjames** [comment]
> @sjames, the new compiler has been merged this afternoon. Some time ago we talked about your efforts with regards to cyclondedds-idlc. There's one difference that I can think of that might impact your work and that's sequence names. Previously implicit sequences used the name of the struct member. That has been changed to use the name of the type instead and put the definition in an `#ifdef ... #endif` block. It slipped my mind to update you before merging it to the master branch. I'm closing this particular issue, but let me know if you need help.
> 
> @photex, you can mark this one of your whishlist slightly_smiling_face

@k0ekk0ek thanks for the heads-up.  I will take a look.  Its a busy time at work and will keep this for my next holiday.  :-)
