### ISSUE TITLE
[question]Does cyclonedds support sros2 feature?

### ISSUE THREAD

**Issue by Ada-King** [eclipse-cyclonedds/cyclonedds#542]
Hi, **eclipse-cyclonedds** :)
I intented to test the stability of different DDS(cyclonedds, fast-rtps, rti-connext, etc) with the security feature on. In [sros2 readme](https://github.com/ros2/sros2) page, i see the feature supported by `RTI Connext Secure 5.3.1 and eProsima's Fast-RTPS 1.6.0`. So i wonder if the cyclonedds also support it. If so, can you provide an operation document link, Thanks.

**Comment by eboasson** [comment]
Hi @Ada-King, thanks for asking because it is supported — just be sure to use the master branch of Cyclone and not the 0.6.0 or older versions. It has only been merged into master for about a week now and the plan is to start the release process for 0.7.0 as soon as we feel there has been enough time for issues to pop up.

Using current master of Cyclone means you also have to build the current version of rmw_cyclonedds from source. For Foxy, you can use the released version, for Dashing and Eloquent you would have to use the head of the dashing-eloquent branch.

Nothing special needs to be done to make it work. The sros2 tool writes the files and the RMW abstraction does the rest.

**Comment by Ada-King** [comment]
Got it, thanks :) @eboasson  i will test on ros2 e-version.  i have one more question.

> Nothing special needs to be done to make it work

So there is no enable flag like Fast-RTPS, `-DSECURITY=ON`, then if i want to test the performance of cyclonedds without security feature, all i need is just ros2-eloquent-rmw-cyclonedds-cpp(install from binary) **or** rmw-cyclonedds(install from source) and cyclone(0.6.0 or below). right?

**Comment by eboasson** [comment]
@Ada-King: just be sure to build `rmw_cyclonedds` from the head of `dashing-eloquent` branch (for Eloquent) and `cyclonedds` from the `master` branch.

> So there is no enable flag like Fast-RTPS, -DSECURITY=ON

Ah, now I see what you mean. It's enabled by default (the philosophy being that you generally want everything unless you know you don't). You can disable it with `-DENABLE_SECURITY=NO`.

Beware though: the security support is split into two parts:
* The implementation of the interface for and invoking of the authentication, access-control and cryptography plugins. This has no external dependencies, and so always build if you haven't explicitly turned it off with `-DENABLE_SECURITY=NO`.
* The implementation of those plug-ins. This relies on OpenSSL, and so if OpenSSL is not found at configuration time, you'll end up with security support that is useful only if you happen to already have an implementation of those plug-ins.

E.g., on Fedora 32, a simple `cmake <CYCLONEDDS_SOURCE_PATH>` outputs (among other things):
```
-- Found OpenSSL: /usr/lib64/libcrypto.so (found version "1.1.1g")  
```
and you're all set. The same on macOS (default settings):
```
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing: OPENSSL_INCLUDE_DIR) 
```
results in a successful build that includes the support code for security in the core, but the plug-ins are not included in the build. That detail might need some TLC.

I think I should go and add the above to the README. If you would be so kind as to let me know whether this is clear enough and it helps make stuff work, that'd be great.

**Comment by Ada-King** [comment]
Yes, you make things express clearly. By the way, the sros2 related [docuement](https://github.com/ros2/sros2/blob/master/SROS2_Linux.md#install-from-source) mentioned the `openssl` thing. I will do my test in the following time based on your tips. And if you don't have spare time, i can help to improve the **README** document after testing on my host machine.

**Comment by Ada-King** [comment]
emmm... Things not going smoothly.

I. Not setting the security environment 

The directory structure of repository:
```bash
- cyclone
    - src
        - cyclonedds                 <---  branch is `master`
        - rmw_cyclonedds        <---  branch is `dashing-eloquent`
```
There are some warning message during the process of  `colcon build`, but that's not the point.
After the `build && install` process finished, i run the basic **ros2 run demo_nodes_cpp talker** demo, It quits just at it started. 
```bash
root@raspi-new:~/cyclone# ros2 run demo_nodes_cpp talker
1591983155.844352 [0]     talker: using network interface eth0 (udp/192.168.0.93) selected arbitrarily from: eth0, docker0
root@raspi-new:~/cyclone# 
``` 
Then i add the build flag `-DENABLE_SECURITY=NO`(I have questions about this, i will metion later), the phenoment is the same as above.
Then i switch the branch of `cyclonedds` to `0.6.x` and rebuild, the talker demo can run normally.

II. Setting the security environment(ROS_SECURITY_ENABLE=ture, etc).
The branch of repository as below, 
```bash
cyclonedds                 <---  branch is `master`
rmw_cyclonedds        <---  branch is `dashing-eloquent`
```
$ colcon build
the output error as below, it prompts me to add build flag '-DENABLE_SECURITY=ON'(**this is not consistent with your reply above**)
```bash
>>> [rcutils|error_handling.c:107] rcutils_set_error_state()
This error state is being overwritten:

  'Security was requested but the Cyclone DDS being used does not have security support enabled. Recompile Cyclone DDS with the '-DENABLE_SECURITY=ON' CMake option, at /root/cyclone/src/rmw_cyclonedds/rmw_cyclonedds_cpp/src/rmw_node.cpp:834, at /tmp/binarydeb/ros-eloquent-rcl-0.8.4/src/rcl/node.c:336'

with this new error message:

  'rcl node's rmw handle is invalid, at /tmp/binarydeb/ros-eloquent-rcl-0.8.4/src/rcl/node.c:485'
```
So i execute `colcon build --cmake-args -DENABLE_SECURITY=ON`, the error is still exist. 
Can you give me any hint on these two issues? @eboasson

**Comment by eboasson** [comment]
Hi @Ada-King, I was mistaken, I'm sorry about that. Everything I wrote is correct except that the Cyclone CMake files decides whether or not to define `DDS_HAS_SECURITY` before it auto-detects whether to enable it, and so it remains undefined and the RMW layer says it isn't supported when in fact it is. (There are two things going on here, I usually have a "dirty" environment, rebuilding stuff in-place, and it has been a while since I last gave any thought to the SROS-specific stuff.)

Until that bit of CMake stuff in Cyclone is fixed, you indeed have to specify `-DENABLE_SECURITY=YES`. Fixing it shouldn't take long, but I really must put some effort into reviewing various pull requests first.

About
> After the build && install process finished, i run the basic ros2 run demo_nodes_cpp talker demo, It quits just at it started

I think have the same thing on macOS with Dashing after copy-pasting the SROS environment settings from https://github.com/ros2/sros2/blob/master/SROS2_MacOS.md and it turns out that: (1) Foxy uses a different environment variable than Dashing/Eloquent, and (2) Dashing (at least) aborts somewhere in the ROS2 libraries if the `ROS_SECURITY_ENABLE` is set but `ROS_SECURITY_ROOT_DIRECTORY` is undefined.

If you did use https://github.com/ros2/sros2/blob/eloquent/SROS2_MacOS.md#define-the-sros2-environment-variables then there must be something else still.

**Comment by Ada-King** [comment]
> Until that bit of CMake stuff in Cyclone is fixed, you indeed have to specify -DENABLE_SECURITY=YES. Fixing it shouldn't take long, but I really must put some effort into reviewing various pull requests first.

I dont't know what to say, this doesn't work as expected. If the solution just as you saied, then i have no idea which part of the process went wrong.
I run the test on the docker environment of raspiberry4.
- Ubuntu 18.04
- ROS2 eloquent(binary installed throught dockerfile)
- cyclonedds && rmw-cyclonedds(source installed in docker container)

> If you did use https://github.com/ros2/sros2/blob/eloquent/SROS2_MacOS.md#define-the-sros2-environment-variables then there must be something else still.

 Even test on the no security feature condition, the process quit as soon as it started. The problem will disapper after switching the branch of cyclonedds to 0.6.0 as i mentioned above, so the reason for this might be the code of cyclonedds(`master branch`).

**Comment by eboasson** [comment]
@Ada-King this is getting a bit frustrating because it ought to work and it is quite important to me that it gets solved. But I am also pressed for time today and I definitely won't be able to replicate your environment today or tomorrow. So please bear with me ...

My observations are that, with `-DENABLE_SECURITY=YES`:
* ROS2 master (so Foxy + a few patches) + Cyclone master works fine on the ROS2 CI, including security, and that includes running on Ubuntu, and uses both x64 and ARMs, and
* Dashing + Cyclone master works fine on my mac, including security;

and therefore I am pretty sure the basics are fine. Also note that Cyclone 0.6.0 doesn't include security support, so that it behaves very differently is perhaps not too surprising.

What seems likely to be different: network interfaces, IPv4/IPv6 and configuration files. Cyclone can write a trace file that contains a lot of information, https://github.com/eclipse-cyclonedds/cyclonedds/#configuration has an example, but there is also shortcut:
```
CYCLONEDDS_URI='<Tr><V>finest</><Out>stdout</></>' .../talker
```
Should enable a very detailed trace and write it to standard error. That might contain something of interest.

But what I personally would do is start it in a debugger and see where it aborts. As I mentioned, at my first attempt it aborted because of some ROS2 code throwing an exception. So `gdb` might be a practical tool ...

**Comment by fujitatomoya** [comment]
@Ada-King 

did you follow the procedure [here](https://github.com/ros2/sros2/blob/master/SROS2_Linux.md) with source build?

**Comment by Ada-King** [comment]
No, I set up the `eloquent` environment based on the ros2 docker image.
```
...
FROM ros:eloquent
...
```
I was setting up the eloquent(source installed) environment on the raspiberry host, to confirm whether it was the cause. it just took too long time to complete build process yet.

**Comment by fujitatomoya** [comment]
problem confirmed with ros:foxy,

```
root@83cb91c0375e:/# ros2 run demo_nodes_cpp talker --ros-args --enclave /talker_listener/talker
[INFO] [1592355403.157283326] [rcl]: Found security directory: /root/sros2_demo/demo_keys/enclaves/talker_listener/talker

>>> [rcutils|error_handling.c:108] rcutils_set_error_state()
This error state is being overwritten:

  'Security was requested but the Cyclone DDS being used does not have security support enabled. Recompile Cyclone DDS with the '-DENABLE_SECURITY=ON' CMake option, at /tmp/binarydeb/ros-foxy-rmw-cyclonedds-cpp-0.7.1/src/rmw_node.cpp:871, at /tmp/binarydeb/ros-foxy-rcl-1.1.5/src/rcl/node.c:273'

with this new error message:

  'rcl node's rmw handle is invalid, at /tmp/binarydeb/ros-foxy-rcl-1.1.5/src/rcl/node.c:425'

rcutils_reset_error() should be called after error handling to avoid this.
<<<
[ERROR] [1592355403.161740329] [rcl]: Failed to fini publisher for node: 1
terminate called after throwing an instance of 'rclcpp::exceptions::RCLError'
  what():  failed to initialize rcl node: rcl node's rmw handle is invalid, at /tmp/binarydeb/ros-foxy-rcl-1.1.5/src/rcl/node.c:425
```

**Comment by fujitatomoya** [comment]
@Ada-King 

could you try to use master:HEAD with source build?

**Comment by Ada-King** [comment]
@fujitatomoya I have tested it on raspiberry4 with ros2 eloquent(source installed) and my host machine with foxy(source installed), They all run successfully.

**Comment by fujitatomoya** [comment]
@Ada-King 

good to know, can we close this now?

@eboasson 

thanks for the help!!!

**Comment by Ada-King** [comment]
Ok, close it.
Thanks for your help @eboasson
