### ISSUE TITLE
what did `dds_waitset_attach (waitSet, waitSet, waitSet);` do in examples/throughput/subscriber.c?

### ISSUE THREAD

**Issue by dolmens** [eclipse-cyclonedds/cyclonedds#569]
after that, the code `dds_waitset_attach (waitSet, *reader, *reader)` is straightforward, but i just don't understand the former one.

**Comment by eboasson** [comment]
Once upon a time it was decided that there was no need for guard conditions because that functionality could simply be folded into the waitset (so that you could "trigger" a waitset and attach waitsets to waitsets, including to itself).

What I found when I took over the project is that it makes it harder to read the resulting application code while adding several complications in the internals — and so I added a guard condition entity. I kept the old feature around for a while to make life easier in case anyone had already started to use it (unfortunately, I forgot to mark it deprecated).

The examples are really not very good examples and (perhaps because of that) they have been neglected as well. And so it happens that that particular piece of code still uses it. And it doesn't even actually use the feature! (There is no call to `dds_trigger_waitset`.)

**Comment by thijsmie** [comment]
Clearly we should have another look at the examples, and I've just made an issue for it. The actual question here was answered though.
