### ISSUE TITLE
Building and Running the Roundtrip Example

### ISSUE THREAD

**Issue by allangagnon** [eclipse-cyclonedds/cyclonedds#572]
I have installed CycloneDDS on my Mac OS 10.15.6. All the instructions went well until I went to "build and run the roundtrip example". I am getting the error of the following on the command line:

cmake ~/cyclonedds/share/CycloneDDS/examples/roundtrip

CMake Error at CMakeLists.txt:22 (idlc_generate):
   Unknow CMake command "idlc_generate"

--Configuring incomplete, errors occurred!

<img width="1757" alt="cyclonedds_error" src="https://user-images.githubusercontent.com/845281/89677559-4533f500-d8b3-11ea-9774-2de5b865b5ed.png">

**Comment by eboasson** [comment]
Hi @allangagnon, Cyclone DDS currently relies on an IDL compiler written in Java which sometimes causes problems when building (especially) ROS 2 from source because of its dependency on Maven and a JDK. ROS 2 doesn't actually need that IDL compiler (`rmw_cyclonedds_cpp` (de)serialises using the ROS introspection type support) and so we have configured things such that a `colcon`-managed build skips the IDL compiler if its dependencies are missing. This makes building ROS 2 from sources much easier, and that matters to us :)

However, the result is that a ROS 2 build, or even an install from downloaded binaries may be lacking the IDL compiler. (The ROS 2 packages for Linux do include it, the binaries for macOS don't.) While this detail is completely irrelevant for using ROS 2, it does matter when you try to write "regular" DDS programs and CMake happens to pick up a version of Cyclone that doesn't include the IDL compiler. Then the errors/warnings start ... Here CMake didn't see a definition for the `idlc_generate` command.

If you run into this, it is best to just build Cyclone from source including its IDL compiler. That may still not be quite enough, because CMake has a "module path" that tells it where to look for packages. For example, installing ROS 2 and sourcing its (e.g.) `setup.bash` sets the `CMAKE_PREFIX_PATH`, which can make CMake find the ROS 2-provided one instead of the one you just built. Prepending your own install directory to the `CMAKE_PREFIX_PATH` or setting the `CycloneDDS_DIR` variable to ".../lib/cmake/CycloneDDS" should result in CMake finding the correct version.

I have to say the message is very unfriendly. The main thing we're doing to solve this problem is by replacing the Java-based IDL compiler with a new one written in C. There are multiple reasons for this, but this is definitely one of them. (Another is that adding support for XTypes *and* multiple language bindings to the old Java one is a pain.) In a few weeks' time, the new compiler should be far enough along to make the switch. Then the Java dependency and this problem will be gone for good!

**Comment by allangagnon** [comment]
Thank you @eboasson this was it and I am up and running now! Great to hear the new changes coming and am excited to try them out!!

**Comment by thijsmie** [comment]
The changes mentioned by eboasson have come to pass, and we have received no more similar inquiries of failed builds! Solved :smile:.
