### ISSUE TITLE
Lease duration QoS is ignored

### ISSUE THREAD

**Issue by eboasson** [eclipse-cyclonedds/cyclonedds#58]
As noted in #49, the value of the lease duration in the (participant) liveliness QoS is completely ignored and the actual lease duration is taken from the configuration file (``Domain/Lease/ExpiryTime`` setting) instead. An argument can be made that a lease duration is a deployment setting and that a configuration file is a more appropriate place for it than a QoS setting, but to blatantly ignore the QoS setting is definitely not a good approach.

My initial thought is that taking the minimum of the QoS value and the configured would be a sensible approach, but I'd be interested in other people's opinions.

**Comment by xu3stones** [comment]
yes, agree with you. Blatantly ignore the QoS setting puzzles some people indeed including me.

**Comment by dennis-adlink** [comment]
Support for setting lease duration for liveliness kinds _automatic_ and _manual-by-participant_ is added in PR #274

**Comment by Aposhian** [comment]
Has this issue been resolved?

**Comment by dpotman** [comment]
> Has this issue been resolved?

Yes, support for the liveliness QoS is added in #342, including support for the `MANUAL_BY_TOPIC` policy. The participant lease duration from the participant QoS (which is a Cyclone specific extension) is used if present, and the default from [configuration](https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/docs/manual/options.md#cycloneddsdomaindiscoveryleaseduration) is used otherwise (see also https://github.com/eclipse-cyclonedds/cyclonedds/pull/1153).

**Comment by thijsmie** [comment]
This issue was resolved.
