### ISSUE TITLE
Problem about qos update

### ISSUE THREAD

**Issue by jwcesign** [eclipse-cyclonedds/cyclonedds#63]
Hi,
Recently I am very interested about QoS, and I meet one problem about qos updating. And the source code will not update and not resend new participant qos. Here is my example:
~~~
int main(int argc, char **argv) {
  dds_entity_t participant;
  dds_entity_t topic;
  dds_entity_t writer;
  dds_return_t ret;
  (void) argc;
  (void) argv;

  dds_qos_t *qos = dds_qos_create();
  char *x = "hello";
  dds_qset_userdata(qos, (void *) x, 5);

  /* Create a Participant. */
  participant = dds_create_participant(DDS_DOMAIN_DEFAULT, qos, NULL);

  dds_sleepfor(DDS_SECS(5));

  char *y = "yoyol";
  dds_qset_userdata(qos, (void *)y, 5);

  dds_set_qos(participant, qos);


  printf("set done!\n");
  while (true);

}
~~~
I check source code and there is too many status variables connected with participant qos, very confused.
And I check and the subscriber will not receive the new qos. So if I want to make it, How can I do this? 
(1) How to update qos of publisher's participant.
(2)How does the subscriber receive and update the publisher's participant qos.

**Comment by eboasson** [comment]
The shortest answer is qos changes are not supported yet. In this case, too, it would have been much better had "unsupported" been returned, it would have avoided the confusion, even if it would not have helped you make it work ...

There are two paths forward, one is to implement QoS changes, the other is to simply use topics to do whatever you want. The way QoS changes would work once implemented is really similar to publishing your own auto-dispose, transient-local topic. The key difference is that the "user_data" QoS forces you to handle serialisation of the data yourself, whereas using your own topic allows you to properly represent the data and have DDS handle the serialisation and byteswapping. In other words, for anything beyond trivial data, you're better off _not_ using the user/topic/group data QoS ... but for a quick hack they can be useful.

Implementing QoS changes is easy or hard, depending on what one are trying to achieve: correctness is really problematic, but if one can live with the edge cases being completely wrong while it kinda works in practice it becomes quite easy.

A correct implementation means you have to first notice a fundamental flaw in the DDSI specification with regards to QoS changes, and then decide what it means to be "correct", and then of course build it :) When I wrote the initial bits of this DDSI stack close to a decade ago, my interpretation of "correct" caused me to postpone supporting any QoS changes until some agreement on the proper handling of this flaw was reached, even though most of the QoS changes never cause any problems. Nothing being as permanent as the temporary, that decision is still present today in Cyclone DDS ...

The flaw is that QoS are in principle communicated asynchronously from the data in DDSI (the discovery protocol runs independently from the data flowing from writers to readers) and yet some of the mutable QoS settings affect the matching of readers and writers — partition, deadline and latency budget, to be precise. (Anything listed as RxO and Changeable in the big table with QoS settings in section 2.1.3 of the DDS 1.4 specification, and also partition because it does affect matching even though it hasn't been classified as RxO in the table.) The consequence is that naively changing any of these while data is being published brings your system in a state where data may be delivered to readers that shouldn't get it, or conversely, that readers that should, don't.

There are potential ways out, at least for changing the QoS on the writer side — I'm not sure there is any way out for a change on the reader side. For the writer side, the protocol has a notion of "inline QoS" that allow including the QoS in a data message, and so one could synchronously adjust the matches on the writer and include the new QoS settings in every message. The trouble then becomes knowing when you can safely stop including those settings (it is rather a waste of bandwidth, and having to dynamically rematch on every incoming sample is quite costly, too). Unfortunately, the protocol doesn't provide any guarantees on when an update to the discovery data has been processed. (That last detail also means that the alternative of simply waiting until all matched readers have acknowledged the data prior to actually changing the QoS is also problematic.)

That particular detail can be solved fairly easily in principle, for example by assuming that discovery information is fully processed before it is acknowledged and ensuring that that assumption is valid for at least one's own implementation. The quality of the interoperability would then be dependent only on the other implementations, but it would always kinda work, and in some settings work reliably.

So, if that were all ... but it is not all!

The second issue concerns non-volatile data. If I change the QoS on a transient-local writer after having written some data, say by changing the partition from "A" to "B", then any reader in "B" (matching topic and RxO QoS) will now match and start requesting historical data. Should it receive the data from the beginning or only starting with the QoS change? In other words, is the only thing that matters the current writer QoS, or is what matters really the QoS valid at the time of writing? It is the latter in my opinion, but that brings an interesting conundrum: namely that you would have to match all pairs of writers and readers that could potentially have matched in the past, recover the data the writers had written with matching QoS while discarding anything currently written using a non-matching QoS. That goes completely against the desired behaviour in all other dimenions, but I believe it to be the only correct behaviour if such QoS changes are allowed.

This, by the way, is also the matter that resulted in the DDS Security specification disallowing changing the partition on a secure endpoint ... so the problem was eventually acknowledged, if never actually addressed.

To the best of my knowledge all implementations get it wrong one way or another, perhaps with the exception of OpenSplice when using its proprietary "RT networking" protocol (that one handles discovery and RxO QoS completely differently), but as I am not intimately familiar with the other implementations, I can't be certain. Some basis for my belief that everyone gets it wrong lies in a common response to my line of reasoning: "why would you ever want to do something as crazy as playing with RxO mismatches?", but one shouldn't first introduce 20+ QoS plus a costly feature like RxO matching, and then try to dismiss the consequences like that ...

Anyway, what to do with Cyclone DDS?

Firstly, non RxO QoS (and partition) changes are a non-issue, the argument above simply doesn't apply. So those ought to be supported. That includes changing the "user_data" QoS.

Secondly, one could simply ignore the problems, support RxO and partition changes without any synchronisation or attempt at making it safe to use, and put a note in the documentation that it is perhaps a bad idea to base one's design on changing those settings. Alternatively, one could forbid changing any RxO/partition and return an error. Considering the very limited usefulness of changing the deadline and latency budget, and the restrictions put on partition changes by the security spec, that would be a pretty reasonable approach; but it wouldn't completely save one from having to update the matches because other implementations allow them.

Implementation-wise it is pretty straightforward to do any of the above. Publishing an updated QoS is as simple as sending a new SPDP/SEDP discovery message. The code currently ignores updates, but that it is easily fixed, and then one would have to update the locally cached QoS, propagate the changes to the built-in topics, and re-do the matching if any of these three QoS are changed.

Because of the day that re-matching on QoS changes would be added, the code already has a read/write lock for all QoS/reader-writer matching (``qoslock``). It is currently only ever acquired for reading because the QoS are all constant, but for QoS _change_, it would have to be held for writing while redoing the match. Implementing "imprecise" QoS changes is thus pretty straightforward.

My experience is that the problem pops up only rarely, so it might be a while before I would get around to implementing it. If you (or anyone else) were to provide an implementation — even if only partial, e.g., just for the "user_data" on a participant — it would be welcomed.

**Comment by jwcesign** [comment]
@eboasson , Really thanks for detail explaining, u are right, updating some qos is not a good idea, I did just for 'USER_DATA'. My way is to add a participant value in `gv` and than when update it, I call `spdp_write` to do this with new `USER_DATA`.

**Comment by eboasson** [comment]
@jwcesign, yes, that would work and I am happy that it helped you solve your problem. For the longer term, I really want a proper implementation where the "user data" part of the QoS struct in the participant is updated. I don't think there'll be any major changes to the way things work until then, so it shouldn't be very hard for you to locally maintain your simple trick for a while. I hope you'll be ok with that.
