### ISSUE TITLE
How can I get all participant detail information??

### ISSUE THREAD

**Issue by secondage** [eclipse-cyclonedds/cyclonedds#640]
In ddsls code， use `dds_take` to get all the buildin topic and participant info, but only had `dds_builtintopic_participant_t` and `dds_sample_info_t` data,  for participants, only qos and key can be obtained. How do I instantiate participants to obtain information such as their domainid or name？

thx.

**Comment by eboasson** [comment]
Because of how the discovery process works, it only discovers nodes with the same domain id (even if participants from different domains use the same port numbers), so the domain id is simply the same as the local domain id.

Things like process name and id are not included in the spec'd discovery information and currently Cyclone doesn't add them. I am aware of some implementations that add information on process name, id, hostname in the "properties" QoS. That's something that I expect Cyclone to start doing at some point as well, because it is important to have that information and there doesn't seem to be a much better way.

Until then, the only way is to follow the traditional DDS application trick of adding such information to the `USER_DATA` QoS. But be aware that there is no standard for the representation, so generic tooling can only print it, not interpret it.

**Comment by secondage** [comment]
Thank you for your reply, it seems that I only have to add the required information in user_data QoS.
