### ISSUE TITLE
Support for Content Filtered Topics, Writer-Side Filtering and Implementation Architecture?

### ISSUE THREAD

**Issue by JackWinch** [eclipse-cyclonedds/cyclonedds#649]
Hey there folks,

Great to see another open source DDS implementation become available.  I shall be watching the progression of this project with very keen eyes due to my personal and professional interest in the DDS technology.

I've had a quick look over the available documentation and examples, although I'll admit I haven't sifted thoroughly through the source at this point in time (I plan to though).

Could you please confirm whether the implementation supports Content Filtered Topics (CFTs) and Writer-Side Filtering?  If not, are these items planned for implementation within the near future?

Also, is this implementation of a single process architecture (i.e., all DDS capability provided by the library is executed within the context of the user application process), or does the implementation use an external service / daemon (e.g., much like the PrismTech implementation used to, before single process capability became available).

Any clarification you can provide would be greatly appreciated,
Jack

**Comment by JackWinch** [comment]
@eboasson - could you provide a one line reply to this?

**Comment by eboasson** [comment]
Hi @JackWinch, strangely I have this sense that I did respond ... that must have been my imagination because I am surely not seeing any response from my side! Terribly sorry about that and thanks for pinging me again.

> Could you please confirm whether the implementation supports Content Filtered Topics (CFTs) and Writer-Side Filtering? If not, are these items planned for implementation within the near future?

CFT is supported in a limited way, you can set a filter function that is presented with a sample and says pass/reject. That is not at all what I want (nor what the DDS spec describes), which is expressions that are parsed and validated by the implementation. Basically, the current support:
* Is relative expensive for sample representations (`sertype` after PR #559, a.k.a. type support) that store the sample in CDR, like the current default implementation. There are advantages and disadvantages to storing CDR, but as far as filtering goes, it requires deserializing the sample *just for filtering* because the filter function can do anything. So that's a bit of a downside.
* It is impossible for the implementation to know whether the filter is only on fields that are part of the key, or also looks at other fields. Various optimizations are possible if you know it is the former case. Again, getting the filter specification as an expression addresses this problem.
* One cannot transfer an arbitrary function to another machine across the network, but one can transfer an expression in a string. So writer-side filter is not possible with the current model.

Consequently, the plan is firstly to change the interface (probably maintaining the current interface for compatibility) to accept the filter expression as a string. Secondly, there are various important use cases where writer-side filtering is very beneficial, and so that is in the plan as well.

It's actually on the roadmap https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/ROADMAP.md#midterm-milestones 😄 .

> Also, is this implementation of a single process architecture (i.e., all DDS capability provided by the library is executed within the context of the user application process), or does the implementation use an external service / daemon (e.g., much like the PrismTech implementation used to, before single process capability became available).

Currently it is a pure single-process model. There are plans (but at lowish priority) to additionally allow running it as a daemon process that the application processes call into for actually providing the service. I actually studied that model and the performance on modern hardware before we made a bunch of Cyclone's design choices and the performance would still be acceptable. The long-term version of that is combining that "agent"-based variant with shared memory to speed up read/write.

**Comment by JackWinch** [comment]
Hey @eboasson,

Thanks for the reply.  I saw there was the ability to set a Topic filter function callback via `dds_set_topic_filter()` function in the C API documentation.  While this offers a method of being able to filter, I agree with your comments regarding the current implementation.  Better functionality, and likely better performance, will be achievable with a standard aligned (DDS and RTPS-DDSI) implementation of content filtering and querying.

I work with DDS in a context where writer-side filtering is crucial to the performance and function of the deployment, so I'm glad to hear that it will be a priority for the project in due time.  I missed the roadmap when I was digging around.

> The long-term version of that is combining that "agent"-based variant with shared memory to speed up read/write.

To be honest, the single-process model approach is typically preferable for my use-cases.  Just curious about this statement, however.  Is the plan to implement the initial "agent" with a stream-based interface between the user application and "agent"?

Thanks for the response and information.

Jack

**Comment by eboasson** [comment]
> To be honest, the single-process model approach is typically preferable for my use-cases. Just curious about this statement, however. Is the plan to implement the initial "agent" with a stream-based interface between the user application and "agent"?

I think it'll be a stream-based one — the primary use case that I have in mind would be satisfied quite well with unix domain sockets, possibly combined with some shared memory, but that model extends naturally to TCP or even TCP+TLS, which would give a way of "dialling in" from a remote node. That in turn has lots of interesting applications.
