### ISSUE TITLE
Memory keeps increase

### ISSUE THREAD

**Issue by BH1SCW** [eclipse-cyclonedds/cyclonedds#653]
Hi,  I found my demo keeps consume memory. Could you help me to correct it? 
Thanks
IDL:

```
typedef struct OGM_Map_Struct
{
    octet data[1212296];
} ogm_map_t;
#pragma keylist OGM_Map_Struct data
```

reader:
```

#include "dds/dds.h"
#include "uos_dds_mw.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#define MAX_SAMPLES 1

int main(int argc, char **argv)
{
  dds_entity_t participant;
  dds_entity_t topic;
  dds_entity_t reader;
  ogm_map_t *ogm_msg;
  void *samples[MAX_SAMPLES];
  dds_sample_info_t infos[MAX_SAMPLES];
  dds_return_t rc;
  dds_qos_t *qos;
  (void)argc;
  (void)argv;

  participant = dds_create_participant(DDS_DOMAIN_DEFAULT, NULL, NULL);
  if (participant < 0)
    DDS_FATAL("dds_create_participant: %s\n", dds_strretcode(-participant));

  topic = dds_create_topic(
      participant, &OGM_Map_Struct_desc, "uos_gps", NULL, NULL);
  if (topic < 0)
    DDS_FATAL("dds_create_topic: %s\n", dds_strretcode(-topic));

  /* Create a reliable Reader. */
  qos = dds_create_qos();
  dds_qset_reliability(qos, DDS_RELIABILITY_RELIABLE, DDS_SECS(10));
  reader = dds_create_reader(participant, topic, qos, NULL);
  if (reader < 0)
    DDS_FATAL("dds_create_reader: %s\n", dds_strretcode(-reader));
  dds_delete_qos(qos);

  printf("\n=== [Subscriber] Waiting for a sample ...\n");
  fflush(stdout);
  while (true)
  {
    samples[0] = OGM_Map_Struct__alloc();
    int *n = (int *)samples[0];
    rc = dds_take(reader, samples, infos, MAX_SAMPLES, MAX_SAMPLES);
    if (rc < 0)
      DDS_FATAL("dds_read: %s\n", dds_strretcode(-rc));
    if ((rc > 0) && (infos[0].valid_data))
    {
      printf("=== [Subscriber] Received : %d\n", *n);
      fflush(stdout);
      dds_sleepfor(DDS_MSECS(1000));
    }
    else
    {
      dds_sleepfor(DDS_MSECS(20));
    }
    OGM_Map_Struct_free(samples[0], DDS_FREE_ALL);
  }
  rc = dds_delete(participant);
  if (rc != DDS_RETCODE_OK)
    DDS_FATAL("dds_delete: %s\n", dds_strretcode(-rc));
  return EXIT_SUCCESS;
}
```

writer:
```
#include "dds/dds.h"
#include "uos_dds_mw.h"
#include <stdio.h>
#include <stdlib.h>

int main (int argc, char ** argv)
{
  dds_entity_t participant;
  dds_entity_t topic;
  dds_entity_t writer;
  dds_return_t rc;
  ogm_map_t ogm_msg;
  uint32_t status = 0;
  (void)argc;
  (void)argv;

  participant = dds_create_participant (DDS_DOMAIN_DEFAULT, NULL, NULL);
  if (participant < 0)
    DDS_FATAL("dds_create_participant: %s\n", dds_strretcode(-participant));

  topic = dds_create_topic (
    participant, &OGM_Map_Struct_desc, "uos_gps", NULL, NULL);
  if (topic < 0)
    DDS_FATAL("dds_create_topic: %s\n", dds_strretcode(-topic));

  writer = dds_create_writer (participant, topic, NULL, NULL);
  if (writer < 0)
    DDS_FATAL("dds_create_writer: %s\n", dds_strretcode(-writer));

  printf("=== [Publisher]  Waiting for a reader to be discovered ...\n");
  fflush (stdout);

  rc = dds_set_status_mask(writer, DDS_PUBLICATION_MATCHED_STATUS);
  if (rc != DDS_RETCODE_OK)
    DDS_FATAL("dds_set_status_mask: %s\n", dds_strretcode(-rc));

  while(!(status & DDS_PUBLICATION_MATCHED_STATUS))
  {
    rc = dds_get_status_changes (writer, &status);
    if (rc != DDS_RETCODE_OK)
      DDS_FATAL("dds_get_status_changes: %s\n", dds_strretcode(-rc));
    dds_sleepfor (DDS_MSECS (20));
  }

  /* Create a message to write. */
  int *n = (int*) &ogm_msg;
while(1)
{
  (*n)++;
  printf ("=== [Publisher]  Writing : %d\n", *n);
  rc = dds_write (writer, &ogm_msg);
  if (rc != DDS_RETCODE_OK)
    DDS_FATAL("dds_write: %s\n", dds_strretcode(-rc));
  
  dds_sleepfor (DDS_MSECS (1000));
}
  rc = dds_delete (participant);
  if (rc != DDS_RETCODE_OK)
    DDS_FATAL("dds_delete: %s\n", dds_strretcode(-rc));

  return EXIT_SUCCESS;
}
```

I am confused that writer also keeps consuming memory.

**Comment by BH1SCW** [comment]
Another question is：

what is the difference between  OGM_Map_Struct_free() and dds_return_loan() ?

**Comment by eboasson** [comment]
> I am confused that writer also keeps consuming memory.

That's because this:
```
#pragma keylist OGM_Map_Struct data
```
tells Cyclone that the `data` field of `OGM_Map_Struct` is a key, meaning that it needs to track lifetimes for each unique value of `data` (and implement the "keep last" behaviour for reliability when you publish the same data again — the key here is very much like the primary key in a table in a relational database). Every loop of the publisher changes the value, so every to call to `dds_write` forces it to keep an additional copy of the key value (that is, your 1212296 bytes a few extra ones for administration).

I suspect you really didn't want it to do that. You do that by not specifying a key field (so `#pragma keylist OGM_Map_Struct` in the IDL). The default "history" QoS setting is to keep only the most recent data for each key value, and so now you're receiving everything you send. When you remove the key, it'll still keep only the most recent data, but that means you can lose data if the network or the reader can't keep up with the writer.

The solution for that is to set the history QoS to "keep all" or to set it to "keep last 10" to keep a small queue. It's generally best to keep no more data around than you need, so whether you have to do this is for you to decide 😄 . And *if* you want to do this, then strictly speaking you only need to do that on the reader and the writer, but in Cyclone's API, those inherit the setting from the topic. I would recommend setting the QoS on the topic:
```C
dds_qos_t *qos = dds_create_qos();
dds_qset_history (qos, DDS_HISTORY_KEEP_LAST, 10);
dds_qset_reliability (qos, DDS_RELIABILITY_RELIABLE, DDS_INFINITY);
topic = dds_create_topic (participant, &OGM_Map_Struct_desc, "uos_gps", qos, NULL);
```
I added the "reliability" one for good measure. With samples this large, using the reliable protocol is usually a good practice, but that's not an iron rule.

> what is the difference between OGM_Map_Struct_free() and dds_return_loan() ?

`OGM_Map_Struct_free` frees the memory allocated for one sample, `dds_return_loan` releases all memory that Cyclone allocated for you in cases where you asked it to allocate memory for you in `dds_read` or `dds_take` (so that you don't have to do `samples[0] = OGM_Map_Struct__alloc()` yourself):
```C
    samples[0] = NULL;
    int *n = (int *)samples[0];
    rc = dds_take(reader, samples, infos, MAX_SAMPLES, MAX_SAMPLES);
    if (rc < 0)
      DDS_FATAL("dds_read: %s\n", dds_strretcode(-rc));
    if ((rc > 0) && (infos[0].valid_data))
    {
      printf("=== [Subscriber] Received : %d\n", *n);
      fflush(stdout);
      dds_sleepfor(DDS_MSECS(1000));
    }
    else
    {
      dds_sleepfor(DDS_MSECS(20));
    }
    dds_return_loan(reader, samples, rc);
```
When you limit it to just sample, it doesn't make much of a difference 😄.

**Comment by BH1SCW** [comment]
It WORKS!!!
You've saved my life and please accept my endless gratitude!  Above is the most professional answer.

By the way, I found I can set QOS to topic and reader at the same time. Is the any rules or difference? If I just set QOS to reader, will it be okay?

TNX

**Comment by eboasson** [comment]
You're welcome 😄 

> By the way, I found I can set QOS to topic and reader at the same time. Is the any rules or difference? If I just set QOS to reader, will it be okay?

It is fine if you just set it on the readers and writers.

Longer version:

I personally find it easier to think about QoS when thinking about how I want to model the data in the system (and thus, the topics). When approaching things from that angle, I find it makes the most sense to set them on the topics and let the readers and writers inherit it. But in DDS it is the reader and writer QoS that determine the behaviour and therefore there's no need to set the topic QoS. (With one exception: it matters if the "durability kind" is set to transient or persistent, but that's still TBD for Cyclone.)

**Comment by BH1SCW** [comment]
Thank you so much! It is very helpful to me.
Let me close this issue.
