### ISSUE TITLE
dds_create_topic: Bad Parameter if there is "-" in topic string 

### ISSUE THREAD

**Issue by BH1SCW** [eclipse-cyclonedds/cyclonedds#657]
Hi, I found there will be error if using "-" in topic string. Could you help to check this?

`topic = dds_create_topic(participant, &OGM_Map_Struct_desc, "uos-gps", qos, NULL);
`
this will get error message : 

`1607564938.948660 [] Helloworld: dds_create_topic: Bad Parameter
`

but this will be fine:

`topic = dds_create_topic(participant, &OGM_Map_Struct_desc, "uos_gps", qos, NULL);`

The test case is at here: https://github.com/eclipse-cyclonedds/cyclonedds/issues/653

Thanks very much~

**Comment by spiderkeys** [comment]
The DDS specification does not allow hyphens as characters in topic names, only alpha-numeric characters, '/', and '_'.

https://design.ros2.org/articles/topic_and_service_names.html#:~:text=(~)%20in%20them.-,DDS%20Topic%20Names,not%20start%20with%20a%20digit.

**Comment by eboasson** [comment]
Actually ...

If you look at the next-to-last page of https://www.omg.org/spec/DDS/1.4/PDF (which is the only place in the specifications where it is defined what constitutes a valid topic name):

> TOPICNAME - A topic name is an identifier for a topic, and is defined as any series of characters ‘a’, ..., ‘z’, ‘A’, ..., ‘Z’, ‘0’, ..., ‘9’, ‘-’ but may not start with a digit.

Crazily enough, '\_' is technically illegal, '-' is legal. That is considered a typo by OpenSplice (and Cyclone) and they allow '\_' instead. The discussions that led to the decision to consider it a typo happened before my time, so I have no idea of the parties involved nor the reasoning. It certainly fits better with identifiers in some common programming languages.

The claim that '\/' is allowed is a figment of the ROS2's imagination, likely driven by an (ahem) general sloppiness in these sort of things from some DDS implementors. That the '\/' is now pretty universally supported by DDS implementations — in particular also in OpenSplice and Cyclone, which were *changed* for it (e.g. 0014941fad222fb8c0c791ad11950506f42754d6) — is simply because there is no way one can play along in the ROS2 ecosystem if it isn't accepted.

And come to think of it:

>  defined as **any** series of characters

means an empty sequence is also a valid topic name! I am tempted to let it remain illegal in Cyclone ...

**Comment by BH1SCW** [comment]
Great thanks to both of your replies!

**Comment by spiderkeys** [comment]
@eboasson fair enough on the details of the spec itself; I've just grown to accept that the actual implementations allow / and _ :sweat_smile: The inclusion of them seems reasonable, but it would be nice if the official standards and docs matched up...

Thanks for the additional context!
