### ISSUE TITLE
How to reduce dds_write time

### ISSUE THREAD

**Issue by BH1SCW** [eclipse-cyclonedds/cyclonedds#660]
Hi, I did some test on sending big size buffer using cylclone dds. I hope to reduce the time cost of dds_write.

Your advice is always welcome and appreciated. 

```
t1 = get_time();
rc = dds_write(...);
t2 = get_time();
interval = t2 - t1;
```

here we define 2 different test struct: 
1.15MB and 2.448MB

```
typedef struct OGM_Map_Struct
{
    octet data[1212296];
} ogm_map_t

typedef struct Roadmap_Vis
{
    octet data[2602056];
} roadmap_vis_t
```

average time:

```
ogm_map  17.11 ms
roadmap_vis 40.95 ms
```
Max time:

```
ogm_map  26 ms
roadmap_vis 75.02 ms
```

First I am not sure if this is normal range, I hope it is possible to reduce the time because if in a loop it may block the whole process logic.

**I use best effort mode and the data lost is allowed.
All data does not need to do serialisation because it is just array, will it help if I disable serialisation?
How to disable serialisation? set //CycloneDDS/Domain/Internal/MaxSampleSize set to  0 b?**

If async write mode is supported, that sounds a nice way to solve the problem, but from https://github.com/ros2/rmw_cyclonedds/issues/89
it seems async write is not supported by cyclone dds now.

any other way to reduce write time?

Thanks

**Comment by eboasson** [comment]
If you look at where the time is spent, it is spent waiting for `sendmsg` to complete, that is, the network can't keep up. The serialisation ends up being a memcpy and with modern memory subsystems doesn't usually become an issue until you exceed a GB/s. The reasoning behind that figure is simple: memory bandwidth is >>10GB/s, but there's some copies to serialise/send it, so let's say you get 10GB/s effective. At 1GB/s, that means, you're spending 10% of your time in copying.

Indeed asynchronous writes would help, but it just isn't supported yet. What may help is that all network I/O is inherently asynchronous in most operating systems: one writes the data into a socket _send_ buffer, the kernel transfers it from the socket buffer to the network. Cyclone defaults to a pretty small send buffer, but you can raise it to huge sizes, just like you can with the receive buffer. If you make it large enough to contain the sample, the kernel will do the asynchronous write for you.

There are downsides to that: one is that the other outgoing messages get stuck behind it in the buffer (it'll probably survive that with the delays you mention). The other is that it only works if the network is fast enough to keep up with the average rate at which you're trying to send, else you'll just fill up the larger buffer and end up in the same situation (but worse because of that large buffer).

Do-it-yourself async writes could be an option (yes ... really ...), if it is a one-off and you can live with a single-place buffer. Then the code to do it asynchronously would be no more than a few lines of code. Or, if you're feeling adventurous, you could take the asynchronous writing that does exist (but that I try not to tell anyone about because it really was just an experiment that made its way out in the initial commit by accident!) and modify it a bit so that it only handles data for some writers and never blocks. If you make `xpack_send_async` per-writer and change `nn_xpack_send` a bit, you'd be in business.

**Comment by BH1SCW** [comment]
Hey, eboasson
Great thanks for such a detailed answer!
I made some perf with flamegraph
![](https://tva1.sinaimg.cn/large/008eGmZEly1gmf74k6cmwj30dz07imyg.jpg)

if I put big buffer of the calling dds_write tasks into a thread pool, is it a good way to deal with the problem?

**Comment by thijsmie** [comment]
The main problem was solved! There was a secondary question with no follow-up, please open a new issue if that is something you still want to talk about.
