### ISSUE TITLE
Cross compilation broken

### ISSUE THREAD

**Issue by sjames** [eclipse-cyclonedds/cyclonedds#672]
Hi Cyclone team,

I just found out that some recent changes broke the ability to cross-compile cyclonedds.  The change that likely causes the problem is https://github.com/eclipse-cyclonedds/cyclonedds/commit/bc443e62492a538bd6b91104de185667e76d9ef9 .

The build attempts to run the freshly compiled ddsconf to generate defconfig.c . This is fine on native builds, but this fails when cross-compiling.

``
 [ 21%] Built target ddsconf
 make[2]: Entering directory '/home/sjames/playground/tbd_os/target/aarch64-unknown-linux-gnu/release/__build/cyclonedds'
 [ 21%] Generating defconfig.c
/bin/sh: 1: ../../bin/ddsconf: Exec format error
``

Regards,
Sojan

**Comment by eboasson** [comment]
@k0ekk0ek we really need to make sure the cross-builds work fine, so if you have some time to look into how to make this work nicely using cmake that'd be great.

Also if you have some time, it might be a good idea to peruse https://github.com/sjames/cyclonedds-rs: it is a really nice rust binding. It think it would be nice to make the transition to the new IDL compiler as smooth as possible for it.

**Comment by ThijsSassen** [comment]
Hi Sojan,

I had the same problem with a Freertos build. You can build ddsconf as host build on x86 with --target ddsconf in /build-ddsconf for example and then include the binary in the cross compile build with -DCMAKE_PREFIX_PATH=build-ddsconf/bin

**Comment by k0ekk0ek** [comment]
Hi @sjames! #625 fixed the issue. Basically it looks for a `ddsconf` compiled for the host machine if cross compiling. It seems it finds an executable compiled for another architecture (or builds it for the target and then cant execute on the host). This maybe caused by specifying the target compiler directly instead of using `CMAKE_TOOLCHAIN` so that CMake doesn't realize it's actually cross compiling(?) Of course, that's but an initial guess. Can you provide some additional info on how you invoke CMake?

Sidenote: you're/we're very likely to run into the same issue once the new IDL compiler arrives, because it's written in C as opposed to Java, so it requires the executable at build-time too.

As for the rust-binding, I'd be happy to help out. A quick peek at the [cycloneddscodegen](https://github.com/sjames/cycloneddscodegen) repo shows it invokes the Java compiler to generate C code. From memory, (I could be completely off here) you use a RUST based parser to automatically generate bindings for the types? If that's indeed the case, simply replacing the Java command by invoking the new executable is enough and I think all that's required is to drop some code from `cycloneddscodegen`. Of course, happy to help out here too. Eventually it maybe easier to write a backend for the new compiler (the new `idlc` just loads a shared library and calls the `generate` function), but it maybe a bit early for that. I think I'll finish the new compiler this week (I'm close). I propose we update `cycloneddscodegen` once #655 contains the backend, that seems easiest(?)

**Comment by sjames** [comment]
Thank you @k0ekk0ek . You are absolutely right, I did not use a toolchain file, my bad. I will give it a shot with the toolchain file later this week.

About the rust-binding. Yes, I use the Java IDLC to generate the C file.   The structures themselves are generated by an IDL to Rust converter. I will be happy to remove the Java file as soon as the IDLC is ready.

Thank you again,  for your hint on using the toolchain file.

Regards,
Sojan
