### ISSUE TITLE
ROS2 foxy Cyclone DDS multiple nodes - unicast configuration

### ISSUE THREAD

**Issue by anastasiapan** [eclipse-cyclonedds/cyclonedds#687]
Currently I have ROS2 foxy on a linux docker container and what I want to do is to work by communicating with Windows host and ROS2 running in containers. I had solved this problem by posting an issue here (https://github.com/eclipse-cyclonedds/cyclonedds/issues/677)) but what I have noticed now is that I cannot run multiple ROS nodes on the Windows host.

## Expected behavior:
Have multiple ROS nodes on my machine and communication with Docker.

## Actual behavior:
When I try to start more than one nodes the following happen:
1. The first node starts successfully
2. The second node crashes with this error: ` rtps_init: failed to create unicast sockets for domain 0 participant index 0 (ports 7410, 7411)`

## System
- OS: Windows 10 
- Network Interfaces: My Ethernet adapter 
- ROS2: Foxy
- and the configuration proposed on issue https://github.com/eclipse-cyclonedds/cyclonedds/issues/677)

## Things I tried:
- Set AllowMulticast to true - nothing changed
- Set the Participant Index to the default value. With this config the nodes start but the Docker container is not being discovered and the communication is lost.

**Comment by dennis-adlink** [comment]
The two nodes on the host that are configured using unicast and have the same participant index will try to bind to the same ports (7410/7411) on the configured interface, which will fail and prevents the 2nd node from starting. 

I've tried your setup using 2 nodes on a (Windows) host and a node in a docker container, and got it working with the configuration below. 

On the host, use this Cyclone configuration for the 2 nodes:
```xml
<CycloneDDS>
  <Domain id='any'>
    <General>
      <NetworkInterfaceAddress>${HOST_ADDR}</NetworkInterfaceAddress> 
      <AllowMulticast>true</AllowMulticast>
    </General>
    <Discovery>
      <ParticipantIndex>auto</ParticipantIndex>
      <MaxAutoParticipantIndex>9</MaxAutoParticipantIndex>
    </Discovery>
    <Tracing><Verbosity>config</Verbosity><Out>stderr</Out></Tracing>
  </Domain>
</CycloneDDS>
```
And configure the node on Docker using a participant index higher than `MaxAutoParticipantIndex` (which can be increased if required), so that it won't interfere with the nodes on the host:
```xml
<CycloneDDS>
  <Domain id='any'>
    <General>
      <ExternalNetworkAddress>${HOST_ADDR}</ExternalNetworkAddress>
      <AllowMulticast>false</AllowMulticast>
    </General>
    <Discovery>
      <ParticipantIndex>10</ParticipantIndex>
      <Peers><Peer address='${HOST_ADDR}'/></Peers>
    </Discovery>
    <Tracing><Verbosity>config</Verbosity><Out>stderr</Out></Tracing>
  </Domain>
</CycloneDDS>
```
Then start the Docker container with the port mapping for participant index 10, using ports 7430 and 7431:
`docker run -it -p 1.2.3.4:7430:7430/udp -p 1.2.3.4:7431:7431/udp --rm my/ros:app`

The docker node will send unicast discovery data to the host on the default port numbers (7410, 7412, 7414, etc), and advertises its own address (the host IP address on port 7430), so that the nodes on the host can reach the docker node.

**Comment by anastasiapan** [comment]
@dennis-adlink Thanks for your response it is working!
