### ISSUE TITLE
Implement CycloneDDS across different networks

### ISSUE THREAD

**Issue by destkk** [eclipse-cyclonedds/cyclonedds#688]
Operating System:
    Ubuntu 20.04

    DDS implementation:
    rmw_implementation used: rmw_cyclonedds

Hi there. May I know what are the methods that I could implement CycloneDDS across different networks? Current method could only be able to establish in the same network for discovery and communication of topics and services.

P.S: I have tried using the VPN method in .xml file and the issue is I could not launch gazebo with rmf_demos files. I am not sure if this configuration is compatible with the current rmf_demos version.
```

<?xml version="1.0" encoding="UTF-8" ?>
<CycloneDDS xmlns="https://cdds.io/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://cdds.io/config https://raw.githubusercontent.com/eclipse-cyclonedds/cyclonedds/master/etc/cyclonedds.xsd">
    <Domain id="any">
        <General>
            <NetworkInterfaceAddress>auto</NetworkInterfaceAddress>
            <AllowMulticast>false</AllowMulticast>
            <MaxMessageSize>65500B</MaxMessageSize>
        <FragmentSize>4000B</FragmentSize>
        <Transport>udp6</Transport>
        </General>
    <Discovery>
        <Peers>
            <Peer address="IPV6"/>
            <Peer address="IPV6"/>
        </Peers>
        <ParticipantIndex>auto</ParticipantIndex>
    </Discovery>
        <Internal>
            <Watermarks>
                <WhcHigh>500kB</WhcHigh>
            </Watermarks>
        </Internal>
        <Tracing>
            <Verbosity>severe</Verbosity>
            <OutputFile>stdout</OutputFile>
        </Tracing>
    </Domain>
</CycloneDDS>
```

When launching gazebo with rmf_demos file, I receive the following error below,
```
[building_map_server-3] 1612940156.042290 [0] building_m: Failed to find a free participant index for domain 0
[building_map_server-3] [ERROR] [1612940156.042372026] [rmw_cyclonedds_cpp]: rmw_create_node: failed to create domain, error Error
[building_map_server-3] 
[building_map_server-3] >>> [rcutils|error_handling.c:108] rcutils_set_error_state()
[building_map_server-3] This error state is being overwritten:
[building_map_server-3] 
[building_map_server-3]   'error not set, at /tmp/binarydeb/ros-foxy-rcl-1.1.10/src/rcl/node.c:276'
[building_map_server-3] 
[building_map_server-3] with this new error message:
[building_map_server-3] 
[building_map_server-3]   'rcl node's rmw handle is invalid, at /tmp/binarydeb/ros-foxy-rcl-1.1.10/src/rcl/node.c:428'
[gzserver-13] 1612940156.138800 [0]   gzserver: Failed to find a free participant index for domain 0
[gzserver-13] 1612940156.138800 [0]   gzserver: Failed to find a free participant index for domain 0
[gzserver-13] [ERROR] [1612940156.139039182] [rmw_cyclonedds_cpp]: rmw_create_node: failed to create domain, error Error
[gzserver-13] 
[gzserver-13] >>> [rcutils|error_handling.c:108] rcutils_set_error_state()
[gzserver-13] This error state is being overwritten:
[gzserver-13] 
[gzserver-13]   'error not set, at /tmp/binarydeb/ros-foxy-rcl-1.1.10/src/rcl/node.c:276'
[gzserver-13] 
[gzserver-13] with this new error message:
[gzserver-13] 
[gzserver-13]   'rcl node's rmw handle is invalid, at /tmp/binarydeb/ros-foxy-rcl-1.1.10/src/rcl/node.c:428'
[gzserver-13] 
[gzserver-13] rcutils_reset_error() should be called after error handling to avoid this.
[gzserver-13] <<<
[gzserver-13] [ERROR] [1612940156.139215831] [rcl]: Failed to fini publisher for node: 1
[gzserver-13] terminate called after throwing an instance of 'rclcpp::exceptions::RCLError'
```

**Comment by eboasson** [comment]
Hi @destkk, thanks for being willing to try setting up a VPN for this. I'd say there are two different things at play here.

The first is that Cyclone DDS should support "multi-homing", that is, using multiple network interfaces at the same time. I basically had it working on my own fork in the summer, but then "the things of life" intervened and it got figuratively snowed under. Now, while literally almost snowed in, I put some effort into turning it into a decent PR. Testing is still tricky for me, I think I'll have to write my own virtual network stack just for that.

I did test it a while back with some combination of loopback, ethernet and VM-based virtual networks, and it seemed to work fine then. Hopefully, my efforts at cleaning up my work didn't break things, and you're welcome to give it a try. Just checkout https://github.com/eboasson/cyclonedds/tree/multi-home-red-netw and specify the names of the networks you want to use in General/NetworkInterfaceAddress, separate with commas. No guarantees, but I'd love to hear what you run into — that is, whether it works or not.

The second is that by default there is a rather low limit to number of Cyclone processes on a machine when it runs with multicast disabled, which is the error you got when starting gazebo. (The typical case is when it uses the loopback interface on Linux because many kernels claim not to support multicast on loopback, even though it works perfectly fine.) This is mostly because of the way participant discovery requires sending periodic bursts of (relatively large) messages to all possible peers, and somewhat because of a long history. Raising the value for [MaxAutoParticipantIndex](https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/docs/manual/options.md#cycloneddsdomaindiscoverymaxautoparticipantindex) should take care of that error.

**Comment by thijsmie** [comment]
The support for multi-homing was merged a while ago! 🥳
