### ISSUE TITLE
add cyclonedds to lgtm quality & security analysis

### ISSUE THREAD

**Issue by joespeed** [eclipse-cyclonedds/cyclonedds#694]
please add cyclonedds to lgtm quality & security analysis https://lgtm.com 

I was intrigued to see lgtm is used with the code that runs in NASA's Mars helicopter 
https://github.com/nasa/fprime 
<img width="719" alt="image" src="https://user-images.githubusercontent.com/8238588/108609044-7d4ee100-7388-11eb-8f38-1e9320b11efa.png">

**Comment by k0ekk0ek** [comment]
With the removal of Java dependencies automatically building worked out-of-the-box. Results can be found over at the [LGTM page for Eclipse Cyclone DDS](https://lgtm.com/projects/g/eclipse-cyclonedds/cyclonedds/). I think we have to disable the query for `FIXME:` comments, but other than that I guess we could add this. @eboasson, any objections?

**Comment by eboasson** [comment]
No objections. I agree with the need to do something about the `FIXME:`s. The only reason there are so many is because I have a habit of calling every place I want to revisit a FIXME whereas others probably use less scary words. I know no-one never asked *me* how a FIXME should be treated by a tool!

Disabling the query seems fine, but only if we then also introduce a GitHub issue to do something about the FIXMEs and re-enable the query. I think most can realistically be reclassified as TODOs, some probably really should be turned into issues.

And some of those warnings ... yuck ... I do think those tools are a bit stupid:
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/16984005/112265984-b32b0200-8c73-11eb-9659-c84100a20139.png">
it kinda does look like the author did consider that one must be careful ... How are you then supposed to write loops like this? If you do run-time tests (the overhead would be negligible and certainly irrelevant in this particular case) any truly decent static analysis tool would figure out that the tests are redundant and warn that the code may mislead the reader into thinking it can fail ...

Anyway, rant over. Let's do it.

**Comment by joespeed** [comment]
Great! Will you add lgtm badge to cyclonedds? https://blog.semmle.com/project-badges/ 

How about lgtm for rmw_cyclonedds? Would love all the tools and tests you run for cyclonedds to also be run for rmw_cyclonedds.
