### ISSUE TITLE
[Question] Correct way to manage samples

### ISSUE THREAD

**Issue by photex** [eclipse-cyclonedds/cyclonedds#695]
Hello! We're chugging along with our Rust bindings, but largely just sticking to the C API. We have some confusion however regarding the way in which you should correctly manage samples.

When reading/taking: Are we supposed to provide a pointer to a null pointer, or an array of null pointers?

As it stands... we get a lot of "ghosts" and then when returning/releasing the samples (dds_return_loan) we seem to only be returning the first sample (it's set to null) while others remain as "empty" samples (aka initialized to zero). 

When writing: we are experiencing a noticeable memory leak in a node that sends large amounts of data. We use dds_alloc and copy items from a Vec into a dds style sequence struct and mark `_release` as true expecting this to mean that cyclone is going to free that. We were making this copy because we don't actually see it stated when the serialization occurs and whether that pointer becomes owned by cyclone.. or even how long it holds on to that pointer.

Much of our issues are clearly related to ignorance since this is our first time using any DDS. :D Please be patient with us and forgive me if this is obviously easy to find information someplace.

**Comment by eboasson** [comment]
> When reading/taking: Are we supposed to provide a pointer to a null pointer, or an array of null pointers?

I'm rather glad that you asked. It is a rather strange interface, so inflicting some pain on those who still have not replaced by a straightforward one is no more than fair 🙂. Basically `dds_read` has two modes, one in which it allocates memory for samples for you, and one in which you have to provide the memory for the samples. It decides based on the *first* pointer in the array of pointers-to-samples that you pass in: if that is a null pointer, it will allocate for you and store the addresses in the array of pointer. If it isn't a null pointer, the samples must be pre-allocated.

Preallocated mode requires an array of pointers to samples, and they must all be valid (I'm deliberately doing 3 individual variables for the samples, because they don't have to be consecutive in memory as they are in an array):
```C
T a, b, c;
dds_sample_info_t si[3];
void *ptrs[3] = { &a, &b, &c };
for(int i = 0; i < 3; i++)
  memset(ptrs[i], 0, sizeof(T));
int32_t n = dds_read(reader, ptrs, si, 3, 3);
for(int i = 0; i < n; i++)
  T_free(ptrs[i], DDS_FREE_CONTENTS);
```
The `memset` part is irrelevant if there are no sequences or strings in T, but if there are, they have to be properly initialised or zero'd out (there is a small difference for sequences).

And if there are, then it will (re)allocate those strings/sequences, but that means that eventually you will have to free the memory. That requires knowing the type and writing it out by hand, or using the somewhat awkward "free" function I used above. `DDS_FREE_CONTENTS` means it just frees any embedded allocations but doesn't free `ptrs[i]` itself. An alternative is to expand the "T_free" macro that is generated by the IDL compiler and call `dds_sample_free(ptrs[i], &T_desc, DDS_FREE_CONTENTS)` directly (`T_desc` is the descriptor generated by the IDL compiler).

So this is somewhat inconvenient, one might say. Non-preallocated mode is slightly better:
```C
dds_sample_info_t si[3];
void *ptrs[3];
ptrs[0] = NULL;
int32_t n = dds_read(reader, ptrs, si, 3, 3);
for (int i = 0; i < n; i++) {
  T * const s = ptrs[i];
  // do something interesting
}
dds_return_loan(reader, ptrs, n);
```
The fact that `ptrs[0]` is a null pointer makes `dds_read` allocates sample array of size N (here 3), clear them, fill ptrs[0] .. ptrs[N-1] with pointers into this array and proceed as in the pre-allocated case. If no samples are returned (or an error), it is as if the allocation never happened. `dds_return_loan` then cleans up (it is a no-op if n ≤ 0), and is really the same as the loop freeing the samples contents above.

(You can do `void *ptrs[3] = { 0 };`, but that zeros the entire array rather than just the first element. Perfectly fine, but not *required*. Hence my initializing just the first element.)

> As it stands... we get a lot of "ghosts" and then when returning/releasing the samples (dds_return_loan) we seem to only be returning the first sample (it's set to null) while others remain as "empty" samples (aka initialized to zero).

It indeed also resets `ptrs[0]` to a null pointer: that way the next time round it will behave the same.

There is something else going on, and that is that it caches the allocated memory. If you were to execute the above snippet twice, the second time round you'd get the same pointers, because the samples it allocated the first time were kept around and reused.

Naturally, any sane person would then see what happens if you do the above twice, but delaying the first `dds_return_loan` call until after the second `dds_read` call. In that case, the *second* call will observe that the cached memory is still in use, and allocate new memory. Returning that "loan" then observes that it isn't the cached memory and frees everything immediately. That is, it loops over the samples to free what is inside, then frees the array itself.

Quite a complicated affair. In most cases, the non-pre-allocated variant gives the least trouble.

> When writing: we are experiencing a noticeable memory leak in a node that sends large amounts of data. We use dds_alloc and copy items from a Vec into a dds style sequence struct and mark _release as true expecting this to mean that cyclone is going to free that. We were making this copy because we don't actually see it stated when the serialization occurs and whether that pointer becomes owned by cyclone.. or even how long it holds on to that pointer.

The `dds_write` operation always makes a copy. As things stand today, that is done by serializing it to CDR, but the key bit is that it promises not to touch the memory after `dds_write` completes.

The `_release` flag is used only when freeing memory via `dds_sample_free`, and so it ties in with the pre-allocated/non-pre-allocated version of read and the freeing of samples. If an embedded sequence has the `_release` flag set, it means the memory is managed by the middleware, and is reallocated if you receive a sequence that is longer than what has been allocated up to now.

The case where all fields (length, maximum and release to be precise) are 0 is treated specially so that zero'ing the memory works. In that case, it will allocate memory and set the `_release` flag to true.

> Much of our issues are clearly related to ignorance since this is our first time using any DDS. :D Please be patient with us and forgive me if this is obviously easy to find information someplace.

No worries! Some of these details are rather quirky in DDS, and I dare say that with the behaviour of `dds_read`, Cyclone turns up the quirkiness a bit more.

The `dds_read` interface *will* be changed at some point (hopefully sooner rather than later), but the details still need to be decided.

**Comment by sjames** [comment]
I had some trouble figuring out reading buffers too.  Here is how I'm implementing it in Rust.  
https://github.com/sjames/cyclonedds-sys/blob/064cb6c6570ff87f7b9d540e072cd1c0264a47db/src/lib.rs#L153

Side note: The DdsLoanedData is just a box type that makes sure the memory is deallocated using the cyclonedds deallocator.

Cheers,
Sojan

**Comment by photex** [comment]
This is very illuminating! :D Thank you both.

I'm definitely not handling samples correctly in certain cases. For example, we have a simple function that takes a Vec and produces a suitable DDS sequence representation without copying, but there is a problem where I use some common Rust idioms for sub-sequences that actually make copies by allocating and are thereby not freed.

@sjames I like this approach you've established. We opted to make a `SampleArray` type and it's a bit in flux as we learn more:

```
pub struct SampleArray<T> {
    owner: dds_entity_t,
    buf: Vec<*mut T>,
    info: Vec<dds_sample_info_t>,
}

impl<T> SampleArray<T> {
    pub fn new(maxs: usize) -> Self {
        Self {
            owner: DDS_ENTITY_NIL as i32, // TODO: This is flimsy
            buf: vec![null_mut(); maxs],
            info: vec![Default::default(); maxs],
        }
    }

    pub fn max_samples(&self) -> usize {
        debug_assert_eq!(self.info.len(), self.buf.len());
        self.buf.len()
    }

    #[inline]
    pub fn num_samples(&self) -> usize {
        // TODO: any reason why we don't just store the value returned by read or take?
        self.info.iter().filter(|i| i.valid_data).count()
    }

    pub fn data(&self) -> &[T] {
        unsafe { std::slice::from_raw_parts(self.buf[0], self.buf.len()) }
    }

    #[inline]
    pub fn iter(&self) -> impl Iterator<Item = &T> {
        // TODO: What about a version of iter that doesn't remove the sample_info_t?
        self.data()
            .iter()
            .zip(self.info.iter())
            .filter(|(_, i)| i.valid_data)
            .map(|(s, _)| s)
    }

    pub fn release(&mut self) -> Result<()> {
        let has_loan = !self.buf[0].is_null();
        if !has_loan {
            log::trace!("No active loan to return.");
            return Ok(());
        }

        if self.owner == DDS_ENTITY_NIL as i32 {
            if has_loan {
                // Let this fall through and the Result returned will become
                // a ReturnCode::BadParameter
                log::error!("Previously loaned memory is un-releasable without an entity handle.");
            } else {
                return Ok(());
            }
        }

        log::debug!("Releasing samples allocated by reader");
        let sample_count = self.info.len();
        let rc = unsafe {
            let data = self.buf.as_mut_ptr() as *mut *mut c_void;
            dds_return_loan(self.owner, data, sample_count as i32)
        };

        self.owner = DDS_ENTITY_NIL as i32;
        if rc < DDS_RETCODE_OK {
            Err(ReturnCode::from(rc).into())
        } else {
            Ok(())
        }
    }
}

impl<T> Drop for SampleArray<T> {
    fn drop(&mut self) {
        if let Err(err) = self.release() {
            log::error!("An error occurred when dropping SampleArray: {}", err);
        }
    }
}
```

Our `TopicReader::take` implementation takes a `&mut SampleArray` as an argument. I'm not sure it really makes any sense to have these things separated like this. Storing the entity handle in the array in order to release it is error prone as well. It is probably better if the `TopicReader` is responsible for initializing the array and releasing it in this case... 
We'll see! :D

Thanks again for the explanations here!

**Comment by thijsmie** [comment]
The question was answered, even though this makes none of us _really_ happy :sweat_smile:. This is going into the knowledge base due to the fact it will 100% come up again.
