### ISSUE TITLE
Large pointcloud pubsub is unstable when there are many subscribers.

### ISSUE THREAD

**Issue by wep21** [eclipse-cyclonedds/cyclonedds#713]
### How to reproduce

- clone test repo
`git clone https://github.com/wep21/pointcloud_performance_test.git`
- import repository
`vcs import src < workspace.repos`
- build
`colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release --symlink-install`
- edit relay node number here
https://github.com/wep21/test_pointcloud_launch/blob/680ae57be180a099122be7237b139d853fd03c4e/launch/test_pointcloud.launch.py#L66
- launch pointcloud publisher and multiple relay nodes
`ros2 launch test_pointcloud_launch test_pointcloud.launch.py`
- measure topic hz
`ros2 topic hz /output`

### Expected behavior
The output of topic hz is 10 Hz.

### Actual behavior
The output of topic hz is decreasing less and less when the number of subscriber is more than 10.

### cyclonedds setting
```
 <?xml version="1.0" encoding="UTF-8" ?>
<CycloneDDS xmlns="https://cdds.io/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://cdds.io/config https://raw.githubusercontent.com/eclipse-cyclonedds/cyclonedds/master/etc/cyclonedds.xsd">
    <Domain id="any">
        <General>
            <NetworkInterfaceAddress>auto</NetworkInterfaceAddress>
            <AllowMulticast>default</AllowMulticast>
            <MaxMessageSize>65500B</MaxMessageSize>
            <FragmentSize>4000B</FragmentSize>
        </General>
        <Internal>
            <HeartbeatInterval max="100ms">100ms</HeartbeatInterval>
            <MinimumSocketReceiveBufferSize>30MB</MinimumSocketReceiveBufferSize>
            <Watermarks>
                <WhcHigh>500kB</WhcHigh>
            </Watermarks>
        </Internal>
        <Tracing>
            <Verbosity>config</Verbosity>
            <OutputFile>stdout</OutputFile>
        </Tracing>
    </Domain>
</CycloneDDS>
```
### kernel parameter
`net.core.rmem_default = 30971520`
`net.core.rmem_max = 30971520`

**Comment by eboasson** [comment]
I am pretty sure I know why you are seeing this, but while trying to confirm this, I ran into a build problem: I'm missing a package named `pcl`. I thought adding `perception_pcl` might do the trick, but that one also complains about it. Perhaps you can tell me where to go look for it?

Alternatively, you could yourself check my suspicion. It is built on the assumption that the N subscribers configured at https://github.com/wep21/test_pointcloud_launch/blob/680ae57be180a099122be7237b139d853fd03c4e/launch/test_pointcloud.launch.py#L66 are all in the same process.

Cyclone's RMW layer (`rmw_cyclonedds_cpp`) currently stores the serialized representation of the messages and deserializes during the `take` operation. Deserializing a point cloud takes some (approximately) fixed amount of time D, and with N subscribers it therefore spends a total of N * D in the deserializer. In the profiler, that should show up as a stack trace containing `serdata_rmw_to_sample`. The easiest way to check is to do a build with `CMAKE_BUILD_TYPE=RelWithDebInfo` (performance will be very nearly that of a `Release` one, but it includes debugging information) and then run it with a profiler attached.

If so, the good news is that this is simply a performance issue in the Cyclone's RMW layer rather than in Cyclone itself. Changing the behaviour to deserializing immediately on arrival of the data and using a copy/move constructor to hand it over to the application is something that can be done entirely inside the RMW layer. As a nice bonus, that also eliminates a copy and makes it possible to do the zero-copy interface for taking data. So a win all-around.

But it is best to first confirm that this is really what you are running into.

**Comment by wep21** [comment]
I'm sorry, but I made a mistake in dependency of `pcd_publisher`. Could you run `vcs pull src` and `rosdep install --from-paths src --ignore-src -r -y --rosdistro foxy`? This will install missing packages.
`

**Comment by eboasson** [comment]
Installing all that is going to be a bit of an effort for me (I'm neither using Ubuntu, nor an intel/amd CPU, except when in dire straits), are you sure those dependencies are really needed? It looks to me like you don't actually need libpcl to reproduce the problem. I'll get around to it, but this means it isn't something I can quickly do in between other things.

**Comment by wep21** [comment]
This pointcloud is equivalent to one scan of velodyne vls128. It is not necessary to use pointcloud if a message size which is published and subscribed is approximately equal  to that of velodyne vls128(about 60 MB/s).

**Comment by eboasson** [comment]
But it is with 1 process publishing and with *N* subscribers in one process, correct? Because then I can re-hack my hacked versions of ROS 2 hello world ... (I am vastly more familiar with the details of DDS than of the ROS 2 API, even if I have a fair bit of knowledge of the lower layer and some of the innards of ROS 2.)

**Comment by wep21** [comment]
There is 1 publisher and N relay nodes including N publishers and N subscribers in single process.

**Comment by eboasson** [comment]
I got the information I was looking for (with thanks to @dennis-adlink who had a setup that allowed running the test following your description), and it has really nothing to do with Cyclone, and everything with ROS 2. So I'll do the detailed response on https://github.com/ros2/rmw_cyclonedds/issues/292.

**Comment by mitsudome-r** [comment]
Just as a note, the test @wep21 was doing is in ROS2 Foxy with the latest binary release.
