### ISSUE TITLE
API Organisation for Languages other than C

### ISSUE THREAD

**Issue by kydos** [eclipse-cyclonedds/cyclonedds#73]
Dear all, I'd like to discuss the matter of APIs -- other than C --  organisation in cyclone DDS. My proposal is to ensure that API are external repository that have dependencies from the cyclone library. 

From my perspective the advantage of keeping the API separated from cyclone core are manyfold. Some of the most relevant being (1) we keep cyclones base small and with minimal set of external dependencies -- BTW, would be good to remove the dependency on JDK to build it; (2) We can more easily have people contribute and experiment with new API;  and (3) we can have different level of maturity for APIs and core.

We should also define some guidelines to follow for those that want to implement a new language bindings. 

Finally, I'd like to hear from the community what'd their needs would be. 

@kydos

**Comment by k0ekk0ek** [comment]
Hi Angelo,

I too hate the dependency on JDK for the core. The good news is that 
we're in the process of removing it. i.e. we're working on a new IDL 
compiler, or rather, type support system. I don't have a strong opinion 
on the matter, we can just enable building only the core by adding build 
options. The only problem is getting the proper backends in the IDL 
compiler. However, that problem can be solved by making the backends 
plugin based. That's what I originally envisioned anyway. For example, 
running "idlc -l java" or something would result in the compiler loading 
libcyclonejava from a certain directory and use that to generate type 
support for the target language.

1. I see the added benefit, so agreed as far as I'm concerned. Don't 
know how other committers and contributors feel though.
2. True, would certainly allow other people to come up with initiatives 
more easily. I think we should strive towards having the backends in the 
same organization though. Eclipse IoT for the project and the Eclipse 
IoT managed eclipse-cyclonedds GitHub organization for the code, but 
that's something we can worry about later.
3. Agreed. Especially useful during the initial phase I think.

One of the added benefits is also the that we're forced to have clearly 
defined internal API's, which is a big plus if you ask me.

@k0ekk0ek

**Comment by jeanmarline** [comment]
Hi Angelo,
I agree to  have API as external repository.

**Comment by k0ekk0ek** [comment]
@jeanmarline. Feel free to set it up as a separate repository if that works for you. But keep in mind that if it's meant to be supported as an official API, it must be kept under the eclipse-cyclonedds organization and you will have to go through a certain process for that (initial code-drop process comes to mind) and you will have to do the work required for the ip review etc. Also, everything must be reviewed for quality if people are required to support it. Until any kind of process is started, I don't think this needs to be discussed on the Eclipse Cyclone DDS issues, as it's not within the Eclipse Cyclone DDS project. If you have any questions, feel free to start a discussion over the [cyclonedds-dev mailing list](https://accounts.eclipse.org/mailing-list/cyclonedds-dev) for help, which I think is a better fit for this discussion. Of course, @eboasson may have a different opinion on this matter.

**Comment by jeanmarline** [comment]
@k0ekk0ek if @eboasson is ok I will create a separate repository for now, and I will set the Eclipse process later

**Comment by rvloon** [comment]
@jeanmarline @eboasson @k0ekk0ek I am not a huge fan of this idea. It should be enough to organize the repository in such a way that API development can be separate from the core, but keeping it outside of the repository would, imho, introduce the problem of diverging code bases whereas if they are kept in one repository, the impact of core changes would immediately be clear, also to those contributing.

**Comment by k0ekk0ek** [comment]
@eboasson. I think it's best this issue is closed? It has very little to do with the project in it's current state as there have been no official contributions regarding language bindings yet. As with any open source project: if you'd like to contribute, please start by issuing a pull request or at least ask if the maintainers of the project would be interested in accepting a certain piece of work. As there have been no pull requests or references to possible contributions, I don't see why this issue should live on. To everyone who has an opinion but hasn't contributed. Before you're allowed to pitch in, please ensure you have a noticeable and confirmed track record within the project. Thank you.

**Comment by rvloon** [comment]
@k0ekk0ek Considering the amount of time and effort ADLINK is contributing to this project, including your own company time, as well as the time of your colleagues spent on improving Cyclone, telling people to shut up because you may or may not agree with them is (a) hypocritical, because your contributions might be visible, but other people's contributions, still in the pipeline, might not be, and (b) hardly inviting to those who might contribute but who will now refrain because his highness @k0ekk0ek has not determined them worthy. It is an interesting interpretation of "Open" you have - and one I do not share.

**Comment by k0ekk0ek** [comment]
I apologize if I may have come across rude or unwilling to accept contributions. To be honest, I'm not even in a position to accept *anything*. I simply mean to say that, as long as nothing is being offered, there's no need to discuss how hypothetical contributions are best organized. Everyone, including @rvloon, is invited to pitch ideas, I'm not biased in any way. It's just that it seems rather pointless to discuss things that aren't. This is of course my opinion.

As I do not wish to participate in flame wars, I'll refrain from commenting on this ticket any further except for answering actual questions. Again, my humble apologies, I should have taken the time to phrase my comment a bit better.

**Comment by eboasson** [comment]
@rvloon, perhaps you are not aware that this is the official repository of an Eclipse project and that fighting personal feuds, slinging insults or discussing internal company matters for whatever company one happens to work for have no place here. @k0ekk0ek's comment may have been phrased a bit awkwardly, but there's really no need to take offence.

**Comment by eboasson** [comment]
It so happens that I agree with those who think maintaining different languages bindings in separate repositories is the better option. The reasons are primarily organizational. It ensures the core remains small with minimal dependencies, it allows for different maturity levels, gives a clearer division of responsibilities, and it makes it easier for others to contribute or maintain language bindings of their own. In other words, exactly as @kydos originally suggested.

Maintaining a single "meta repository" or maintaining a list of repositories that you can then easily import at specific commits and build in one go (like ROS2) is not rocket science and mitigates the risk of unintended divergence.

The official policy is therefore to have separate repositories. Should a proposed contribution come with solid arguments why that policy is unwise, it will be reconsidered.

**Comment by hansvanthag** [comment]
I assume that those repositories are all part of the single  CycloneDDS project !
(so are not 'external' let-alone Eclipse-external)

**Comment by eboasson** [comment]
@hansvanthag: such a "meta repository" and all it references would be part of the Eclipse project, but that doesn't preclude the existence of others outside the scope of the project.

**Comment by rvloon** [comment]
> @rvloon, perhaps you are not aware that this is the official repository of an Eclipse project and that fighting personal feuds, slinging insults or discussing internal company matters for whatever company one happens to work for have no place here. @k0ekk0ek's comment may have been phrased a bit awkwardly, but there's really no need to take offence.

There is never a *need* to take offence. There also is no need to be offensive. Telling people what to do or not to do, by the same token, and apparently without the authority to backup such an "awkward" statement, also has no place here.

**Comment by eboasson** [comment]
@rvloon while it is true that there is never a need to take offence, nor to be offensive, that is true for everyone involved. I humbly suggest that you read what you wrote and ask yourself whether you have met the standard you describe here, in particular with respect to this project.

Should you then decide to require further discussion because you cannot find yourself in my position, feel free to state so here, but I will not tolerate any subsequent continuation of that discussion in this forum. That is, if you require having the final word on this _on this forum_, you're herewith invited to have it.
