### ISSUE TITLE
CMake Windows warning CMP0115

### ISSUE THREAD

**Issue by emersonknapp** [eclipse-cyclonedds/cyclonedds#741]
This is making the ROS2 buildfarm go yellow on the nightlies - see for example https://ci.ros2.org/view/nightly/job/nightly_win_deb/1943/consoleText

The warning output is as follows

```
CMake Warning (dev) at src/idl/CMakeLists.txt:41 (add_library):
  Policy CMP0115 is not set: Source file extensions must be explicit.  Run
  "cmake --help-policy CMP0115" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  File:

    C:/ci/ws/src/eclipse-cyclonedds/cyclonedds/src/idl/src/hashid.c.in
This warning is for project developers.  Use -Wno-dev to suppress it.
```

**Comment by eboasson** [comment]
@k0ekk0ek just from the name of the file involved I think this relates to #735. Are you ok with me leaving it for you to look into in more detail?

**Comment by k0ekk0ek** [comment]
@eboasson, absolutely, but I missed the notification. I'll have a go at it.

**Comment by k0ekk0ek** [comment]
I think this particular issue is fixed by #737. Looking at the description provided in #756, I think CMake previously searched for `hashid.c` and found `hashid.c.in`. The error of course being it should use the generated version. I've tried to reproduce locally with CMake 3.20, but the warning didn't occur. The warning also isn't in the latest ROS builds, so I think we can safely close this. @emersonknapp, do you agree?

**Comment by emersonknapp** [comment]
Yep, this was opened to make ROS builds green - I don't have any particular input beyond that :)

**Comment by k0ekk0ek** [comment]
Closing this issue. Thanks for the feedback.
