### ISSUE TITLE
The condition is always 'false'

### ISSUE THREAD

**Issue by secondage** [eclipse-cyclonedds/cyclonedds#754]
https://github.com/eclipse-cyclonedds/cyclonedds/blob/3108aff3ee8c8b4cdb418441d1fe0925de3ef273/src/core/ddsc/src/dds_rhc_default.c#L1068

so `inst->wr_guid = wrinfo->guid;` will never be executed.

**Comment by thijsmie** [comment]
I am not sure about the details here and why this exactly is an issue. Feel free to re-open if you can provide more detail on:
 * In what situation a problem occurs
 * Why this exact piece of code is the culprit

If it is just *dead* code because someone was overly careful with conditionals I would not consider that a bug most of the time 😃.

**Comment by eboasson** [comment]
Actually ... this smells like it a bug or an improper clean-up after one. @thijsmie I hope you don't mind if I reopen it!
