### ISSUE TITLE
How to tune cyclonedds to reduce cpu usage

### ISSUE THREAD

**Issue by wep21** [eclipse-cyclonedds/cyclonedds#769]
Is there a way to reduce cpu usage which cyclonedds utilizes?
The kernel graph above shows libddsc.so utilizes 60% of cpu.(This process utilizes about 8% in 1
 core.)
![image](https://user-images.githubusercontent.com/42202095/115664048-53ac3900-a37c-11eb-9442-bb2fd6024078.png)

**Comment by eboasson** [comment]
As far as I can tell from the (sometimes rather dramatically) abbreviated names in the flame graph:

* `dq.bu..` is the thread processing "built-in" data, which really is primarily discovery data. The `recv` one is the thread most likely to be receiving that data and handing it off. The amount of time spent there suggests there are quite a few endpoints, but this should be time spent only during startup and so not the primary issue.

* `recvMC` is the thread receiving incoming multicast data. Here:
  * The `deli..`/`deliver_..` bit has to do with delivering data to readers. Why there are two of those stacks, I'm not sure (not enough characters in the flame graph!).
  * The bulk of the time spent by `recvMC` is `ddsrt_recvmsg`, which is a thin wrapper around the `recvmsg` system call (as is also evident from the flame graph).

The remainder of the time spent in Cyclone is minor, I'd say. The cost of `rcl_wait` is due to the total mismatch between the RMW wait interface and the DDS wait interface, and overhead of ROS 2 executors (`rclcpp::Executor`) is a well-known performance issue within ROS 2.

Reducing the number of packets would probably help. Fortunately, the default maximum message size used by Cyclone is a bit odd and raising it to (nearly) 64kB should significantly reduce the number of packets. Setting [`General/MaxMessageSize`](https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/docs/manual/options.md#cycloneddsdomaingeneralmaxmessagesize) to 65500B in the Cyclone DDS configuration should take care of that. I think you know how to do those settings, right?

If this is all within a single machine, then the [Iceoryx integration work](https://github.com/eclipse-cyclonedds/cyclonedds/tree/iceoryx) should allow switching to end-to-end zero-copy communication but whether that's an option for you depends on various factors — ROS 2 version, QoS settings, whether you're using a fixed-size type. Etc. I'm mentioning it mostly as a heads-up of what is to come, but you are of course welcome to try it.

**Comment by wep21** [comment]
I'm sorry, but I take some expanded pictures.
![Screenshot from 2021-04-22 20-12-49](https://user-images.githubusercontent.com/42202095/115705979-22e1f900-a3a8-11eb-85bf-56eeef97c86c.png)
![Screenshot from 2021-04-22 20-13-24](https://user-images.githubusercontent.com/42202095/115705983-237a8f80-a3a8-11eb-9d76-f74fef287ab7.png)
![Screenshot from 2021-04-22 20-13-57](https://user-images.githubusercontent.com/42202095/115705988-24132600-a3a8-11eb-9ab6-8245a07492f5.png)
![Screenshot from 2021-04-22 20-14-57](https://user-images.githubusercontent.com/42202095/115705990-24132600-a3a8-11eb-887f-b650db8f1107.png)
![Screenshot from 2021-04-22 20-15-49](https://user-images.githubusercontent.com/42202095/115705993-24abbc80-a3a8-11eb-939d-36b307177c80.png)

**Comment by wep21** [comment]
> Reducing the number of packets would probably help. Fortunately, the default maximum message size used by Cyclone is a bit odd and raising it to (nearly) 64kB should significantly reduce the number of packets. Setting General/MaxMessageSize to 65500B in the Cyclone DDS configuration should take care of that. I think you know how to do those settings, right?

Thank you for your comment. I will try it.

**Comment by eboasson** [comment]
> I'm sorry, but I take some expanded pictures.

Apologies are not necessary, but having the expanded pictures is very interesting. Thank you!

Comments per picture:

1. That the `dq.builtins` thread spends most of its time in creating/deleting proxy readers/writers is expected. I know of some cases where readers/writers got created and deleted almost continuously (like several per second) and that induced a lot of load, but in most systems there is a just a bit of initial load in doing the discovery. From the original flame graph, I think you just have this latter, normal case. In a time line, you'd probably see the create_proxy_reader/writer at the beginning of the experiment, and the delete_... at the end.
2. The `gc` thread should be idle most of the time, and from the original flame graph, I think you probably zoomed in quite a bit because I can't really find it there 🙂 That's good, because otherwise at the very least the `ddsi_tk..` stack frame would have had me worried.
3. The `recv` thread is the only one that uses `select` to service multiple sockets at the same time. Select is not the smartest choice, but the work to eliminate that seems to get derailed all the time. Fortunately, the existence of the `recvUC` and `recvMC` threads means that it really doesn't spend much time in `select` anyway.
4. The `recvMC` thread handles all application data arriving via multicast, and it seems it is spending most of its time (other than waiting for a packet to arrive) in delivering user data. The one that is zoomed in on `delivery_locally_all_in_sync` seems to be wasteful by spending time both in `entity_status_signal` and in signalling `DATA_AVAILABLE`. I think I know why that is, and a few tweaks to the RMW layer would probably help with that. I'll try to look into that. Otherwise I think this is the one labelled `deli..` in the original flamegraph, and it seems to be less expensive than the other one, which is:
5. `deliver_locally_one`. That one is used for all cases where things don't line up perfectly, so for retransmits, while reader/writer matching is still ongoing, etc. On the one hand, I expect it to be more costly per message than the other one; on the other hand, I would not expect it to be done much once the system is running fine, unless you have retransmits all the time. Do you? 😀

That final question is tongue-in-cheek: it is not so easy to tell from the outside. It is most likely to happen if you are sending samples that are large compare to the socket receive buffer size. Without explicitly configuring a socket receive buffer size, Cyclone will ask the kernel for 1MB but the default settings of Linux are to then give it only 400kB or so. It'll happily operate with that size, but if you are sending 10MB point clouds, it is less than ideal (the option is https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/docs/manual/options.md#cycloneddsdomaininternalminimumsocketreceivebuffersize).

**Comment by wep21** [comment]
I'm sorry for late reply. Thank you for your helpful comments. I have solved the high cpu usage problem, so I close this.

**Comment by sgf201** [comment]
> I'm sorry for late reply. Thank you for your helpful comments. I have solved the high cpu usage problem, so I close this.

hi, what did you do to solve this problem?  I find that cpu usage big also~
