### ISSUE TITLE
assert(0) in init_one_parameter function in q_plist.c

### ISSUE THREAD

**Issue by raiars** [eclipse-cyclonedds/cyclonedds#79]
Hi, when I was using CycloneDDS, I found that the code could get into assert(0) in init_one_parameter in q_plist.c which shows it cannot happen. 

![02](https://user-images.githubusercontent.com/11205435/50435518-95e41d80-091c-11e9-9913-ca15b1f933bc.PNG)
![01](https://user-images.githubusercontent.com/11205435/50435522-98467780-091c-11e9-8344-ed1b18eac91e.png)

![image](https://user-images.githubusercontent.com/11205435/50435793-bf517900-091d-11e9-95fe-7c7111cf2ce9.png)

When I check the code, I find that when pid equals 53701, it gets into if (pid & PID_UNRECOGNIZED_INCOMPATIBLE_FLAG) then runs into assert(0). Did you design it in that way or is this a bug?

**Comment by eboasson** [comment]
Hi @raiars, that's an easy question to answer. It is a bug.

The sensible thing to do is to simply return ``ERR_INVALID``, as that gets you into the standard path for handling invalid input. I think the original idea was to set the ``PP_INCOMPATIBLE`` flag and then refuse to create any entities when that flag is set, but it seems it isn't checking for it anywhere. Adding such checks would be possible, of course, but since that code was written, another problem has appeared on the horizon.

The xtypes specification uses pretty much this same parameter list encoding for mutable types, but extends it to handle values larger than 64kB by inserting a 32-bit length immediately after the parameter-id+length field that this code is handling. If I am not mistaken, in this case the "unrecognised incompatible flag" is set, with the idea that it would be a safe extension as all recipients would ignore it. Note that the spec doesn't actually say what to do:

> If the ParameterId is not recognized, treat the parameter as an incompatible QoS. In this case, no communication will be established between the two Entities.

to me it is perfectly acceptable to keep parsing and validating parameters, but the xtypes format extension suggests that parsing should be abandoned.

Now, the parameter lists used in discovery are not yet the full mutable format, but a natural next step in the evolution would be to allow the free format values in the QoS (partition and user/group/topic data) to also be larger than 64kB, as there is now an accepted encoding for that. At that point, the consequence of this original plan of merely marking the parameter list as incompatible while continuing parsing would possibly result in interpreting (part of) a large value as if it were part the parameter list.

That misinterpreted value should then still be validated, and no entities should be created based on it; but I'm sure it would open up interesting possibilities. And so the sensible thing is bail out as quickly as possible. By definition, the data is of no use anwyay.

**Comment by eboasson** [comment]
Closing this as it has been fixed
