### ISSUE TITLE
Building standalone application with using CycloneDDS

### ISSUE THREAD

**Issue by madmax440** [eclipse-cyclonedds/cyclonedds#794]
Hello,

I have just been using CycloneDDS and built an example HelloWorld application and tested it on the Host (X86 ubuntu linux).

I am also able to cross compile CycloneDDS as well.

I wanted to custom build applications by using the Cyclone DDS libraries and the code generator. So i try to build only 'HelloWorld' for the target platform (ARM gcc - yocto)

I am building it the following way.

```bash
$ source ./yocto-env-setup.bash
$ cd examples/helloworld/
$ mkdir build/
$ cd build/
$ cmake ..

```

build errors:

```bash
CMake Error at CMakeLists.txt:19 (find_package):
  By not providing "FindCycloneDDS.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "CycloneDDS", but CMake did not find one.

  Could not find a package configuration file provided by "CycloneDDS" with
  any of the following names:

    CycloneDDSConfig.cmake
    cyclonedds-config.cmake

  Add the installation prefix of "CycloneDDS" to CMAKE_PREFIX_PATH or set
  "CycloneDDS_DIR" to a directory containing one of the above files.  If
  "CycloneDDS" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
```

and then i added the following in the CMakeLists.txt  by showing it the CMake dependency.

```bash
set(CycloneDDS_DIR "/home/user/wkspaces/cyclonedds/cyclonedds_cross_output/lib/cmake/CycloneDDS/")
````

But then i got into the below issue,

```bash
CMake Error at CMakeLists.txt:27 (idlc_generate):
  Unknown CMake command "idlc_generate".


-- Configuring incomplete, errors occurred!
See also "/home/user/wkspaces/cyclonedds/examples/helloworld/build/CMakeFiles/CMakeOutput.log".
````

Any help is greatly appreciated.

**Comment by madmax440** [comment]
thanks. I suspect the issue being that Generate.cmake is missing in the exported Cmake files. But may be more than that is missing?

**Comment by madmax440** [comment]
Anymore pointers to help running cross builds on standalone applications outside the cyclonedds work directory? thanks

**Comment by k0ekk0ek** [comment]
We regularly cross compile Cyclone DDS for embedded targets so it should just work. Does CMake know it's cross compiling, because it matters where it tries to find the IDL compiler. If the variable `CMAKE_CROSSCOMPILING` is true, it'll look for both `ddsconf` and `idlc` on the host, otherwise it'll build them itself. That is of course only of importance for the library itself. It maybe the case that it cannot find idlc, etc from the CMake files for the application/example. Because the compiler is not built in a cross compile scenario, it cannot install it. Hence, it also makes no sense to install Generate.cmake from a cross build perspective. The simplest fix is therefore to use the same trick we use in cross compilation scenarios for Cyclone DDS itself, and that is to use `find_program` for idlc and include Generate.cmake from the example.

**Comment by alsora** [comment]
@k0ekk0ek Hi, I;m trying to cross-compile cycloneDDS but it's failing due to `ddsconf` not being found.
I had a look at https://github.com/eclipse-cyclonedds/cyclonedds/pull/625 and it is unclear to me where `ddsconf` should be found.

Is it required to first build cycloneDDS for x86_64 and somehow expose the ddsconf executable before cross-compiling?

**Comment by k0ekk0ek** [comment]
Hi @alsora! Indeed, you need to do a host build first to have `ddsconf` (and `idlc`) available. The CMake files check if `CMAKE_CROSSCOMPILING` is true, which is the case if you use a toolchain file, if it is, it'll try to find the executable on your host system. `src/tools/ddsconf/CMakeLists.txt` shows what it does for `ddsconf`. [cmake-toolchains(7)](https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html) provides more information on how to cross compile the CMake way. Depending on your setup you may have to watch `CMAKE_FIND_ROOT_PATH_MODE_PROGRAM` and perhaps provide additional prefix paths for CMake to check.

**Comment by alsora** [comment]
Is there any plan to move ddsconf to a separate package/repository ?
As it is right now, it feels kind of strange to have to build CycloneDDS twice if I only care about the cross-compiled version

**Comment by k0ekk0ek** [comment]
I've encountered it in other places too, but I'll admit that it may seem weird at first. Splitting it into separate repositories is not possible though, because both `ddsconf` and `idlc` are very tightly integrated with the exact commit. `ddsconf` is a clever trick to generate the default configuration in C (and the `.xsd` schema, etc) and `idlc` is required to generate the serialization code.

**Comment by alsora** [comment]
Ok, that's kind of unfortunate I think... 
Anyhow, after tweaking with my build pipeline I have it working.

It's worth noticing that running the install step results in installing everything except `ddsconf`, which I had to manually copy from the build to the install directory.

**Comment by thijsmie** [comment]
Cross-compiling has been much improved since this ticket, no longer requiring `ddsconf` at build time. You'll still need the host-idl-compiler if processing IDL files at build time, which is the case for most applications and tools like `ddsperf`.

**Comment by alsora** [comment]
Hi @thijsmie do you have updated cross-compilation instructions?
What is the "host-idl-compiler" and how is it built?

**Comment by thijsmie** [comment]
Hi @alsora,

The cross compilation is the same as before: with a CMake toolchain file it _should just work_. You used to need to build Cyclone once for the host environment before your target environment to get hold of an executable called `ddsconf`, this is no longer necessary. However, if you need to process IDL files to code you will still need a build of Cyclone with IDL compiler for the host before doing the target build, since you cannot run a target IDL compiler executable on your host system. I just used the "host-idl-compiler" to indicate that process. I hope that clears things up, if not you can join us on discord for some help or open a new issue :smile:

**Comment by stan-guer** [comment]
Hi @thijsmie ,

can you recommend a way of calling "host-idl-compiler" for the `idlc_generate` command when crosscompiling ?

My current situation is: I have the target **CycloneDDS::ddsc** library in a crosscompilation toolchain sysroot and the **IDL compiler** in host and i want to generate the IDL files to code.

A workaround i found is to include the Generate.cmake file directly, 
```
if(CMAKE_CROSSCOMPILING)
  include("/usr/local/lib/cmake/CycloneDDS/idlc/Generate.cmake")
endif()
```
but that just looks messy. I was thinking if you have a trick to have Cmake find the file from host sysroot. Mine keeps picking up the one in the crosscompilation sysroot. I tried all the find_package directives without any luck.

Otherwise builds and and works on target, for c++ as well, if [cxx#302](https://github.com/eclipse-cyclonedds/cyclonedds-cxx/pull/302) gets merged.

**Comment by thijsmie** [comment]
Hi @stan-guer,

I reviewed the [Generate.cmake](https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/cmake/Modules/Generate.cmake) code and checked the cmake docs for [find_path](https://cmake.org/cmake/help/latest/command/find_path.html) and I think that needs some tweaks to ensure we find the _host_ idlc and not the _target_ idlc. This current setup will work when we are building CycloneDDS for _target_ architecture but not enough consideration has been given to depending projects. I actually think it is best to supply an environment variable, e.g. `HOST_CYCLONEDDS_ROOT` or similar and use that to resolve the `idlc` executable and the `idlc` language backend libraries. We can then remove the CMAKE_CROSSCOMPILING dependend resolution and just let the env variable override.

Would you be so kind as to open a separate issue for this @stan-guer?

**Comment by Entropy512** [comment]
@thijsmie did @stan-guer ever open a separate issue?  It would be nice to have a pointer to that other issue if it is open.  If he never opened it, I'll open one.

BTW, the idea you have of using an environment variable is similar to how protobuf handles it - Protobuf_PROTOC_EXECUTABLE can be set in the toolchain file to point to the host protoc location.  ( implementation in https://github.com/protocolbuffers/protobuf/blob/main/cmake/protobuf-module.cmake.in#L137 ) Since you also have to resolve some libraries, it makes sense to point to a root directory instead though.
