### ISSUE TITLE
documentation for idl supported types

### ISSUE THREAD

**Issue by devendranaga** [eclipse-cyclonedds/cyclonedds#795]
with regards to the idl types there is a related bug that is closed [here](https://github.com/eclipse-cyclonedds/cyclonedds/issues/350) . What i'd also like to know is the following.

1. including one IDL file into another.
2. compiling groups of IDL files at the same time.
3. bit operations for example Fast-DDS support below format:
```c

    bitset lights
    {
        bitfield<1> head_lights;
        bitfield<1> parking_lights;
        bitfield<1> left_turn_signal;
        bitfield<1> right_turn_signal;
    };
``` 

if there's a document with regards to these, a  link to it would be greatly appreciated.

**Comment by NoeSechet** [comment]
Hi @eboasson :) 

Any updates regarding this issue? 
I tried to find a list of the supported types and I couldn't find a clear one that seemed complete. 

Also, I found this on the documentation page: https://cyclonedds.io/content/faq.html#question-what-non-xtypes-idl-is-supported

So I assumed it had not been tackled yet. 

Is there any current way to have a clear list?

**Comment by thijsmie** [comment]
Hi @NoeSechet and @madmax440,

This is indeed something that needs some attention. I've recently written a post about some of the new XTypes features that are supported [which you can find here](https://cyclonedds.io/content/blog/xtypes-features.html). This is not exhaustive but together with the reference you already linked looks pretty complete to me.

Note that the `bitset` mentioned above is not something we're currently looking to support, because while in C you get native support this is not something that maps to basically any other language and the XTypes spec doesn't even properly describe how to map them to typeobjects. We did implement `bitmask`s on all language bindings.
