### ISSUE TITLE
Discovering all topics

### ISSUE THREAD

**Issue by AlperColak** [eclipse-cyclonedds/cyclonedds#831]
Hi. I want to write a recorder/logger tool for cyclone. Is there a way to discover and subscribe all topics published on a LAN based on a particular descriptor?
Regards
Alper

**Comment by eboasson** [comment]
I don't know exactly what you mean by "based on a particular descriptor" but to monitor the topics/writers/readers you can look at the built-in topics:

- a data reader for the `DDS_BUILTIN_TOPIC_DCPSTOPIC` topic allows you to discover all topics that have been created in the system (regardless of whether readers/writers exist for it). This gives you the topic name, type name, topic QoS and a type identifier.
- a data reader for the `DDS_BUILTIN_TOPIC_DCPSPUBLICATION` topic allows you to discover all writers that have been created, these also contain topic name, type name and type identifier, but instead of the topic QoS you get the writer QoS. (You can do the same for data readers.)

If you have the type definition available already, you can simply create topics matching those you discovered. If you don't, you can use `dds_find_topic` to look up a topic in the system and create a local copy in your process; or you can use `dds_domain_resolve_type` to look up the type definition corresponding to a type identifier you have. That gets you a `struct ddsi_serype *` that you can pass to `dds_create_topic_sertype`, which again gets you a topic.

And then once you have a topic, you can take a subscription.

You also might want to have a look at `dds_takecdr` which gives you a reference to a `struct ddsi_serdata`, which is an opaque sample representation. The CDR can be extracted from that using `ddsi_serdata_to_ser` (or if you want to avoid a copy) `ddsi_serdata_to_ser_ref`.

**Comment by AlperColak** [comment]
Thank you  @eboasson. I will try them ASAP.

**Comment by sjames** [comment]
> Thank you @eboasson. I will try them ASAP.

@AlperColak . I am curious to see how this works. Before I try something, I wanted to ask if you got this working and if you will be willing to share the results.

**Comment by AlperColak** [comment]
Hi @sjames
I am sorry but, i could not try it yet, it is still on my todo list.

**Comment by rkilic** [comment]
Hi, I tried to discover all topics but unfortunately  I failed. This is the situation : 

I created a reader to discover all topics like below ;
 
reader = dds_create_reader (subscriber, DDS_BUILTIN_TOPIC_DCPSPUBLICATION , drQos, NULL);

auto rdcond = dds_create_readcondition (reader, DDS_ANY_STATE);

int status = dds_waitset_attach (waitSet, rdcond, reader);

Firstly, I used  DDS_BUILTIN_TOPIC_DCPSTOPIC topic to discover all topics; but I could not  catch any topic. Then I used DDS_BUILTIN_TOPIC_DCPSPUBLICATION  topic, I discovered something but I couldn't use that data to get topic names, type names etc. In documentation file , I could  not find anything to solve this problem.   I will be glad if you help.

REGARDS

**Comment by rkilic** [comment]
Thank you @eboasson. I run  the example and it worked thank you so much again.

**Comment by eboasson** [comment]
Glad that it now works!

**Comment by rkilic** [comment]
Hi,  is there a way to Disable TOPIC DISCOVERY on run time because the cost of topic discovery? I want  to  disable topic discovery after getting all topics.  

THANK YOU

**Comment by eboasson** [comment]
The overhead is only during discovery. So unless you keep creating new participants and/or new topics, there will not be any additional cost after all topics have been discovered.

Or perhaps I misunderstood your question ...

**Comment by hansvanthag** [comment]
just a thought: what about 'others' creating new entities (most notably topics), would that induce some local cost ?

**Comment by rkilic** [comment]
Thank you @eboasson  this is exactly what I  wanted to know.

**Comment by eboasson** [comment]
> just a thought: what about 'others' creating new entities (most notably topics), would that induce some local cost ?

Well, anyone creating participants that are discovered and any topics created by those participants would induce some cost. But that really amounts to no more than my "you" in 

> So unless you keep creating new participants and/or new topics

being simply the second part of
<img width="357" alt="image" src="https://user-images.githubusercontent.com/16984005/132692029-c502bbdd-14a5-488a-84a2-5d9470dcb194.png">

wouldn't you — hah! 😁 — agree?

**Comment by gsnuffles** [comment]
> Thank you @eboasson. I run the example and it worked thank you so much again.

@rkilic / @eboasson : How did you make the example work? For me the output is
```
alive: 954e4f2a:a0d12b87:7fe4cac2:0a0a19fa DCPSPublication org::eclipse::cyclonedds::builtin::DCPSPublication
alive: 8a85d4ad:c906db14:921caa4c:b51d50c1 DCPSSubscription org::eclipse::cyclonedds::builtin::DCPSSubscription
disposed: 954e4f2a:a0d12b87:7fe4cac2:0a0a19fa
disposed: 8a85d4ad:c906db14:921caa4c:b51d50c1
No topics discovered but remote readers/writers exist. Is topic discovery enabled in the configuration?
```
when a writer or reader is available on some topic. I am using the config:

```idl
<CycloneDDS xmlns="https://cdds.io/config">
	<Domain Id="any" >
		<General>
			<Transport>udp</Transport>
			<NetworkInterfaceAddress>127.0.0.1</NetworkInterfaceAddress>
			<MulticastRecvNetworkInterfaceAddresses>127.0.0.1</MulticastRecvNetworkInterfaceAddresses>
			<AllowMulticast>default</AllowMulticast>
			<EnableMulticastLoopback>true</EnableMulticastLoopback>
		</General>
		<Compatibility>
			<StandardsConformance>lax</StandardsConformance>
		</Compatibility>

		<Discovery>
			<EnableTopicDiscoveryEndpoints>true</EnableTopicDiscoveryEndpoints>
		</Discovery>
	</Domain>
</CycloneDDS>
```

Without a other reader/writer present I get the following (which was expected, I think):
```
alive: 954e4f2a:a0d12b87:7fe4cac2:0a0a19fa DCPSPublication org::eclipse::cyclonedds::builtin::DCPSPublication
alive: 8a85d4ad:c906db14:921caa4c:b51d50c1 DCPSSubscription org::eclipse::cyclonedds::builtin::DCPSSubscription
```

**Comment by rkilic** [comment]
Hi @gsnuffles , actually I did not run the example with using cyclonedds-cxx.  I checked here https://github.com/eclipse-cyclonedds/cyclonedds/releases. In 0.8.0 (Réplique) release candidate 3  ,  Topic and type discovery exists.  Maybe, it not supported with cyclonedds-cxx, I am not sure.

**Comment by t0ny-peng** [comment]
@eboasson Hi I guess I'm the person you pinged to review the change in the first place😂 Right unfortunately I was preempted by another task with higher priority this month. Finally everything is sorted out and I'm pick up from where I left. There were some problems in my test and I've reported in that PR.

**Comment by gsnuffles** [comment]
@eboasson Does this mean that both sides of the communication need built-in topics support for topic discovery to work? 
Or in other words: If only one side has built-in topics support (in this case cyclonedds) and the other side does not (in this case cyclonedds-cxx) the example listtopics will not work?
