### ISSUE TITLE
Unicast sending of a message to a known reader (RPC, service)

### ISSUE THREAD

**Issue by i-and** [eclipse-cyclonedds/cyclonedds#911]
Is there a way to restrict sending a response message to the node that sent the corresponding request (for example in the service rmw_cyclonedds_cpp)? 

This will exclude the reception of responses by client nodes of the one service that did not send the request.

**Comment by eboasson** [comment]
Eventually that'll be done with content filtered subscriptions in the RMW layer, I suppose.

What I consider the proper way is to use unique partition names to basically construct a session. The trouble with that is that, as things stand in DDS today, constructing that session has so much discovery overhead that it is worse than simply sending that broadcasting the reply. (If there are many requests from the same client, then one could cache the sessions, amortize the overhead and live happily forever after.)

Assuming one knows where the service is, there is an elegant solution to that by extending the protocol with a point-to-point session setup request. Then one can send the session set-up request and the applications request in a single packet, and send the response along with the acknowledgement back. Then three unicast packets suffice.

**Comment by i-and** [comment]
> Eventually that'll be done with content filtered subscriptions in the RMW layer, I suppose.

"Content filtered subscriptions" means blocking the sending of Topics to the network from the writer's side that do not match the filter that is set from the reader's side? Is this function implemented in the cyclonedds?

"partition" means DDS_HAS_NETWORK_PARTITIONS?

>Then one can send the session set-up request and the applications request in a single packet, and send the response along with the acknowledgement back. Then three unicast packets suffice.

Is it planned to implement the described session establishment protocol?

---

What if the request header includes the Reader's GUID, which will be used by the Service Writer when sending a response to the request? After passing this GUID to dds_write (), cyclonedds sends only to the Reader with the specified GUID.

**Comment by eboasson** [comment]
> > Eventually that'll be done with content filtered subscriptions in the RMW layer, I suppose.
> 
> "Content filtered subscriptions" means blocking the sending of Topics to the network from the writer's side that do not match the filter that is set from the reader's side? Is this function implemented in the cyclonedds?

Yes, and no it isn't in Cyclone yet. The actual filtering is "but an extension" to what DDS Security already uses for implementing token exchange without flooding the network with all those token exchanges during discovery. The biggest practical obstacle is metadata, but with #904 we're getting there.

> "partition" means DDS_HAS_NETWORK_PARTITIONS?

No, I meant the DDS "partition" QoS, which always supported and is part of the reader/writer matching in DDS.

Cyclone tries to find a reasonable set of addresses to reach all matched subscribers (a process that's slowly improving). The `DDS_HAS_NETWORK_PARTITIONS` allows mapping topics/partitions to multicast addresses, and so affects which addresses are involved in computing that set of addresses.

Unless you set `General/PreferMulticast` (I expect you remember that option), it will always end up using unicast if all matching data readers are reachable at the same address. So simply creating a unique DDS partition for the reader and writer involved in the request/response will quite naturally make it use unicast.

> > Then one can send the session set-up request and the applications request in a single packet, and send the response along with the acknowledgement back. Then three unicast packets suffice.
> 
> Is it planned to implement the described session establishment protocol?

I do intend to work out the details and implement it in Cyclone, yes. With an API to make it available to anyone who wants to use it, for whatever purpose. The current plans for implementing "transient" data also depend on it, because if you can efficiently create a session, you can also use that to send a large sequence of samples.

> What if the request header includes the Reader's GUID, which will be used by the Service Writer when sending a response to the request? After passing this GUID to dds_write (), cyclonedds sends only to the Reader with the specified GUID.

That's pretty much a particular kind of content filter, but it so happens to be exactly what is currently implemented to do the aforementioned token exchange in DDS Security. I have to admit I had not really given any thought to whether that specific mechanism could be made available in an elegant way in the API, but it quite likely could be done. Interesting.

**Comment by thijsmie** [comment]
Question answered 😄.
