### ISSUE TITLE
IDL parser buffer not extended when parsing multi-line comment

### ISSUE THREAD

**Issue by dennis-adlink** [eclipse-cyclonedds/cyclonedds#977]
There is an issue in the parsing of multi-line comments in IDL files, which seems to be caused by the parser buffer not being extended while parsing a multi-line comment. 

To reproduce: create an IDL file that contains only a multi-line comment, with a length > 4041 characters (exclusing the /* and */). Compiling this file fails with an error message 'syntax error'.

**Comment by reicheratwork** [comment]
This issue seems to occur whenever a buffer refill is requested while a comment is being read. The 4041 character size you see is caused by the chunk size of the buffer (default = 4096) and the paths of the files being parsed being prepended to the contents of the file in the buffer (which in your case seems to be ~55 chars).

This issue occurs when a comment is being parsed, and scanning the available buffer does not reveal the end of the comment marker `*/`.
The refill operation then moves new data into the buffer.
The part of the buffer being "dropped" to make place however ends at the current position of the cursor, which is inside the comment.
Then when the new attempt is made at parsing block of data is made, it begins reading inside the comment, and finds a terminating comment marker without the start, causing the error in the parser.

Working on a fix now.
